### ISSUE TITLE
build boost libs do not have absolute path's set on Linux

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#1002]
## Description
The mpi and serialization library part of stan-math are not build with hard-coded dll path's which make them potentially unsafe to use.

## Example
Build stan-math on Linux with MPI. Then execute `ldd` on the `libboost_mpi.so` file. It will show that the references to the `libboost_serialization.so` are not found (unless the user includes the `lib/boost*/stage/lib` directory in `LD_LIBRARY_PATH`).

## Expected Output
Calling `ldd` on that file should confirm that all dll path's are correctly resolved.

## Additional Information
Any additional information goes here.

## Current Math Version
v2.18.0

**Comment by andrjohns** [comment]
Closed via #1003
