### ISSUE TITLE
Build should fail when there are compiler warnings

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#1032]
## Description
Right now a Math build will not fail if there are compiler warnings. There is a PR that started to try to address this, but ran into problems with the MPI build: https://github.com/stan-dev/math/pull/891

## Current Math Version
v2.18.0

**Comment by seantalts** [comment]
@syclik is the reporter

**Comment by rok-cesnovar** [comment]
Is this still relevant? I know sundials compilation spits out some warnings so I guess this wasnt addressed?

**Comment by mcol** [comment]
Are there known warnings remaining? If not, it should be enough to add `-Werror` to the compiler flags to make the builds fail on warnings.
