### ISSUE TITLE
Remove access qualifiers in the GPU kernels

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1033]
## Description
The access qualifiers `read_only`, `write_only` and `read_write` should only be used for pipe and image types. We need to remove them from the existing kernels. The problem occured because the NVIDIAs OpenCL JIT compilers and older AMD compiler are not strict with this and ignore the use of access qualifiers for types that are not image or pipes.

## Example
For **bug reports**:

On recent Windows AMD implementations the AMDs JIT OpenCL compiler outputs the following error: `error: access qualifier can only be used for pipe and image type`. 

## Current Math Version
v2.18.0

**Comment by pengyuanwei** [comment]
Sorry, may I ask how to remove the access qualifiers `read_only`, `write_only` and `read_write` from the existing kernels?
