### ISSUE TITLE
read_only and write_only decorators in GPU kernels cause tests to fail on windows

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1034]
## Description

The Windows OpenCL driver reserves read_only, write_only, and read_write argument decorators for pipes and image type arguments so our tests are failing on Rok's Windows test machine. The decorators are mostly a 'nice-ity' so we can remove them without much impact. The problem occured because the NVIDIAs OpenCL JIT compilers and older AMD compiler are not strict with this and ignore the use of access qualifiers for types that are not image or pipes.

## Example

On recent Windows AMD implementations the AMDs JIT OpenCL compiler outputs the following error: error: access qualifier can only be used for pipe and image type.

## Additional Information

Just going to remove the decorators. This should have no material effect on the kernels.

## Current Math Version
v2.18.0

**Comment by rok-cesnovar** [comment]
It seems that we both posted the same issue :) You pick one and close the other :)

**Comment by SteveBronder** [comment]
lol, I merged your comments into mine above so will close the other.
