### ISSUE TITLE
Add better error handling for CVODES

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#1039]
## Description

Currently, our calls to CVODES just pass the exceptions back out. CVODES throws `std::runtime_exception` (I backed this out by printing `typeid(e).name()`.)

There are two things we could fix:

1. The errors look like: `CVode failed with error flag -1`. We could make that friendlier by stating the error message from the manual (which isn't much better): `SUNLS_MEM_NULL (-1) – the memory argument to the function is NULL`

2. Either throw a `domain_error` so sampling continues or adjust the exceptions the samplers catch to allow for `runtime_errror`.

Currently, if it runs into one of these errors, it stops immediately.

What we'd want to do is to have it continue to the next iteration after a failure.

## Current Math Version
v2.18.0

**Comment by syclik** [comment]
> I disagree that they aren't much better. I assume we're talking about: https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/functor/cvodes_utils.hpp#L16

Nope, we're not talking about the same thing. It's embeded in the [CVODE manual](https://computation.llnl.gov/sites/default/files/public/cv_guide.pdf) as Table 8.4 on page 146. As far as I can tell, the error codes are shared across Sundials, but maybe I'm wrong. Screenshot below:
![image](https://user-images.githubusercontent.com/425751/45881329-da3dab80-bd78-11e8-890c-3855bee79f86.png)

I was suggesting that the error messages that is described in the manual isn't much better than the code. Thanks for digging up the `cvodes_util.hpp` -- I hadn't stumbled on that. Yes, that's better than just returning the error code.

> But I agree we shouldn't be eating the errors here.

I don't think we're eating error messages. What's happening is that these errors aren't being caught and that bubbles all the way up to the top and the process quits.

> Re: domain_error vs runtime_error -- after a bunch of domain_errors does the sampler give up?

Sorry about the confusion. The clearest doc, in this case, is in the issue that outlines what happens: stan-dev/stan#2188.

To summarize, right now, all the sampling algorithms treat `std::domain_error` as a recoverable exception and things like `std::invalid_argument` as something that's not recoverable. By recoverable, what I mean is that in the current iteration, given the values of the parameters, I can evaluate the `log_prob()` function and it failed to evaluate the function value or the gradients for some reason. But, that doesn't mean the next time I call `log_prob()` it will fail; it might work with different parameter values.

If there's a user coding error, let's say someone defines `vector[2] x` and then calls  `x[4]`, then no matter how many times I run `log_prob()`, that error will still be an error. The idea was that the algorithms shouldn't try to continue under those sorts of errors.

When this was speced and implemented, we only took `std::domain_error` as recoverable exceptions and everything else as not. We could have done it the other way (enumerate all the non-recoverable exceptions and everything else is recoverable), but we didn't. So... `std::runtime_error` is treated as an unrecoverable error.

I think we should treat `runtime_error` as recoverable (so the algorithms will continue to sample after hitting one; that iteration should die gracefully).

> ... we're assuming that these errors mostly coming from running ODEs in crazy parts of parameter space where its solution doesn't exist or is way weird (that aren't always easy to disclude with constraints).

Exactly. If we recover from the exception, the hope is by having different ODE parameter values, we'd get into a good place. That said, I don't know the error conditions well enough to know whether some of these error codes are actually indicating something that's not recoverable.

---

Does that info help?

**Comment by bbbales2** [comment]
> I think we should treat runtime_error as recoverable (so the algorithms will continue to sample after hitting one; that iteration should die gracefully).

Yeah I think I'd be happy switching these errors to domain_errors (it seems scary switching the meaning of runtime_error to suite this issue rather than switching this to just thrown domain_errors).

Did this come up in a particular problem you were working with though?

I agree with the intent though.

Just to make this unnecessarily hard, could we enumerate all the CVODES errors and decide which are recoverable and what's not? If that's all the error CVODES uses, this is easy. I can list which ones I think are recoverable or not. Can you verify this?

SUNLS_QR_FACT is probably recoverable. SUNLS_MEM_NULL probably isn't, etc.

**Comment by syclik** [comment]
> Did this come up in a particular problem you were working with though?

Yup. This came up working on one of the models with @pourzanj. Obviously, it's better to fix it for everyone than just patch it for our use.

> Yeah I think I'd be happy switching these errors to domain_errors (it seems scary switching the meaning of runtime_error to suite this issue rather than switching this to just thrown domain_errors).

I'm looking at the [list of `std::exceptions` on cppreference](https://en.cppreference.com/w/cpp/error/exception).

Based on that list, I think I'd be ok catching `std::runtime_error`s and treating that as ok.

I think of the `std::logic_error`, `std::domain_error` is the right one to treat as recoverable. (what we currently do)

Thoughts?

> Just to make this unnecessarily hard, could we enumerate all the CVODES errors and decide which are recoverable and what's not? If that's all the error CVODES uses, this is easy. I can list which ones I think are recoverable or not. Can you verify this?

There isn't much more information in their doc. We could dig into their source code and figure it all out... although, there wouldn't be any guarantee that this won't change with different versions of CVODES.

But yes, in practice, we could do this.

I'm still trying to put together a minimal example that triggers this. We'll need to do that to fix the issue properly.
