### ISSUE TITLE
allow vector arguments for ordered_logistic

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#105]
_From @bob-carpenter on December 9, 2014 15:46_

We need to supply array first arguments for `ordered_logistic`.   We should have the mechanisms already in place to handle array of integer arguments (they should be in Poisson, etc.)

_Copied from original issue: stan-dev/stan#1162_

**Comment by syclik** [comment]
_From @chmullig on March 30, 2015 0:55_

A :+1: for this. For Gelman's survey course we're doing a bunch of mulitlevel ordered logistics and doing them one case at a time is painfully slow, even with n = ~800.

**Comment by syclik** [comment]
_From @tmalsburg on April 27, 2015 2:7_

FWIW, I would like to see this feature as well.

**Comment by syclik** [comment]
_From @rtrangucci on April 27, 2015 23:57_

@bob-carpenter I've found the current implementation to be pretty slow as well. Not good for our stan_lmer implementation. I'll create a branch for this.

**Comment by bob-carpenter** [comment]
Closing this as it'll get rolled into #97 along with all the other multivariates.
