### ISSUE TITLE
Math library should use functions in std where possible rather than Boost

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#1055]
## Description

The Stan Math library was written with a lot of reliance on Boost. The C++11 and later C++14 standards incorporated a lot of what Boost had done over the years, so now it is no longer necessary for Stan to use Boost as much. Much of

https://en.cppreference.com/w/cpp/numeric/math

could be called by Stan instead of calling the Boost versions (which I think often would call the std versions anyway). Also, I think a lot of the type promotion stuff could be replaced by `auto` in C++14

## Example

https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/fun/lgamma.hpp#L37
could be `std::lgamma` and many other similar things.

stan/math/prim/mat/fun/add.hpp could be just
```
#ifndef STAN_MATH_PRIM_MAT_FUN_ADD_HPP
#define STAN_MATH_PRIM_MAT_FUN_ADD_HPP

#include <stan/math/prim/mat/fun/Eigen.hpp>
#include <stan/math/prim/mat/err/check_matching_dims.hpp>

namespace stan {
namespace math {

/**
 * Return the sum of the specified matrices.  The two matrices
 * must have the same dimensions.
 * @tparam T1 Scalar type of first matrix.
 * @tparam T2 Scalar type of second matrix.
 * @tparam R Row type of matrices.
 * @tparam C Column type of matrices.
 * @param m1 First matrix.
 * @param m2 Second matrix.
 * @return Sum of the matrices.
 * @throw std::invalid_argument if m1 and m2 do not have the same
 * dimensions.
 */
template <typename T1, typename T2, int R, int C>
inline auto
add(const Eigen::Matrix<T1, R, C>& m1, const Eigen::Matrix<T2, R, C>& m2) {
  check_matching_dims("add", "m1", m1, "m2", m2);
  return (m1 + m2).eval();
}

/**
 * Return the sum of the specified matrix and specified scalar.
 *
 * @tparam T1 Scalar type of matrix.
 * @tparam T2 Type of scalar.
 * @param m Matrix.
 * @param c Scalar.
 * @return The matrix plus the scalar.
 */
template <typename T1, typename T2, int R, int C>
inline auto
add(const Eigen::Matrix<T1, R, C>& m, const T2& c) {
  return (m.array() + c).matrix().eval();
}

/**
 * Return the sum of the specified scalar and specified matrix.
 *
 * @tparam T1 Type of scalar.
 * @tparam T2 Scalar type of matrix.
 * @param c Scalar.
 * @param m Matrix.
 * @return The scalar plus the matrix.
 */
template <typename T1, typename T2, int R, int C>
inline auto
add(const T1& c, const Eigen::Matrix<T2, R, C>& m) {
  return add(m, c);
}

}  // namespace math
}  // namespace stan
#endif
```

## Expected Output

Should be no change in output.

## Additional Information

None

## Current Math Version
v2.18.0

**Comment by bob-carpenter** [comment]
This would be great.  There are a bunch of related C++11 issues.

**Comment by rok-cesnovar** [comment]
Isnt this a duplicate issue of #1010 ?

**Comment by bgoodri** [comment]
Yeah, mostly. I didn't see #1010 . We can close this one an add replacing a lot of the type promotion in Boost to `auto` to #1010.
