### ISSUE TITLE
GoodGammaP Test broken on GCC 7.3

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#1063]
This came up on [this other issue](https://github.com/stan-dev/math/issues/943) - I think @bgoodri knew what was going on in these tests. He mentioned that the implementation of the function is fine, it's just our tests that are broken.

Here is a link to a test run with that (it happens to be using MPI, but these errors also exist without MPI): http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1059/8/pipeline

**Comment by bob-carpenter** [comment]
Is there a suggested fix?

**Comment by bob-carpenter** [comment]
@bgoodri --- can you say more about what the behavior should be as the argument approaches zero (I know you explained it to me in person, but I failed to take notes).

If we use the `std::lgamma`, we have to deal with its lack of thread safety to be safe with threaded MPI.  

```
The POSIX version of lgamma is not thread-safe: each execution of the function stores the sign of the gamma function of arg in the static external variable signgam. Some implementations provide lgamma_r, which takes a pointer to user-provided storage for singgam as the second parameter, and is thread-safe.
```

The only non-threadsafe standard library functions for math functions (aside from random number generators, which we don't use), seem to be`gamma(), lgamma(), lgammaf(), lgammal()`.

I see two options here:

* keep the existing Boost implementation, which is thread safe, and clean up our tests as originally suggested in the issue, 

* replace the Boost version with `std::lgamma` and wrap all calls with a mutex (i.e., enforce our own thread safety by serializing calls to `lgamma`)

**Comment by bob-carpenter** [comment]
There's also the question about what to do with errors.  I believe Boost may throw exceptions in some cases (without explicit error policy overrides) whereas the `std::lgamma` version does not.  

Previously, we tried (not always successfully) to match the error and value behavior of the standard library.  Now, `std::lgamma` just got added to C++11, so there's no precedent.  I still think we should follow the standard library here, which would mean turning some of the exceptions into NaN returns.

**Comment by sakrejda** [comment]
@bob-carpenter this came up for me on a PR a while back: we could just explicitely set the policies when we wrap boost::lgamma and related functions into the stan::math namespace.  It's not complicated we just need to be clear about what the math lib functions _should_ do and then chase down the inconsistent expectations in the manual tests.  IIRC the auto-testing can be adjusted to give consistent results via policies, it's all the other tests for quiet NaN vs. throwing that would take longer.

**Comment by bob-carpenter** [comment]
That's what we do now---we explicitly set the policies for `boost::lgamma`. And yes, the auto-testing does give consistent results---everything's tested versus the double version, which is assumed to be correct and tested independently.

**Comment by sakrejda** [comment]
I meant consistent across functions, currently our policies for the doubles versions are not consistent across functions.  That inconsistency gets enforced by auto-testing for gradients as well.

**Comment by bob-carpenter** [comment]
> On Nov 20, 2018, at 12:19 PM, Krzysztof Sakrejda <notifications@github.com> wrote:
> 
> I meant consistent across functions, currently our policies for the doubles versions are not consistent across functions. 

Is there something specific here that you think is inconsistent? 

The C/C++ standard lib functions (e.g., lgamma which recently moved from C99 to  C++11) were designed so you'd get the same answer, including exception behavior, using either double or var.  The motivation was portability of existing code by replacing double with template parameters.

For our own built-in functions (e.g., log_sum_exp), we tended to throw with informative error messages where possible.

I'm not sure that was a good idea to do two different things here, but the error throwing behavior seemed desirable, as did not messing with standard library behavior.

Do you have a suggestion for an alternative strategy?

> That inconsistency gets enforced by auto-testing for gradients as well.

The automatic testing framework I wrote for all levels indeeds just verifies that the derivative versions have the same value and exception behavior as the primitive versions.

**Comment by sakrejda** [comment]
> Do you have a suggestion for an alternative strategy?

Yes, we should just keep wrapping functions (std:: or boost::) and accept a policy.  The default policy should throw and when functions are used as part of a stan::math function that agrees to deal with the complexity introduced by quiet NaN the policy can easily be switched to the non-throwing version at the call site.  That way it's obvious that Stan users should expect a non-recoverable numerical failure to result in a rejection of the current trajectory.  If a particular function wants to eek out the last bit of performance it can check for NaN's and continue via alternative strategies.

**Comment by bgoodri** [comment]
In this case though, Boost returning NaN for lgamma(0) is mathematical
rather than statistical. It basically means in each function in Stan Math
that calls lgamma would have to override with the statistically correct
limit at 0.

**Comment by bob-carpenter** [comment]
> On Nov 20, 2018, at 2:16 PM, Krzysztof Sakrejda <notifications@github.com> wrote:
> 
> Do you have a suggestion for an alternative strategy?
> 
> Yes, we should just keep wrapping functions (std:: or boost::) and accept a policy. 

This sounds like what we're doing now.

> The default policy should throw

That would mean that stan::math::log would behave differently than std::log, because the latter does not throw.  



> and when functions are used as part of a stan::math function that agrees to deal with the complexity introduced by quiet NaN the policy can easily be switched to the non-throwing version at the call site. That way it's obvious that Stan users should expect a non-recoverable numerical failure to result in a rejection of the current trajectory.

A NaN is not non-recoverable. You can do things like this:

real y = log(x);
if (is_nan(y)) { ... do one thing ... }
else { ... do something else ... }

>  If a particular function wants to eek out the last bit of performance it can check for NaN's and continue via alternative strategies.

So you mean we'd do something like this:

real y;
if (x <= 0) { ... do something else ... }
else { ... do one thing ... }

**Comment by sakrejda** [comment]
There are two contexts.  From Stan language I think this should be available:

```
real y = log(x) 
```

If you get a failure (e.g.-`x=0`) then you get a throw and rejection like you currently do.

In the math library you might want this behavior too so you should be able to do

```
double y = log(x);
```

Sometimes in the C++ in the math library you might want to recover from a `NaN` so you could carry out an alternative calculation:

```
real y = log(x, policy = quietNaN);
if (is_nan(y)) { z = slow_calculation(x) }
else {z = fast_calculation(y) }
```

So if you're writing C++ you get sensible defaults and can use an alternative policy if you need it.  If you're writing Stan code you get the training wheels and you have to live with them (e.g.-if you want something more robust in Stan you might need to figure out what regions of `x` are problematic and switch on that).

**Comment by sakrejda** [comment]
> That would mean that stan::math::log would behave differently than std::log, because the latter does not throw.

The standard library seems to be taking a different path than what we need.  We expect Stan language users to code complex math in hard-to-test contexts and they will benefit from solid error messages.  Between quietNaN and a thread-unsafe lgamma I'm not sure what the standard library is going for (pure speed probably).

**Comment by bgoodri** [comment]
I don't think

real y = log(x);

should throw an error if x is a real number that happens to be zero. You
should get the correct limit, which is negative_infinity(). Same thing with
lgamma at zero, you should get positive_infinity, which is what C++11 gives
you but not Boost by default policy.

**Comment by bob-carpenter** [comment]
> If you get a failure (e.g.-x=0) then you get a throw and rejection like you currently do.

That won't throw, it'll return negative infinity.  Providing a negative or NaN value will return NaN.  That's because it's a built-in library function and we set things up initially so that our autodiff functions have the same throw behavior as the library functions.  That meant we had to go and add the no-throw policies to Boost, which by default throw exceptions.

> a thread-unsafe lgamma 

I'm not sure it's not thread safe in every context we use.  That's why I want to know what that cryptic message in the spec for lgamma means.  Also, that's the *only* function in the standard math library that is not thread safe.

The version of `lgamma` for which I just posted a PR follows the behavior of (a) returning infinity at non-positive intger valued (not necessarily integer typed) inputs, and (b) returning NaN rather than throwing in cases of a NaN input.

We could change this behavior, but I'd rather do that in a backward-compatiblity breaking move for Stan 3.

**Comment by bob-carpenter** [comment]
> I'm not sure what the standard library is going for (pure speed probably).

I think it's a least common denominator.   

You can wrap the standard library `log()` as

```
if (isnan(x) || x < 0) throw ... whatever you like ...
return std::log(x);
```

It's harder the other way around precisely because C++ doesn't have functions declare the exception types they throw.  So you have to evaluate the whole call graph to figure out where exceptions might arise, and some of that code may not be yours.  So nested functions might, say, run out of memory and throw that exception, which should be handled differently than a negative input to `log`. 

This is why operations like Google [forbid exceptions in their C++ coding standard](https://google.github.io/styleguide/cppguide.html#Exceptions) (with an exception for Windows).  That forces one to go back to old C-style patterns of return codes and gotos to cleanup blocks.  The link has their motivation.

https://google.github.io/styleguide/cppguide.html#Exceptions

**Comment by sakrejda** [comment]
> That won't throw, it'll return negative infinity.

Yes I meant to write `x<0`,

> We could change this behavior, but I'd rather do that in a backward-compatiblity breaking move for Stan 3.

OK

> I think we may be OK in every version of the C++ standard library we use. 

Right, what I'm pointing out is that when you do this, you're taking on the responsibility of **checking** this as the standard library implementations evolve.  That checking is what we tried to minimize when we narrowed down which compilers are supported so in my opinion we shouldn't use std lib functions that explicitly say they might produce hard-to-find-and-rare bugs when a library is updated: our users don't need that.

> So nested functions might, say, run out of memory and throw that exception, which should be handled differently than a negative input to log.

I've run into the Google style guide recommendation against exceptions before but they also [want at most c++11](https://google.github.io/styleguide/cppguide.html#C++_Version) so they're not the best match for Stan in terms of math lib policies.  We can throw a different exception for out-of-memory vs. out-of-domain operations. 

 I know that some guidelines recommend _not_ using self-defined exceptions in library code because library clients won't know what to do with them.  OTOH we're not just a library, Stan is a whole stack so we can shepherd appropriate handling of exceptions through to the interfaces.  We would only need a few Stan-specific things (out-of-domain, maybe catastrophic accuracy failures, out-of-memory, etc..).  

More on the std lib math functions:

They seem to recommend the style where you check error codes, and there's some consistency in the use of domain errors and pole errors:

https://en.cppreference.com/w/cpp/numeric/math/math_errhandling

So by propagating NaN's (when it's really out-of-domain we're not even using the "correct" pattern for the std libraries.  We do have a policy around checking domain and throwing but it's only applied to user-level-ish functions.

**Comment by sakrejda** [comment]
> That's true of all the implementations we use. Boost isn't exactly guaranteeing backward compatibility of error codes in perpetuity.

They would document that though, but lgamma become thread-unsafe is not something they'd need to document (e.g.-I just looked at some of the std lib lgamma code on my laptop and the extern signgam _is_ stored but not necessarily used, and there's another implementation that takes a pointer to signgam and therefore can use a local one w/o bothering with thread-local storage.  This is in math.h, no sure which one Stan would pull in.  So after a few minutes that's potential for garbled results unless they only set it at the end of the lgamma function call.

**Comment by seantalts** [comment]
Anyone have leads on this? The EC2 node situation we had that was allowing us to test MPI on Linux seems over for now, so we need to get this working to be able to do Math PRs (or remove the Linux MPI tests. The MPI tests are the problem because they have to use the system compiler, which for the Linux box is now gcc 7 or 8 since we upgraded it to a newer Ubuntu LTS).

**Comment by seantalts** [comment]
Doesn't seem like merging #1080 fixed it: http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1111/6/pipeline

**Comment by seantalts** [comment]
Wrote up a summary on another issue:
> @bgoodri and I were just talking about it / working on it. It's something to do with gcc 7, which the MPI tests use because they always use the system compiler right now (as recommended by @wds15). Ben is running the full unit tests locally with GCC 8 as that compiler doesn't seem to trigger this failure. GCC 7 with -O2 also doesn't trigger this failure. So a theory is that there is a gcc7 bug we've stumbled into only on high optimization and we may be able to just run tests with 8.

@bgoodri wrote:
> There is still some bug with autodiff_tester under mix with g++-8, although it gets past the gamma_p thing and passes test/unit/math/{prim, rev, fwd}. The new error is

```
make: 'test/unit/math/mix/core/operator_addition_test' is up to date.
Running main() from lib/gtest_1.8.1/src/gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from mathMixCore
[ RUN      ] mathMixCore.opratorAddition
./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102842023e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102842023e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102845976e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102845976e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102849928e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102849928e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102853881e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102853881e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102853881e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: inf
  x2
    Which is: 4.68095e-310
expect_near(inf, 4.6809511102853881e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(-nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102857833e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102857833e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102857833e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(-nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:72: Failure
Expected equality of these values:
  x1
    Which is: -inf
  x2
    Which is: 4.68095e-310
expect_near(-inf, 4.6809511102857833e-310)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

./test/unit/math/mix/mat/util/autodiff_tester.hpp:68: Failure
Value of: is_nan(x1) && is_nan(x2)
  Actual: false
Expected: true
expect_near(nan, 0)
gradient_fvar fx == fx_ad

[  FAILED  ] mathMixCore.opratorAddition (2 ms)
[----------] 1 test from mathMixCore (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] mathMixCore.opratorAddition

 1 FAILED TEST
------------------------------------------------------------
make -j1 test/unit/math/mix/core/operator_addition_test
------------------------------------------------------------
test/unit/math/mix/core/operator_addition_test --gtest_output="xml:test/unit/math/mix/core/operator_addition_test.xml"
```
> which looks like pure uninitialized / undefined mistakes somewhere.

**Comment by seantalts** [comment]
Yeah, those simple mixed mode addition test failures expecting `nan` to be near `0` seem really bad for either mixed mode or the autodiff tester (possibly under mixed mode only). @bob-carpenter do you have any ideas on how to dig further here?

Also curious that it keeps expecting `inf` and `-inf` to be near numbers that are ~ `4e-310`.

**Comment by bgoodri** [comment]
Also, too, it is fine with anything other than O=3.

**Comment by bob-carpenter** [comment]
It may be different implementations.  We just switched out gamma elsewhere and don't know if it relates to this.  1e-310 is getting about as low as a number can get without underflowing.  It then get down to normalized (leading base digit is 1) vs. unnormalized representations.  The latter let you get smaller at the cost of lack of precision.  Different libraries treat these differently.  For example, Boost's lexical cast thing can't handle unnormalized representations but the standard library seems to be able to.

**Comment by bgoodri** [comment]
We have gotten past the gamma_p error. The current error is with addition
in the mixed case but only with NaNs and Infs.

**Comment by bgoodri** [comment]
Initializing some Eigen::VectorXd to zero in autodiff_tester fixes the
problem with operator_addition under g++-8

**Comment by seantalts** [comment]
Which one(s)?

**Comment by bgoodri** [comment]
I fixed them on dc6a20b143 of the boost1.69.0 PR

**Comment by bgoodri** [comment]
That is fine, although there are plenty of other instances where we are
passing in uninitialized values that we just haven't gotten bit yet.

**Comment by seantalts** [comment]
Do you think we should just always be initializing in places like [this](https://github.com/stan-dev/math/blob/develop/stan/math/mix/mat/functor/finite_diff_grad_hessian.hpp#L50)?

**Comment by bgoodri** [comment]
I think we should always be initializing everywhere, even if it is not
currently manifesting itself in bug reports. It is undefined behavior.

**Comment by bob-carpenter** [comment]
> I think we should always be initializing everywhere, even if it is not
> currently manifesting itself in bug reports. It is undefined behavior.

+1.
