### ISSUE TITLE
allow time in integrate_ode calls to be autodiff variables

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#1071]
## Description
The integrate functions currently do now allow to have the initial time or the time vector to be varying. However, in some applications in can be useful to allow the observation time to be varying.

## Example

Right now the initial time and the time vector passed to the integrate_ode function must be data (double) and it would be good to relax this.

## Expected Output

Same output as before, just allow more cases to be handled by the integrate calls.

## Additional Information
Any additional information goes here.

## Current Math Version
v2.18.0

**Comment by syclik** [comment]
@wds15: I just renamed the issue. Is the title still descriptive? It used to be "allow time as varying in integrate_ode calls"

**Comment by wds15** [comment]
Sure...title is better like this. Btw, this feature is important to get lag times in pk models going.

**Comment by syclik** [comment]
Just to be clear, this would allow either the initial time or the times or both to be autodiff variables? Are there specialization for each of those cases? (So are we looking at 4 different implementations?)

**Comment by wds15** [comment]
This has been merged. So closing.
