### ISSUE TITLE
Bug in map_rect_concurrent(); depends on number of threads and number of shards

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#1075]
## Description
This is the bug that's causing stan-dev/stan#2708.

This bug occurs when threading is turned on and the number of threads is some function of the number of shards.

It occurs in the [`map_rect_concurrent()`](https://github.com/stan-dev/math/blob/develop/stan/math/prim/mat/functor/map_rect_concurrent.hpp#L71) function and this function returns an Eigen vector that is short one element. (`Eigen::Matrix<T, -1, 1>`, but the runtime size is off by one.)

## Example

As we dig, we need a reproducible example in C++, but for now, please see the Stan program in the Stan bug report: stan-dev/stan#2708.

## Additional Information
Thanks, @ermeel86, for uncovering this bug!

## Current Math Version
v2.18.0

**Comment by ahartikainen** [comment]
Are these correct

    const int num_big_threads
        = (num_jobs - num_jobs_per_thread) % (num_threads - 1);

and

    for (int i = 1, job_start = num_jobs_per_thread, job_size = 0;
                i < num_threads; ++i, job_start += job_size) {
         job_size = i >= first_big_thread ? num_jobs_per_thread + 1
                                       : num_jobs_per_thread;
        futures.emplace_back(
             std::async(std::launch::async, execute_chunk, job_start, job_size));
    }

Should the first block be

    const int num_big_threads
        = num_jobs - num_jobs_per_thread * num_threads;

And should the second loop start from 0? TBH not sure about what is going on here, but I think the `job_size` is off-by-one for some chunks if the `num_big_threads` is wrong.

Some tests with Python

    num_threads = 6
    for num_jobs in range(num_threads, 3*num_threads):
        num_jobs_per_thread = num_jobs // num_threads
        print(num_jobs - num_jobs_per_thread * num_threads, (num_jobs - num_jobs_per_thread) % (num_threads - 1))

```
0 0
1 1
2 2
3 3
4 4
5 0
0 0
1 1
2 2
3 3
4 4
5 0
```


    num_threads = 2
    for num_jobs in range(num_threads, 3*num_threads):
        num_jobs_per_thread = num_jobs // num_threads
        print(num_jobs - num_jobs_per_thread * num_threads, (num_jobs - num_jobs_per_thread) % (num_threads - 1))

```
0 0
1 0
0 0
1 0
```

So it might just be a play between  the `num_jobs` and `num_threads` which is easier to hit with lower number of threads.

**Comment by ahartikainen** [comment]
Actually

    const int num_big_threads
    = num_jobs - num_jobs_per_thread * num_threads;

This is same as

    const int num_big_threads
    = num_jobs % num_threads;

**Comment by sakrejda** [comment]
@ahartikainen I reviewed this code for @wds15 when it was merged and I even remember going back and forth about how to code it.. if this is the bug no idea how it made it in there!  I recall the motivation was that the main thread should have fewer jobs than the rest of the threads (?) but I haven't reproduced your suggestion about the error yet.  I'll try to look at it tonight.

**Comment by ahartikainen** [comment]
I tested this with the stan example ( https://github.com/stan-dev/stan/issues/2708 ) and after making the change to

    const int num_big_threads = num_jobs % num_threads;

there are no errors anymore.

**Comment by wds15** [comment]
Thanks to everyone looking into this! We should check the mpi variant as well, just to make sure. I don’t Have time right now to work on this. Should someone file a pr Before i get to it, then I am happy to review.

**Comment by sakrejda** [comment]
I have a fix just making tests, I'll do a pr.

**Comment by bob-carpenter** [comment]
Can you close Stan issue 2708 if this is the fix for it?  Or does it need another fix in the stan-dev/stan repo?

**Comment by bob-carpenter** [comment]
Is there going to be a PR for Stan with appropriate tests that fail now and succeed after the fix?  If not, I'd close it.  But it's up to you either way.

**Comment by syclik** [comment]
I wasn't thinking about that, but I think that's the right thing to do. I
believe we already have tests for threading at the Stan level. If not, we
should have some.

So, yes, let's keep the issue on Stan open. I can think about what tests to
add there so we verify that this is fixed (and won't be broken again for
the exact same reason).
