### ISSUE TITLE
Upgrade to Boost 1.69.0

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#1081]
## Description

Math should use Boost 1.69.0 because

https://github.com/boostorg/math/issues/134

fixes a build error with `integrate_1d` on Solaris.

## Example

Try to use `integrate_1d` on Solaris

## Expected Output

A value of the integral

## Additional Information

None

## Current Math Version
v2.18.0

**Comment by andrjohns** [comment]
closed via #1082
