### ISSUE TITLE
[Windows] Makefile dependencies don't seem to be working quite right?

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#1087]
## Description
It looks from [the test runs](http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/Math%20Pipeline/detail/develop/198/pipeline/88) like, on Windows, the makefiles only suffice to keep one or two files from being remade when make is called twice in a row. This calling of make twice in a row happens during a typical test run nowadays because we added a `--make-only` flag to `runTests.py` which will not actually run the tests, just make them; we then wrote in the `Jenkinsfile` that we should make all tests with `--make-only` and then run them as normal. That 2nd normal `runTests.py` invocation (without `--make-only`) will ask make to remake the targets; on Linux and Mac this works fine but on Windows you can see almost all of them get rebuilt. 

## Proposed solution
I can see two paths forward:
1) figure out how to fix Make on Windows to work as it does on *nix (seems hard)
2) On Windows, opt out of this --make-only step, which was put in to help end-users diagnose error conditions.

## Current Math Version
v2.18.0

**Comment by syclik** [comment]
@seantalts, yeah, it's definitely a bug.

Here's what I'm doing to isolate and reproduce it:
```
>make test/unit/math_c11_test.exe
g++ -std=c++1y -m64 -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs     -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.66.0 -I lib/sundials_3.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1   -D_USE_MATH_DEFINES  -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE  -c -o test/unit/math_c11_test.o test/unit/math_c11_test.cpp
g++ -std=c++1y -m64 -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs     -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.66.0 -I lib/sundials_3.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1   -D_USE_MATH_DEFINES  -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE         test/unit/math_c11_test.o lib/gtest_1.8.1/src/gtest_main.cc lib/gtest_1.8.1/src/gtest-all.o  -static-libgcc -static-libstdc++      -o test/unit/math_c11_test.exe
```

On multiple runs, that should just run without needing to rebuild. I'll take a look... it might be as simple as a typo somewhere in the latest pull request.

Here's what it looks like on Mac:
```
$ make test/unit/math_c11_test
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.66.0 -I lib/sundials_3.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION    -DGTEST_USE_OWN_TR1_TUPLE         test/unit/math_c11_test.o lib/gtest_1.8.1/src/gtest_main.cc lib/gtest_1.8.1/src/gtest-all.o        -o test/unit/math_c11_test

$ make test/unit/math_c11_test
make: `test/unit/math_c11_test' is up to date.
```

**Comment by syclik** [comment]
And... I found out why it's not working: the dependency file generates this:
```
test/unit/math_c11_test.o: test/unit/math_c11_test.cpp gtest/gtest.h
```
but it should really be generating something like this:
```
test/unit/math_c11_test.o: test/unit/math_c11_test.cpp lib/gtest_1.8.1/include/gtest/gtest.h
```

It doesn't know how to resolve `gtest/gtest.h` so it thinks it has to rebuild everything.
