### ISSUE TITLE
Cleanup and Breakup Rev Cholesky Code

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1094]
## Description

In the cholesky rev file below we currently have 2 different evaluation methods (`cholesky_block` and `cholesky_scalar`). With the gpu code coming in as well I'd like to clean these up by moving the block and scalar classes to their own files. We will do the same thing for the gpu code as well.

https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/fun/cholesky_decompose.hpp

Does anyone have objections to this?

#### Current Version:
v2.18.1

**Comment by seantalts** [comment]
Why do you want them to be in their own files?

**Comment by SteveBronder** [comment]
Ah ic my bad, I assumed breaking them up into more files would be more accessible. As I put the gpu code in it seemed like there was a lot going on, but if your past experience makes you think that is too much then we can not do this
