### ISSUE TITLE
The MPI implementation doesn't correctly stop listening

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#1109]
## Description
There's currently a bug in how our current MPI handles its resources.

This call to `boost::mpi::broadcast()` is incorrect:
https://github.com/stan-dev/math/blob/develop/stan/math/prim/arr/functor/mpi_cluster.hpp#L225

The second argument, `command`, needs to be `*command` because `command` is a `std::shared_ptr`

## Example
I need to come up with a MWE, but under certain circumstances, I was seeing different messages depending on the environment I ran on. Under Mac, I'm seeing this:
```
libc++abi.dylib: terminating with uncaught exception of type boost::archive::archive_exception: unregistered class - derived class not registered or exported
Abort trap: 6
```

It doesn't stop the actual run because as far as I can tell, we only use these commands to set up cluster locks.

#### Current Version:
v2.18.1

**Comment by wds15** [comment]
No, I think this is all correct. We have to sue pointers to get boost serialization to ship a virtual base class. On the respective recieving end we also read shared pointers.

The error you report sound like as if you did not have the right instantiations baked into you binary. For every command you want to send you have to call the `STAN_REGISTER_COMMAND` macro here:

https://github.com/stan-dev/math/blob/develop/stan/math/prim/arr/functor/mpi_command.hpp#L47

Failing to call it will cause the errors your report.

**Comment by syclik** [comment]
Thanks. I'll do some more investigation. I'm not convinced yet.

**Comment by syclik** [comment]
@wds15, correction, you're right. Linking can be order-dependent.
