### ISSUE TITLE
Documenting, testing and cleanup of metaprograms

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1122]
## Description

Some metaprograms in `meta` subfolders are missing documentation and/or tests. @syclik mentioned this in on Discourse https://discourse.mc-stan.org/t/help-with-the-math-library/7390/.

I will post the list of files that need commenting and those that have no tests in their respective `test/unit/math/` as a response to this issue.

Other minor cleanup stuff that I noticed while doing a thorough check:

- [x] [prim/scal/meta/seq_view.hpp](https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/seq_view.hpp) is an empty file and should be removed. 
- [x] ~~[prim/scal/meta/scalar_seq_view.hpp](https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/scalar_seq_view.hpp) should could be renamed (not sure on this) to seq_view~~
- [ ] `prim/arr/VectorBuilderHelper`, `prim/scal/VectorBuilder`, `prim/scal/VectorBuilderHelper`,  `prim/scal/StdVectorBuilder` should be  in snake_case not camelCase
- [x] replace the use of boost with the std lib equivalent where applicable
- [x] simplify `is_var_or_arithmetic`, `contains_nonconstant_struct` and others by using C++11 parameter packs (mentioned by @syclik in #1127)
- [ ] resolve the inconsistent namespaces for the metaprograms (or at least create some guidelines on when to use which namespace)
- [ ] create a matrix_return_type for cases like [this](https://github.com/stan-dev/math/pull/1185/files#diff-47fd23464dc444b604d42a25edfc1d8fR65)
- [x] ~~make a parameter packs version of `is_constant_struct`~~ consolidate all metaprograms that deal with type being constant to use `is_constant_all`

## Expected Output

Documented structs, functions, classes and cleaned up minor stuff related to `meta` subfolders.

#### Current Version:
v2.18.1

**Comment by rok-cesnovar** [comment]
Files that are missing comments. * denotes that only some functions are missing comments or that the comments should be "doxygenized".
```
fwd/mat
	operands_and_partials
fwd/scal
	ad_promotable
	is_fvar
	operands_and_partials*
	partials_type
prim/arr
	contains_std_vector
	get
	index_type
	is_constant_struct
	is_vector
	length
	scalar_type
	VectorBuilderHelper
prim/mat
	empty_broadcast_array
	get
	is_constant_struct
	is_vector
	length_mvt
	length
	operands_and_partials
	scalar_type
	seq_view
prim/scal
	broadcast_array*
	contains_fvar
	contains_nonconstant_struct
	contains_std_vector
	contains_vector
	error_index
	get
	is_constant_struct*
	is_fvar
	is_var_or_arithmetic
	is_var
	is_vector
	length
	likely
	max_size_mvt
	max_size
	partials_type
	scalar_type_helper_pre
	scalar_type
	size_of
	VectorBuilder*
	VectorBuilderHelper*
rev/mat
	operands_and_partials
rev/scal
	ad_promotable
	is_var
```

**Comment by rok-cesnovar** [comment]
Files in `meta` subfolders that are missing tests in the respective `test/unit/math/` subfolder.
```
fwd/scal
	is_fvar
prim/arr
	index_type
prim/mat
	append_return_type
	empty_broadcast_array	
	length_mvt
	operands_and_partials	
prim/scal
	broadcast_array
	index_type
	is_fvar
	is_var_or_arithmetic
	is_var
	length_mvt
	likely
	max_size_mvt
	max_size
	partials_type
	scalar_type_pre
	size_of
	value_type
rev/scal
	is_var
	operands_and_partials
	partials_type
```

**Comment by rok-cesnovar** [comment]
@seantalts @syclik (@ anyone with an opinion on this) I want to tackle the cleanup of metaprograms via parameter packs first, but would like your input before I dive to deep.

In [containst_nonconstant](https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/contains_nonconstant_struct.hpp) meta program, if we wanted to use parameter packs we essentially have the same problem as [here](https://stackoverflow.com/questions/29603364/type-trait-to-check-that-all-types-in-a-parameter-pack-are-copy-constructible). There are some other similar stackoverflow questions that basically all come back to this one and the 2 solutions written here. Does anyone have any preference on which one would we want to use if any?

**Comment by syclik** [comment]
Thanks for looking up two sensible solutions. I think both would work.

When I look at it, the first one makes a lot of sense to me: https://stackoverflow.com/a/29603857/1762960

One reason that makes sense is that it uses a pattern that will be introduced in C++17. See the first comment to the answer below: https://stackoverflow.com/a/39701423/1762960

Both look fine and they shouldn't have any difference at runtime. (I have no intuition about compiler times.) And I don't see both implementations and see one as being that much easier to understand or to code than the other. So, either one is fine by me.

In this case, it should simplify the code quite a bit and be more general, both of which are awesome.

**Comment by rok-cesnovar** [comment]
@syclik sorry to keep pinging you, I have another question regarding the cleanup. 

It seems that not all metaprograms are in the stan::math:: namespace but are rather in the stan:: namespace. Is this by design and I am missing something or should this be cleaned up as well?

**Comment by syclik** [comment]
@rok-cesnovar: no bother at all!

We had originally put all the metaprograms in the `stan::` namespace, not `stan::math::` namespace. It's been a while since we tracked that very carefully, so it's possible that things were added inconsistently.

I think the first thing to do is to take a quick inventory? I think the other thing that might be happening is that there are functions in meta that aren't really template meta programs. Some of them are runtime programs now, I think. I haven't thought through that far....

**Comment by rok-cesnovar** [comment]
```
fwd/mat
	operands_and_partials	stan::math::internal

fwd/scal
	ad_promotable		stan::math
	is_fvar			stan
	operands_and_partials	stan::math::internal
	partials_type		stan

prim/arr
	contains_std_vector	stan
	get			stan
	index_type		stan::math
	is_constant_struct	stan
	is_vector		stan
	length			stan
	scalar_type		stan
	value_type		stan::math
	VectorBuilderHelper	stan

prim/mat
	append_return_type	stan::math
	broadcast_array		stan::math::internal
	get			stan
	index_type		stan::math
	is_constant_struct	stan
	is_vector_like		stan
	is_vector 		stan
	length_mvt		stan
	length 			stan
	operands_and_partials	stan::math::internal
	scalar_type		stan
	seq_view 		stan::math
	value_type		stan::math
	vector_seq_view		stan

prim/scal
	ad_promotable				stan::math
	broadcast_array				stan::math::internal
	child_type				stan::math
	contains_fvar				stan
	contains_nonconstant_struct		stan
	contains_std_vector			stan
	contains_std 				stan
	error_index				stan
	get					stan
	include_summand				stan::math
	index_type				stan::math
	is_constant_struct			stan
	is_constant 				stan
	is_fvar					stan
	is_var_or_arithmetic			stan
	is_var 					stan
	is_vector_like				stan
	is_vector 				stan
	length_mvt 				stan
	length 					stan
	likely 					/
	max_size_mvt				stan
	max_size 				stan
	operands_and_partials			stan::math::internal
	partials_return_type 			stan::math
	partials_type 				stan
	return_type 				stan
	scalar_seq_view 			stan
	scalar_type_helper_pre 			stan
	scalar_type 				stan
	seq_view 				empty file
	size_of	 				stan					
	StdVectorBuilder 			stan					
	value_type 				stan::math
	VectorBuilder 				stan
	VectorBuilderHelper 			stan
rev/mat
	operands_and_partials			stan::math::internal
rev/scal
	ad_promotable 				stan::math	
	is_var 					stan
	operands_and_partials    		stan::math::internal
	partials_type 				stan
```

**Comment by syclik** [comment]
whoa... yeah, we let some things sneak into `stan::math` and `stan::math::internal`.

I'm not sure what we should do to be consistent without looking deeply. Suggestions?

**Comment by rok-cesnovar** [comment]
My suggestion would be to either: 
- have them all in the same workspace,  `stan`, `stan::math` or `stan::math::internal`
- define a set of rules/guidelines of when to use each of the 3 namespaces we currently have

I added this to the issue so it doesnt get burried by something else over time.

**Comment by syclik** [comment]
Thanks. I think that’s absolutely the right assessment. My guess: the functions that are not template meta programs are in the stan::math namespace (and probably should be moved to the fun/ directory). But that’s just a guess. We can look through these together.

**Comment by seantalts** [comment]
The stuff in `stan::math::internal` is not part of even the metaprogram API; that namespace is for hiding implementation details. The stuff that lives there now should continue to live there, but you'll notice it's not the entirety of e.g. `operands_and_partials` but just the various edge implementations.

**Comment by rok-cesnovar** [comment]
After #1186 was merged, te only metaprogram code that is without test is `prim/scal/scalar_type_pre`.

**Comment by rok-cesnovar** [comment]
I am going to close this as all the major stuff listed here was fixed and I am not too sure on whether we really need to do the snake_case vector builder renaming. If anyone feels that is still required we can open another, smaller issue.
