### ISSUE TITLE
Stuff to do before making GPU announcement

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1133]
There's a list of a few smaller open issues we want to address before we make a formal announcement that we have GPU stuff now.

#### Blocking:

-------------

- [x] Change the folder name to `opencl` and the matrices from `matrix_gpu` to `matrix_cl`
  - The OpenCL stuff can also use CPUs, so I think it's appropriate we change this
- [x] Make sure the install instructions in the wiki are clear and correct
  - I think this is mostly good, but I want to spin up a docker container / aws instance and go through them to make sure the instructions make sense. We could probably even include a gist to an install script for aws.
- [ ] Make a commit to Cmdstan with the right compile flags
#### Non-blocking but still to-do

----------------------------

- [ ] Add higher level support for tuning the parameters in the GPU code during model warmup. (possibly allow users to set those)
- [ ] Run sampling tests on a few example models and tuning parameters for sanity checks
  - How to do this will probably be the biggest discussion in this issue, I'll review below how we are thinking about this.

#### Things to talk about on Thursday March 7th Meeting

---------------------------------------
 
- [x] Discuss how to push this up to cmdstan, Rstan and Pystan
- [ ] Add to Seans repo for performance tests so easier to test branches of the math library
- [ ] Reach out to Nvidia / Khronos Group about joint press release (?)

Is there anything else I'm missing here?

**Comment by rok-cesnovar** [comment]
I will tackle the renaming stuff today.

**Comment by bob-carpenter** [comment]
Thanks a lot for laying this out.  I'm really looking forward to GPU support!

> On Mar 1, 2019, at 8:04 PM, Steve Bronder <notifications@github.com> wrote:
> 
> There's a list of a few smaller open issues we want to address before we make a formal announcement that we have GPU stuff now.
> 
> Blocking:

...

> Non-blocking but still to-do

...

**Comment by syclik** [comment]
I was trying to run doxygen from `develop` and it failed. It looks like it's coming from the GPU code:
```
$ make doxygen
mkdir -p doc/api
doxygen doxygen/doxygen.cfg
.../math/stan/math/opencl/kernels/sub_block.hpp:41: error: argument 'src_rows' from the argument list of stan::math::opencl_kernels::sub_block has muliple @param documentation sections (warning treated as error, aborting now)
make: *** [doxygen] Error 1
```

Could someone verify that this is happening? If it runs correctly for you, then maybe something's misconfigured on my end.

**Comment by SteveBronder** [comment]
I'm not getting this error, but I am seeing a doxygen error for the place that you posted in #1139 . Oddly, I swear I ran doxygen before that branch merged and it was fine. Though if I go back to the pre gpu rev commit 5f5bbf4f43dce0cbd9d94ee2bc35f98e28f9e00b the doxygen compiles fine. I'll try to trace where this happened

**Comment by syclik** [comment]
if you're not getting it, don't worry about it for now. No need to get sidetracked on this if it's not your problem.

**Comment by SteveBronder** [comment]
Correction: I am seeing the doxygen error from matern32 before 5f5bbf4f43dce0cbd9d94ee2bc35f98e28f9e00b (before gpu rev stuff). If you need any help trying to trace this lemme know. Looked at the latex the matern32 doc produces in an online latex compiler and, though latex does complain for a bit, it does produce results.

**Comment by rok-cesnovar** [comment]
I can confirm that the instructions work on:

- an Ubuntu AWS GPU instance (working on potentially having a CmdStan AMI as Steve suggested)
- a clean Windows installation with NVIDIA GPU
- a clean Windows installation with an AMD GPU

Everything worked fine, except for the last one, the path to the lib file in the provided (and latest) AMD APP SDK is `"$(AMDAPPSDKROOT)lib\x86_64"` not `"$(AMDAPPSDKROOT)lib\x64"`. I fixed it in the Stan Math Wiki.

I dont have access to a Mac+GPU machine to test unfortunately.
