### ISSUE TITLE
Doxygen errors on develop

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#1139]
## Description
Running `make doxygen` fails on `develop` right now.

There are a few things we need to do:
1. check why Jenkins is letting this pass; fix it so it prevents errors from getting through
2. fix the problems.

## Example
```
make doxygen
...
Package amsmath Warning: Foreign command \atopwithdelims;
(amsmath)                \frac or \genfrac should be used instead
(amsmath)                 on input line 71.

[20] [21] [22] [23] [24] [25] [26] [27] [28] [29] [30] [31]
! Missing { inserted.
<to be read again> 
                   \endgroup 
l.107 ...qrt{\sum_{k=1}^{K}\frac{d(x, x')^}{l_k^2}
                                                  }) exp(-\sqrt{3}\sqrt{\sum...
```
and it hangs.

I'm also seeing this behavior on our Jenkins box for a recent `develop` run: http://d1m1s1b1.stat.columbia.edu:8080/blue/rest/organizations/jenkins/pipelines/Math%20Pipeline/branches/develop/runs/226/nodes/49/log/?start=0

## Expected Output

We shouldn't be having doxygen errors.

#### Current Version:
v2.18.1

**Comment by syclik** [comment]
cc:
- @seantalts - any ideas on how to get Jenkins to stop the build?
- @drezap - this error looks like it's coming from `gp_matern32_cov.hpp` and it's malformed latex. Mind taking a look?

**Comment by syclik** [comment]
for anyone working on this, I've got a branch open: `bugfix/issue-1139-doxygen-errors`

**Comment by seantalts** [comment]
If you're logged in, there's a square in a circle near the top right of the
blue ocean screen.

**Comment by syclik** [comment]
So... running locally, I’m seeing make doxygen hang with the same output as
our Jenkins processes.

There’s a LATEX_BATCHMODE setting we can turn on, which will get past that,
but I haven’t determined whether it’s actually just swallowing the error or
if we can safely ignore the regular process wanting user input.

**Comment by drezap** [comment]
I'm on it

**Comment by syclik** [comment]
Thanks. I can’t even tell yet whether your latex is a problem. Honestly,
it’ll just help to know if it’s actually well formed latex.

**Comment by drezap** [comment]
It was not well formed latex. Pushing the commits to this branch momentarily

**Comment by SteveBronder** [comment]
Can this be closed?
