### ISSUE TITLE
Add optimization for special cases of matrix multiply for OpenCL

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1142]
## Description

For cases when we know that an input matrix has certain properties, we can optimize the OpenCL kernels significantly. 

In the near future we would like to add at least the following: 

- [x] `lower_tri` x `rect` 
- [x] `rect` x `lower_tri`
- [x] `upper_tri` x `rect`
- [x] `rect` x `upper_tri`

Where `lower_tri` and `upper_tri` are lower and upper triangular matrices and `rect` is a non-triangular matrix. These are all pretty straightforward to implement (some indexing wizardry but not much more) but reduce the multiplication execution times down to 55% of the regular OpenCL matrix multiply.

- [x]  [N, K] x [K, M] where K >>> N,M; NxM is "not large" and K is "large"

This cases do not offer as much speedup (more in the range of 10-20% depending on N,K &M).However these cases of matrix multiply come up quite often in Stan models which makes this worthwile. Large is in quotes as this are soft limits that will require a thorough performance analysis to set. 

With this issue we would also like to:

- [x] replace regular OpenCL multiply in the merged Cholesky OpenCL implementation with applicable optimizations 
- [x] investigate the possibility to check these conditions in a general matrix multiply and call the appropriate kernels if the conditions are met [ will maybe be possible with the new compiler ]
- [x] improve the `multiply_transpose` kernel with this optimizations
- [x] investigate if we can remove padding without huge impact to the overall performance

## Example
In order to use the special case of `lower_tri` x `rect` we will be able to use:
```
stan::math::matrix_cl m11(m1); // lower triangular matrix
stan::math::matrix_cl m22(m2);

auto m33 = multiply<TriangularViewCL::Lower, TriangularViewCL::Entire>(m11, m22);

```
## Expected Output

Faster OpenCL matrix multiplication for special cases that occur quite often in Stan/Stan Math.

#### Current Version:
v2.18.1

**Comment by SteveBronder** [comment]
Esoteric, but it could be cool in the overloaded `*` operator to check the matrices for these conditions and call the appropriate kernels as well as exposing them normally.

Keeps feeding into my want for doing Seans PR where we check square and symmetry conditions on data once and then keep those check results. Then for the end user and us there would be no overhead in having `*` check these conditions and do the appropriate routine.

**Comment by rok-cesnovar** [comment]
Great point, thanks! Will add to the issue to investigate this.
