### ISSUE TITLE
Use enums in OpenCL kernel parameters

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1157]
## Description

As discussed in #1143 we need to cleanup the OpenCL kernels with the use of enums where applicable. We currently use 2 enum classes in `TriangularViewCL` and `TriangularMapCL` that could also be used in the kernels. 

The `enum` values in both C++ and the kernels need to match, so they have to be added to the helpers in `helpers.hpp`. 
 
Together with this change we can also merge the copy and copy_triangular kernels as there is no real need to have them separated. There is no performance difference if we join them.

## Example

The zeros kernels signature is now

```
    __kernel void zeros(__global double* A, unsigned int rows,
                        unsigned int cols, unsigned int part) {
```
and should be 
```
    __kernel void zeros(__global double* A, unsigned int rows,
                        unsigned int cols, TriangularViewCL tri_view) {
```

## Expected Output

Cleaned up kernel parameters.

#### Current Version:
v2.18.1

**Comment by seantalts** [comment]
generally wanna follow the style guide: https://google.github.io/styleguide/cppguide.html#Enumerator_Names but we confusingly have some overrides in [this wiki](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms). We don't mention enums and what we write about classes on that wiki doesn't actually say what the style is, but I think basically your last example is probably what we should aim for.

**Comment by bob-carpenter** [comment]
> On Mar 14, 2019, at 1:42 PM, seantalts <notifications@github.com> wrote:
> 
> generally wanna follow the style guide: https://google.github.io/styleguide/cppguide.html#Enumerator_Names but we confusingly have some overrides in this wiki.

If we followed the GSG as written, we wouldn't have references or exceptions or Boost.
