### ISSUE TITLE
Typo in simplex validation message (probabilites)

### ISSUE THREAD

**Issue by helske** [stan-dev/math#1174]
## Description
There is a typo in the error message relating to the simplex parameter check:

In `math/stan/math/prim/mat/prob/multinomial_lpmf.hpp` and `stan/math/prim/mat/prob/multinomial_lpmf.hpp` there is a line
`check_simplex(function, "Probabilites parameter", theta);`
      
## Expected Output
`check_simplex(function, "Probabilities parameter", theta);`

#### Current Version:
v2.19.0

**Comment by syclik** [comment]
Thanks! Want to create a PR?
