### ISSUE TITLE
Add Intel TBB library

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#1179]
## Description
The Intel TBB (Threading Building Blocks) is used a lot in scientific computing to add optional parallelization to existing programs in a C++ framework. Key benefits for stan-math are:

- faster malloc functions which are beneficial for stan-math and in particular for threading
- work stealing queuing facilities which will optimally distribute work packets
- no more need to focus on programming with threads - the library rather abstracts those details away
- lot's of engineering went into the library to make best use of cache-locality and what not else is out there to take into account for threading.

Additional info is available at:

https://github.com/stan-dev/math/wiki/Dependency-Checklist-for-the-Intel-TBB

## Example

The first examples where we will use the library are:

- use it as a drop-in replacement for malloc to speedup programs
- code `map_rect` on the basis of `tbb::parallel_for` to get automatic sharding by the work stealing queuing.

## Expected Output

Things will run faster.

#### Current Version:
v2.19.0

**Comment by rok-cesnovar** [comment]
Not sure on all the TBB details yet, so posting this here if anyone has any idea. Could we do "speculative execution" with TBB? The largest use case for this would be in the GPU code, but it could be used elsewhere. 

So if we have 2 ways of computing something we could spawn 2 threads and whichever thread finishes successfully first can stop the other thread and we can continue on? Or do we have to wait for both threads to finish before going forward.

This wont work with anything that changes the memory arena but could potentially be plausible for everything else?

**Comment by wds15** [comment]
That's very aggressive parallelisation, but I would guess that you can do that... I would check the docs of the TBB for the term of a `task_group`.

**Comment by wds15** [comment]
addressed with PR #1180
