### ISSUE TITLE
Small wiki problem in "Adding a new function with known gradients"

### ISSUE THREAD

**Issue by andrew-matteson** [stan-dev/math#1204]
## Description
I believe the wiki, [Adding a new function with known gradients](https://github.com/stan-dev/math/wiki/Adding-a-new-function-with-known-gradients), has an error in the section "Vector function with one output".

Given the signatures of the functions to calculate value and gradient, I believe the rest of the code should be:

```
namespace stan {
    namespace math {

        double foo(std::vector<double>& x) {
            return bar::foo(x);
        }

        var foo(std::vector<var>& x) {
            std::vector<double> a = value_of(x);
            double fa = bar::foo(a);
            std::vector<double> grad_fa = bar::grad_foo(a);
            return precomputed_gradients(fa, x, grad_fa);
        }

    }
}
```

It would've been useful to me to also note the signature for this function:
```
add("foo", bare_expr_type(double_type()), bare_expr_type(bare_array_type(double_type(), 1)));
```
[I also got tripped up that that this was not a "vector" in the Stan sense, but an array of double.](https://discourse.mc-stan.org/t/trouble-adding-a-function-of-a-vector-with-known-gradients/8492/3)

#### Current Version:
v2.19.0

**Comment by ode33** [comment]
From the example how did you include `stan/math/rev.hpp`? I don't see that file.

**Comment by andrew-matteson** [comment]
Oh, yeah, that looks broken too. My includes were:

```
#include <ostream>
#include <vector>
#include <stan/math/rev/core.hpp>
```

**Comment by ode33** [comment]
Makes sense. I see that `core.hpp` is the origin of the type `var`, very interesting.

**Comment by rok-cesnovar** [comment]
This took way too long. I went ahead and fixed the wiki issues (header and replaced a with x), thank you for the report. 

I think the second part appliesto the "Adding a function to Stan" [wiki](https://github.com/stan-dev/stan/wiki/Contributing-New-Functions-to-Stan), and you can find an example there. This is just a wiki on the Stan Math part.
