### ISSUE TITLE
Implement gp_exp_quad_cov in opencl

### ISSUE THREAD

**Issue by t4c1** [stan-dev/math#1205]
## Description
`gp_exp_quad_cov()` could use GPU to be faster.

## Example
gp_exp_quad_cov is faster when using GPU.

## Expected Output
gp_exp_quad_cov is faster when using GPU.

#### Current Version:
v2.19.0

**Comment by SteveBronder** [comment]
Nice!! Could you post a performance test?

Tag me as a reviewer when this is ready to rock!
