### ISSUE TITLE
rev cov_exp_quad calls prim gp_exp_quad_cov

### ISSUE THREAD

**Issue by t4c1** [stan-dev/math#1208]
## Description
Rev implementation of `cov_exp_quad()` is implemented as a call to `gp_exp_quad_cov()`. Due to missing include it calls prim implementation instead of rev.

## Example
Compile rev unittest for `cov_exp_quad()` with debug symbols. Use debugger to step into `cov_exp_quad_dvv` test. Check which implementation of `gp_exp_quad_cov()` is called.

## Expected Output
Rev implementation of `gp_exp_quad_cov()` should be called.

#### Current Version:
v2.19.1

**Comment by drezap** [comment]
@t4c1 

Yeah I noticed this. I'm pretty familiar with this. We want the function to fall back on the `prim` version when the other isn't called. 

I've already gone through and I know which functions are not being called. Would you suggest may be another specialization that covers all cases of double/var combinations? Or what's your solution?

If I remember correctly, the current implementation will bug if we have a `double` types for `x`. I can go ahead and implement that specialization if you think that's a good solution?

**Comment by t4c1** [comment]
I have already opened a pull request with the solution. It turns out just one `#include` statement is missing. With that added compiler selects correct specialization.

**Comment by drezap** [comment]
great thanks..
