### ISSUE TITLE
Reduce strictness of floating point tests in mdivide_left_test for Intel MKL

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#121]
## Feature Request

__Version__

2.7.0

__Description__

For the tests to pass on Intel MKL, reduce the strictness of the test to `1.0e-10` (from `1.0e-12`) for `test/unit/math/rev/mat/fun/mdivide_left_test.cpp`

__Example__

replace: `EXPECT_NEAR(1.0,I(0,0).val(),1.0E-12);`
with: `  EXPECT_NEAR(1.0,I(0,0).val(),1.0E-10);`

__Additional Information__

We won't be able to verify directly. We'd need a response from Sebastian to see if this works.

**Comment by bob-carpenter** [comment]
As far as I know tests are passing on MKL now that we relaxed strictness, so I'm closing.
