### ISSUE TITLE
Problem with coupled_ode_system

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#1210]
## Description

There is a memory problem with the ~`coupled_ode_system`~ `coupled_ode_system` test; it is indexing past the end of a `std::vector`. I've only verified that this happens on one instantiation of the many different instantiations and I believe this problem may exist in some more of these instantiations.

This problem doesn't show up all the time because we've used `[]` for indexing, which does not check for bounds. By changing the implementation (at least temporarily) to use `at()` for indexing, it's clear that this problem exists.

This memory issue was masked for a long time since it's indexing into memory the process owns. It's only triggered a failed test in #1171.

This is actually a ~pretty big~ bug in the test:
1. it may cause programs to seg fault without indicating why
2. the results from using the ODEs under these conditions are undefined. It's clearly not computing the correct thing.

## Example

Check out branch `bugfix/issue-1210-coupled_ode_system`. Run:
```
./runTests.py test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp
```

Current output:
```
$ ./runTests.py test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp
------------------------------------------------------------
make -j1 test/unit/math/rev/arr/functor/coupled_ode_system_test
make: `test/unit/math/rev/arr/functor/coupled_ode_system_test' is up to date.
------------------------------------------------------------
test/unit/math/rev/arr/functor/coupled_ode_system_test --gtest_output="xml:test/unit/math/rev/arr/functor/coupled_ode_system_test.xml"
Running main() from lib/gtest_1.8.1/src/gtest_main.cc
[==========] Running 18 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 18 tests from StanAgradRevOde
[ RUN      ] StanAgradRevOde.coupled_ode_system_dv
[       OK ] StanAgradRevOde.coupled_ode_system_dv (0 ms)
[ RUN      ] StanAgradRevOde.decouple_states_dv
[       OK ] StanAgradRevOde.decouple_states_dv (0 ms)
[ RUN      ] StanAgradRevOde.initial_state_dv
[       OK ] StanAgradRevOde.initial_state_dv (0 ms)
[ RUN      ] StanAgradRevOde.size_dv
[       OK ] StanAgradRevOde.size_dv (0 ms)
[ RUN      ] StanAgradRevOde.memory_recovery_dv
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:152: Failure
Expected: coupled_system_dv(y, dy_dt, t) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] StanAgradRevOde.memory_recovery_dv (0 ms)
[ RUN      ] StanAgradRevOde.memory_recovery_exception_dv
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:180: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:166: iteration 0
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:180: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:166: iteration 1
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:180: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:166: iteration 2
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:180: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:166: iteration 3
[  FAILED  ] StanAgradRevOde.memory_recovery_exception_dv (0 ms)
[ RUN      ] StanAgradRevOde.coupled_ode_system_vd
[       OK ] StanAgradRevOde.coupled_ode_system_vd (0 ms)
[ RUN      ] StanAgradRevOde.decouple_states_vd
[       OK ] StanAgradRevOde.decouple_states_vd (0 ms)
[ RUN      ] StanAgradRevOde.initial_state_vd
[       OK ] StanAgradRevOde.initial_state_vd (0 ms)
[ RUN      ] StanAgradRevOde.size_vd
[       OK ] StanAgradRevOde.size_vd (0 ms)
[ RUN      ] StanAgradRevOde.memory_recovery_vd
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:327: Failure
Expected: coupled_system_vd(y, dy_dt, t) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] StanAgradRevOde.memory_recovery_vd (0 ms)
[ RUN      ] StanAgradRevOde.memory_recovery_exception_vd
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:355: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:341: iteration 0
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:355: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:341: iteration 1
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:355: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:341: iteration 2
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:355: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:341: iteration 3
[  FAILED  ] StanAgradRevOde.memory_recovery_exception_vd (1 ms)
[ RUN      ] StanAgradRevOde.coupled_ode_system_vv
[       OK ] StanAgradRevOde.coupled_ode_system_vv (0 ms)
[ RUN      ] StanAgradRevOde.decouple_states_vv
[       OK ] StanAgradRevOde.decouple_states_vv (0 ms)
[ RUN      ] StanAgradRevOde.initial_state_vv
[       OK ] StanAgradRevOde.initial_state_vv (0 ms)
[ RUN      ] StanAgradRevOde.size_vv
[       OK ] StanAgradRevOde.size_vv (0 ms)
[ RUN      ] StanAgradRevOde.memory_recovery_vv
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:508: Failure
Expected: coupled_system_vv(y, dy_dt, t) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] StanAgradRevOde.memory_recovery_vv (0 ms)
[ RUN      ] StanAgradRevOde.memory_recovery_exception_vv
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:536: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:522: iteration 0
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:536: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:522: iteration 1
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:536: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:522: iteration 2
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:536: Failure
Expected equality of these values:
  1
  count_matches(message, e.what())
    Which is: 0
expected message: ode throws
found message:    vector
Google Test trace:
test/unit/math/rev/arr/functor/coupled_ode_system_test.cpp:522: iteration 3
[  FAILED  ] StanAgradRevOde.memory_recovery_exception_vv (0 ms)
[----------] 18 tests from StanAgradRevOde (1 ms total)

[----------] Global test environment tear-down
[==========] 18 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 12 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] StanAgradRevOde.memory_recovery_dv
[  FAILED  ] StanAgradRevOde.memory_recovery_exception_dv
[  FAILED  ] StanAgradRevOde.memory_recovery_vd
[  FAILED  ] StanAgradRevOde.memory_recovery_exception_vd
[  FAILED  ] StanAgradRevOde.memory_recovery_vv
[  FAILED  ] StanAgradRevOde.memory_recovery_exception_vv

 6 FAILED TESTS
test/unit/math/rev/arr/functor/coupled_ode_system_test --gtest_output="xml:test/unit/math/rev/arr/functor/coupled_ode_system_test.xml" failed
exit now (04/19/19 08:51:25 EDT)
```

#### Current Version:
v2.19.1

**Comment by syclik** [comment]
This is linked to #1108. But it's unclear if this issue is the only problem in the ode system.

**Comment by syclik** [comment]
Issue description has been updated. When fixing this, it's not sufficient to just make it not seg fault. Now that we've recognized this is a problem, we need to introduce tests that check for correct behavior.

**Comment by syclik** [comment]
tagging @wds15

**Comment by wds15** [comment]
Whow. Thanks for catching this. I can look at this the next days. So let me understand what’s going on, write a test and then fix it it. If you don’t mind I may alter an existing test to fail on our existing code base.

Should this fix our tls pr problems, then windows turns out to be very sensitive to many things and hence a pain to work with, but very good after all.

**Comment by syclik** [comment]
Thanks! Yes, please alter an existing test. I just want to make sure we're
actually testing behavior this time... the way it's written, it's using
stuff that's off the end of memory. Unless it happened to have the right
values there, this should result in behavior that's only right
accidentally. I want to make sure we're checking for the right values this
time around. Does that make sense?

I'm hoping we fix this, then just revert the tls branch and that's ok.

**Comment by wds15** [comment]
It’s surprising to see an error here...but this is a complex beast. I suspect that some of our examples used for testing are too simple as too many sensitivities are zero. 

And yeah...we need to understand this and make sure we won’t commit this error again in the future by having a unit test. At the moment I am not too worried that results are garbage as we have lots of test for correctness, but let’s see what this one will lead to.

**Comment by wds15** [comment]
Ok, diving into this shows that the *test* is violating the assumptions of the `coupled_ode_system`!

Everything is in working order and I did check the test

`test/unit/math/rev/arr/functor/integrate_ode_rk45_grad_test.cpp`

carefully to make sure that this test would have caught any error in this code - and it indeed would have catched any mistake which we commit in calculating the gradients as all gradients are non-zero.

So what happened is that we had this in our test code:

```c++
TEST_F(StanAgradRevOde, memory_recovery_dv) {
  using stan::math::coupled_ode_system;
  using stan::math::var;
  mock_ode_functor base_ode;

  const size_t N = 3;
  const size_t M = 4;

  std::vector<double> y0_d(N, 0.0);
  std::vector<var> theta_v(M, 0.0);

  coupled_ode_system<mock_ode_functor, double, var> coupled_system_dv(
      base_ode, y0_d, theta_v, x, x_int, &msgs);

  std::vector<double> y(3, 0);
  std::vector<double> dy_dt(3 + N * M, 0);
  double t = 10;

  EXPECT_TRUE(stan::math::empty_nested());
  EXPECT_NO_THROW(coupled_system_dv(y, dy_dt, t));
  EXPECT_TRUE(stan::math::empty_nested());
}
```

However, the problem here is that we must call the `coupled_ode_system` with the **coupled** state `z` and NOT the base state `y`. Thus, the line

`EXPECT_NO_THROW(coupled_system_dv(y, dy_dt, t));`

failed, since `y` is of length 3 which corresponds to the number of states of the base system, but the coupled ODE system actually has `coupled_system_dv.size()` states which is equal to `3 + N * M` (just like the `dy_dt` length).

The requirement that the first argument of the `operator()` of the `coupled_ode_system` must have length `size()` is clearly documented.

Thus, in this instance I think it is OK to change the test to go along with the specs. Once I did that the test succeeds (even with the `.at()` in the code as you can see from commit e7d650e0e104543bb0e82991f1a4d653c81b2275).

The decision to not check the size of `z` and `dz_dt` for being equal to `size()` is OK within Stan as this is internal to our library. Thus, I think we can just leave the `coupled_ode_system` as is, but make the test aligned with our own specs. To do that I renamed things so that it is clear that `y` refers to the base system and `z` to the coupled system.

If those changes make sense to you, @syclik , then I would file a PR for this.

But again... our ODE system is not affected by a big bug. Moreover, I recall that the person reporting issues with ODE memory stuff on windows did report that with 2.19 things resolved (as I recall). There is no definite confirmation of that yet, but my hope was that 2.19 solves the CVODES issues as we upgraded to sundials 4.1.0. It's premature to conclude that all is just fine, but at least we have good reason to be optimistic.

**Comment by syclik** [comment]
Great! Thanks for hunting that down. Please change the test and change back the `.at()` calls to `[]`. One thing I noticed was that the offset used skipped the `0` element... is that as intended? (It might be, I haven't checked it.)

Maybe it's time to reevaluate the doc? Do you think the doc is clear enough for the developers to understand the preconditions and assumptions necessary?

But please, create a PR with the change. I can look at the doc with you.

**Comment by syclik** [comment]
And I updated the description to indicate that it's a bug in the test.

**Comment by wds15** [comment]
Ok.. I changed back the `.at()` to `[]`, improved the test for readability and reevaluated the doc. The doc did say what we need, but not as clear as it could have been doced. I added a bit more text to make the pre- and post-conditions more clear.
