### ISSUE TITLE
Trimming boost

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1213]
## Description
This is a follow up issue from this thread on Discourse: https://discourse.mc-stan.org/t/trimming-boost-removing-unused-files/8375/8

The issue is that Boost takes 600+MB currently. 

So far we know that by eliminating tests, examples and doc we can get below 200MB easily.

My plan is: 

- [x] create a dummy PR to test what else could be trimmed besides tests, examples & doc. I suspect that it will be a lot of stuff.
- [ ] prepare a Boost update script, similar to the sundails one, that we will be able to use in the future & trim the current Boost lib with it

## Example

/

## Expected Output

Smaller hard drive footprint of Stan Math.

#### Current Version:
v2.19.1

**Comment by SteveBronder** [comment]
Also I'm pretty sure we can get rid these in the CL folder


```
// for directX stuff
cl_d3d10.h
cl_d3d11.h
cl_dx9_media_sharing.h
cl_dx9_media_sharing_intel.h
```
