### ISSUE TITLE
change name of opencl `copy` function

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#1217]
## Description
Right now whenever someone uses the copy function, we end up writing
```
copy(dst, src);  // NOLINT
```
I think it would be better to change the name and avoid triggering cpplint / forcing users of the API to write NOLINT. @SteveBronder had some suggestions, I'll let him edit & weigh in.

#### Current Version:
v2.19.1

**Comment by rok-cesnovar** [comment]
@SteveBronder any thoughts on the new name? Something like `copy_cl()`? I can take care of this one.

**Comment by rok-cesnovar** [comment]
Other option is to make the function return the matrix and call them t`o_matrix_cl(A)` and `from_matrix_cl(A_cl)`.

**Comment by SteveBronder** [comment]
I dont hate `to_cl()` and `from_cl`

**Comment by seantalts** [comment]
+1 have them return something; copy(dst, src) is like reading assembly, you always have to remember if dst goes first or last :P

**Comment by SteveBronder** [comment]
^yeah I think we were just going off other libraries for that. We could shoot for something like

```cpp
matrix_cl A = to_matrix_cl(eigen_mat_a); 
// Could just use the constructor that takes in Eigen matrices
matrix_cl A(eigen_mat_a); 
...
eigen_mat_a = from_matrix_cl(A);
```
