### ISSUE TITLE
stan-math tests break with Intel MKL

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#122]
The test mdivide_left_grad_vv and mdivide_left_grad_vd do fail for small deviations from the expected precision (1.5e-12 > 1.0e-12) when I run the Stan-Math tests with -DEIGEN_USE_MKL_ALL (which is equal to EIGEN_USE_BLAS, EIGEN_USE_LAPACKE, and EIGEN_USE_MKL_VML). If possible, can the thresholds be relaxed to 1.0E-10 (given that this very high precision is not needed)?

For more information on Eigen+MKL, see

http://beamteam.usask.ca/mark/acquaman/dd/d88/_topic_using_intel_m_k_l.html

Even using the more "strict" EIGEN_USE_BLAS, EIGEN_USE_LAPACKE_STRICT and EIGEN_USE_MKL_VML triggers this test to fail. I can only get successfull Stan-Math tests iff I use

EIGEN_USE_BLAS and EIGEN_USE_MKL_VML

which is not optimal I guess, as the LAPACK routines from MKL would not be used.  This stuff may be included in the cmdstan documentation on MKL for other users.

Best,
Sebastian

[ RUN      ] AgradRevMatrix.mdivide_left_grad_vv
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:86: Failure
The difference between Cd(i,j) and g[k] is 1.5916157281026244e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to -273.0000000000008,
g[k] evaluates to -273.00000000000239, and
1.0E-12 evaluates to 9.9999999999999998e-13.
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:86: Failure
The difference between Cd(i,j) and g[k] is 1.3073986337985843e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to 210.00000000000054,
g[k] evaluates to 210.00000000000185, and
1.0E-12 evaluates to 9.9999999999999998e-13.
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:86: Failure
The difference between Cd(i,j) and g[k] is 1.3073986337985843e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to -280.0000000000008,
g[k] evaluates to -280.0000000000021, and
1.0E-12 evaluates to 9.9999999999999998e-13.
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:86: Failure
The difference between Cd(i,j) and g[k] is 1.1084466677857563e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to 217.00000000000054,
g[k] evaluates to 217.00000000000165, and
1.0E-12 evaluates to 9.9999999999999998e-13.
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:86: Failure
The difference between Cd(i,j) and g[k] is 1.0516032489249483e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to 195.00000000000054,
g[k] evaluates to 195.00000000000159, and
1.0E-12 evaluates to 9.9999999999999998e-13.

[ RUN      ] AgradRevMatrix.mdivide_left_grad_vd
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:178: Failure
The difference between Cd(i,j) and g[k] is 1.5916157281026244e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to -273.0000000000008,
g[k] evaluates to -273.00000000000239, and
1.0E-12 evaluates to 9.9999999999999998e-13.
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:178: Failure
The difference between Cd(i,j) and g[k] is 1.3073986337985843e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to 210.00000000000054,
g[k] evaluates to 210.00000000000185, and
1.0E-12 evaluates to 9.9999999999999998e-13.
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:178: Failure
The difference between Cd(i,j) and g[k] is 1.3073986337985843e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to -280.0000000000008,
g[k] evaluates to -280.0000000000021, and
1.0E-12 evaluates to 9.9999999999999998e-13.
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:178: Failure
The difference between Cd(i,j) and g[k] is 1.1084466677857563e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to 217.00000000000054,
g[k] evaluates to 217.00000000000165, and
1.0E-12 evaluates to 9.9999999999999998e-13.
test/unit/math/rev/mat/fun/mdivide_left_test.cpp:178: Failure
The difference between Cd(i,j) and g[k] is 1.0800249583553523e-12, which exceeds 1.0E-12, where
Cd(i,j) evaluates to 195.00000000000054,
g[k] evaluates to 195.00000000000162, and
1.0E-12 evaluates to 9.9999999999999998e-13.
[  FAILED  ] AgradRevMatrix.mdivide_left_grad_vd (1 ms)

**Comment by wds15** [comment]
Hi!

I just decreased the precision from 1e-12 to 1e-10 (file test/unit/math/rev/mat/fun/mdivide_left_test.cpp) and now all tests in 

test/unit/math/rev/mat/fun/ 

do pass. I will run tests on full stan-math unit tests with MKL, let's see...

**Comment by wds15** [comment]
... all tests with Intel 14+MKL pass in stan math once the precision in test/unit/math/rev/mat/fun/mdivide_left_test.cpp has been lowered to 1e-10.

**Comment by bob-carpenter** [comment]
I don't see any problem with lowering precision in the tests for Intel compatibility.   We can let Intel users make their own decision to sacrifice a couple decimal places of accuracy for speed.
