### ISSUE TITLE
Use Eigen Real FFT half-spectrum for autocorrelation

### ISSUE THREAD

**Issue by avehtari** [stan-dev/math#1220]
## Description
Change autocovariance computation in `stan/math/prim/mat/fun/autocorrelation.hpp` from
```
  fft.fwd(freqvec, centered_signal);
  for (size_t i = 0; i < Mt2; ++i)
    freqvec[i] = complex<T>(norm(freqvec[i]), 0.0);

  fft.inv(ac, freqvec);
```
to
```
  fft.SetFlag(fft.HalfSpectrum);
  fft.fwd(freqvec, centered_signal);
  for (size_t i = 0; i < Mt2; ++i)
    freqvec[i] = complex<T>(norm(freqvec[i]), 0.0);

  fft.inv(ac, freqvec);
  fft.ClearFlag(fft.HalfSpectrum);
```
This will make the inverse transformation faster as "only half the spectrum is actually used if the expected output type is real." http://eigen.tuxfamily.org/index.php?title=EigenFFT

## Expected Output
The output should stay the same.

#### Current Version:
v2.19.1

**Comment by roualdes** [comment]
Good idea and thanks for the thought.  The change won't take long, but a speed comparison will take a bit longer.  Do you want an analysis on the relative speed gain from this change?

**Comment by avehtari** [comment]
I think it would be useful to have at least some speed comparison. The current tests should be sufficient to check that the output is not changing,
