### ISSUE TITLE
complex numbers with vars

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#123]
_From @bgoodri on July 18, 2015 15:10_

The following C++ program compiles but segfaults (with clang++-3.6 and g++-5)

```
#include <stan/math.hpp>
#include <iostream>
#include <complex>

int main() {
  stan::math::var x = 1;
  std::complex<stan::math::var> z = x;
  std::cout << "imaginary part is " << z.imag().val() << std::endl;
  return 0;
}
```

I think we should try to prevent that from compiling, or at least dying gracefully, but failing that I guess we should initialize the imaginary part to zero?

_Copied from original issue: stan-dev/stan#1554_

-----

There were a lot of things learned by @ChrisChiasson's effort to implement `std::complex` for Stan's autodiff variables in PR #789. Some of the important takeaways:

- The scope is for both the real and imaginary parts of `std::complex<T>` to be of type `T`. We can either autodiff the real component, the imaginary component, or the result of a function that takes a `std::complex<T>` and returns a `T`. This means we don't have to extend autodiff to deal with adding a `.grad()` function to `std::complex<T>` and we can focus on making sure `std::complex<T>` compiles and behaves appropriately.

- `std::complex<T>` where `T` is our autodiff types (e.g. `stan::math::var`, `stan::math::fvar<U>`) are explicitly unspecified (as of C++11, 08/2018). "The effect of instantiating the template complex for any other type is unspecified." https://en.cppreference.com/w/cpp/numeric/complex

- Given that `std::complex<T>` is unspecified, it is a requirement for any implementation to have tests for the basic operations of `std::complex<T>`. The list of functions can be found here: https://en.cppreference.com/w/cpp/numeric/complex. That means that we should be testing for construction, the member functions, the non-member functions, etc. It's ok to do this in small chunks, but since we're relying on unspecified behavior, we need to be able to tell when our implementation fails in the basic tests before trying to push this through Eigen functions.

- The core reason why `std::complex<T>` can't just be instantiated with one of our autodiff types is because in the current implementation, there are calls to `T()` to construct real or imaginary components. In our current autodiff design, `stan::math::var()` results in an uninitialized variable. This is intentional so we don't create a `vari` on the stack. In order for this to work, we would need to replace `T()` with `T(0)` or some other way of instantiating an autodiff variable on the stack when instantiating a new `std::complex<T>`. For specific places where this happens (especially in the default constructor), search for `_Tp()` in the implementation file: https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/complex

- @ChrisChiasson's PR #789 cleverly worked around the above problem. `std::complex<stan::math::var>` was implemented by relying on `stan::math::complex<stan::math::var>` which then relied on `std::complex<stan::zeroing<stan::math::var>>`. `stan::zeroing<stan::math::var>` was a type that had a default constructor that actually made it to the stack. There was a lot of template magic to make this work properly. There is a prototype of this in the closed PR. In order to finish out this design, the full design would need to be written up (it's tricky templating and it extends our meta traits) and fully tested.

- An alternative design might be to write explicit template instantiations for our types for places where it constructs uninitialized autodiff variables for different components. See [this comment](https://github.com/stan-dev/math/pull/789#issuecomment-410898478) for an example of how to template specialize the constructor. If this works, we may only need to specialize a few functions within `std::complex<T>` and not have to use tricky templating. (This is speculation and should be verified with tests.)

- We may need to implement functions in the `std` namespace like `isnan(std::complex<T>)` and `isinf(std::complex<T>)` because Eigen relies on them being in the `std` namespace. @ChrisChiasson was able to do this using ADL by adding these functions to the `stan::math` namespace, but we've already gone ahead and implemented `std::isnan(T)` for both our autodiff types.

**Comment by syclik** [comment]
@bgoodri, do you know if it's a default constructor issue? Can you point a link to the doc for complex, specifically what constructor it uses and the contract for classes?

**Comment by bgoodri** [comment]
According to

http://en.cppreference.com/w/cpp/numeric/complex

The specializations std::complex<float>, std::complex<double>, and std::
complex<long double> are LiteralTypes
<http://en.cppreference.com/w/cpp/concept/LiteralType> for representing and
manipulating complex numbers <http://en.wikipedia.com/wiki/Complex_number>.

The effect of instantiating the template complex for any other type is
unspecified.

But even if it were defined, we don't have any implementations for anything
with complex numbers, so who knows what would result if someone tried to
utilize them (which Eigen does occasionally).

**Comment by bob-carpenter** [comment]
This would make a great project for someone to explore over a summer.  The first thing to do is to overload the `std::complex<var>` constructor to do the right thing with real and imaginary parts (yes, init imaginary to 0 with one input) and then see what happens in Eigen.

**Comment by bgoodri** [comment]
When Eigen just extracts the real and imagainary parts to do something with
them, we would probably be okay. But I would worry about our autodiff doing
the right thing with complex<var>.

**Comment by bob-carpenter** [comment]
Do complex numbers have different rules for derivatives than just autodiffing
the real and imaginary components?  I got lost in the theory straightway, but
this looks promising:

https://en.wikipedia.org/wiki/Differentiation_rules#Elementary_rules_of_differentiation

If we can just apply the usual chain rule, we'd be OK, right?  I know
a lot of people reading this know complex analysis!

**Comment by bgoodri** [comment]
It might work out-of-the-box for some things but not others. For example,
log() is defined for any non-negative real number but any complex number.
So, we would have to do template specializations for a lot of functions and
worry about things like branch cuts.

**Comment by betanalpha** [comment]
GIANT RABBIT HOLE WARNING.

Derivatives in complex spaces are actually more
constrained that derivatives in real spaces, which
makes them both easier and harder to use.  As
Ben alluded to, once you have to worry about
branch cuts and the like your life gets equally
more difficult and more fun.

But if we simplify things and just consider a
complex number as a tuple of two real functions
then we can naively apply autodiff and be fine
(mathematically this corresponds to differentiating
with respect to real variables only).

**Comment by bob-carpenter** [comment]
I wasn't even considering differentiating w.r.t. the 
complex part --- no wonder I couldn't understand anything
I was seeing :-)

- Bob

**Comment by bgoodri** [comment]
I think we should put off the idea of auto-diffing complex vars but fix the original issue that Stan Math can be compiled a `std::complex<stan::math::var>`.

**Comment by betanalpha** [comment]
Exposing a complex type which is just a pair would be
handy as we could then expose FFTs.

**Comment by davidmanheim** [comment]
This should allow using eigen for finding arbitrary eigenvalues, (i.e. for nonsymmetric matrices,) right?

So if/when this project is done, it would be nice to provide that functionality to STAN as well.

**Comment by bob-carpenter** [comment]
@davidmanheim  We could already implement something that returned the complex and real components.  The complexity comes in from trying to extend derivatives for functions of complex variables.

**Comment by davidmanheim** [comment]
If you can already make a change to the current implementation to allow finding eigenvalues to nonsymmetric matrices, that would be helpful for me at least...

**Comment by bob-carpenter** [comment]
@davidmanheim --- We could probably do that.  Would you mind opening a separate more limited issue for just eigenvalues of non-symmetric matrices?  What do you expect to get as a return (that is, what's the signature as a Stan function in terms of argument and return types) and what do you expect the derivatives to be w.r.t. the inputs.

**Comment by bgoodri** [comment]
We cannot do that because the eigenvalues of non-symmetric matrices are
generally complex and we cannot autodiff that. Request the
pseudo-eigendecomposition, which is (or could be) done with only real
numbers.

**Comment by bob-carpenter** [comment]
What's the use case here?  It might help to start with that and work down (I have a blog post on that scheduled for tomorrow!).

I assume the problem with returning complex numbers, even as two separate arrays of components, is that we can't just operate on the imaginary component without bringing in proper complex derivatives, which we don't have.

Are there situations where users are only going to care about the real component and can we autodiff through that and just ignore the complex compnents?

**Comment by davidmanheim** [comment]
My use case is actually fairly simple. In infectious disease modeling, I'm hoping to generate the largest eigenvalue of the non-symmetric "next generation matrix" - which, under reasonable assumptions, is always real - even if other components are not.

So yes, I only care about the real component. I'm unsure if that's a really unique use case, or if others would find this useful as well.

**Comment by sakrejda** [comment]
even in those population models the imaginary components of sub-dominant
eigenvalues are related to transient oscillations so I don't know that
there's much of an argument for ignoring them in general.  It's easier to
find the dominant eigenvalue than anything else so I wonder if a good
compromise for David's use-case might be a function that just extracts the
dominant eigenvalue (and throws if it's not real).

**Comment by bgoodri** [comment]
It is difficult to ignore the imaginary component because it causes a
segfault. I think we should static_assert on the var constructor for
complex double once we get to C++11. The pseduo-eigendecomposition suffices
for the "I am only interested in the real eigenvalue(s)" use case and the
"All the eigenvalues are real, I promise" use case.

**Comment by bbbales2** [comment]
How much of a C++ fan are you David? There's some stuff with cmdstan that
you can hook in some C++ code that interfaces with the autodiff. I've used
it a couple times now and it works pretty slick.

If the parameter here is real, then the derivative of the largest
eigenvalue with respect to this parameter should be possible to get at
analytically (eq. 14 here
http://www.win.tue.nl/analysis/reports/rana06-33.pdf).

You could make sure it's real on the fly like Krzysztof said. What's the
matrix size?

Ben

**Comment by ChrisChiasson** [comment]
Wanted to leave some references on this issue:
[https://www.domob.eu/research/AutoDiffComplex.pdf](Paper that shows use of std::complex<adouble>)
[https://github.com/gcc-mirror/gcc/blob/trunk/libstdc++-v3/include/std/complex](GCC implementation of std::complex<T> as a struct with two T data members)

**Comment by bob-carpenter** [comment]
I didn't think you could just plug an autodiff type into `std::complex<T>` as that first paper suggests (it uses ADOL-C's `adouble` type).  The chain rule won't let you just plug in autodiff variables for the complex and eal components.  See, e.g.,[the Wikipedia definition of the complex chain rule](https://en.wikipedia.org/wiki/Wirtinger_derivatives#Chain_rule).

**Comment by ChrisChiasson** [comment]
I think the reason why the example is segfaulting could be related to stan's imitation of the uninitialized behavior of doubles. Specifically, I think stan tries to imitate with `var x` the same kind of non-initialization that would happen with `double x`. However, in the templated implementation of the `abs` function template or, say, the complex copy assignment member function, when `T()` is called, it invokes `var()`, which has different behavior than `double()`, because `double()` will give `0.0`.

**Comment by ChrisChiasson** [comment]
Here is a naive partial implementation that tries to allow leverage of whatever complex functions don't rely on `T()` being `0`. 
```
#include <stan/math.hpp>
#include <iostream>
#include <complex>

namespace stan::math{
 template<class T> struct complex : std::complex<T>{

 	template<class U> complex(const U& u){
  	reinterpret_cast<T(&)[2]>(*this)[0] = u;
  	reinterpret_cast<T(&)[2]>(*this)[1] = U(0); //note zero here vs gcc
  }
 };

 template<class T> T abs(const complex<T>&z){
  T x(z.real());
  T y(z.imag());
  T m(fmax(fabs(x),fabs(y)));
  if(m==T(0)) return m; //note zero here vs gcc
  x/=m;
  y/=m;
  return m*sqrt(x*x + y*y);
 }
}

int main() {
 stan::math::var x(3.);
	using stan::math::complex;
 complex<stan::math::var> z = x;
 std::cerr<<"first z = "<<z<<"\n";
 stan::math::var y(x+1.);
 z.imag(y);
 std::cerr << "now z = " << z << "\n";
 auto zabs(abs(z));
 std::cerr << "Abs(z) = "<< zabs <<"\n";
 return 0;
}

```

Produces this output on MinGW GCC on Windows
```
first z = (3,0)
now z = (3,4)
Abs(z) = 5
```

**Comment by ChrisChiasson** [comment]
Presumably if this were actually implemented for stan-math, it would just be a class template specialization of std::complex for `var` and `fvar`. That way you could control what happens with Eigen. Alternatively, perhaps someone knows a way to make the `T()` calls behave like `double()` but still retain the `var x` vs. `double x` behavior (do you need that to save room on the AD stack or something?).

**Comment by ChrisChiasson** [comment]
Here is a simple implementation along with a slightly more complicated and more versatile one that is commented out. The client code can just use `std::complex` and `var`. What do y'all think?
```
#include <stan/math.hpp>
#include <iostream>
#include <complex>

namespace stan::math{
struct zvar:var{
 zvar(double const z=0.):var(z){};
 zvar(var const z):var(z){};
};
//template<class T> struct zeroing{typedef T type;};
//template<> struct zeroing<var>{typedef zvar type;};//maybe add fvar later
//template<class T> struct complex : std::complex<typename zeroing<T>::type>{
// using std::complex<typename zeroing<T>::type>::complex;
//};
}

//Instead of using this code, you could comment it and uncomment the other two
//blocks. That would let you hide a controlled interface in stan::math::complex,
//maybe for implementing fabs as stan-math seems to use.
namespace std{
template<> struct complex<stan::math::var> : complex<stan::math::zvar>{
 using complex<stan::math::zvar>::complex;//I realize this is newer C++
};
}

//namespace std{
// template<> struct complex<stan::math::var> :
//	 stan::math::complex<stan::math::zvar>{
// 	using stan::math::complex<stan::math::zvar>::complex;
// };
//}

int main() {
 stan::math::var x(3.);
 std::complex<stan::math::var> z(x);
 std::cerr<<"first z = "<<z<<"\n";
 stan::math::var y(x+1.);
 z.imag(y);
 std::cerr<<"now z = " <<z<< "\n";
 auto zabs(abs(z));
 std::cerr<<"Abs(z) = "<<zabs<<"\n";
 zabs.grad();
 //z^2 = x^2 + (x+1)^2 = 2x^2+2x+1 ==> 2z dz/dx = 4x + 2
 //dz/dx = (4x + 2)/(2 z) = (2 x + 1) / z = (2 * 3 + 1) / 5 = 7/5 = 1.4
 std::cerr<<"x.adj() = "<<x.adj()<<"\n";
 return 0;
}
```
Output:
```
first z = (3,0)
now z = (3,4)
Abs(z) = 5
x.adj() = 1.4
```

**Comment by bob-carpenter** [comment]
I think given the discussion above from @betanalpha that this will be OK if you only need derivatives w.r.t. the real parts.  

I'm not clear on what a bunch of that C++ is doing, such as the `zeroing` template and its specializations---given that they only have typedefs, I'm assuming it's some kind of traits metaprogram, but I don't see where the typedefs get used anywhere.

I also didn't understand the purpose of `zvar`, which just seems to mark `var` for some reason (there's no other interface or implementation beyond its superclass's).

**Comment by ChrisChiasson** [comment]
The zvar is providing a default double argument when called with no
arguments (via std::complex). The default double is passed to var's ctor,
which causes var to us a nonzero PIMPL to vari, so it doesn't segfault when
it is dereferenced via imag(). The commented parts are an alternative
implementation that might be easier to use if fvar is desired also. BTW,
that complex derivative wiki page is just a rearrangement of the general
chain rule, where it has been acknowledged that one of the variables is
purely real, and the other is purely complex.

**Comment by ChrisChiasson** [comment]
I want to work on this Monday so I can use it in a ship response amplitude operator problem I'm working on. I will attempt to follow the documentation for the developer process.

**Comment by bob-carpenter** [comment]
Our documentation's still way short of where it should be for onboarding new devs.  Let us know if you need help.  And we'd love to hear back if you get it working on an interesting problem you can share.

There's an arXiv paper that goes over the whole structure of our autodiff if you haven't found that yet.

**Comment by ChrisChiasson** [comment]
When I try to push my feature branch:
```
chris.chiasson@<snip> MINGW64 ~/workspace/stan-dev/math (feature/issue-123-complex-numbers-with-vars)
$ git push origin feature/issue-123-complex-numbers-with-vars
ERROR: Permission to stan-dev/math.git denied to ChrisChiasson.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I am sure I'm doing something wrong because I don't usually contribute to other projects...
Should I fork your repo?

**Comment by seantalts** [comment]
Yes please! Thanks!

**Comment by ChrisChiasson** [comment]
Sorry about what appear to be tabs in the diff... In my editor, tabs are shown as single spaces, and I guess I forgot to tell it to always save files with spaces only.

**Comment by seantalts** [comment]
I think Jenkins should auto-format that stuff soon, so no worries.

**Comment by syclik** [comment]
I just updated the top-level comment. @bgoodri and @ChrisChiasson, could you check to see if that's appropriate? Were there things I missed? @seantalts, mind taking a look to see if that's clear enough to keep the issue open? I just reopened it.

**Comment by bgoodri** [comment]
I think the original issue 123 is basically moot. It segfaults, we once tried to prevent it from compiling with a `std::complex<stan::math::var>`, we failed to prevent it from compiling, but nothing you can do in the Stan language results in a `std::complex<T>`. 

If we wanted to reopen #789 and support complex operations in Stan Math, that would be a feature rather than a bugfix.

**Comment by bbbales2** [comment]
> The list of functions can be found here

I had a look at the functions that need tested. I can do some work on these. I presume it's just simply checking values + gradients for each one?

What branch should I work from? #789 is showing "unknown repository"

**Comment by bbbales2** [comment]
Also I'll say it again here just so it's written down somewhere, but I like the idea of only implementing `std::complex<stan::math::var>`. I don't think I'd need `std::complex<stan::math::fvar>` or the more complicated stuff for what I want to do.

**Comment by bob-carpenter** [comment]
What do you want to do?  

We're going to have a bunch of things already that we're going to have to disallow for samplers or optimizers using higher-order autodiff.

**Comment by bob-carpenter** [comment]
This has been resolved.
