### ISSUE TITLE
Variadic is_nan function

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#1232]
## Description
Several functions call ```is_nan``` multiple times using the ```||``` operator, such as in ```prim/scal/fun/grad_reg_inc_gamma```:
```
  if (is_nan(a) || is_nan(z) || is_nan(g) || is_nan(dig))
    return std::numeric_limits<TP>::quiet_NaN();
```
This could be replaced with the introduction of a variadic version of ```is_nan``` (like that used for ```size_zero```):
```
  if (is_nan(a, z, g, dig))
    return std::numeric_limits<TP>::quiet_NaN();
```

#### Current Version:
v2.19.1

**Comment by syclik** [comment]
This would be great for clarity and usability! Thanks!

**Comment by bob-carpenter** [comment]
I don't find this clear without changing the name to is_any_nan or is_nan_any to make it clear it's an OR not an AND putting the multiple arguments together.

**Comment by andrjohns** [comment]
> I don't find this clear without changing the name to is_any_nan or is_nan_any to make it clear it's an OR not an AND putting the multiple arguments together.

I see what you mean. That then raises the question of whether we have:

-  Two versions of ```is_nan```: single inputs call ```is_nan(x)``` and multiple inputs call ```is_nan_any(x,y)```
-  One version and update the naming for all functions  :  single inputs call ```is_nan_any(x)``` and multiple inputs call ```is_nan_any(x,y)```

@wds15 The Eigen plugin PR is waiting on a PR in [stan](https://github.com/stan-dev/stan/pull/2754), so there's not much more I can do for that atm

**Comment by betanalpha** [comment]
Opinion: I think that “is_any_nan” sounds much nice grammatically.

Won’t variadic implementations just dispatch single-argument calls to
the base case?  In which case we could have a single function 
is_any_nan that holds for any size, no?

**Comment by andrjohns** [comment]
> Won’t variadic implementations just dispatch single-argument calls to the base case? In which case we could have a single function is_any_nan that holds for any size, no?

Yep, that's what I was suggesting as the second option above

**Comment by betanalpha** [comment]
My bad —for some reason I mistakenly thought you were suggesting 
an overload for the multiple-argument and single-argument.  Poor 
reading comprehension on my part.

I definitely support a single variadic “is_any_nan” implementation
which has the smallest maintenance burden and most clear naming.

**Comment by andrjohns** [comment]
No worries, equally poor clarity on my part!

@syclik and @bob-carpenter  - how does that sound? A single variadic ```is_any_nan``` function?

**Comment by syclik** [comment]
I think it makes sense to keep the single arg is_nan function so we can
expose that to the Stan language easily. The code gen is simple if the
names match up.

Does that make sense? (I’m suggesting single arg is_nan and a variadic arg
is_any_nan)

**Comment by syclik** [comment]
If the template deduction makes that a pain, just go with is_any_nan.

**Comment by andrjohns** [comment]
> I’m suggesting single arg is_nan and a variadic arg is_any_nan

That's pretty easy actually, will do
