### ISSUE TITLE
get function is too generic in prim/scal/meta/get.hpp?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1236]
## Description

[`get`](https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/get.hpp) in scales is probably too general.

```cpp
template <typename T>
inline T get(const T& x, size_t n) {
  return x;
}
```

We have other more specialized templates in arr and mat e.g.

```cpp
template <typename T>
inline T get(const std::vector<T>& x, size_t n) {
  return x[n];
}
```

If `scales` `get` is included in a file there's a pretty good chance it's used when we really wanted the second one. We're seeing an error with this in the gp_exp_quad_cov OpenCL PR

http://d1m1s1b1.stat.columbia.edu:8080/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1206/15/pipeline#step-107-log-856

## Expected Output

We expect template deduction for cases of vectors to choose the second one while simple types should go to the first.

## Resolution

We can template the `get` in `stan/math/prim/scal/meta/get.hpp` to only compile if it's a fundamental type using [`std::is_fundamental`](https://en.cppreference.com/w/cpp/types/is_fundamental)

```cpp
template <typename T, typename = std::enable_if_t<std::is_fundamental<T>::value>>
inline T get(const T& x, size_t n) {
  return x;
}
```

This is a pretty small change so if it's cool I'm going to add it in #1206 if people are cool with that

#### Current Version:
v2.19.1

**Comment by SteveBronder** [comment]
@syclik is it okay if I include `stan/math/prim/arr/meta/get.hpp` in `stan/math/prim/scal/meta/get.hpp>`?

Otherwise the fix I made throws errors

**Comment by SteveBronder** [comment]
Nah nvm Jenkins is not happy about that answer
```
stan/math/prim/scal/meta/get.hpp(4): File includes an array header file. [scal]
make: *** [test-math-dependencies] Error 1
script returned exit code 2
```

**Comment by SteveBronder** [comment]
Wait also why are the functions in meta defined in `stan` and not `stan::math`?

https://github.com/stan-dev/math/blob/develop/stan/math/prim/arr/meta/get.hpp

**Comment by syclik** [comment]
No. What are you trying to do? There’s probably another way to do it.

What you’re suggesting will just make sure the std::vector traits are all
instantiated before the generic traits are called. What did you do to make
it fail? Where it failed, should you have included an arr header instead?

Btw, there is an effort to simplify this all. But we won’t get there if we
tangle everything up in our current structure. The magic that holds
everything together is how the traits are defined (by includes) and
instantiated (sometimes implicitly).

**Comment by SteveBronder** [comment]
> No. What are you trying to do? There’s probably another way to do it.

I'm trying to restrict the type deduction for `get` in `stan/math/prim/scal/meta/get` to just scalar types. Right now if we included `scal` and `arr` there's instances where the template deduction will pick the `get` in `stan/math/prim/scal/meta/get` where it should pick the `get` in `stan/math/prim/arr/meta/get`.

The issue is that both of the templates below are satisfied by `std::vector<double>`. I'm pretty sure the main issue here is that the compiler gets confused and picks the wrong function because it doesn't use the return type in choosing the right function

```cpp
// `stan/math/prim/scal/meta/get.hpp`
// T = std::vector<double>
// Returns back std::vector<double>
template <typename T>
inline T get(const T& x, size_t n) {
  return x;
}
```

```cpp
//// `stan/math/prim/arr/meta/get.hpp`
// T = std::vector<double>
// returns back double
template <typename T>
inline T get(const std::vector<T>& x, size_t n) {
  return x[n];
}
```

With my change this should stop the scal version from getting used when it shouldn't. 

```cpp
// `stan/math/prim/scal/meta/get.hpp`
// SFINAE kicks this out for T = std::vector<double>
template <typename T, typename = std::enable_if_t<std::is_fundamental<T>::value>>
inline T get(const T& x, size_t n) {
  return x;
}
```

Does that make sense? If so I can go through and check the arr version is included in the right places

**Comment by SteveBronder** [comment]
Actually the other alt here is to move the code for [`is_positive`](https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/err/check_positive.hpp#L30) that handles vectors into arr

**Comment by syclik** [comment]
Can you let me know what code you’re running?

What you’re describing doesn’t make sense. It’s doing exactly as it’s
supposed to behave, by design. That’s why we need to include the traits in
the right order and then it’ll behave.

**Comment by syclik** [comment]
To be more specific, you shouldn’t need to restrict get in prim scal. It’ll
be taken care of when you include the correct headers for prim arr.

**Comment by syclik** [comment]
I’m trying to look through the Jenkins error, but having trouble tracking
through the output on my phone.

Can you isolate this to a particular test case? I feel like this is
happening on that branch due to having the traits not instantiated in the
correct order.

I think it should be an easy-ish fix on the branch, but shouldn’t require a
change to Math directly, if I’m right about what the problem is. If I’m
wrong, then we’ll pick out what exactly is going on.

**Comment by SteveBronder** [comment]
yes! One sec doing a writeup of what's going on rn. It's a bit of a weird one

**Comment by syclik** [comment]
Thanks. This stuff is tricky.

**Comment by syclik** [comment]
Btw, I just checked out the branch for #1206. It seems like it's way behind; hard to tell what's actually different from `develop` with the current state.

**Comment by SteveBronder** [comment]
So I think what your saying is correct, I think my confusion here is that the code for `check_positive` doesn't do what it looks like I would think it does.

Here's an example where things are kind of confusing for me

```cpp
#include <stan/math/prim/scal.hpp>
#include <gtest/gtest.h>
#include <limits>


template <typename T>
void supposed_to_be_vec(T A) {
  if (stan::is_vector_like<T>::value) {
    printf("We Good!\n");
  } else {
    printf("Mamma Mia!!\n");
  }
}

TEST(ErrorHandlingScalar, check_is_vec_like) {
  // Prints 'Mamma Mia'
  std::vector<double> A{-1, -2, -3, -4};
  supposed_to_be_vec(A);

  // Prints "We Good"  
  double** foo;
  supposed_to_be_vec(foo);

  // Prints "We Good"
  double lalala[10];
  supposed_to_be_vec(lalala);
}

}

```

I would expect that when `is_vector_like` received a vector it would say yes right?

But looking at the code for [`is_vector_like`](https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/is_vector_like.hpp) it's supposed to give a value of true when T can be accessed by brackets. But vectors can be accessed by brackets so idk why that's false? ([`stan::is_vector`](https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/is_vector.hpp) only returns false when using the definition only from `scal`.

So, I think the real issue here is that we have code in `scale` that looks as if it should handle vectors but doesn't. In particular idt the code in that `positive` struct really does what it looks like it does.

At first glance, it appears the code below is made to handle the case of vectors, but because of how `is_vector_like` is defined in `scal` it's actually a specialization for pointers.

```cpp
template <typename T_y, bool is_vec>
struct positive {
  static void check(const char* function, const char* name, const T_y& y) {
    if (!std::is_unsigned<T_y>::value && !(y > 0))
      domain_error(function, name, y, "is ", ", but must be > 0!");
  }
};

template <typename T_y>
struct positive<T_y, true> {
  static void check(const char* function, const char* name, const T_y& y) {
    // NOTE: We're gonna talk about this length function in a second
    using stan::length;
    for (size_t n = 0; n < length(y); n++) {
      if (!std::is_unsigned<typename value_type<T_y>::type>::value
          && !(stan::get(y, n) > 0))
        domain_error_vec(function, name, y, n, "is ", ", but must be > 0!");
    }
  }
};
```

So the code above is never going to go off for a vector, but will go off for pointers. But what's the code for `length` in `scal`?

```cpp
template <typename T>
size_t length(const T& /*x*/) {
  return 1U;
}
```

So now things start getting weirder! Here's three tests which I would expect to throw but go along just swimmingly.

```cpp
TEST(ErrorHandlingScalar, check_is_posi_pointer) {
  double* poo[5];
  *poo[0] = -1.0;
  *poo[1] = -2.0;
  // whoops ¯\_(ツ)_/¯
  *poo[4] = 3.0;
  // This is true for is_vector_like so check_positive
  // is going to use the template specialization
  supposed_to_be_vec(poo);
  stan::math::check_positive("check_positive", "foo", poo);
}

TEST(ErrorHandlingScalar, check_is_posi_double_array) {
  double butt[5];
  butt[0] = -1.0;
  butt[1] = -2.0;
  // whoops ¯\_(ツ)_/¯
  butt[4] = 3.0;
  // This is true for is_vector_like so check_positive
  // is going to use the template specialization
  supposed_to_be_vec(butt);
  stan::math::check_positive("check_positive", "foo", butt);
}

TEST(ErrorHandlingScalar, check_is_posi_double_array_bounds) {
  double gutt[0];
  gutt[0] = -1.0;
  // This is true for is_vector_like so check_positive
  // is going to use the template specialization
  supposed_to_be_vec(gutt);
  // Because length() returns 1 this goes past the array bounds
  stan::math::check_positive("check_positive", "foo", gutt);
}

```

Another weird thing, the final definition of check_positive in the `prim/scal/err` folder actually checks whether the size argument it's past is > 0, where all the other definitions check whether `y` is a positive value.

```cpp
inline void check_positive(const char* function, const char* name,
                           const char* expr, int size) {
  if (size <= 0) {
    std::stringstream msg;
    msg << "; dimension size expression = " << expr;
    std::string msg_str(msg.str());
    invalid_argument(function, name, size, "must have a positive size, but is ",
                     msg_str.c_str());
  }
}
```

Now with all the above said, am I just not understanding the intent of the `struct positive<T_y, true>`? I've never really looked at this code before so maybe I'm not getting it in context.

If the above stuff should fail or (work for pointers) I think there's a couple of solutions / fixes.

1. Give `length`s argument a name and have the function return back `sizeof(blah) / sizeof(*blah)` or something like that so that pointers size is looked at and the `for` loop there goes off the right number of times. change `is_vector_like` to say vectors are vector like.

2. Totally remove the concept of vectors and anything that can be array like accessed from `scal`, template the functions to check that the types are scalar, then define the vector array accessor like versions  in `arr`

**Comment by SteveBronder** [comment]
Also, I'm watching GoT right now bit I think just adding the code for prim/arr will do what I want the code to do there

**Comment by syclik** [comment]
Ha. I just finished. We can talk later.

But quick fix to the whole problem:

instead of including stan/math/prim/scal.hpp, include
stan/math/prim/arr.hpp.

arr.hpp refers to array; this is the confusing part. It’s actually
describing Stan’s notion of arrays—that translates to std::vector in C++.
In your test, you use std::vector. Just swap to the arr.hpp header and that
will instantiate and include the right template specializations the Math
library so all of it works.

The way the check functions (and everything else) works is that it just
relies on the template metaprograms to behave. They behave if and only if
everything is instantiated correctly. We’ve tried to get it to not have
this sort of order dependence, but it’s a fundamental templated C++ thing
that multiple efforts to detangle it have failed.

Let me know if that works.

**Comment by SteveBronder** [comment]
Okay so I think I got it!

Though `agrad_test` was failing in `./test/unit/math/rev/core/agrad_test` was failing because of weird header orders so I had to get those in order and everything worked fine for me locally. We'll see how travis does.

I still think my above is true tho'. May be good to do something to flag the above so people don't do one thing expecting another.

>  It’s actually
describing Stan’s notion of arrays—that translates to std::vector in C++.
In your test, you use std::vector.

But for `prim.hpp` this would be the stuff that passes `is_vector_like` right? Which in my examples above idt the function does what the user would expect it to do in the case of an array of doubles. If the function isn't for that in prim then I'd rather have the deduction fail so I know to look elsewhere for the function that does the thing I want

**Comment by rok-cesnovar** [comment]
> Wait also why are the functions in meta defined in `stan` and not `stan::math`?

This is something we are investigating in #1122. Basically template metaprograms are in `stan::` by design (except for those that arent, those shouldnt be in `stan::math::`). Runtime programs should (probably?) be moved to `stan::math::` at some point. This namespace confusion is something I plan to resolve (will open a discussion) once I cleanup everything else in that issue. And then make a wiki with guidelines.

**Comment by SteveBronder** [comment]
Word! Also @syclik I couldn't figure out the right dependency order for the headers,  would you have time to take a look?

**Comment by syclik** [comment]
Sure.... what does that mean? What should I look at?

**Comment by SteveBronder** [comment]
Oh apologies, for pr #1206 theres an error from Jenkins caused by the dependencies. It used to be because the check_positive function was not getting its header orders correctly and threw for prim/gp_exp_quad and rev/adiff_test.cpp**. I modified test/.../rev/util.hpp so that those passed, but now its throwing because of integrate_ode_adams_rev_test.cpp which I'm guessing is because it expects a different order of the headers.

You can see the changes to util.hpp in 5aabdc9. I think we need to revert those and look at what the correct header order is for prim/gp_exp_quad_cov.hpp. 

**I'm on mobile and cant remember the name of the right rev test but will look when I get to a comp

**Comment by SteveBronder** [comment]
Closing this because I'm pretty sure it's just that I didnt get the dependency structure
