### ISSUE TITLE
Implement softmax regression GLM

### ISSUE THREAD

**Issue by t4c1** [stan-dev/math#1241]
## Description
Right now someone that wants to do softmax regression has to write something like this or equivalent in stan language:

```
var softmax_regression(const Matrix<int, Dynamic, 1>& y,
                                  const Matrix<double, Dynamic, Dynamic>& x,
                                  const Matrix<var, 1, Dynamic>& alpha,
                                  const Matrix<var, Dynamic, Dynamic>& beta) {
  Eigen::Matrix<T_return, Dynamic, Dynamic> tmp = (x * beta).array().rowwise() + alpha.array();
  var lpmf = 0;
  const size_t N_instances = x.rows();
  for (int i = 0; i < N_instances; i++) {
    lpmf += categorical_logit_lpmf(y[i], tmp.row(i).transpose().eval());
  }
  return lpmf;
}
```

This is a bit cumbersome and quite slow. Like existing GLMs this one should use analitically derived gradients to be significantly faster. GPU can be used for further speedup.

## Example
This is how the new GLM shall be used:
```
Matrix<int, Dynamic, 1> y = ...
Matrix<double, Dynamic, Dynamic> x = ...
Matrix<var, 1, Dynamic> alpha = ...
Matrix<var, Dynamic, Dynamic> beta  = ...

var lpmf = categorical_logit_glm_lpmf(y, x, alpha, beta);
```

## Expected Output
Should be equivalent to the function in description section.

#### Current Version:
v2.19.1

**Comment by bob-carpenter** [comment]
This looks like it's using `K` coefficient vectors for a `K`-way classification.  That's not identified other than through the prior.  So the softmax regression defined above is just the non-identified likelihood.

If `categorical_logit` were vectorized like our other distributions and allowed a matrix as the parameter, the function you're trying to write would be a one-liner:

```
categorical_logit_lpmf(y, x * beta);
```

I think it's still worth building this to be in line with everything else and for the performance gains.
