### ISSUE TITLE
common_type function deprecated by return_type

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#1243]
## Description
The function ```common_type``` is used for determining the promoted type from two input types:
```
template <typename T1, typename T2>
struct common_type {
  typedef typename boost::math::tools::promote_args<T1, T2>::type type;
};
```
This has been superseded by ```return_type```, which determines the promoted type from any number of inputs:
```
template <typename T, typename... Types_pack>
struct return_type {
  typedef typename boost::math::tools::promote_args<
      double, typename scalar_type<T>::type,
      typename return_type<Types_pack...>::type>::type type;
};

template <typename T>
struct return_type<T> {
  typedef typename boost::math::tools::promote_args<
      double, typename scalar_type<T>::type>::type type;
};
```

#### Current Version:
v2.19.1

**Comment by bob-carpenter** [comment]
It's making me happy every time I see one of these issues and even happier with the PRs.  Metaprogram bloat has been an ongoing problem, so it's great you've achieved a high enough vantage point to start diagnosing the problems.  Thanks!

**Comment by andrjohns** [comment]
Happy to help, it's nice to make an effective change!

**Comment by mcol** [comment]
I had a look at this, and it seems to me that the only effective use of `common_type` is inside stan/math/prim/mat/fun/promote_common.hpp. Unfortunately, replacing it with `return_type` is not currently possible, as the latter doesn't have specializations for vector and matrix types.

So is the right approach to add those specialization to `return_type` (and remove `common_type`) or should we just close this? Perhaps there's a third way, but with my current understanding of metaprogramming I can't see it.

**Comment by mcol** [comment]
I'm hitting a snag, in that `common_type` for mat would produce an Eigen::Matrix, but `return_type` would return the base scalar type. So at this stage I can't see how to replace `common_type` with `return_type` without changing existing assumptions.

**Comment by bob-carpenter** [comment]
Thanks.  Got it.  

I'm running into similar issues with complex numbers, which feel like scalars on the one hand and containers on the other.
