### ISSUE TITLE
Relative difference based finite differences

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1265]
## Description

Add finite difference derivative functors that automatically set the value of the difference based on the scale of the inputs.

`stan::math::finite_diff_gradient` and related functions use a fixed difference.  For robustness with small and large scale inputs, the [Wikipedia page on numerical differentiation](https://en.wikipedia.org/wiki/Numerical_differentiation) recommends evaluating `f(x)` and `f(x + h)`, where

```
h = sqrt(epsilon) * fabs(x)
```

and `epsilon` is the machine precision (about `1e-16` with double-precision floating point, so `sqrt(epsilon)` is around `1e-8`).  I will use this for each `x(i)` in the input vector `x`.

The immediate application will be the automatic differentiation testing framework, which is the subject of the work-in-progress PR #1262 for issue #1258.  #1262 will remain a work-in-progress until this relative difference version of finite differences is merged.

#### Current Version:
v2.19.1

**Comment by betanalpha** [comment]
You’ll still definitely want to use the centered finite difference,

( f(x + h) - f(x - h) ) / (2 * h)

to maximize accuracy per unit cost.

**Comment by bob-carpenter** [comment]
The algorithm being used takes deltas in argument component x(i) of 3h, 2h, 1h, -1h, -2h, and -3h, then uses a weighting that emphases the close ones.  The citation is

* Robert de Levie. 2009. An improved numerical approximation
  for the first derivative. Journal of Chemical Sciences 121(5).

The code is in prim/mat/functor/finite_diff_gradient.hpp.

**Comment by rok-cesnovar** [comment]
Closed with #1267
