### ISSUE TITLE
Add sparse matrix (csr format) by dense vector multiplication

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/math#127]
I let this go stale, I'm going to fix it up so I can get it in now, the background is in pull request [1405](https://github.com/stan-dev/stan/pull/1405).  It needs to be two separate pull requests now, one for [stan-dev/stan](https://github.com/stan-dev/stan/issues/1565) and one for stan-dev/math []().  

__Fixes__
* [x] Make just one multiplication function---named "csr_matrix_times_vector"
* [x] `csr_matrix_times_vector` needs to be hardened. Right now, it is unsafe.
    * [x] `v`: check that each element is between 1 and `n`
    * [x] `u`: check that it's ordered, each element is greater than or equal to 1, that every element is less than or equal to length of `w`
    * [x] `z`: check that each number is greater than or equal to 0. Sum is equal to length of `w`.  NOT doing this as the Eigen implementation I'm mirroring allows for unused entries of w.  Instead: 
      * [x] 'z' implicitly check z by making sure calculations never run off the end of 'w' (check on "end" in code).
      * [x] 'b' implicitly checked by making sure v is checked against the number of columns.
* [x] change explicit 1-index to `stan::error_index::value` -- this is `#define`d as 1, but can be changed to 0
* [x] Add a constructor of a dense matrix using the sparse format--named csr_to_dense_matrix
* [x] Rename extractors to csr_extract_* this makes all functions in the group named as csr_* 
* [x] Add extractors for w/v/u/z that work from dense matrices, wrap around the sparse ones (work by going from Eigen dense to sparse then calling the usual extractors, less indexing code to maintain.  These would usually be called only in transformed data block anyway.  These will be:
  * [x] "csr_extract_w"
  * [x] "csr_extract_v"
  * [x] "csr_extract_u"
  * [x] "csr_extract_z"
* [x] Follow Daniel's suggestion to split out each extractor function into a separate file with its own corresponding test file.

**Comment by sakrejda** [comment]
__ More Fixes__
* [ ] Usage of <T, R, C> versus <T, Dynamic, Dynamic>
* [ ] use row/nze notation everywhere rather than j/p.
* [ ] Tests:
  * [ ] Move tests for csr_matrix_times_vector.hpp
  * [ ] csr_matrix_times_vector.hpp tests should include missing row/ missing column patterns.
  * [ ] Move tests for csr_extract_w.hpp
  * [ ] Move tests for csr_extract_v.hpp
  * [ ] Move tests for csr_extract_u.hpp
  * [ ] Move tests for csr_extract_z.hpp
  * [ ] Fixed matrix test for csr_to_dense_matrix.hpp
  * [ ] Round-trip test for csr_to_dense_matrix.hpp and csr_extract_*.hpp
  * [ ]

**Comment by bgoodri** [comment]
jenkins, test this please
