### ISSUE TITLE
Add check for non-meta.hpp includes?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1270]
## Description

Now that we are only supposed to include the `meta.hpp` includes, should we add a check for any file included that comes from `./meta/*.hpp`?

## Expected Output

I would expect we can include this in the dependency checks we already have?

#### Current Version:
v2.19.1

**Comment by drezap** [comment]
There was one file in the library that we left `./meta/*.hpp` because we (meaning I) couldn't figure out how to get it to compile quickly. But mostly I agree that we should include this in continuous integration. 

So +1 from me.

No idea how to do it though. May be someone that's familiar with the integration tests can point us in the right direction?

**Comment by rok-cesnovar** [comment]
#1242 that has been merged after #1268 already broke this meta include flatten. We really need to add this. Will open a PR to fix what was introduced with #1242 and also try my best with a check.

**Comment by syclik** [comment]
Thanks for brining this up. Can someone spec it out a little further? What
rules need to be in place? I can help with implementation if it hasn’t
already been done.

**Comment by rok-cesnovar** [comment]
My attempt on this is here https://github.com/stan-dev/math/pull/1271#issuecomment-505898075

**Comment by syclik** [comment]
Rok, sorry for the delay. Looks cool. I didn't check the functionality, but
hopefully it works. Sorry about the crazy scripting within Make. Probably a
bad idea and we can move from that.

**Comment by rok-cesnovar** [comment]
No worries, thanks for the feedback. We could replace this header checks with python scripts. Would that be ok with you?

I dont have the time to do this right now, but can take a crack at it once I have it.

**Comment by syclik** [comment]
Yes! When that was originally written, there was still a Python2 vs Python3
installation issue.

It doesn’t strictly need to be formatted in this way either. I did it that
way to piggyback on the Jenkins plug-in to parse warnings.
