### ISSUE TITLE
Update all pdfs/pmfs to take in std::vector, rowvec, scalar types

### ISSUE THREAD

**Issue by drezap** [stan-dev/math#1275]
## Description
Users will sometimes encounter a situation will they will need to cast response data into an `matrix [N, 1]`. This is because the majority of the pmfs/pdfs only take `Eigen::Matrix<foo, Eigen::Dynamic, 1>` (column vectors). 

There's consensus among developers (Bob, t4c1) we'd like to support rowvectors, std::vectors, and scalars moving forward. 

This will take going through each pmf/pdf and adding a templated version for the response input.

There are some caveats described by Bob in this thread as to why we didn't do this before, which will have to be addressed: #1269.

## Example
Here's one example of what a user might have to do, given the current pdf/pmf implementations: https://github.com/stan-dev/math/pull/1242#issuecomment-496652705

## Expected Output
N/A
#### Current Version:
v2.19.1

**Comment by andrjohns** [comment]
I'm a fan of this change, and I'm happy to help with this one. As well as changing the templating for inputs we'd also need to update the meta-programs and error-checking (e.g. #798)

**Comment by drezap** [comment]
@andrjohns that would be awesome. Good call with 798, I'll take a look soon and put a checklist together.

Before we touch the metaprograms I want to get the flattening done, as this could make flattening more difficult and we might end up tearing it apart anyway. Ill ping you when I'm more certain about what needs to happen.

Thanks for chiming in.

**Comment by andrjohns** [comment]
Great! Just to update what I was thinking for the error-checking programs (a-la #798). Feel free to ignore this until you're ready.

Using ```check_ordered``` as an example, we can make the input templating more general and then map that input to an Eigen::Vector:

Old template:
```
template <typename T_y>
void check_ordered(const char* function, const char* name,
                   const Eigen::Matrix<T_y, Eigen::Dynamic, 1>& y) {


  ...loop checking ordered (using y)...
}
```

New template:
```
template <typename T_y>
void check_ordered(const char* function, const char* name,
                   const T_y& y) {

  Eigen::Map<const Eigen::Matrix<typename T_y::value_type, Eigen::Dynamic, 1>>
    y_map(y.data(),y.size());


  ...loop checking ordered (using y_map)...
}
```

**Comment by drezap** [comment]
Sweet. I'm glad someone's excited about this....

**Comment by bob-carpenter** [comment]
It'd be great to move to a more map-based solution.  The only thing to be careful about is whether ::value_type, .data(), and .size() exist.  In the past, we've had to write general wrapper functions that could apply to both std::vector and Eigen::Matrix.  Probably not an issue here, because ordered requires an Eigen vector argument.

**Comment by SteveBronder** [comment]
^ Soundsl like we want concepts. Perusing online there are a few ways to get pseudo concepts in C++14 that are semi-reasonable

**Comment by drezap** [comment]
@SteveBronder, this looks like the way.... post some links, bb. 

I'll come up with a similar example to what @andrjohns did but using C++ 14 concepts... thanks for the lead..

**Comment by SteveBronder** [comment]
got u bb. There are two I've found which are a bit weird but do let us have concept-ey like metaprogramming

https://izzys.casa/2016/09/implementing-concepts-in-cxx/

https://foonathan.net/blog/2016/09/09/cpp14-concepts.html

**Comment by bob-carpenter** [comment]
I think those are mainly traits programs.  I think we'll just need extractors.  We already have the trait metaprogram to extract base scalar type.
