### ISSUE TITLE
Update to OpenCL 2.0

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1276]
## Description

I want to update us to the OpenCL 2.0 headers. We are currently on version 1.2. This cleans up the OpenCL headers by just making it one and brings a few bug updates.

The slide below shows some of the new features we can start working on by using OpenCL 2.0

![](https://images.anandtech.com/doci/7161/OCL1.png)

The implications for each of the slides above

1. We can start focusing on supporting CPUs and APUs. Right now we _can_ use these, but doing stuff on the CPU/APU still requires a copy which is not cool. With Shared Virtual Memory (SVM) we can give ownership of the data to OpenCL without actually making a copy.

2. We can call kernels in kernels. Rok and I have discussed this previously and think we could actually fully do the cholesky on the device side without even making host side function calls to the device.

3. The generic address space thing doesn't help us very much tbh

#### Current Version:
v2.19.1

**Comment by bob-carpenter** [comment]
Thanks for the update and summary.

(1) in particular looks huge.  Will (2) require compiler support?  If so, we may want to start thinking about what'll be required there---probably some kind of dataflow analysis.

**Comment by SteveBronder** [comment]
Yes v pumped for (1)! (2) does require an SDK that supports OpenCL 2.0. There are some gotchas with that. For instance Mac Mojave dropped support for OpenCL since Apple wrote their own gpu language called metal. Tensorflow GPU doesn't run on Mojave either since it depends on cuda which also cannot be compiled

But setting the right flags in the above PR I think we can keep supporting Mac pre-mojave. If not, then we'll probably want to have an actual discussion in the math meeting about whether it's okay for the OpenCL side to drop mac support. Though we are fine on Windows (lol) and Linux which is a pretty decent part of our user base.

Another alternative for mac support (I think) is to have users install the Intel OpenCL SDK that supports 2.0. @seantalts would I be able to install that on the mac to see if that can work? We would run using the CPU on the mac, but idt that's like the worst thing ever

**Comment by seantalts** [comment]
I think we should investigate how much of a win this is compared with any additional support costs we'd incur. Could you fill out this checklist in this issue? https://github.com/stan-dev/math/wiki/Checklist-for-adding-a-dependency-to-the-Math-library

**Comment by SteveBronder** [comment]
^yeah def that's on my todo list before we merge this

**Comment by seantalts** [comment]
> Another alternative for mac support (I think) is to have users install the Intel OpenCL SDK that supports 2.0. @seantalts would I be able to install that on the mac to see if that can work? We would run using the CPU on the mac, but idt that's like the worst thing ever

That's just for CPU support on Mac, right? 

I think we should evaluate the ROI (and checklist) on this before we do any implementation work. For example, if we just get CPU support out and 2% performance boost for Cholesky then it's probably not worth the support headache and losing Macs. That's assuming Cholesky OpenCL CPU is not much faster than Cholesky CPU now, which seems fair given that the algorithm we're using with OpenCL is designed for massively parallel hardware and CPUs are not, so I would expect the CPU-specific algo will win out. But I think evaluating the ROI means testing those assumptions with some simple benchmarks of e.g. OpenCL 2.0 Cholesky.

**Comment by SteveBronder** [comment]
> That's just for CPU support on Mac, right?

Yes

> I think we should evaluate the ROI (and checklist) on this before we do any implementation work. For example, if we just get CPU support out and 2% performance boost for Cholesky then it's probably not worth the support headache and losing Macs. That's assuming Cholesky OpenCL CPU is not much faster than Cholesky CPU now, which seems fair given that the algorithm we're using with OpenCL is designed for massively parallel hardware and CPUs are not, so I would expect the CPU-specific algo will win out. But I think evaluating the ROI means testing those assumptions with some simple benchmarks of e.g. OpenCL 2.0 Cholesky.

Yeah so the path I'm thinking about here is that if I can get the OpenCL 2.0 code to use Shared Virtual Memory then that CPU gain should be pretty good. Do you think the attack plan here should be to do the checklist first or to do a little prototype branch with SVM so we can first evaluate whether CPU support is worth it?

**Comment by seantalts** [comment]
My personal risk estimate here would be that it's more likely that the CPU doesn't show significant performance improvements than that we couldn't add the dependency because of reasons on the checklist, so I'd do the latter first personally.

**Comment by t4c1** [comment]
Would this drop support for OpenCL devices (GPUs) that only support Opencl 1.2? This includes many older devices and ALL NVidia GPUs.

**Comment by SteveBronder** [comment]
> Would this drop support for OpenCL devices (GPUs) that only support Opencl 1.2? This includes many older devices.

The device kernels can still be compiled with OpenCL 1.2 support. Though that would mean we couldn't utilize passing SVMAlloc'd pointers directly to the kernels which would be nice to use.

This would effect computers that come with the OpenCL 1.2 ICD by default. Those users would have to update to a 2.0 compatible ICD

**Comment by seantalts** [comment]
I think we want to keep fully supporting nVidia devices, so if doing so nixes the major benefit from OpenCL 2.0...

**Comment by SteveBronder** [comment]
Yeah so before we merged this I'd want to test a bunch of Nvidia GPUs. Most of the ones from the last few years do support the OpenCL 2.0 features (page 7 of this doc lays out what's supported, though not 'officially yet')

http://us.download.nvidia.com/Windows/430.86/430.86-win10-win8-win7-release-notes.pdf

ftr i'm fine with closing this until I have a branch written up that utilizes this stuff so we can see if we benefit from it or not. Would be easier to weight the pros/cons

**Comment by SteveBronder** [comment]
Closing this until I have time to write out an example of the benefits
