### ISSUE TITLE
Cleanup template metaprogramming

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1288]
## Description

In some parts of Stan we use `enable_if` within the return type. We've written some `enable_if_*` methods now and can move the template metaprogramming into the template instead of putting it in the return type

## Example

Instead of 

```cpp
template <typename T1, typename T2, int R2, int C2, int R3, int C3>
inline typename std::enable_if<
    !stan::is_var<T1>::value && !stan::is_var<T2>::value,
    typename boost::math::tools::promote_args<T1, T2>::type>::type
trace_inv_quad_form_ldlt(const LDLT_factor<T1, R2, C2> &A,
                         const Eigen::Matrix<T2, R3, C3> &B)
```

We can use 

```cpp
template <typename T1, typename T2, int R2, int C2, int R3, int C3, 
  typename = enable_if_all_not_var<T1, T2>>
inline return_type_t<T1, T2>
trace_inv_quad_form_ldlt(const LDLT_factor<T1, R2, C2> &A,
                         const Eigen::Matrix<T2, R3, C3> &B)
```
#### Current Version:
v2.20.0

**Comment by rok-cesnovar** [comment]
The only left function with the `typename std::enable_if...` return type is [gp_periodic_cov](https://github.com/stan-dev/math/blob/47b0595203bd9df718940baedac19c48d4179af4/stan/math/rev/fun/gp_periodic_cov.hpp#L304) for two signature. Once that is cleaned up we can close this.

**Comment by yizhang-yiz** [comment]
iinm this is cleaned up. Ready to close? @rok-cesnovar

**Comment by rok-cesnovar** [comment]
Indeed it is! Thanks!
