### ISSUE TITLE
Rewrite the test-math-dependencies script in Python

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1294]
## Description
The [test-math-dependencies](https://github.com/stan-dev/math/blob/develop/make/test-math-dependencies) Makefile script is difficult to maintain and add new features to it. Mainly due to the weird scripting style of Make. It should be rewritten in Python.

Initially it was not written in Python due to some installation issues (see: https://github.com/stan-dev/math/issues/1270). We should be able to rewrite and use it now.

Additionaly add the following checks:
- check that all `.cpp` files inside test/unit/math end on `_test.cpp`

## Expected Output

Exact same functionality of test-math-dependencies, but in Python.

#### Current Version:
v2.20.0

**Comment by syclik** [comment]
This would be awesome! Yes, we're well past the python 2 vs 3 battle!

**Comment by rok-cesnovar** [comment]
I have added a note in the top comment to also add a check for any `*.cpp` inside `test/unit/math` that dont end on `_test.cpp`. So that we avoid issues like these https://github.com/stan-dev/math/issues/1312
