### ISSUE TITLE
Replace EXPECT_FLOAT_EQ with EXPECT_DOUBLE_EQ when comparing doubles

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1295]
## Description

This issue was identified by @alashworth in his monorepo [README](https://github.com/alashworth/stan-monorepo). Quoting: 

> While messing around with Cotire unity builds, I discovered that a lot of the unit tests erroneously use EXPECT_FLOAT_EQ instead of EXPECT_DOUBLE_EQ for tests with double and `fvar<double>`, and I was getting angry compiler errors about ambiguous template function calls having to do with type widening and type narrowing.

I think this is an issue worth fixing in the Stan Math directly.

## Example

Replace `EXPECT_FLOAT_EQ` with `EXPECT_DOUBLE_EQ`. 

## Expected Output

Correct

#### Current Version:
v2.20.0

**Comment by bob-carpenter** [comment]
Sounds like a good idea.  We didn't even know there was an EXPECT_DOUBLE_EQ or we'd have been using it from the beginning. 

Some occurrences may have to be replaced with EXPECT_NEAR in order to pass if the tolerances are tighter for EXPECT_DOUBLE_EQ.

**Comment by alashworth** [comment]
Are there any valid uses of float in the unit tests? That was the only thing stopping me from doing a global find-replace.

**Comment by syclik** [comment]
The only places I could think of would possibly be where we delegate
externally. Specifically: GPU and possibly CVODES.

**Comment by rok-cesnovar** [comment]
We dont use floats in the OpenCL code and tests, the float GLM was just an idea and an experiment branch. If it isnt in CVODES then its fine to just find replace globally.

**Comment by syclik** [comment]
@wds15, do you know if we're going to have a problem by numerically testing
double instead of float with CVODES? I didn't think so, but C++ never
ceases to amaze me.

**Comment by alashworth** [comment]
I replace all occurrences of `EXPECT_FLOAT_EQ` with `EXPECT_DOUBLE_EQ`; this broke a number of unit tests. They will have to be replaced with `EXPECT_NEAR`. Is there a particular abs or rel tolerance that should be used, or does it have to be determined per-test?

**Comment by alashworth** [comment]
Here's the output of the Stan math unit tests, if you want to look at the differences: [log here](https://gist.githubusercontent.com/alashworth/a38aac9b749c206ed82a79945daaace8/raw/9a7cc7678a04e412deb9ae1c0f2aef6ecbd5eb3e/errors.txt)

**Comment by bob-carpenter** [comment]
It has to be determined per test.  And not only per test, but per input, as the numerical functions have different absolute and relative tolerances throughout their domains.

A simple approach would be to replace the ones that used to be EXPECT_FLOAT_EQ with whatever the default tolerance was there.

Usually, we're not super concerned with high precision and just want to make sure we're getting near the right answer.

**Comment by bob-carpenter** [comment]
> On Jul 31, 2019, at 9:23 PM, Andrew Ashworth <notifications@github.com> wrote:
> 
> Are there any valid uses of float in the unit tests? That was the only thing stopping me from doing a global find-replace.

Nope---we just thought that was the way to test floating point.

**Comment by alashworth** [comment]
Unfortunately, the simple approach doesn't suffice - the calculations are done under the hood in `EXPECT_FLOAT_EQ`, `EXPECT_DOUBLE_EQ` in terms of ULP, while the Google Test `EXPECT_NEAR` only allows specification of absolute tolerance.

This means a manual review of all 1000 failing tests is neccessary, unless I'm missing something..?

**Comment by bob-carpenter** [comment]
I don't think it's the end of the world to leave them as EXPECT_FLOAT_EQ.  We are not going to be testing up to machine precision here as it's the result of often complex iterative algorithms.

The alternative is to replace with our own interface that can call the google test interface under the hood.  I have no idea what's easiest here.

**Comment by alashworth** [comment]
Actually, I agree. The original issue I mentioned in my README is that there were ambiguous template definitions due to uncontrolled type casting. This didn't have much to do with `EXPECT_FLOAT_EQ` per se, but rather lack of `static_cast`.

Something Stan might consider is adopting use of boost::numeric_cast and static_cast when moving between numeric types that might overflow or lose precision. I tried enabling warnings about this in my own repo with `-Wconversion` but there's a lot of code cleanup that would need to be done.
