### ISSUE TITLE
matrix_cl copy constructor and copy assigment operator should do the same thing

### ISSUE THREAD

**Issue by t4c1** [stan-dev/math#1307]
## Description
Right now `matrix_cl` has a copy constructor that does a deep copy - copys underlying `cl::Buffer` and a copy assigment operator that does a shallow copy - same underlying memory is used in both objects. Copy constructor and copy assigment operator should do the same thing. 

a)
They do shallow copies. For deep copies `copy_cl()` could be used.

b)
They do deep copies. In this case we must add move constructor and move assigment operator that do shallow copies.

## Example
The way things work now we rely on copy elision. If the compiler does not do it every time a `matrix_cl` is returned from a function its contents are copied!

#### Current Version:
v2.20.0

**Comment by t4c1** [comment]
@rok-cesnovar @SteveBronder Which option would you prefere?

**Comment by SteveBronder** [comment]
Thanks for the catch! I think I would prefer b so have explicit move/assignment constructors

**Comment by rok-cesnovar** [comment]
Thanks! b) definitely.
