### ISSUE TITLE
Definition missing in matrix_cl_view.cpp

### ISSUE THREAD

**Issue by alashworth** [stan-dev/math#1312]
Hi,

I just pulled the latest develop and the unit tests no longer work for me. The problem arises from matrix_cl_view.cpp, which uses stan::math::from_eigen_triangular type. I'm not sure what that is. When I grep over the code base I cannot find any references to it. 

-Andrew

**Comment by rok-cesnovar** [comment]
Thanks! I had a look and what I am seeing is that it was renamed to `from_eigen_uplo_type`, but not in [the test](https://github.com/stan-dev/math/blob/develop/test/unit/math/opencl/matrix_cl_view.cpp). The question is how did this pass the tests required to merge. I need to look into that.

 @t4c1 do you maybe have time to fix the tests?

**Comment by rok-cesnovar** [comment]
The [test file](https://github.com/stan-dev/math/blob/develop/test/unit/math/opencl/matrix_cl_view.cpp) should end on `_test.cpp` but it does not and runTests does not pick it up.

**Comment by alashworth** [comment]
I think there is more to it than that, `opencl_matrix_test.cpp` is lacking `<double>` specialization too, for example.

**Comment by alashworth** [comment]
Another note: I just finished running tests excluding `from_eigen_triangular_type` and TEST(matrix_cl_view, invert) is failing for me.

**Comment by rok-cesnovar** [comment]
> `opencl_matrix_test.cpp` is lacking `<double>` specialization too

I am not sure which file you are referring to. There is no `opencl_matrix_test.cpp`? At least I cant find it.

> Another note: I just finished running tests excluding `from_eigen_triangular_type` and TEST(matrix_cl_view, invert) is failing for me.

The entire test file needs to be checked as it was never actually used. Me or @t4c1 will get to this tomorrow. Thanks and sorry for the troubles.

**Comment by alashworth** [comment]
No problem! Also, my mistake with `opencl_matrix_test`, apparently it was deleted since 2.20 release (https://github.com/stan-dev/math/blob/23ccc2731dae9bd977c84b2fe4441f98bb908020/test/unit/math/opencl/opencl_matrix_test.cpp). Merging is always a bit tricky for me.
