### ISSUE TITLE
EXPECT_DEATH unit test does not die when -NDEBUG is set.

### ISSUE THREAD

**Issue by alashworth** [stan-dev/math#1313]
Hi,

In https://github.com/stan-dev/math/blob/edf99d8469566fa869d871efbd5bf6cd28c84832/test/unit/math/prim/mat/err/is_pos_definite_test.cpp#L39

There are several expect_death tests in isPosDefinite_not_square and isPosDefinite_0_size. These tests depend on Eigen assertions firing. However, these assertions expand to nothing when `NDEBUG`. Therefore when running the Stan Math test suite with release optimizations, the test fails to die (at least they don't die in MinGW) and we get a false failure. 

As to how this problem should be fixed, if you want to preserve the current behavior across all compilation modes, the eigen assertion macro should be redefined so that it isn't a wrapper around C's assert. 

Otherwise, it is possible to add logic to the build system to conditionally compile this source file only if NDEBUG is not set.

https://eigen.tuxfamily.org/dox/TopicAssertions.html

**Comment by alashworth** [comment]
Just a note the same kind of test is present in `check_pos_definite_test.cpp`.

**Comment by syclik** [comment]
Is this a problem with how the test is being run (the python script)? If
you run the actual executable from the command-line, does it properly die?

**Comment by alashworth** [comment]
I'm not using runTests.py, this is running the executable directly.

**Comment by syclik** [comment]
Thanks for the clarification.

**Comment by syclik** [comment]
Just from reading the issue, there really isn't enough info here:
- what do you expect to happen? 
- Is the test incorrect? 
- Should the test be fixed? 
- Is this something that should no longer be tested?
- Is there some incorrect behavior in the code?

**Comment by alashworth** [comment]
Yes. The test is incorrect. It relies on behavior that is only present in debug builds. As to how it should be fixed, if you want to preserve the current behavior across all compilation modes, the eigen assertion macro should be redefined so that it isn't a wrapper around C's assert. 

https://eigen.tuxfamily.org/dox/TopicAssertions.html

**Comment by syclik** [comment]
Great. Can you put that info in the top-level issue comment? That way someone can read the issue and fix it.

**Comment by alashworth** [comment]
Made the edits. Sorry about that!

**Comment by syclik** [comment]
No problem! The clearer the issue, the easier it is to fix. (It's really hard to intuit what someone reporting has discovered if it's not in a convenient format.)

Also... there is a GH issue template for a reason. If you think that needs to be patched to something more useful, we can do that.

**Comment by rok-cesnovar** [comment]
@alashworth its the same on Ubuntu. Compiling the test with -DNDEBUG:

```
g++ -DNDEBUG -std=c++1y -pthread -Wno-sign-compare   -I lib/opencl_1.2.8  -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.69.0 -I lib/sundials_4.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1 -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1      -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -DSTAN_OPENCL -DOPENCL_DEVICE_ID=0 -DOPENCL_PLATFORM_ID=0 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -D__CL_ENABLE_EXCEPTIONS -Wno-ignored-attributes  -DGTEST_USE_OWN_TR1_TUPLE -DGTEST_USE_OWN_TR1_TUPLE  -c -o test/unit/math/prim/mat/err/is_pos_definite_test.o test/unit/math/prim/mat/err/is_pos_definite_test.cpp

g++ -DNDEBUG -std=c++1y -pthread -Wno-sign-compare   -I lib/opencl_1.2.8  -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.69.0 -I lib/sundials_4.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1     -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -DSTAN_OPENCL -DOPENCL_DEVICE_ID=0 -DOPENCL_PLATFORM_ID=0 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -D__CL_ENABLE_EXCEPTIONS -Wno-ignored-attributes  -DGTEST_USE_OWN_TR1_TUPLE         test/unit/math/prim/mat/err/is_pos_definite_test.o lib/gtest_1.8.1/src/gtest_main.cc lib/gtest_1.8.1/src/gtest-all.o      -lOpenCL  -o test/unit/math/prim/mat/err/is_pos_definite_test
```
results in a failed test.

Looking at these tests I actually am wondering why are we even testing this? 
We have the following tests with LLT/LDLT with `EXPECT_DEATH`:
```
EXPECT_DEATH(llt.compute(y), "");
EXPECT_DEATH(y.ldlt(), "");
EXPECT_DEATH(ldlt.compute(x), "");
EXPECT_DEATH(llt.compute(y), "");
EXPECT_DEATH(y.ldlt(), "");
EXPECT_DEATH(ldlt.compute(x), "");
```
We are basically just testing an Eigen function directly? Why is that needed? Not saying it isnt, I may be missing something. 

We dont expose `ldlt()` or `compute()` directly to the Stan Math/Cmdstan/... user. Its always through one of the Stan Math functions. For those we have to test that they handle the non-square case and they all do.

If there is a reason for keeping them, I propose we wrap them like:
```
#ifndef EIGEN_NO_DEBUG
  EXPECT_DEATH(ldlt.compute(x), "");
#endif
```
We already do this in some spots in the tests so I guess that should be fine. `EIGEN_NO_DEBUG` is set when NDEBUG is set ([link](https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html)).

**Comment by alashworth** [comment]
@rtrangucci thoughts?
