### ISSUE TITLE
agrad_distributions_multi_gp_cholesky tests fail: matrices not symmetric

### ISSUE THREAD

**Issue by alashworth** [stan-dev/math#1315]
In `multi_gp_cholesky2_test.cpp` the following tests are failing for me:

`agrad_distributions_multi_gp_cholesky, Propto`
`agrad_distributions_multi_gp_cholesky, ProptoY`
`agrad_distributions_multi_gp_cholesky, ProptoYMu`
`agrad_distributions_multi_gp_cholesky, ProptoYSigma`
`agrad_distributions_multi_gp_cholesky, ProptoMu`
`agrad_distributions_multi_gp_cholesky, ProptoMuSigma`
`agrad_distributions_multi_gp_cholesky, ProptoSigma`

There's a check-symmetric call in these tests, but the result is not symmetric.

All the tests fail with:

unknown file: Failure
C++ exception with description "multi_gp_lpdf: Kernel is not symmetric. Kernel[1,2] = 0, but Kernel[2,1] = -1" thrown in the test body.

And the actual matrix is, indeed, non-symmetric: 

[    3,     0]
[   -1, 1.732]

I'm not quite sure how to debug this because I don't understand what the expected output of these tests is supposed to be. Let me know if I should post this on Discourse instead of here.

**Comment by seantalts** [comment]
How are you running the tests? Are these passing on develop?
