### ISSUE TITLE
Implement GLMs in OpenCL

### ISSUE THREAD

**Issue by t4c1** [stan-dev/math#1319]
## Description
OpenCL GLMs were waiting for caching of matrices on GPU, since GPU GLMs require caching to achieve speedups compared to execution on CPU.

There was an attempt to implement caching (PR #1065), but it was abandoned due to problems with caching matrices that can change. On Stancon we have decided to simplify it by caching only matrices that are constant.

On discourse https://discourse.mc-stan.org/t/gpu-glms-float-or-double/9484/40 there was a discussion whether we could use floats instead of doubles in GLMs. The conclusion was that there might exist cases where reduced precision of floats could cause problems.

There will be a series of pull requests:
- [x] caching
- [x] normal_id
- [x] bernoulli_logit
- [x] poisson_log
- [x] neg_binomial_log
- [x] categorical_logistic
- [x] ordered_logistic ~~(after CPU code is merged - PR #1252)~~

## Example / Expected Output
GLMs are faster when using GPU.

#### Current Version:
v2.20.0

**Comment by rok-cesnovar** [comment]
All of these were merged so closing. Thanks!
