### ISSUE TITLE
Use clang scan-build for static analysis

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1324]
## Description

It's pretty simple on my machine to run the clang static analysis checker

```bash
scan-build-8 -o ../ ./runTests.py ./test/unit/math/rev/mat/
```

I'm running some stuff right now and will post up what the report looks like tmrw

Could we add this to jenkins to run and send a report on each release? Then at least on the next release we will know a bunch of things we need to fix up.

**Comment by wds15** [comment]
+1

**Comment by SteveBronder** [comment]
I started messing around with clang tidy here

https://github.com/bstatcomp/math/tree/clang-tidy

You can run clang-tidy over tests with
```bash
make clang-tidy folder=./test/unit/math/rev files=multiply
```

**Comment by SteveBronder** [comment]
Alright it's looking a bit prettier!

The above branch and command will run the performance, readability, modernization, google guide, and a few misc checks. I also have a `clang-tidy-fix` that does the same as above but automatically applies the fixes suggested.

They are all available in more detail below. I'm going to run this over a few of the tests and make a PR with the automated fixes

https://clang.llvm.org/extra/clang-tidy/

**Comment by syclik** [comment]
Can you post an example here? Even a screenshot would be useful.

**Comment by SteveBronder** [comment]
Yep! I actually ran this over a bunch of the tests just fixing the missing parenthesis around conditionals

https://github.com/stan-dev/math/pull/1326

For the output of clang-tidy it looks like the below

```
./stan/math/fwd/core/fvar.hpp:88:29: warning: statement should be inside braces [google-readability-braces-around-statements]
    if (unlikely(is_nan(v)))
                            ^
                             {
./stan/math/fwd/core/fvar.hpp:104:75: warning: use nullptr [modernize-use-nullptr]
       typename std::enable_if<ad_promotable<V, T>::value>::type* dummy = 0)
                                                                          ^
                                                                          nullptr
./stan/math/fwd/core/fvar.hpp:106:29: warning: statement should be inside braces [readability-braces-around-statements]
    if (unlikely(is_nan(v)))
                            ^                                                                                
```

scan-build-8 gives an actual html output which is nice though I think a bit overkill. I'm really just looking for something that gives me some sanity checks
