### ISSUE TITLE
Test failures with Intel14+MKL (Cholesky), Intel14 and g++ 4.4.7 (AgradMixMatrixMdivideLeftSPD.fv_exceptions)

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#133]
- Intel 14 with MKL fails over some Cholesky unit test.
- Intel 14 and g++ 4.4.7 fail with AgradMixMatrixMdivideLeftSPD unit test

compressed log files sent by mail

**Comment by syclik** [comment]
Failures:

- g++ 4.4.7
```
[ RUN      ] AgradMixMatrixMdivideLeftSPD.fv_exceptions
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:526: Failure
Expected: mdivide_left_spd(fd2, rvf2) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:527: Failure
Expected: mdivide_left_spd(fd2, rvf1) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:528: Failure
Expected: mdivide_left_spd(fd2, vf1) throws an exception of type std::domain_error.
  Actual: it throws a different type.
[  FAILED  ] AgradMixMatrixMdivideLeftSPD.fv_exceptions (1 ms)
...
[ RUN      ] AgradMixMatrixMdivideLeftSPD.ffv_exceptions
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:1493: Failure
Expected: mdivide_left_spd(fd2, rvf2) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:1494: Failure
Expected: mdivide_left_spd(fd2, rvf1) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:1495: Failure
Expected: mdivide_left_spd(fd2, vf1) throws an exception of type std::domain_error.
  Actual: it throws a different type.
[  FAILED  ] AgradMixMatrixMdivideLeftSPD.ffv_exceptions (1 ms)
...
[  FAILED  ] AgradMixMatrixMdivideLeftSPD.fv_exceptions
[  FAILED  ] AgradMixMatrixMdivideLeftSPD.ffv_exceptions
```
- Intel 14
```
[ RUN      ] AgradMixMatrixMdivideLeftSPD.fv_exceptions
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:526: Failure
Expected: mdivide_left_spd(fd2, rvf2) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:527: Failure
Expected: mdivide_left_spd(fd2, rvf1) throws an exception of type std::domain_error.
  Actual: it throws a different type.
test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp:528: Failure
Expected: mdivide_left_spd(fd2, vf1) throws an exception of type std::domain_error.
  Actual: it throws a different type.
[  FAILED  ] AgradMixMatrixMdivideLeftSPD.fv_exceptions (1 ms)
...
[  FAILED  ] AgradMixMatrixMdivideLeftSPD.fv_exceptions
```
- Intel 14 with MKL:
```
[ RUN      ] AgradMixMatrixCholeskyDecompose.mat_1st_deriv
unknown file: Failure
C++ exception with description "cholesky_decompose: Cholesky decomposition of m failed" thrown in the test body.
[  FAILED  ] AgradMixMatrixCholeskyDecompose.mat_1st_deriv (2 ms)
[ RUN      ] AgradMixMatrixCholeskyDecompose.mat_2nd_deriv
unknown file: Failure
C++ exception with description "cholesky_decompose: Cholesky decomposition of m failed" thrown in the test body.
[  FAILED  ] AgradMixMatrixCholeskyDecompose.mat_2nd_deriv (0 ms)
[ RUN      ] AgradMixMatrixCholeskyDecompose.mat_3rd_deriv
unknown file: Failure
C++ exception with description "cholesky_decompose: Cholesky decomposition of m failed" thrown in the test body.
[  FAILED  ] AgradMixMatrixCholeskyDecompose.mat_3rd_deriv (0 ms)
...
[  FAILED  ] AgradMixMatrixCholeskyDecompose.mat_1st_deriv
[  FAILED  ] AgradMixMatrixCholeskyDecompose.mat_2nd_deriv
[  FAILED  ] AgradMixMatrixCholeskyDecompose.mat_3rd_deriv
```

**Comment by bob-carpenter** [comment]
I'm guessing these are due to tolerances given where they're at and what else we've seen.  I updated the milestone to 2.8.0, but we can push this back to 2.8.0++ if necessary.  Motivation from Sebastian Weber on stan-dev:

<blockquote>
The g++ 4.4.7 is part of RedHat Linux Enterprise 6.5 which is installed in many production systems.
</blockquote>

**Comment by syclik** [comment]
Was that one of the tests Ben removed recently?

**Comment by bob-carpenter** [comment]
It's a few tests that are still failing.  We just need
to fix the tests and verify that they work.

I'm on the sparse multiply thing.

- Bob

**Comment by wds15** [comment]
Hi!

I analyzed the matter and it appears that the test checks possibly for the wrong expectation, i.e. the test expects a std::domain_error to be thrown when infact a std::invalid_argument is thrown from the check_size_match call. Here is a small patch fixing this:


diff --git a/test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp b/test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp
index bb2c4e9..a1ef28b 100644
--- a/test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp
+++ b/test/unit/math/mix/mat/fun/mdivide_left_spd_test.cpp
@@ -523,9 +523,9 @@ TEST(AgradMixMatrixMdivideLeftSPD,fv_exceptions) {
   EXPECT_THROW(mdivide_left_spd(fd1, rvf2), std::domain_error);
   EXPECT_THROW(mdivide_left_spd(fd1, rvf1), std::domain_error);
   EXPECT_THROW(mdivide_left_spd(fd1, vf2), std::domain_error);
-  EXPECT_THROW(mdivide_left_spd(fd2, rvf2), std::domain_error);
-  EXPECT_THROW(mdivide_left_spd(fd2, rvf1), std::domain_error);
-  EXPECT_THROW(mdivide_left_spd(fd2, vf1), std::domain_error);
+  EXPECT_THROW(mdivide_left_spd(fd2, rvf2), std::invalid_argument);
+  EXPECT_THROW(mdivide_left_spd(fd2, rvf1), std::invalid_argument);
+  EXPECT_THROW(mdivide_left_spd(fd2, vf1), std::invalid_argument);
 }
 
 TEST(AgradMixMatrixMdivideLeftSPD,matrix_ffv_matrix_ffv1) {

**Comment by wds15** [comment]
uhh, posting patches here doesn't seem to work well (text gets processed in an unexpected manner).

I am happy to share the patch; albeit I guess the change is obvious.

**Comment by bob-carpenter** [comment]
What we need are GitHub pull requests.  But we can fix this
one easily enough.  No idea why it'd be passing on other machines
if the error's this basic.

- Bob

**Comment by wds15** [comment]
ok, let me get familiar with your pull request process, etc. This one is very easy to fix indeed. However, once this one was out of the way, another test blocked me -

test/unit/math/prim/mat/err/check_pos_definite_test.cpp:66

a DEATH test does not trigger a  death when executed on our linux platform. Should I go for a new issue?

... I really think a testing system which tests all the way through and gives a summary page over what failed and what not would be very useful going forward. Would you guys agree on that or is this not needed as such a functionality already exists somewhere?

**Comment by bob-carpenter** [comment]
I thought there was a way to configure that behavior, but I don't
see it in the Python tests, which claim they only take one argument.
Daniel? 

We don't usually bother because the tests cascade --- when one fails,
it causes other things to fail, so you get a huge overload of false positives.

I don't know what you mean by DEATH test.  You mean the EXPECT tests
in Google test?

Also, "make help" still does all this extra work --- it takes like 15s
to run on my machine.

- Bob

**Comment by wds15** [comment]
Well, there is the -k switch which tells make to keep on going even if there was an error. However, this only works within a directory and still stops early. But I think I found a solution, i.e. I can simply find all those _test.cpp files with find and then call with its exec functionality a runTest.py on it. That should do it, right?

Concerning test/unit/math/prim/mat/err/check_pos_definite_test.cpp:66 - in that file a couple of EXPECT_DEATH tests do not cause a program termination on my machine. The absence of program termination does cause the test to fail (platform is Linux). I guess I open a new issue for that one.

**Comment by syclik** [comment]
Yes, please open a new issue for those.

Action is still on me to get this patch in.

**Comment by bob-carpenter** [comment]
Closing because we fixed this ages ago by lowering the arithmetic tolerance to deal with MKL's inaccuracy.
