### ISSUE TITLE
GLMs tests are missing tests for edge cases

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1359]
## Description
We dont test all GLMs for edge cases, particularly size zero inputs. Some have a test or two (categorical at least) but a more systematic approach would be preferred.
The same is probably true for many other Stan Math functions as Bob mentioned, this is just something I realized while reviewing GPU GLM code.

Its pretty trivial to see from the code that it works with size zero vector and matrix inputs but it should be tested for all possibilities of zero sized input anyways.

## Example

For examples see any GLM tests, for instance: 

https://github.com/stan-dev/math/blob/develop/test/unit/math/rev/mat/prob/ordered_logistic_glm_lpmf_test.cpp
https://github.com/stan-dev/math/blob/develop/test/unit/math/rev/mat/prob/normal_id_glm_lpdf_test.cpp

## Expected Output
Better edge case testing for GLMs.

#### Current Version:
v2.20.0

**Comment by SteveBronder** [comment]
Kind of a meta side note, but how do other packages handle one of the dimensions being zero in a matrix? Like doing (0x5) * (5x0) is a matrix with zero rows and zero columns? What do you return back? Even a NaN would have 1x1 dims. I conceptually don't understand how that should be evaluated

**Comment by t4c1** [comment]
Simple: you return a 0x0 matrix.

**Comment by SteveBronder** [comment]
That makes sense math wise after looking at the below

https://math.stackexchange.com/questions/249826/does-zero-vector-have-zero-dimension

**Comment by bob-carpenter** [comment]
+1.  

All the sizes work on boundaries.  It's always (M x N) when you multiply (M x K) and (K x N).  Overall size is just M x N.  

To generalize something like inverse, you'd need to treat the (0 x 0) matrix as a unit matrix.  I don't know if that's commonly done as an edge case.

**Comment by rok-cesnovar** [comment]
Fixed with #1399
