### ISSUE TITLE
Unnecessary copying in `system_functor` constructor

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/math#1367]
## Description
The issue here is noticed in review of #1339, as @charlesm93 pointed out it deserves its own issue.

There's a lot of copying in `system_functor` constructor:
- By not using `const` ref in the definition, the construction does numerous copies.
- The struct needs redesign: when `x_is_iv=true`, `x` copied into the structure is never used. Since there are only two scenarios, maybe just define `struct algebra_system_fx` and `struct algebra_system_fy`. A refactorization of `hybrj_functor_solver` would be even better.

## Expected Output
Same. But more efficient with large nonlinear systems.

#### Current Version:
v2.20.0

_Originally posted by @yizhang-yiz in https://github.com/stan-dev/math/diffs_

**Comment by charlesm93** [comment]
Thanks for creating this. I'm happy to implement the fix.

How would you test for the gain in efficiency?

**Comment by yizhang-yiz** [comment]
You can just test the construction of `system_functor` on a large `x`, `y` input.

**Comment by SteveBronder** [comment]
> By not using const ref in the definition, the construction does numerous copies.

Which constructor? I'm looking at `system_functor` in `rev/mat/functor/algebra_system.hpp` and it looks like the constructor is using const refs?

> The struct needs redesign: when x_is_iv=true, x copied into the structure is never used. Since there are only two scenarios, maybe just define struct algebra_system_fx and struct algebra_system_fy. A refactorization of hybrj_functor_solver would be even better.

Instead of having two different ones could you just use `if (x_is_iv) {` in the constructor?

**Comment by yizhang-yiz** [comment]
This has been fixed after refactoring.
