### ISSUE TITLE
Test is not being executed / header file does not exist

### ISSUE THREAD

**Issue by alashworth** [stan-dev/math#1368]
Problem file: test/unit/math/fwd/mat/vectorize/fwd_scalar_unary_test.hpp

The included header file, test/unit/math/prim/mat/vectorize/expect_types.hpp does not exist. I suspect this is not being picked up because the test file has a *.hpp file extension, causing it to not be picked up by the automated test script.

Current version: develop HEAD (as of 3 days ago).

**Comment by rok-cesnovar** [comment]
Good catch, will fix this and add a check to the check script to search for `_test.hpp` files.

**Comment by rok-cesnovar** [comment]
There is actually more of this _test.hpp files. Though other probably dont fail so they werent a problem for you. 

After I updated the check script.
```
test/unit/math/fwd/mat/vectorize/fwd_scalar_unary_test.hpp:
	 A *_test.hpp file found. Must be *_test.cpp to run.
test/unit/math/rev/mat/vectorize/rev_scalar_unary_test.hpp:
	 A *_test.hpp file found. Must be *_test.cpp to run.
test/unit/math/mix/mat/vectorize/mix_scalar_unary_test.hpp:
	 A *_test.hpp file found. Must be *_test.cpp to run.
```
