### ISSUE TITLE
Uninitialized memory access in test/unit/math/memory/stack_alloc_test.cpp#L28

### ISSUE THREAD

**Issue by alashworth** [stan-dev/math#1372]
https://github.com/stan-dev/math/blob/afe2881f088d97466319e4846660295f63a67fd5/test/unit/math/memory/stack_alloc_test.cpp#L28

The inner loop variable k starts at 1 when it should start at 0. As a result, currently the memory location pointed to by that index is uninitialized in the EXPECT_FLOAT_EQ comparison three lines below it. This unit test passes in debug mode since most compilers zero out the memory for you, but in release mode the memory contents are undefined and I get a test failure.

**Comment by rok-cesnovar** [comment]
Thanks @alashworth for the report. I will fix it this evening.
