### ISSUE TITLE
Add testing scripts for MSVC 2008 or 2010 or 2015 for Windows

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#138]
## Feature Request

__Version__

2.7.0

__Description__

@patricksnape just submitted a patch allowing the Math Library to be compilable under MSVC 2008 / 2010.

Adding a script to run the tests in Windows would allow the developers to run it in a Windows environment with MSVC to verify whether it does or does not run with MSVC.

__Additional Information__

At the moment, we (the Stan developers) are *not* committing to supporting MSVC 2008 or 2010. If it's really easy to maintain that while we're still stuck with pre-C++-11, I think we'll do our best to write around it.

Once again, fixing this issue will not commit us to supporting MSVC 2008 or 2010 or 2015.

(I just wanted to make sure that was clear to anyone reading this issue.)

**Comment by patricksnape** [comment]
My Windows scripting foo is not very strong - but I may have some time to at least look at this next week. It may be that something like CMake becomes a valuable tool here - since then you could write the logic for compiling the tests once and just generate the make scripts automatically per platform?

**Comment by ariddell** [comment]
Stan is being tested on Visual Studio 2015 via PyStan's appveyor CI config. Perhaps this is enough for the short term?

Here's the appveyor link: https://ci.appveyor.com/project/ariddell/pystan

**Comment by bob-carpenter** [comment]
Given comment of @ariddell and lack of recent complaints from MSVC users, I'm going to close this.
