### ISSUE TITLE
rev_mat_functor_map_rect_prim_test needs special compile flags with Clang/libstdc++11

### ISSUE THREAD

**Issue by alashworth** [stan-dev/math#1380]
I'm not sure if this issue should be raised here, because my understanding is that Clang/libstdc++11/mingw-w64 is not a supported combination? Only clang with libc++ is? If this is true, please let me know and close this issue. Anyway, when compiling *map_rect_prim_test with Clang on MinGW-W64 I run into an incompatibility between Clang and GCC in how thread-local variables are handled. You can fix by passing -femulated-tls to Clang, possibly this ought to be noted in the documentation somewhere.

**Comment by rok-cesnovar** [comment]
So this is clang on Windows? The last time I tried Stan Math on Windows with clang there were multiple issues, not necessarily treading related. I presume this is on the monorepo?

Can you list what flags you set?

**Comment by alashworth** [comment]
It's not just clang on windows, the bug tracker issue I found on the LLVM mailing list says this is for all older versions of Clang that link against gcc-built libraries.

Currently for debug versions I'm doing a very basic 

CXX_FLAGS = -g   -femulated-tls -pthread -std=c++14
CXX_DEFINES = -DNO_FPRINTF_OUTPUT -D_USE_MATH_DEFINES

**Comment by rok-cesnovar** [comment]
Do we want to just set -femulated-tls every time one uses clang? That seems to broad?

I am not exactly sure under which conditions should we do that. If we nail it down to a specific case we can add that to the makefiles.

**Comment by alashworth** [comment]
You are right. You do not want to set this every time someone uses Clang. Instead, it is a specific workaround for an ABI incompatibility between Clang and GCC stdlibc++, for certain versions of Clang/GCC.

I am just suggesting maybe put a comment in the build instructions.  The ideal solution is that I detect this in the CMake script and set the appropriate flag automatically, but I don't have time to test and code such functionality. Maybe in the future.
