### ISSUE TITLE
Incorrect output when using link time optimization

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1383]
## Description

I was trying out link time optimization in gcc with the `-flto` flag and found that it caused incorrect results to come out of the benchmarks for the sir model. You can check what I'm doing in the branch [`feature/flto`](https://github.com/stan-dev/math/blob/feature/flto/make/compiler_flags#L193). The `-flto` flag goes in both the CPP flags and the LD flags since it's a compilation and linking flag.

## Example
For **bug reports**:

The below shows the performance tests with the branch `feature/flto` using the cmdstan-performance-benchmarks repo

```bash
# NOTE: This does 20 runs, you can change --runs to 1 or 2 for faster results
./compare-git-hashes.sh "stat_comp_benchmarks -j15 --runs 20" develop develop develop 9c8a6f1aeef88bbfce7bfcb3e333372a1848731d
```

```
('stat_comp_benchmarks/benchmarks/gp_pois_regr/gp_pois_regr.stan', 1.06)
('stat_comp_benchmarks/benchmarks/low_dim_corr_gauss/low_dim_corr_gauss.stan', 1.03)
('stat_comp_benchmarks/benchmarks/arK/arK.stan', 1.21)
('stat_comp_benchmarks/benchmarks/pkpd/one_comp_mm_elim_abs.stan', 0.97)
('stat_comp_benchmarks/benchmarks/eight_schools/eight_schools.stan', 1.0)
('stat_comp_benchmarks/benchmarks/irt_2pl/irt_2pl.stan', 1.07)
('stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan', 1.08)
('performance.compilation', 1.82)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix_collapse/low_dim_gauss_mix_collapse.stan', 1.0)
('stat_comp_benchmarks/benchmarks/low_dim_gauss_mix/low_dim_gauss_mix.stan', 1.0)
('stat_comp_benchmarks/benchmarks/sir/sir.stan', 1.0)
('stat_comp_benchmarks/benchmarks/pkpd/sim_one_comp_mm_elim_abs.stan', 0.99)
('stat_comp_benchmarks/benchmarks/garch/garch.stan', 0.93)
('stat_comp_benchmarks/benchmarks/gp_regr/gen_gp_data.stan', 1.01)
('stat_comp_benchmarks/benchmarks/arma/arma.stan', 0.82)
1.06575491826
```

Over 80% decrease in compilation time? It may be because lto is done in parallel? Or maybe I'm reading the results wrong? The result output from the failing `sir` model is [here](https://gist.github.com/SteveBronder/3cea7878ad44c0647a02d893de35d878) apologies it does not come out well printed.

Also `stat_comp_benchmarks_benchmarks_gp_regr_gp_regr` has an error during warmup that I normally do not see

```
Iteration:    1 / 2000 [  0%]  (Warmup)
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: cholesky_decompose: A is not symmetric. A[1,2] = inf, but A[2,1] = inf  (in '../stat_comp_benchmarks/benchmarks/gp_regr/gp_regr.stan' at line 16)
```

and in `sir` this `Inf` exception shows up which normally does not

```bash
Iteration:    1 / 2000 [  0%]  (Warmup)
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: integrate_ode_rk45: parameter vector[3] is inf, but must be finite!  (in '../stat_comp_benchmarks/benchmarks/sir/sir.stan' at line 55)
```

I'm not sure what causes that, but it would be nice to be able to use link time optimization

## Expected Output

I'd expect the results to get better so, seeing the large changes here over 20 runs is odd.

#### Current Version:
v2.20.0

**Comment by SteveBronder** [comment]
@charlesm93 can you check out the `sir` model we use for the benchmarks below for an idea of what we get the `integrate_ode_rk45` error? That's the only performance benchmark failing and if that all passes we could do something like check if the user's compiler has link time optimization support and it should help our compile times by quite a lot. If I'm reading the results right above it should be almost twice as fast to compile a stan model

**Comment by SteveBronder** [comment]
@yizhang-yiz do you know about the above? Should the `sir` model be using a different solver?

**Comment by charlesm93** [comment]
@SteveBronder Sorry for taking a while to notice this. I'm not familiar with the `stir` model, but if you want we can sit down and work through it at the department.

Tagging @wds15, as he may have some insight.

**Comment by yizhang-yiz** [comment]
@SteveBronder sorry for letting this fall through. There's nothing wrong with using rk45 integrator on SIR. All I can tell at this point is that the exception is not caused by improper usage of integrator.

**Comment by SteveBronder** [comment]
Ah, I was compiling stuff incorrectly. All is well!

**Comment by SteveBronder** [comment]
When you use link time optimization all of your intermediary objects have to also use lto and the same optimization level

**Comment by SteveBronder** [comment]
This was an issue with Eigen 3.3.3, with Eigen 3.3.7 these discrepancies go away

**Comment by bob-carpenter** [comment]
@SteveBronder If it's fixed in 3.37, can you close this and open an issue to upgrade Eigen that points to this?

**Comment by rok-cesnovar** [comment]
We are already using 3.3.7, so we can just close this I guess.

**Comment by SteveBronder** [comment]
Yes this was closed but I wanted to post the resolution here
