### ISSUE TITLE
Add doxygen module for #1392's require_* template metaprogramming

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1396]
## Description

Need to add a doxygen module for #1392 's require_* metaprogramming. There' s a bunch of stuff I wrote in that PR that would be better as a module on mc-stan.org/math

#### Current Version:
v2.20.0

**Comment by syclik** [comment]
Thanks! Any more detail you can leave behind? Naming convention? How you used conjunctions and negations? Possible types?

**Comment by SteveBronder** [comment]
> Thanks! Any more detail you can leave behind? Naming convention? How you used conjunctions and negations? Possible types?

Will def add these Qs! I wanted to mess around with them today and make sure the style makes sense. I think it does! There's a few weirds I'll have to talk about tho'
