### ISSUE TITLE
consolidate matrix autodiff tests into framework

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1412]
## Description

Remove the piecemeal testing for matrices at all levels of autodiff and replace them with tests using the autodiff framework in `mix`.

## Functions

The functions whose tests will be updated are:

* [x] `add` (had fwd tests in `operator_addition`; was missing mix tests)
* [x] `add_diag` (was missing fwd and mix tests)
* [x] `append_col`
* [x] `append_row`
* [x] `block` (was missing rev tests)
* [x] `cholesky_decompose`
* [x] `col`
* [x] `columns_dot_product` (was missing rev tests)
* [x] `columns_dot_self` (also missing rev tests)
* [x] `crossprod`
* [x] `cumulative_sum`
* [x] `determinant`
* [x] `diag_matrix`
* [x] `diag_post_multiply`
* [x] `diag_pre_multiply`
* [x] `diagonal` (was missing rev mode tests)
* [x] `distance` (missing some value tests in refactor)
* [x] `divide` (fwd tests in `operator_division`; was missing mix tests)
* [x] `dot_product`
* [x] `dot_self`
* [x] `eigenvalues_sym`
* [x] `eigenvectors_sym` (was missing rev tests)
* [x] `elt_divide`
* [x] `elt_multiply`
* [x] `head` (was missing rev tests)
* [x] `inverse_spd`
* [x] `log_determinant_ldlt`
* [x] `log_determinant_spd` (was missing prim, rev symmetry checks in function impl)
* [x] `log_determinant`
* [x] `log_softmax`
* [x] `log_sum_exp` (was missing row vector tests)
* [x] `matrix_exp_2x2` (was missing mix tests---all the matrix_exp were missing these)
* [x] `matrix_exp_multiply` (was missing fwd and mix tests)
* [x] `matrix_exp` (was missing mix tests)
* [x] `matrix_exp_pade` (was missing mix tests)
* [x] `max` (was missing mix tests)
* [x] `min`
* [x] `mdivide_left_ldlt`
* [x] `mdivide_left_spd`
* [x] `mdivide_left`
* [x] `mdivide_left_tri_low`
* [x] `mdivide_left_tri` (left OPENCL tests in rev)
* [x] `mdivide_right_ldlt`
* [x] `mdivide_right_spd` (was missing rev tests)
* [x] `mdivide_right_tri_low` (was also missing rev tests)
* [x] `mdivide_right_tri` (this too also missing rev tests)
* [x] `mdivide_right`
* [x] `mean`
* [x] `minus`
* [x] `multiply_lower_tri_self_transpose`
* [x] `multiply` (fwd tests in `operator_multiply`; was missing mix tests; left OPEN CL tests in rev)
* [x] `prod`
* [x] `qr_Q`
* [x] `qr_R`
* [x] `qr_thin_Q` (was missing mix tests)
* [x] `qr_thin_R` (was missing mix tests)
* [x] `quad_form_diag`
* [x] `quad_form_sym`
* [x] `rep_matrix` (was missing rev tests)
* [x] `rep_row_vector` (was also missing rev tests)
* [x] `rep_vector` (this too missing rev tests)
* [x] `row`
* [x] `rows_dot_product` (was missing rev tests)
* [x] `rows_dot_self` (was also missing rev tests)
* [x] `sd`
* [x] `segment` (was missing rev tests)
* [x] `singular_values` (was missing rev tests)
* [x] `softmax`
* [x] `sort_asc` (in `sort_test.cpp`)
* [x] `sort_desc` (also in `sort_test.cpp`)
* [x] `squared_distance`
* [x] `sub_col` (was missing rev tests)
* [x] `sub_row` (also missing rev tests)
* [x] `subtract` (had fwd tests in `operator_subtract`; was missing mix tests)
* [x] `sum`
* [x] `tail` (was missing rev test)
* [x] `tcrossprod`
* [x] `trace_inv_quad_form_ldlt`
* [x] `trace_quad_form`
* [x] `trace`
* [x] `transpose`
* [x] `variance`

The constraining variable transforms and their derivatives and their Jacobian derivatives are moved to the ad test framework:

* [x] `cholesky_corr_constrain` (was missing fwd and mix tests)
* [x] `corr_matrix_constrain` (was missing fwd and mix tests)
* [x] `cov_matrix_constrain` (was missing fwd and mix tests)
* [x] `ordered_constrain` (was missing fwd and mix tests)
* [x] `positive_ordered_constrain` (was missing fwd and mix tests)
* [x] `simplex_constrain` (was missing fwd and mix tests)
* [x] `unit_vector_constrain` (was missing mix tests [and didn't work], had redundant rev tests)

These scalar versions were also added (can't do `lub_constrain` without ternary):

* [x] `lb_constrain` (was missing rev, fwd, and mix tests)
* [x] `ub_constrain` (also missing rev, fwd, and mix tests)
* [x] `identity_constrain` (also missing rev, fwd, and mix tests)

#### Current Version:
v3.0.0

**Comment by bbbales2** [comment]
Do we have three argument functions yet?

I was writing some code for Aki and, even though it is prim-only code, I had a problem with type algebra that the upstream tests caught.

I just implemented the necessary rev tests manually to get it done (https://github.com/stan-dev/math/blob/f573698ea3c6095a6d24de65915a501e9f3b84bc/test/unit/math/rev/mat/fun/gp_dot_prod_cov_test.cpp), but is there a way to write these in the test-framework?

**Comment by bbbales2** [comment]
The most complicated signature looks like https://github.com/stan-dev/math/blob/f573698ea3c6095a6d24de65915a501e9f3b84bc/stan/math/prim/mat/fun/gp_dot_prod_cov.hpp#L445

**Comment by bob-carpenter** [comment]
Not in the test framework.  Just some legwork to expand eight possible argument combos to add them.

**Comment by bob-carpenter** [comment]
There are not three-arg versions yet.  It'd be easy to add.  The types don't matter as long as they're Stan types.

Three arg versions would let us add `fma` and `log_mix` at the scalar level.

Do you want me to add the three-arg tests?  These branches are getting stacked up on top of each other waiting for the release to clear.
