### ISSUE TITLE
inverse_spd should have consistent errors on size 0

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1432]
## Description

This test should pass in `test/unit/math/mix/mat/fun/inverse_spd_test.cpp`:

```
Eigen::MatrixXd m00(0, 0);
stan::test::expect_ad(f, m00);
```

Edit:  I previous indicated this was an error, but I don't see why the unique 0 x 0 matrix isn't considered the inverse of the 0 x 0 matrix.  It satisfies the identity laws.  Also, I'd think that the determinant of an empty matrix would be one as it's a product, and the empty product is one.

#### Current Version:
v3.0.0

**Comment by mcol** [comment]
Reopening as the updated description indicates that we shouldn't throw but return an empty matrix.
