### ISSUE TITLE
do not print matrix when check_pos_definite fails

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#145]
See

https://groups.google.com/d/msg/stan-users/_0bBC-F2368/XvtzKhfFFQAJ

Particularly since big matrices are the most likely to be numerically indefinite this outputs a ton of numbers that are diagnostically useless. Also the unit test needs to be changed because it checks that the matrix is printed out correctly.

**Comment by syclik** [comment]
Sounds good. What do you think is reasonable here?

**Comment by bgoodri** [comment]
I would say print nothing from the matrix, but if you have to print
something then print the last diagonal element of the Cholesky factor.

**Comment by bob-carpenter** [comment]
I find those error messages very confusing that give you a single
entry in a matrix.

If models are consistently running into numerical issues with
covariance matrices, won't that signal a bigger problem?  Not that
I think you need the actual entries.  

- Bob

**Comment by bgoodri** [comment]
Even if the matrix were 2x2, what is to be gained from seeing it when it is
numerically singular?
