### ISSUE TITLE
make matrix exponentials work on size 0 inputs

### ISSUE THREAD

**Issue by mcol** [stan-dev/math#1456]
## Description
Currently matrix exponentials use `check_nonzero_size` to throw on 0x0 inputs. The discussion in #1454 led to the decision to make all matrix exponentials return a 0x0 matrix on 0x0 inputs. This requires changing `matrix_exp` and `matrix_exp_multiply`.

**Comment by rok-cesnovar** [comment]
Reasons for reopening are given [here](https://github.com/stan-dev/math/pull/1457#issuecomment-557544562)
