### ISSUE TITLE
consistent documentation of row/col template parameters to Eigen::Matrix

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1473]
#### Summary:

We should be documenting the row and column template parameters of our functions involving Eigen types following the convention used by Eigen in their own documentation (with additional namespace qualifier `Eigen::` for us):

 * @tparam R number of rows or `Eigen::Dynamic`
 * @tparam C number of columns or `Eigen::Dynamic`

#### Current Version:
v2.21.0

**Comment by peterwicksstringfield** [comment]
I did some of this in #1486.

Every file in
stan/math/prim/mat/err/*
should be okay now, as far as this ticket is concerned; that is, any R/C tparams in those files are documented correctly.

As far as I can tell, no changes are necessary in:
stan/math/prim/mat/eigen_plugins.h
stan/math/prim/mat/functor/*
stan/math/prim/mat/prob/*
stan/math/prim/mat/vectorize/*

stan/math/prim/mat/{meta,fun}/* is left to do. Also everything outside of stan/math/prim/mat. All that work is up for grabs, as I cannot commit to doing it.

**Comment by rok-cesnovar** [comment]
Thank you, will take a look shortly. Also thanks for clarifying what is left to do.
