### ISSUE TITLE
tweedie regression in stan

### ISSUE THREAD

**Issue by nazi123** [stan-dev/math#1481]
Hello everybody
I am a green hand to Stan and I want to run a tweedie spatio-temporal model on my dataset with Bayesian estimation. Now my question is:
Do I have to write both of “the model on (mu)” and “the tweedie distribution for (y)” in a stan page?
Or I should just write the tweedie distribution in stan and after that, define the model in R? I really need an example of modeling in stan but I couldn’t find anything. May anybody help me?
I appreciate any suggestion and help.
Many thanks

**Comment by bob-carpenter** [comment]
We do not have the Tweedie distribution built into Stan.  I don't know how hard it would be implement as a Stan program.  See the [Stan home page](https://mc-stan.org/), which has all the doc.  If you know you want to use R and write Stan models from scratch, then you can start with the RStan getting started page.  Here's the [user's guide chapter on custom distribution](https://mc-stan.org/docs/2_21/stan-users-guide/custom-probability-functions-chapter.html);  Aki also wrote a [case study on custom densities](https://mc-stan.org/users/documentation/case-studies/gpareto_functions.html).

I suggest taking future general questions about usage and modeling to the [Stan forums](https://discourse.mc-stan.org).  We like to reserve GitHub for bug reports and feature requests.

**Comment by nazi123** [comment]
Thank you very much for your reply and the links. I will ask my questions about modeling and bug reports in the future.
Many thanks
