### ISSUE TITLE
doxygen is broken on Mac OS X after latest upgrade

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1484]
## Description

Neither @mitzimorris nor I can get the new doxygen updates working on our Macs.  We've spent a couple hours on it and the formatting changes that were made in []() don't seem to be worth this effort.

One fix would be to revert the PR that made the changes as they're minor formatting things.  I personally don't think they're worth the trouble I've already had with this.

## Example

```
~/cmdstan/stan/lib/stan_math(feature/0123-complex-var)$ make doxygen
mkdir -p doc/api
doxygen doxygen/doxygen.cfg
warning: the dot tool could not be found at /usr/bin/dot
```

## More info

The problem originated in  https://github.com/stan-dev/math/pull/1397, which is why I assigned it to @SteveBronder.

Here's my doxygen setup:

```
~/cmdstan/stan/lib/stan_math(feature/0123-complex-var)$ which doxygen
/usr/local/bin/doxygen
~/cmdstan/stan/lib/stan_math(feature/0123-complex-var)$ doxygen --version
1.8.16
```

And here's `dot`:

```
~/cmdstan/stan/lib/stan_math(feature/0123-complex-var)$ which dot
/usr/local/bin/dot
```

The relevant config in `doxygen/doxygen.cfg` is:

```
# The default value is: YES.
HAVE_DOT               = NO
...
DOT_PATH               = /usr/bin/dot
```

Now if I change the `DOT_PATH` to the path to my version of `dot`, I get this:

```
~/cmdstan/stan/lib/stan_math(feature/0123-complex-var)$ make doxygen
mkdir -p doc/api
doxygen doxygen/doxygen.cfg

```

returning instantly and only the boilerplate doc is generated.

#### Current Version:
v3.0.0

**Comment by SteveBronder** [comment]
Can you try commenting out the `DOT_PATH`? i.e.

# DOT_PATH = blah

That should remove the dot path thing

From there is there no index.html in doc/api/html ? When I build it on my work mac and open the index.hpp I can do the search and all of the other stuff? Are you on develop or on the complex branch?

**Comment by SteveBronder** [comment]
Also what version of doxygen do you have? I do need to sit down and see what's going on with `
```
stan/math/opencl/copy.hpp:218: warning: argument 'src' from the argument list of stan::math::copy_cl has multiple @param documentation sections
```

**Comment by mitzimorris** [comment]
removed DOT_PATH - doxygen runs in under 1 sec - it populates doc/api/html with index.html etc, but doesn't build docs for any of the code base.
no entries for classes, functions, modules, or namespaces.

first upgraded to doxygen 1.8.13,  then upgraded to latest - doxygen 1.8.16

**Comment by mitzimorris** [comment]
changed the file `doxygen/doxygen.cfg` as follows:

```
diff --git a/doxygen/doxygen.cfg b/doxygen/doxygen.cfg
index a693c01d26..9eef42b23d 100644
--- a/doxygen/doxygen.cfg
+++ b/doxygen/doxygen.cfg
@@ -826,10 +826,7 @@ RECURSIVE              = YES
 # Note that relative paths are relative to the directory from which doxygen is
 # run.
 
-EXCLUDE                = */test/* \
-                         */lib/* \
-                         *sundials* \
-                         */LICENSE.md \
+EXCLUDE                = LICENSE.md \
                          doxygen/howto_add_page.md
 
 # The EXCLUDE_SYMLINKS tag can be used to select whether or not files or
@@ -846,7 +843,7 @@ EXCLUDE_SYMLINKS       = NO
 # Note that the wildcards are matched against the file with absolute path, so to
 # exclude all test directories for example use the pattern */test/*
 
-EXCLUDE_PATTERNS       = */lib/*
+EXCLUDE_PATTERNS       =
 
 # The EXCLUDE_SYMBOLS tag can be used to specify one or more symbol names
 # (namespaces, classes, functions, etc.) that should be excluded from the
@@ -2353,7 +2350,7 @@ INTERACTIVE_SVG        = YES
 # found. If left blank, it is assumed the dot tool can be found in the path.
 # This tag requires that the tag HAVE_DOT is set to YES.
 
-DOT_PATH               = /usr/bin/dot
+DOT_PATH               =
 
```

this builds:

<img width="777" alt="Untitled" src="https://user-images.githubusercontent.com/5466612/70266980-8051b780-176b-11ea-8eff-ac3644c2feca.png">

**Comment by mitzimorris** [comment]
the `EXCLUDE` and `EXCLUDE_PATTERNS` config isn't needed as far as I can tell:

the following find commands return nothing:

```
~/github/stan-dev/cmdstan/stan/lib/stan_math (develop)> find stan -type d -and -name lib
~/github/stan-dev/cmdstan/stan/lib/stan_math (develop)> find stan -type d -and -name test
~/github/stan-dev/cmdstan/stan/lib/stan_math (develop)> find stan -type d -and -name sundials
```

**Comment by SteveBronder** [comment]
Oh interesting! Okay I think I can just make a PR to fix those excludes and we will be good to go! Apologies for the goof

**Comment by mitzimorris** [comment]
filed a PR and assigned you as reviewer.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/math/pull/1487
