### ISSUE TITLE
include-what-you-use errors

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1485]
## Description

The following files (at least) have include-what-you-use violations:

* `rev/mat/fun/ordered_constrain.hpp`
* `rev/mat/fun/positive_ordered_constrain.hpp`

They use `exp(double)` without including a definition or bringing `std::exp` into scope with a using statement.  The fix is to include `<cmath>` and add a `using std::exp` in functions that use it.  

The header tests didn't catch it because there's an `exp()` definition lurking in `::` for C99 compatibility.  These have caused us enormous headaches in the past for this reason.

I found this bug when introducing `exp(const std::complex<T>&)`, which broke the header tests.   

#### Current Version:
v3.0.0

**Comment by syclik** [comment]
Thanks for trapping this! And for writing a clear issue.

**Comment by bob-carpenter** [comment]
I'm finding more and more of them as I expose std:: functions like sin and exp operating on complex numbers.  I'm just fixing them as I go, but I can probably pull them off into their own PR when I'm done.

**Comment by rok-cesnovar** [comment]
There is also an include of `<math.h.>` here https://github.com/stan-dev/math/blob/develop/stan/math/prim/mat/fun/gp_periodic_cov.hpp#L4 

Not sure why that is there.
