### ISSUE TITLE
dirichlet_lpmf should be dirichlet_lpdf

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1488]
## Description

In `stan/math/prim/mat/prob/dirichlet_lpmf.cpp`, there is a function defined called `dirichlet_lpmf`.   It should be `dirichlet_lpdf` because the simplex variate is continuous.  

I have no idea how the Dirichlet can work with this definition.

#### Current Version:
v3.0.0

**Comment by nhuurre** [comment]
It can work because the old Stan compiler substitutes `dirichlet_log`. It doesn't work with the new compiler.

**Comment by mcol** [comment]
I have the renaming working locally, but before I open a PR I'd like to know one thing: do we need to maintain support for the `_lpmf` version? I don't see that being used directly in cmdstan, rstan, or even stanc3 or docs.

**Comment by bob-carpenter** [comment]
> do we need to maintain support for the _lpmf version?

Even the doc says `dirichlet_lpdf`, so I would rather just get rid of `dirichlet_lpmf`.  The only possible problem this will cause is someone calling `dirichlet_lpmf` directly in C++ code somewhere.  

But given that I don't quite understand @syclik's intentions w.r.t. backward compatibility, we should ask him, too.

**Comment by mcol** [comment]
@syclik's most recent stance on backward compatibility was expressed in https://github.com/stan-dev/math/pull/1482#issuecomment-564169935.

**Comment by bob-carpenter** [comment]
This was resolved in the affirmative with the PR, which deprecates the `_lpmf` form but doesn't remove it.
