### ISSUE TITLE
get rid of 1e-15 fudge in lb_constrain

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1489]
## Description

As of now, there's a check in `stan/math/prim/scal/fun/lub_constrain.hpp` that will return 1e-15 rather than underflowing to zero.  This can cause problems and should be changed to just returning the closest output, even if it's 1.  Currently, it's

```
 if ((x > NEGATIVE_INFTY) && (inv_logit_x == 0)) {
      inv_logit_x = 1e-15;
```

This conditional should just be eliminated.

For some discussion, see [this forum discussion](https://discourse.mc-stan.org/t/simple-example-of-an-improper-posterior-without-warnings-from-stan/11554/22)

#### Current Version:
v3.0.0

**Comment by nhuurre** [comment]
Some more discussion #1441

**Comment by bob-carpenter** [comment]
Duplicate of #1441.  Thanks for the gentle reminder, @nhuure---despite commenting on thae issue you raised, I  had forgotten about it. I'll go clarify the original issue #1441 with the intended fix.
