### ISSUE TITLE
fix gitignore for test directory

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#149]
Currently, new tests are masked by gitignore. This is due to copying the gitignore directly from stan-dev/stan when we split this out.

**Comment by syclik** [comment]
@bgoodri, I'm having a lot of trouble getting this working. Mind taking a stab at it?

**Comment by bgoodri** [comment]
This seems difficult. One option would be to do
```
find test/ -executable -type f >>.gitignore
```
rather than excluding the entire test directory. But it seems like a cleaner idea would be to put the hand-written tests in a test/ directory under stan/ and then exclude the top-level test directory where all the generated stuff goes.
