### ISSUE TITLE
Some loops may need to be interchanged; column major

### ISSUE THREAD

**Issue by peterwicksstringfield** [stan-dev/math#1490]
## Description
There are a few places in the code where we walk a column-major Eigen matrix row-major style, when we could interchange the loops. Probably the compiler does it for us anyway, but interchanging the loops would make the code more self-documenting. This might be worth it? Feel free to close this ticket and trust the compiler to handle it.

Two such interchanges are performed in PR #1491.

The diffs would be trivial, but the change would not. A certain amount of close-reading is required to be sure the interchange is safe and the surrounding code is tested.

- [X] stan/math/prim/mat/prob/lkj_cov_lpdf.hpp
```
  for (int m = 0; m < y.rows(); ++m) {
    for (int n = 0; n < y.cols(); ++n) {
      check_finite(function, "Covariance matrix", y(m, n));
      ...
```
(Don't even need the loops here? Looks like this predates a generalization of check_finite, which can accept matrices.)

- [ ] stan/math/prim/mat/prob/gaussian_dlm_obs_lpdf.hpp
122 and 283
```
    for (int i = 0; i < C0.rows(); i++) {
      for (int j = 0; j < C0.cols(); j++) {
        C(i, j) = C0(i, j);
        ...
```
(See #1466.)

- [X] stan/math/prim/mat/prob/matrix_normal_prec_rng.hpp
102
```
  for (int row = 0; row < m; ++row) {
    for (int col = 0; col < n; ++col) {
      double stddev = row_stddev(row) * col_stddev(col);
      ...
      X(row, col) = stddev * std_normal_rng();
```

- [X] stan/math/fwd/mat/fun/to_fvar.hpp
52
```
  for (int i = 0; i < val.rows(); i++) {
    for (int j = 0; j < val.cols(); j++) {
      ret(i, j).val_ = val(i, j);
      ret(i, j).d_ = deriv(i, j);
      ...
```

- [X] stan/math/fwd/mat/fun/mdivide_left_ldlt.hpp
```
  for (int i = 0; i < b.rows(); i++) {
    for (int j = 0; j < b.cols(); j++) {
      b_val(i, j) = b(i, j).val_;
      b_der(i, j) = b(i, j).d_;
      ...
```

- [X] stan/math/fwd/mat/fun/inverse.hpp
22
```
  for (size_type i = 0; i < m.rows(); i++) {
    for (size_type j = 0; j < m.cols(); j++) {
      m_inv(i, j) = m(i, j).val_;
      m_deriv(i, j) = m(i, j).d_;
      ...
```

- [X] stan/math/rev/mat/functor/kinsol_data.hpp
37
```
    for (int i = 0; i < Jac.rows(); i++)
      for (int j = 0; j < Jac.cols(); j++)
        SM_ELEMENT_D(J, i, j) = Jac(i, j);
        ...
```
That SUNMatrix is also column major, I think, see
lib/sundials_4.1.0/include/sunmatrix/sunmatrix_dense.h
lib/sundials_4.1.0/include/sundials/sundials_matrix.h
(I would be afraid to touch this code.)

## Example
```
-  for (int i = 0; i < m.rows(); i++) {
-    for (int j = 0; j < m.cols(); j++) {
+  for (int j = 0; j < m.cols(); j++) {
+    for (int i = 0; i < m.rows(); i++) {
```

## Expected Output
Same as before, but with nicer code.

#### Current Version:
v3.0.0

**Comment by wds15** [comment]
Nice catches! I would not trust the compiler here and change the loop order if that’s easy to do.

**Comment by bob-carpenter** [comment]
> On Dec 7, 2019, at 4:56 PM, Peter Wicks Stringfield <notifications@github.com> wrote:
> 
> Description
> 
> There are a few places in the code where we walk a column-major Eigen matrix row-major style, when we could interchange the loops. Probably the compiler does it for us anyway, but interchanging the loops would make the code more self-documenting. This might be worth it? Feel free to close this ticket and trust the compiler to handle it.

I'd be surprised if the compiler could reorder loops to improve memory locality.

> 
> Two such interchanges are performed in PR #XXX.
> 
> The diffs would be trivial, but the change would not. A certain amount of close-reading is required to be sure the interchange is safe and the surrounding code is tested.
> 
> 	•  stan/math/prim/mat/prob/lkj_cov_lpdf.hpp
>   for (int m = 0; m < y.rows(); ++m) {
>     for (int n = 0; n < y.cols(); ++n) {
>       check_finite(function, "Covariance matrix", y(m, n));
>       ...
> 
> (Don't even need the loops here? Looks like this predates a generalization of check_finite, which can accept matrices.)

Right---We should be moving to using check functions on collections, because otherwise we lose indexes in the error messages.  They don't all exist yet, but many of them do now that didn't when we first wrote the code.

> 
> 	•  stan/math/prim/mat/prob/gaussian_dlm_obs_lpdf.hpp
> 122 and 283
>     for (int i = 0; i < C0.rows(); i++) {
>       for (int j = 0; j < C0.cols(); j++) {
>         C(i, j) = C0(i, j);
>         ...
> 
> (See #1466.)

This can't just be C = C0 or at worst a blocked version of the same?

> 
> 	•  stan/math/prim/mat/prob/matrix_normal_prec_rng.hpp
> 102
>   for (int row = 0; row < m; ++row) {
>     for (int col = 0; col < n; ++col) {
>       double stddev = row_stddev(row) * col_stddev(col);
>       ...
>       X(row, col) = stddev * std_normal_rng();
> 
> 	•  stan/math/fwd/mat/fun/to_fvar.hpp
> 52
>   for (int i = 0; i < val.rows(); i++) {
>     for (int j = 0; j < val.cols(); j++) {
>       ret(i, j).val_ = val(i, j);
>       ret(i, j).d_ = deriv(i, j);
>       ...


For large matrices, it can sometimes help to break this down into two loops to reduce memory pressure.  No reason to get that carried away, though.  Presumably we can't just have ret = val and then have a loop for the tangents (d_)?

> 
> 	•  stan/math/fwd/mat/fun/mdivide_left_ldlt.hpp
>   for (int i = 0; i < b.rows(); i++) {
>     for (int j = 0; j < b.cols(); j++) {
>       b_val(i, j) = b(i, j).val_;
>       b_der(i, j) = b(i, j).d_;
>       ...
> 
> 	•  stan/math/fwd/mat/fun/inverse.hpp
> 22
>   for (size_type i = 0; i < m.rows(); i++) {
>     for (size_type j = 0; j < m.cols(); j++) {
>       m_inv(i, j) = m(i, j).val_;
>       m_deriv(i, j) = m(i, j).d_;
>       ...

What this is saying to me is that we should pull out a function to do this rather than reimplementing it in a bunch of files.  More work, I'm afraid, but a much better code organization.

> 
> 	•  stan/math/rev/mat/functor/kinsol_data.hpp
> 37
>     for (int i = 0; i < Jac.rows(); i++)
>       for (int j = 0; j < Jac.cols(); j++)
>         SM_ELEMENT_D(J, i, j) = Jac(i, j);
>         ...
> 
> That SUNMatrix is also column major, I think, see
> lib/sundials_4.1.0/include/sunmatrix/sunmatrix_dense.h
> lib/sundials_4.1.0/include/sundials/sundials_matrix.h

Cool.  Thanks for diving down.

> (I would be afraid to touch this code.)

I really like the book "The Pragmatic Programmer".  It's
all about strategies to control exactly this kind of fear.

In your case, you should be able to rely on the unit tests.

**Comment by peterwicksstringfield** [comment]
Regarding check functions, yeah there's several other instances of "check_foo(blah, blah, xxx(i))" that should be "check_foo(blah, blah, xxx)". I'm going to fix this one instance in this PR, and I've got a list of the others, I'll put it on another ticket.

> This can't just be C = C0 or at worst a blocked version of the same?

It can be C=C0. Might leave this alone for a bit to avoid merge conflicts with the other ticket.

Thanks for the advice, I'll put up a PR in a bit that covers all but the gaussian_dlm one.
