### ISSUE TITLE
Wiener_log: raise exception for tau >= y

### ISSUE THREAD

**Issue by randommm** [stan-dev/math#150]
@bob-carpenter commented 3 days ago (at https://github.com/stan-dev/stan/pull/1578):

"Our general convention for probabilty functions is to raise an
exception.  So rather than the comparisons, this should use
another check function.

And there's never any reason to set a value and then immediately
return it.  It could be written as

  return stan::math::negative_infinity();

But I really think it should be replaced with something that
throws an informative exception --- the idea is to trap errors
as early as possible and let the user know where they arise.

- Bob"

**Comment by randommm** [comment]
Something strange is happening: the test `ValidValues` for branch https://github.com/stan-dev/math/compare/feature/issue-150-raise-exception-for-tau-greater-than-or-equal-to-y won't pass:

      [ RUN      ] AgradDistributionWiener_v_95/AgradDistributionTestFixture/0.ValidValues
      ./test/prob/test_fixture_distr.hpp:110: Failure
      Expected: ({ lp = TestClass.template log_prob <true,T0,T1,T2,T3,T4,T5> (p0,p1,p2,p3,p4,p5); }) doesn't throw an exception.
        Actual: it throws.
      Valid parameters failed at index: 0 -- (1.1000000000000001, 2.1000000000000001, 0.29999999999999999, 0.55000000000000004, 0.40000000000000002)
      ./test/prob/test_fixture_distr.hpp:110: Failure
      Expected: ({ lp = TestClass.template log_prob <true,T0,T1,T2,T3,T4,T5> (p0,p1,p2,p3,p4,p5); }) doesn't throw an exception.
        Actual: it throws.
      Valid parameters failed at index: 1 -- (2.1000000000000001, 4.0999999999999996, 1.8999999999999999, 0.050000000000000003, 0.10000000000000001)
      ./test/prob/test_fixture_distr.hpp:110: Failure
      Expected: ({ lp = TestClass.template log_prob <true,T0,T1,T2,T3,T4,T5> (p0,p1,p2,p3,p4,p5); }) doesn't throw an exception.
        Actual: it throws.
      Valid parameters failed at index: 2 -- (0.10000000000000001, 10.1, 0.050000000000000003, 0.94999999999999996, 0.5)
      ./test/prob/test_fixture_distr.hpp:110: Failure
      Expected: ({ lp = TestClass.template log_prob <true,T0,T1,T2,T3,T4,T5> (p0,p1,p2,p3,p4,p5); }) doesn't throw an exception.
        Actual: it throws.
      Valid parameters failed at index: 4 -- (0.51000000000000001, 1.1000000000000001, 0.29999999999999999, 0.20000000000000001, 10.5)


But when I run 

      parameters {
        real<lower=.3001> a;
      }
      model {
        a ~ wiener(2.1, .3, .55, .4);
        1.1 ~ wiener(2.1, .3, .55, .4);
        increment_log_prob(wiener_log(1.1, 2.1, .3, .55, .4));
      }

in CmdStan, no error message is shown at all. Any ideas?

**Comment by syclik** [comment]
@randommm -- sorry, I missed this comment earlier. I'll take a closer look later.

**Comment by bob-carpenter** [comment]
@syclik  Did you ever take a closer look?  Is this still an issue?
