### ISSUE TITLE
Dead code in test/unit/math/opencl/reference_kernel.hpp

### ISSUE THREAD

**Issue by alashworth** [stan-dev/math#1502]
The function `store_reference_kernel_if_needed` is empty. The ifdef STAN_TEST_KERNEL_GENERATOR_STORE_REFERENCE_KERNELS was removed by @t4c1 in a previous commit.

I discovered this while investigating a test failure on my workstation in test/unit/math/opencl/kernel_generator/binary_operation_test.cpp, in test "reuse_expression_complicated". What is the purpose of the function call on line 221 in this file? And how does that affect the expected output? Apologies if this should go on Discourse.

**Comment by t4c1** [comment]
Some tests of kernel generator work by comparing generated kernel with saved "reference" version. If this macro is defined running tests regenerates these reference kernels and saves them.

**Comment by syclik** [comment]
Sounds like at the very least, it should be documented. @t4c1, is that knowledge somewhere in the documentation? If not, would you mind putting it on the function itself?

**Comment by alashworth** [comment]
Is the test not supposed to succeed, then, unless the macro is defined?

**Comment by t4c1** [comment]
@alashworth The test is supposed to succeed regardless of whether the macro is defined or not. Running a test that was compiled with the macro defined will just update the reference kernel file. This needs to happen only if there are changes in code that modify generated kernel code. These reference kernels are stored on git in `test/unit/math/opencl/kernel_generator_reference_kernels`.

@syclik It is documented on the function. Do you think it is unclear?

**Comment by syclik** [comment]
> @syclik It is documented on the function. Do you think it is unclear?

I'm assuming you mean this doc: https://github.com/stan-dev/math/blob/e74b8fdac3a1b27f475cdda1440174d39c3455ee/test/unit/math/opencl/kernel_generator/reference_kernel.hpp#L26

It's not really clear, but it's ok. I think it's meant to be test code. (If it comes up again independently, someone should put some effort into it.)
