### ISSUE TITLE
Failure on develop with Mac Unit with Threading

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1506]
## Description

We are experiencing issues on `develop` with the `Mac Unit with Threading` tests. Example of an error given below. I am fairly certain that it's a Jenkins/configuration issue. I talked to @serban-nicusor-toptal earlier and he is aware of the issue. Just opening an issue to let everyone else know and if someone else has any thoughts. This does not cause issues on PRs as these tests occur only on merge to develop.

Based on `develop` tests history, a similar error occurred 2 weeks ago and then again a  week ago and it started again yesterday. It was fine in between tho. 

## Example

```
/usr/local/opt/llvm@6/bin/clang++ -DSTAN_THREADS -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT       -I lib/tbb_2019_U8/include -O3  -I . -I lib/eigen_3.3.3 -I lib/boost_1.69.0 -I lib/sundials_4.1.0/include -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1 -I lib/gtest_1.8.1/include -I lib/gtest_1.8.1      -DBOOST_DISABLE_ASSERTS        -c -o test/unit/math/mix/mat/fun/asin_test.o test/unit/math/mix/mat/fun/asin_test.cpp

/usr/local/opt/llvm@6/bin/clang++: /usr/local/opt/llvm@6/bin/clang++: cannot execute binary file
```

#### Current Version:
v3.0.0

**Comment by serban-nicusor-toptal** [comment]
I've narrowed it down to `Mac Unit with Threading` stage being run on the `old-imac` machine. Going to see why it fails specifically on that machine and try to fix it. Will post an update here after.

**Comment by serban-nicusor-toptal** [comment]
The `old imac` machine has a different arch than `gelman-mac`. I've removed the `osx` label from `oldimac` so the job will only run on `gelman-mac`.
Build finished successfully last night, we should be good now!
