### ISSUE TITLE
Improve handling of size 0 inputs

### ISSUE THREAD

**Issue by mcol** [stan-dev/math#1515]
## Description
A number of PRs have gone in recently to handle corner cases concerning size 0 inputs that were discovered through the new autodiff test framework, authored in the most part by me.

A couple of comment #1452 ( https://github.com/stan-dev/math/pull/1452#discussion_r352233941 and https://github.com/stan-dev/math/pull/1452#discussion_r352273992) made me look again at these corner cases, and I realised that things could be handled a bit better.

In particular:
- the current checks mishandle matrices of size 0 x N (or N x 0), as we may return an empty square matrix instead of a rectangular one: affects `mdivide_left_ldlt`, `mdivide_right_ldlt` and `matrix_exp_multiply`
- we should check for the input matrix being square before returning anything: affects `matrix_exp_pade` and `scale_matrix_exp_multiply`, for which we currently we return an empty matrix when we should instead throw
- for `trace_inv_quad_form_ldlt` if the input matrix is 0xN we should return 0, but we currently throw

**Comment by bob-carpenter** [comment]
These changes all sound good.  It's really great that you're sanding off all these rough edges---it makes a big difference in the overall feel of a library when boundary conditions behave correctly.
