### ISSUE TITLE
Unnecessary checks in *_lp[dm]f functions

### ISSUE THREAD

**Issue by mcol** [stan-dev/math#1519]
## Description
Inspired by @bbbales2's observation in the first paragraph of https://github.com/stan-dev/math/issues/1498#issuecomment-564581852, I noticed that there are a number of checks for an `include<...>::value` inside a for loop although at the beginning of the function we had returned if that same check was false. 

Edit by @rok-cesnovar : The same changes need to be done in GPU supported _lpdfs.

## Example
In `poisson_log_lpmf` we have this check towards the beginning:
```
if (!include_summand<propto, T_log_rate>::value) {
  return 0.0;
}
```
Therefore, further down the following code
```
for (size_t i = 0; i < length(alpha); i++) {
  if (include_summand<propto, T_log_rate>::value) {
    exp_alpha[i] = exp(value_of(alpha_vec[i]));
  }
}
```
can be simplified to
```
for (size_t i = 0; i < length(alpha); i++) {
  exp_alpha[i] = exp(value_of(alpha_vec[i]));
}
```

## Expected Output
This should perhaps produce a minimal speedup, unless compilers are already taking care of that. Other than that, these functions should produce the same output as before.

**Comment by rok-cesnovar** [comment]
This do get compiled out but that is not a reason to not clean it.
