### ISSUE TITLE
boost 1.72.0

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#1523]
## Description
We should move to boost 1.72.0 as the CRAN package BH just moved to this version.

## Example

Things to watch out for:

- possibly the patches to avoid overflow of lgamma are still needed (our unit tests catch this)
- possibly there are issues with the RK45 integrators, see https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64-gcc8/OncoBayes2-00install.html

This could be a consideration for @bgoodri to get StanHeaders to CRAN.

#### Current Version:
v3.0.0

**Comment by rok-cesnovar** [comment]
Should be pretty easy to make a WIP PR and let Jenkins tell us what happens for the cmdstan/stan/math tests and we can go from there. Will make a PR.
