### ISSUE TITLE
mdivide_right_spd_test.cpp is asinine

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#153]
by trying to unit test behavior on a matrix with uninitialized cells. See https://github.com/stan-dev/math/pull/135 .

**Comment by bob-carpenter** [comment]
Glad there's a fix on the way.  I agree that testing uninitialized
doesn't make sense --- it's undefined behavior according to the spec.
I hate that C++ has all this undefined behavior.

- Bob

**Comment by syclik** [comment]
Thanks, Ben.

This was fixed by #154.
