### ISSUE TITLE
remove extra copies in softmax

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1539]
## Description

`softmax` as currently written in `prim` and `rev` does extra copies and performs extra checks.  

#### Current Version:
v3.0.0

**Comment by rok-cesnovar** [comment]
The softmax functions were refactored and I think there are no extra copies in https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/softmax.hpp or https://github.com/stan-dev/math/blob/develop/stan/math/rev/fun/softmax.hpp
