### ISSUE TITLE
Documentation of require_all_not_t / require_any_not_t is misleading (i.e. these functions are backwards)

### ISSUE THREAD

**Issue by peterwicksstringfield** [stan-dev/math#1548]
## Description

The documentation of require_all_not_t and require_any_not_t is misleading.

Based on the documentation, require_all_not_t<std::true_type, std::false_type> should disable the template, since the docs say "If all conditions are false, template is enabled.". But it fact it enables the template, and we can see this in the tests.

require_generics.hpp:
```
/**
 * If all conditions are false, template is enabled.
 *
 * Returns a type void if all of the conditions are false.
 */
template <class... Checks>
using require_all_not_t
    = std::enable_if_t<!math::conjunction<Checks...>::value>;
```

require_generics_test.cpp:
```
TEST(requires_prim_scal, all_not_test) {
  using stan::require_all_not_t;
  using stan::test::require_variadic_checker;
  EXPECT_TRUE((require_variadic_checker<require_all_not_t, std::false_type,
                                        std::false_type>::value));
  EXPECT_FALSE((require_variadic_checker<require_all_not_t, std::true_type,
                                         std::true_type>::value));
  EXPECT_TRUE((require_variadic_checker<require_all_not_t, std::true_type,
                                        std::false_type>::value));
}
```

require_any_not_t is mixed up too. Based on the docs, require_any_not_t<std::true_type, std::false_type> should enable the template, but we can see in the testcase that this disables it.

```
/**
 * If any condition is false, template is enabled.
 *
 * Returns a type void if any of the conditions are false.
 */
template <class... Checks>
using require_any_not_t
    = std::enable_if_t<!math::disjunction<Checks...>::value>;
```

```
TEST(requires_prim_scal, any_not_test) {
  using stan::require_any_not_t;
  using stan::test::require_variadic_checker;
  EXPECT_TRUE((require_variadic_checker<require_any_not_t, std::false_type,
                                        std::false_type>::value));
  EXPECT_FALSE((require_variadic_checker<require_any_not_t, std::true_type,
                                         std::true_type>::value));
  EXPECT_FALSE((require_variadic_checker<require_any_not_t, std::true_type,
                                         std::false_type>::value));
}
```

A bunch of the testcases are oddly named as well. "all_not_same_test" tests a function called "require_any_not_same_t", "all_not_convertible_test" tests a function called "require_any_not_convertible_t", etc.

I would argue that these functions are simply backwards. require_all_not_t should be called "require_not_all_t" or "require_any_not_t"; and require_any_not_t should be called "require_not_any_t" or "require_all_not_t". The tests are backwards too so the backwardness cancels out and they pass.

I think something needs to get swapped, either documentation, or names, or implementations. And the changes might need to be chased through the rest of require_generics.hpp, and require_generics_test.cpp, since a bunch of the compound require_foos use require_all_not_t or require_any_not_t internally.

It looks like the "any_not" versions are used in the signatures of trace_blah_quad_form_blah family. I don't see any users of the "all_not" versions.

## Expected Output
Output of the math library should be the same, documentation should be consistent with the testcases.

#### Current Version:
v3.0.0

**Comment by peterwicksstringfield** [comment]
I'm working up a PR that basically does:

```
using require_all_not_t
-    = std::enable_if_t<!math::conjunction<Checks...>::value>;
+    = std::enable_if_t<!math::disjunction<Checks...>::value>;
 
 using require_any_not_t
-    = std::enable_if_t<!math::disjunction<Checks...>::value>;
+    = std::enable_if_t<!math::conjunction<Checks...>::value>;
```

and chases the changes. Might not get it up until tomorrow though.

And it remains an option to just change the documentation instead.

**Comment by bob-carpenter** [comment]
Good catch.  They are definitely misnamed as is and your proposed fix is the right one.

**Comment by SteveBronder** [comment]
Yes thanks! Agree with Bob I think writing this I got goofed on all the combinations

**Comment by peterwicksstringfield** [comment]
Thanks, I'm glad to know I'm on the right track.

The PR is now ready for review.
