### ISSUE TITLE
Update to eigen 3.4?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1556]
## Description

Eigen has released Eigen 3.4-beta1, should we update? If it's we want to wait for the stable release that's reasonable. Though 3.4 has some cool new features!

http://eigen.tuxfamily.org/index.php?title=3.4

#### Current Version:
v3.0.0

**Comment by wds15** [comment]
Looks really nice indeed. I do not think we would want to merge a beta. You can explore on a branch to spot the issues. However, we anyway have to wait for CRAN to bump the RcppEigen  Version before we merge.

**Comment by bob-carpenter** [comment]
RStan's still at 2.19---is the plan to just skip over 2.20 and 2.21 and go straight to 2.22?

There's a fix pending in 3.4 for mixed-type binary operations that'll complete the complex interface and potentially simplify the non-complex interface.

**Comment by wds15** [comment]
2.20 will be skipped, yes. I think we should deploy RStan 2.21 since this is the last release with the old compiler.

**Comment by bob-carpenter** [comment]
They're still heading toward a stable release and we can't really update until RcppEigen updates or we'll break RStan.  So I'm just going to close this.  We'll update to 3.4 as a matter of course after it's released.  I have checked that everything works---some of the Eigen internal stuff changed signature, but it's a straightforward fix.
