### ISSUE TITLE
Location of ldlt_factor.hpp

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1559]
## Description

This came up during the flattening and is more of a question really. Is the location of the ldlt_factor.hpp file correct (its currently located in prim/mat/fun/ and /rev/mat/fun). Its not really a typical function, but its also not a functor. Would moving it to core/ make more sense?

#### Current Version:
v3.0.0

**Comment by bob-carpenter** [comment]
If it's used in other functions, I think it makes sense to keep it standalone and leave it in `fun` where it's used.  It could also be made internal, I think, as it's not exposed to the Stan language.  

If it's only used in one function, I'd put it in an internal namespace in that function's file.

**Comment by rok-cesnovar** [comment]
Thanks. Lets leave it as is.
