### ISSUE TITLE
Should the requires_* meta programming be named enable_if_*?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1568]
### Naming Things is Hard

The SFINAE metaprogramming all starts with `require_` such as `require_arithmetic_t<...>`, `require_not_all_eigen_vt<..., ...>`, etc. Bob suggested we move to `enable_if_*` (`enable_if_arithmetic_t<...>`, `disable_if_all_eigen_vt<..., ...>`) instead of `require_*`. I'm looking for feedback to see if people who have been using the `require_*` stuff think the naming should be changed.

I wrote that stuff while staring at [concepts](https://en.cppreference.com/w/cpp/language/constraints) with a lot of envy. I went with `require_*` since it can be elbow-greased to a legacy concepts look/feel. But imo I do like that `disable_if_all_*` and `disable_if_any_*` are more clear than `require_not_all_*` and `require_not_any_*`.

#### Current Version:
v3.0.0

**Comment by t4c1** [comment]
I think require is a bit more readable, since it expresses the same meaning in less words.

**Comment by bob-carpenter** [comment]
The standard library uses "enable_if" and I think we should follow their convention.  The reason to stick to the conventions is to make it more learnable for people who know the langauge, but don't know our code base.

**Comment by mcol** [comment]
I was more in the require camp, but disable is much better than require_not, so I agree with changing them. Let's hear from other folks: @syclik, @rok-cesnovar, @wds15, @martinmodrak

**Comment by SteveBronder** [comment]
My intention with calling them `require_*` was to try to phrase them like the new C++20 requires. For instance, `require_vector_like<>` in C++20 would be something like

```cpp
// Check that a type T has operator[]
template <typename T>
concept VectorLike = requires (T x) {x[0]}; 

template<typename T>
requires VectorLike<T>
void f(T a);  

// Or alt
template <VectorLike T>
void f(T a);
```

With our stuff this is 

```cpp
template <typename T, typename = require_vector_like<T>>
void f(T a);
```

It's kind of close and imo I think C++20 is going to be popular in the future so people will be used the requires and concepts in the future

**Comment by SteveBronder** [comment]
Though I also agree disable_if looks nicer

**Comment by bob-carpenter** [comment]
Coo.  If that's the new standard in C++20, then I'm all for it.  My only concern
was not matching the enable_if terminology.

**Comment by SteveBronder** [comment]
Word! I'll leave this open for a bit in case anyone else has Qs
