### ISSUE TITLE
Move /vectorize files to /meta

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1595]
## Description

Could we move the files in /vectorize to the /meta folder? I feel that there is no real need to have a separate folder for 1 file that could easily be placed in the /meta subfolder. They arent that far off from the vector builders etc.

Are there any specific reasons behind having a separate folder or the apply_* header files? Else I will move them to /meta once we finish the flatten.

We currently have the following files in */vectorize:

```
stan/math/fwd/vectorize/apply_scalar_unary.hpp
stan/math/rev/vectorize/apply_scalar_unary.hpp
stan/math/prim/vectorize/apply_scalar_unary.hpp
```

#1558  will also add stan/math/prim/vectorize/apply_scalar_unary.hpp

#### Current Version:
v3.0.0

**Comment by bob-carpenter** [comment]
OK with me to move vectorize/* to meta/.
