### ISSUE TITLE
tests for normal_* can be updated to use expect_ad

### ISSUE THREAD

**Issue by mcol** [stan-dev/math#1597]
## Description
In #1580 I added tests for `std_normal_*` by copying the existing tests for `normal_*`. During review, @bbbales2 suggested to switch them to use expect_ad, and I did that there. This issue is for updating in a similar way the tests for `normal_*`.

## Expected Output
Improved test coverage using fewer lines of code or hand-written code.

#### Current Version:
v3.0.0

**Comment by bob-carpenter** [comment]
It would be ideal if we had adaptors that could test the log density/mass functions---they're vectorized reductions, so have very regular container behavior given base test cases.
