### ISSUE TITLE
log_falling_factorial returns incorrect value

### ISSUE THREAD

**Issue by randommm** [stan-dev/math#161]
`log_falling_factorial(x, n)` is documented as `log(gamma(x + 1)/gamma(x - n + 1))` but returns `log(gamma(x + 1)/gamma(n + 1))`

**Comment by randommm** [comment]
Also, it seems confusing that `falling_factorial(x, n)` == `gamma(x + 1)/gamma(x - n + 1)` == `x!/(x-n)!`, but `rising_factorial(x, n)` == `gamma(x + n)/gamma(x) == (x + n - 1)!/(x - 1)!`

**Comment by bob-carpenter** [comment]
Could the offset be so that rising * falling gives you something
reasonable?  I never use these functions.

**Comment by randommm** [comment]
It seems that it follows Mathematica convention:

http://mathworld.wolfram.com/FallingFactorial.html
http://mathworld.wolfram.com/RisingFactorial.html

So, all that is left is to fix the bug itself.
