### ISSUE TITLE
Start merging post release now?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1640]
## Description

We have a pretty decent sized backlog of PRs to merge. Should we do them in some order and all the other ones have to merge after? We should get on it soon since the testing will have to sound off for each one

#### Current Version:
v3.1.0

**Comment by rok-cesnovar** [comment]
Lets wait for cmdstan to release (should happen soon) just to be safe and then go by number, starting with https://github.com/stan-dev/math/pull/1558 and on. Poor Jenkins will be pretty busy over the weekend :)

**Comment by rok-cesnovar** [comment]
1558, 1602, 1603, 1618, 1626, 1630, 1632, 1634 are all approved or have a comment that they are gtg after release. It might be best if someone volunteers and merges them one by one.

**Comment by rok-cesnovar** [comment]
Everything merged, lets close once this batch of merge-to-develop tests all pass.
