### ISSUE TITLE
Variadic argument lists for ODEs

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1642]
## Description

Provide a way to use variadic argument lists for odes to avoid the inconvenient packing/unpacking that goes along with using the current ODE solvers.

Moved here from PR #1641.  

## Example

```
real[ , ] integrate_ode_rk45(function ode, real[] initial_state,
                             real initial_time, real[] times,
                             T1 arg1, T2 arg2, ...)
```
where the ode right hand side function looks like:
```
real[] ode(real time, real[] state, T1 arg1, T2 arg2, ...)
```

We'll need to create new signatures for these functions to handle the issue with inferring types described https://discourse.mc-stan.org/t/default-arguments-parameter-packs/12748/14.

#### Current Version:
v3.1.0

**Comment by bbbales2** [comment]
Closed by #1641
