### ISSUE TITLE
[proposal] Stop using the wiki and make pages on the new site

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1658]
## Description

Right now we have two sources of high level docs for stan math, [the site](http://mc-stan.org/math/) and the [wiki](https://github.com/stan-dev/math/wiki). idt it's a good idea to have two floating resources floating around since there's a non-zero chance they will go out of sync. I think it would be better to move everything over to the site so that docs are versioned along with what version of Stan we are on.

I have some docs here on adding new pages to the website, if they don't make sense lmk and I can update them with more examples!

https://github.com/stan-dev/math/blob/develop/doxygen/howto_add_page.md

Is there anything else on the wiki we need to move over to the site? If people agree with this then I think it would be good to have a deprecated warning on the homepage of the wiki redirecting to the stan math site

#### Current Version:
v3.1.0

**Comment by rok-cesnovar** [comment]
Yes please. The wiki has a bunch of outdated stuff already and has a lot of pages that are probably not needed anymore (like the TBB dependency checklist for instance) The only thing I would like to see done before we move to this is not run the full test suite for changes to the /doxygen folder.

**Comment by mcol** [comment]
What's needed to skip running the CI for changes limited to the doxygen folder? Pinging also @serban-nicusor-toptal in case he can help here.

**Comment by serban-nicusor-toptal** [comment]
I will open a PR for the Jenkinsfile to ignore changes that do not touch the source code. Around the lines of 

```
#!/bin/bash
declare -a source_files=(
    "src"
    "tests"
    "Makefile"
)

for i in "${source_files[@]}"
do
   echo "Checking differences for: $i"
   differences=`git diff $i`
   if [ -z "$differences" ]
   then
        echo "No diffs for: $i"
   else
        echo "Found diffs for: $i"
        exit 1
    fi
done
```

We should define what source code means for each project and skip ci/cd for whatever doesn't touch it.

**Comment by rok-cesnovar** [comment]
For Math which is the most pressing I think this is it: 
- top level folder: everything except *.md and *.txt
- entire /lib, /make, /src and /test folders

**Comment by serban-nicusor-toptal** [comment]
[stan](https://github.com/stan-dev/stan/blob/develop/Jenkinsfile#L36), [math](https://github.com/stan-dev/math/blob/develop/Jenkinsfile#L31) and [cmdstan](https://github.com/stan-dev/cmdstan/blob/develop/Jenkinsfile#L33) will now skip intensive ci/cd on changes that do not affect source code.
