### ISSUE TITLE
Release of Math 3.1.1

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1659]
## Description

With the merge of https://github.com/stan-dev/math/pull/1644 everything is ready to proceed with the hotfix release for Math. This PR fixed https://github.com/stan-dev/math/issues/1643 which was the standing issue in 3.1.

So the merge commit https://github.com/stan-dev/math/commit/987ffae6966a49e47f28f89b398a293f234ff701 should be cherry picked to master and released. If anyone objects or has any comments please dont hestitate to comment.

#### Current Version:
v3.1.0

**Comment by SteveBronder** [comment]
Thanks for being so on top of this @rok-cesnovar and @serban-nicusor-toptal !

**Comment by mcol** [comment]
I'm not sure where to mention this, so I'll leave a note here: it seems that the search and replace for "3.1.0" to "3.1.1" also affected the sundials path in `doxygen/contributor_help_pages/windows_devnotes.md`, which makes the instructions in those files incorrect.

**Comment by rok-cesnovar** [comment]
This is the perfect spot to mention that. Thanks

**Comment by serban-nicusor-toptal** [comment]
Thanks @mcol

**Comment by serban-nicusor-toptal** [comment]
Math master failed after the 3.1.1 see https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/master/52/pipeline

**Comment by rok-cesnovar** [comment]
Order is restored, hotfix was released and master looks [healthy ](https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/master/54/pipeline/). Once Jenkins finishes we will proceed with the Stan release. Closing.
