### ISSUE TITLE
math::multiply should be able to handle empty matrix or vectors

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/math#1669]
## Description

The math lib function `multiply` requires that `rows()` and `cols()` are positive.  This should be changed to non-negative in order to support matrices or vectors of size zero.

## Example

see https://github.com/stan-dev/cmdstanpy/issues/203

## Expected Output

All rules for output sizes work.  That is, matrix multiplication is (M x N) times (N x K), yielding an (M x K) matrix, even if some are zero.  Same for row-vector/matrix mulitply and matrix/vector multiply.

#### Current Version:
v3.1.0

**Comment by mitzimorris** [comment]
@syclik  - this issue needs someone who can handle the C++ and knows the math.   I'm timing myself out on this one.   maybe @dpsimpson, @charlesm93  or @bbbales2 could review the list of functions and give us a ruling as on which of m1.rows, m1.cols, m2.rows, m2.cols - can be zero or must be positive?

**Comment by mcol** [comment]
Copying the testcase from https://github.com/stan-dev/cmdstanpy/issues/203:
```
data {
  int num_points;
  matrix[num_points, 1] features;
  int labels[num_points];
}
parameters {
  vector[1] x;
}
model {
  x[1] ~ normal(0, 1);
}
generated quantities {
  real test_log_likelihood;
  test_log_likelihood = bernoulli_logit_lpmf(labels | features * x);
}
```
I've run it in cmdstanr with `list(num_points=0, features=matrix(0, 0, 1), labels=integer())` as data. If I change the `check_multiplicable` in `multiply.hpp` to a `check_size_match("multiply", "m1.cols", m1.cols(), "m2.rows", m2.rows())` the testcase runs:
```
> fit$summary()
# A tibble: 3 x 10
  variable       mean  median    sd   mad    q5      q95  rhat ess_bulk ess_tail
  <chr>         <dbl>   <dbl> <dbl> <dbl> <dbl>    <dbl> <dbl>    <dbl>    <dbl>
1 x[1]         0.0323  0.0668 0.995 0.987 -1.59  1.63     1.00    1470.    1847.
2 test_log_l…  0       0      0     0      0     0       NA         NA       NA
3 lp__        -0.495  -0.226  0.704 0.308 -1.86 -0.00240  1.00    1736.    2144.
```
Similar change should be done to the rev/fwd versions. Is this enough or do you need a more general solution?

**Comment by mitzimorris** [comment]
@mcol  - I think this needs a more general solution.   if this works, that would be great.
yesterday afternoon I edited the issue, but it would seem that my edits got lost  - here's a summary:

`check_multiplicable`  is used in a lot of places - approx 40 math functions.
`check_multiplicable` enforces too strict a definition of multiplicability - it requires that both matrices are non-empty.  however, Stan users are using models that sometimes have empty matrices because the language and the I/O allow it.    this bug was reported for `multiply`, but we need an audit of the math library, because it potentially exists for other operations as well.

**Comment by bob-carpenter** [comment]
Replaced by more general issue #1689.
