### ISSUE TITLE
csr_extract_v for dense matrix was mis-named csr_extract_w

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/math#168]
Broken signature in the one part of the code without test coverage.  Shows up when running stan test-models/good tests.

**Comment by syclik** [comment]
looks like we'll need to fix this before releasing, correct?

**Comment by sakrejda** [comment]
Yeah, I think so, I don't think it gets used directly except that it messes up the compiled_models tests in the stan repo itself.  There's a [pull request](https://github.com/stan-dev/math/pull/169) for it.
