### ISSUE TITLE
Some check_consistent_sizes are in the wrong place

### ISSUE THREAD

**Issue by mcol** [stan-dev/math#1681]
## Description
There are a few cases in which we do a `check_greater` before a `check_consistent_sizes`. If the sizes of the arguments being tested is inconsistent, this may lead to an assertion from Eigen.

## Example
In `stan/math/prim/prob/uniform_lpdf.hpp`, we currently have:
https://github.com/stan-dev/math/blob/044cbcb1932116c8905e4e2232a2ccce6f400e6c/stan/math/prim/prob/uniform_lpdf.hpp#L53-L56

Executing this code:
```
Eigen::VectorXd v(2);
Eigen::VectorXd w(4);
v << 1, 2;
w << 2, 3, 4, 5;
stan::math::uniform_lpdf(4, v, w);
```
produces
```
uniform_test: lib/eigen_3.3.3/Eigen/src/Core/DenseCoeffsBase.h:162:
Eigen::DenseCoeffsBase<type-parameter-0-0, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0>::operator[](Eigen::Index) const [Derived = Eigen::Matrix<double, -1, 1, 0, -1, 1>, Level = 0]: 
Assertion `index >= 0 && index < size()' failed.
Aborted (core dumped)
```

## Expected Output
By switching the two checks, we get a meaningful error message:
```
unknown file: Failure
C++ exception with description "uniform_lpdf: Lower bound parameter has dimension = 2, expecting dimension = 4;
a function was called with arguments of different scalar, array, vector, or matrix types, and they were not consistently sized; 
all arguments must be scalars or multidimensional values of the same shape." thrown in the test body.
```

#### Current Version:
v3.1.0

**Comment by bob-carpenter** [comment]
Nice catch.  We definitely don't want Eigen assertions or segfaults popping up. 

Don't we turn off the Eigen assertions when running?  (That doesn't mean this doesn't need to be fixed---it just means we might get segfault errors instead of assert errors.)
