### ISSUE TITLE
signum function

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1686]
We need it.

```
signum(x) = 1 if x > 0
signum(x) = 0 if x = 0
signum(x) = -1 if x < 0
```
- [ ] include in Stan math
- [ ] include in language

**Comment by mcol** [comment]
We already have a `sign` function that works as described for scalar values (and was actually implemented before this issue was filed) but is not exposed. Is that enough or should that be extended in some ways before exposing it?

**Comment by bob-carpenter** [comment]
I think the general issue is whether we want to introduce functions of parameters like this one that aren't continuously differentiable.  This one should be OK, because it's trivial to implement directly in Stan as

```
real signum(real x) { x > 0 ? 1 : x < 0 ? -1 : 0; }
```

**Comment by bob-carpenter** [comment]
> We already have a sign function that works as described for scalar values 

> Is that enough?

Yes, I'm closing.
