### ISSUE TITLE
remove size zero checks in `check_multiplicable`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/math#1689]
## Description

Currently `check_multiplicable(A, B)` checks that both `A` and `B` are non-empty.  This needs to be changed so that either or both can be empty.  Fixing `check_multiplicable` will cause other functions to break rather than throw exceptions for size zero inputs when Eigen hits an assert error.   Each function that uses `check_multiplicable` needs to be checked as to whether it also requires one or both of `A` and `B` to be empty.  

The `multiply` function itself was updated to remove the `check_multiplicable` tests.  These should be returned after `check_multiplicable` is fixed.

A new function `check_nonempty()` should be added to deal with checking for emptiness or size checks can be done on the number of rows or columns. 

 Documentation should be updated in both the C++ and the Stan function reference to reflect the changed boundary conditions.

More generally, all of Stan's matrix functions should be audited for boundary behavior.  Nothing should be able to get through to an Eigen assert.  The entire library does not need to be audited for this issue.

This is a generalization of issue  #1669.

#### Examples

[`matrix_exp_multiply`](https://github.com/stan-dev/math/blob/100c9850a0e4da99ebb9a497ce5902c7340de0a3/stan/math/prim/fun/matrix_exp_multiply.hpp#L20-L27) explicitly checks whether matrix B is 0x0, then calls `check_multiplicable`.

`A * B` currently requires `A` and `B` to be non-empty, but this expression is well-defined for empty matrices.  For example, if `A` is 5 x 0 and `B` is 0 x 4, then `A * B` is 5 x 4 (and contains all zero entries, as that's the boundary case for a summation, which is how entries are defined).

`A / B = A * inverse(B)` and `B \ A = inverse(B) * A` should be able to handle empty matrices in either position, because the inverse of a 0 x 0 matrix is just a 0 x 0 matrix (it satisifes the relevant identity laws).

#### Current Version:
v3.1.0

**Comment by dpsimpson** [comment]
If this is something that isn't particularly urgent, I can do it in my spare time over the next week or two.

**Comment by bob-carpenter** [comment]
We have a quarterly release schedule, so there's a couple months and change to get this in before the next release :-)  I was just saying we need someone like Dan Simpson or Ben Goodrich to figure out the boundary conditions of all these matrix ops.

**Comment by dpsimpson** [comment]
Tbh I’ve been looking for some busywork so this is perfect for me.

**Comment by mcol** [comment]
Some notes regarding the issue description:
- we already have a `check_nonempty` function
- your comment on the inverse contradicts what you suggested in #1432, so we currently throw when computing inverses of empty matrices (#1464): if you want to allow that, we will have to return an empty matrix ourselves, as Eigen chokes on that.

I have started on this, and it doesn't seem too bad. The only weird ones at this point seem to be `mdivide_left_tri` and `mdivide_right_tri`, but I need to get back and double-check. I'm working to expand tests to capture the corner cases, but I'm happy if @dpsimpson wants to take over, I could post my work in progress somewhere.

**Comment by bob-carpenter** [comment]
Thanks for pointing that out.  I updated the old comment to indicate that 0 x 0 matrices should have themselves as inverse (because they satisfy identity laws) and should have 1 as their determinant, because they're diagonal and the determinant is the product of the diagonal entries, and an empty product has value 1 (same way empty sum has value 0---you go with the underlying identity as base case).

We should check with someone better than me at linear algebra in case there are conventions that say this should be otherwise.  I'm worried that Eigen doesn't support 0 x 0 inverses.

**Comment by bob-carpenter** [comment]
I figured I'd just look up [the answer on math.stackexchane](https://math.stackexchange.com/questions/1913141/is-the-0x0-matrix-zero-times-zero-matrix-a-well-defined-concept)

It agrees with my reasoning.  Even so, I'd feel better with signoff from @dpsimpson or @avehtari.

**Comment by dpsimpson** [comment]
I think I might be a bit backwards here because in my mind a 1x1 matrix is
a scalar, a nx1 matrix should behave like a vector, and a 1xn matrix should
behave like a row_vector.

That’s the behaviour consistent with matlab (and I believe numpy). What is
the logic behind also allowing a zero here?

**Comment by mcol** [comment]
Matlab returns an empty matrix (https://nhigham.com/2016/03/15/empty-matrices-in-matlab/).

**Comment by bob-carpenter** [comment]
The MATLAB boundary conditions for empty matrices do what I expect.
Glad my intuition matches Nick Higham's! 


> I think I might be a bit backwards here because in my mind a 1x1 matrix is
> a scalar, a nx1 matrix should behave like a vector, and a 1xn matrix should
> behave like a row_vector.

That's not how typing works in Stan.  We cast down to the lowest possible 
type at the implementation level.  A 1 x 1 matrix is a different type than
real, so you can't assign either to the other in Stan.

**Comment by dpsimpson** [comment]
That’s ok. I understand the issue now. I shall get into the code and start
working out what to do!

**Comment by avehtari** [comment]
I agree with that Nick Higham post (I'm used to zero dimensions in Matlab). The papers de Boor (1990) and Nett and Haddad (1993) mentioned by Higham are good for additional details and cases. 

(R also does most what are expected, e.g. det and norm work, but solve(matrix(nrow=0,ncol=0)) gives an error.)
