### ISSUE TITLE
Avoid check for positive definiteness in mdivide_left_spd

### ISSUE THREAD

**Issue by mcol** [stan-dev/math#1693]
## Description
Currently we always check for positive definiteness of the matrix argument when `mdivide_left_spd` is called. These happen twice for `mdivide_right_spd`, as it checks it then delegates to `mdivide_left_spd` which checks it again.

Discussion in #1688 led us to consider whether this check could be skipped, as it computes a Cholesky factorization, which can be expensive. The Eigen documentation is not clear as to what happens if their `.llt()` method is called on a matrix that's not positive definite. In my tests, it seems to silently return the original matrix, so all subsequent computations will be wrong if we don't throw.

A thread on StackOverflow (https://stackoverflow.com/questions/35227131/eigen-check-if-matrix-is-positive-semi-definite) mentions that one could check `llt.info() == Eigen::NumericalIssue` after the LLT factorization is performed and throw if that's the case. So implementing this should allow us to keep the current expected behaviour of throwing if the matrix is not positive definite and also get rid of the expensive check.

## Expected Output
The functions should still be throwing if the matrix argument is not positive definite, but this will happen after the LLT computation rather than on entry to the function. This should also improve performance of these functions as there will be fewer wasted computations.

#### Current Version:
v3.1.0

**Comment by mcol** [comment]
Note that `check_pos_definite` does the following before computing the Cholesky factors:
- `check_symmetric`
- `check_positive` on the matrix size
- `check_not_nan`
so those checks should not be lost.

**Comment by bob-carpenter** [comment]
This is an important performance issue.  Thanks for figuring this out.  And yes, we want those other checks to fire so we don't get assert errors in the matrix operations.

Have you checked other uses of `check_pos_definite` to see if they can also be eliminated?  I'm guessing pretty much all of them other than the one on transformed data or parameters can be eliminated.

**Comment by mcol** [comment]
Also `cholesky_decompose`, `multi_normal_prec_rng` , `multi_normal_rng`, `multi_student_t_rng` could use the same approach.

I'm thinking of creating a `check_eigen_llt` function defined as follows:
```
template <typename T>
inline void check_eigen_llt(
    const char* function, const char* name,
    const Eigen::LLT<Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>>& llt) {
  if (llt.info() == Eigen::Success) {
    return;
  }
  throw_domain_error(function, name, "is not positive definite.", "");
}
```
@bob-carpenter would such name do?

**Comment by bob-carpenter** [comment]
Sounds good.  

I would probably have written the function the other way, with the condition `(llt.info() != Eigen.Success)` because it's more typical to deal with exceptional conditions first, then the main line of execution.  That feels a bit odd here as the main line of execution is to just return without doing anything, so I'll leave this up to you.

That `throw_domain_error` thing should use parameter packs and take an arbitrary number of arguments so it doesn't need dummy args!  (Different issue, obviously.)

**Comment by rok-cesnovar** [comment]
Isnt this the same as what we already have here https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_pos_definite.hpp#L56

**Comment by mcol** [comment]
@rok-cesnovar I saw that, but I originally dismissed as that's for LDLT, while here we have LLT. Now I think I can add an overload for LLT and enjoy the clearer function name. Thanks for commenting!

Whether we should use LDLT everywhere is another matter, I'm not sure exactly why here we do LLT, but according to https://stackoverflow.com/questions/23309596/eigen-ldlt-slower-than-llt, LLT should be faster.

**Comment by mcol** [comment]
I misread, there's already an LLT overload! It's even easier then! :)

**Comment by mcol** [comment]
Actually `cholesky_decompose`, `multi_normal_prec_rng`, `multi_normal_rng`, and `multi_student_t_rng` are all fine, they only don't check for NaNs.
