### ISSUE TITLE
Use RAII for nested autodiff

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/math#1703]
## Description
Use the RAII idiom to make sure that nested autodiff is always properly deinitialized. More thorough discussion at 
https://discourse.mc-stan.org/t/proposal-raii-for-nested-autodiff/12861

## Example

A code using autodiff would then look like:
```
{
    local_nested_autodiff nested();
    //Do stuff
    nested.set_zero_all_adjoints();
    //Do more stuff
}
```

With the destructor of `local_nested_autodiff` stopping the nested autodiff.

#### Current Version:
v3.1.0

**Comment by wds15** [comment]
Do we really want to make `set_zero_all_adjoints` a member of this local nested thing?

I am not opposed to it... this is just a radical change.

Or asked differently: Are u also suggesting to **remove** the global `recover_memory_nested()` and all the other *global* nested functions?

Going in the direction of representing the entire AD tape as an instance is a good thing from my perspective. It's just that we need to be careful with this given that right now things are thread local. So passing any instance around between threads is a bad idea right now...

**Comment by martinmodrak** [comment]
> Are u also suggesting to remove the global recover_memory_nested() and all the other global nested functions?

No, that would probably constitute a breaking API change. I would however suggest the RAII as "recommended". Also right now my implementation of `local_nested_autodiff` just calls the underlying functions.

> Do we really want to make set_zero_all_adjoints a member of this local nested thing?

Not 100% sure about this, it just felt natural to allow this use so that calling global functions and using the RAII class does not mix. To me this is a minor aesthetic choice on which I do not insist in any way.
