### ISSUE TITLE
Cleanup duplicate prim functions is_inf/isinf, is_nan/isnan

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1708]
## Description

We currently have some duplicate functions in prim/fun: 

- is_nan and isnan
- is_inf and isinf

The former are the ones supported in the language so those should stay. isnan/isinf should be removed.

We can then also rename: 
- isnormal to is_normal
- isfinite to is_finite

#### Current Version:
v3.1.0

**Comment by rok-cesnovar** [comment]
Counterpoint to this is that the names without underscores shadow the c++ standard which has
- std::isfinite
- std::isnan
- std::isinf
- etc.

But underscored names are used in the Stan language and a change there means we need to  deprecate them. I do prefer is_nan to isnan for what is worth.

**Comment by bob-carpenter** [comment]
The counterpoint's right.   I added `is_nan` before we were following C++11---had I known C++11 was going to use `isnan` I'd have gone with that.  As is, I don't think we need to change our language, but we do need to support as many C++ standard library functions as we can.   So I'm going to close this.

**Comment by mcol** [comment]
This answer is not particularly satisfying... As a developer, what should we use? If we want to follow the C++ standard library, should we encourage the use of `isinf/isnan` in the math library, and deprecate the underscore forms? I don't have a preference on which form to use, but having and using one is way better than two.

Also, we could remove `is_inf/is_nan` from the library but still keep them in the language, by changing the stanc3 bindings to point to `isinf/isnan`, right?

Also, is there a reason why we have `prim/fun/isinf.hpp` but `rev/core/std_isinf.hpp` (same for `std_isnan`)?

**Comment by bob-carpenter** [comment]
We can encourage people to use the isnan and isinf forms to match the standard library.  We can deprecate is_inf and is_nan in C++.  I wouldn't remove them because that makes the connection from stanc3 clunkier and harder to maintain.

**Comment by bob-carpenter** [comment]
An alternative is to add isinf and isnan to the language, then deprecate is_inf and is_nan.  Then eventually we can arrive at a clean solution that only supports isinf and isnan.  I'm still not sure it's worth breaking people's old programs for this level of consistency with the C++ standard.

**Comment by rok-cesnovar** [comment]
I agree that its not worth to depracate is_inf and is_nan. Stan language doesnt have to follow the c++ standard, but we should try to in Stan Math. 

Can we merge the files (put is_inf to isinf.hpp) and put a doxygen comment to notify Stan Math devs to use isinf/isnan in Math?

**Comment by mcol** [comment]
That would be good. When I mentioned "deprecate the underscore forms" I had in mind within the math library, not the Stan language (I could have been clearer!).

**Comment by bob-carpenter** [comment]
@rok-cesnovar Can you rewrite this issue or close and open a new one?  I'm OK with merging the two implementations into one file, though it violates our principle of putting functions in files named after the function.

**Comment by rok-cesnovar** [comment]
Closing for now.
