### ISSUE TITLE
double version of trace_gen_quad_form is never used

### ISSUE THREAD

**Issue by mcol** [stan-dev/math#1709]
## Description

There's an unresolved typename declared for `trace_gen_quad_form`, which therefore is never used even when all inputs are double. Here's the definition:
```
template <int RD, int CD, int RA, int CA, typename TB, int RB, int CB>
inline double trace_gen_quad_form(const Eigen::Matrix<double, RD, CD> &D,
                                  const Eigen::Matrix<double, RA, CA> &A,
                                  const Eigen::Matrix<double, RB, CB> &B)
```
Removing `typename TB` allows that double specialization to be used.

#### Current Version:
v3.1.0

**Comment by rok-cesnovar** [comment]
This one will be squashed by #1628 right?

**Comment by mcol** [comment]
Good to know, I hadn't seen that! :)
