### ISSUE TITLE
remove redundant z input to CSR sparse matrix ops

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#171]
Currently, the CSR code is using w, v, u, z input and I want to change it so that it only uses w, v, and u.  This will bring it in line with the standard CSR implementation:

https://en.wikipedia.org/wiki/Sparse_matrix

* [ ] add `u_to_z()` function to compute `z` based on `u`
    * [ ] unit tests
    * [ ] update doxygen doc

* [ ] remove `z`argument from `csr_to_dense_matrix()`
    * [ ] update tests to match
    * [ ] update doxygen doc

* [ ] remove `z` argument from `csr_matrix_times_vector()`
    * [ ] update tests to match
    * [ ] update doxygen doc

* [ ] remove `csr_extract_z()` function
    * [ ] update tests to match

Also, I want to rename these functions:

* [ ] `csr_extract_w` to `csr_values`
    * [ ] rename in tests
    * [ ] update doxygen doc

* [ ] `csr_extract_v` to `csr_col_indexes`
    * [ ] rename in tests
    * [ ] update doxygen doc

* [ ] `csr_extract_u` to `csr_row_starts`
    * [ ] rename in tests
    * [ ] update doxygen doc

**Comment by bob-carpenter** [comment]
Krzyzstzof pointed out that the redundancy was intention for reasons having to do with "garbage" values in Eigen that I don't understand.  So I'm going to close this and open a new issue to document the behavior of "garbage" values in the code and tests.

**Comment by sakrejda** [comment]
I back-pedalled on this, you should re-open. Let me know if you want me to get some pieces of it done.
