### ISSUE TITLE
Fix Jenkins to only run branch tests on develop, not any branch with develop in name

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1713]
## Description

It seems that Jenkins starts tests on any branch with develop in its name. For #1712 I named the branch bugfix/failing_develop and that has now started the PR tests as well as push to branch tests. The latter are not needed and should only be used for the actual develop & master branches.

Links to tests
https://jenkins.mc-stan.org/job/Math%20Pipeline/job/PR-1707/10/
https://jenkins.mc-stan.org/job/Math%20Pipeline/job/bugfix%252Ffailing_develop/1/

@serban-nicusor-toptal feel free to stop the latter tests to not waste resources on the branch tests.

#### Current Version:
v3.1.0

**Comment by serban-nicusor-toptal** [comment]
Hey Rok, I'm currently out of the country. Will be back on Monday and take care of all the issues. Thanks!

**Comment by rok-cesnovar** [comment]
Yeah, no worries, whenever you have time. Enjoy the time off. Just saw this issue and wrote it down before I forget :)

**Comment by serban-nicusor-toptal** [comment]
This has been fixed.

The issue was on Jenkins side and was fixed through UI.
When matching for branches the regex was `.*(PR-\d+|develop|master)` which would match `anything_develop` so it has been changed to `^(PR-\d+|develop|master)$`
