### ISSUE TITLE
rev version of mdivide_left twice as slow

### ISSUE THREAD

**Issue by mcol** [stan-dev/math#1719]
## Description
Running the mix test for `mdivide_left` takes almost double the time than running the same for `mdivide_right` (the two test are effectively equivalent). What's funny is that `mdivide_right` delegates to `mdivide_left`, so one would potentially expect it to perform worse.

The main difference between the two is that there is a rev implementation for `mdivide_left`. If I define it out, then the performance of the two functions is comparable. So perhaps something is buggy in the rev version?

Also `mdivide_left_tri_low` is twice as slow than its `right` counterpart. 

## Example
```
## 41653ms
./runTests.py test/unit/math/mix/fun/mdivide_right_test.cpp 

## 75279ms: stock develop
## 38231ms: rev version ifdef'd out
./runTests.py test/unit/math/mix/fun/mdivide_left_test.cpp 
```

## Expected Output
Similar run times for the two functions.

#### Current Version:
v3.1.0

**Comment by bob-carpenter** [comment]
The prim versions are both implemented from scratch as are the forward versions.

Only mdivide_left has a reverse specialization and that seems to be using a different algorithm (colPivHouseholderQr instead of lu).   

In addition to time in these small tests, we should check (a) memory usage, and (b) reverse-mode autodiff time for larger matrices.  The easiest way to do (b) is to do the division, then sum the result and take the gradient from the sum.   If the prim implementation still dominates for larger matrices and in terms of memory, we should just get rid of the reverse mode (and maybe the forward mode if those also slow things down).

**Comment by mcol** [comment]
Using `lu()` instead of `colPivHouseholderQr()` brings back the speed I was expecting, but tolerances need to be increased quite a lot from defaults, even for such a tiny testcase:
```
auto f = [](const auto& x, const auto& y) {
  return stan::math::mdivide_left(x, y);
};

stan::test::ad_tolerances tols;
tols.gradient_grad_ = stan::test::relative_tolerance(0.1, 1.5);
tols.hessian_hessian_ = stan::test::relative_tolerance(0.9, 2.0);
tols.grad_hessian_hessian_ = stan::test::relative_tolerance(0.9, 2.0);
tols.grad_hessian_grad_hessian_ = stan::test::relative_tolerance(0.9, 3.6);

Eigen::MatrixXd a(2, 2);
a << 2, 3, 3, 7;
stan::test::expect_ad(tols, f, a, a);
```
This suggests to me that the prim implementation is more accurate than the rev one using lu (and faster than the rev one using QR), but I can't understand exactly why. I don't know how to measure memory usage.

**Comment by bob-carpenter** [comment]
> I don't know how to measure memory usage.

You either need a profiler or you need to call the instrumented version.  There's a `bytes_allocated()` method for `stack_alloc`, but it's pretty crude.

**Comment by bob-carpenter** [comment]
> lu() instead of colPivHouseholderQr() brings back the speed I was expecting, but tolerances need to be increased quite a lot from defaults,

> This suggests to me that the prim implementation is more accurate than the rev one using lu

The prim implementation is using `lu()`, so isn't that ess accurate?  We should probably go with whichever of these is more accurate, not the one that's fastest if there's a big difference.

Thanks for looking into this.  It's a really important function for us.

**Comment by rok-cesnovar** [comment]
On current develop these both tests seem to run for the same amount of time (they are effectively the same test as well) so this might have been resolved when moving to the new reverse_pass_callback scheme (or something else in the 6 months that passed). Will close, but feel free to reopen.

**Comment by mcol** [comment]
I've run this again on current develop and I get 36440ms seconds for right and 67930ms for left on Linux, so it doesn't seem to be fixed.

**Comment by rok-cesnovar** [comment]
Thanks!

Just to make sure, you mean
`./runTests.py test/unit/math/mix/fun/mdivide_right_test.cpp` 
vs
`./runTests.py test/unit/math/mix/fun/mdivide_left_test.cpp `

and an empty make/local?

**Comment by rok-cesnovar** [comment]
Ubuntu 20.04, no make/local, g++ 9.3

```
python3 runTests.py test/unit/math/mix/fun/mdivide_left_test.cpp 
------------------------------------------------------------
make -j1 test/unit/math/mix/fun/mdivide_left_test
make: 'test/unit/math/mix/fun/mdivide_left_test' is up to date.
------------------------------------------------------------
test/unit/math/mix/fun/mdivide_left_test --gtest_output="xml:test/unit/math/mix/fun/mdivide_left_test.xml"
Running main() from lib/benchmark_1.5.1/googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MathMixMatFun
[ RUN      ] MathMixMatFun.mdivideLeft
[       OK ] MathMixMatFun.mdivideLeft (1024 ms)
[----------] 1 test from MathMixMatFun (1024 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1025 ms total)
[  PASSED  ] 1 test.
```

```
python3 runTests.py test/unit/math/mix/fun/mdivide_right_test.cpp 
------------------------------------------------------------
make -j1 test/unit/math/mix/fun/mdivide_right_test
make: 'test/unit/math/mix/fun/mdivide_right_test' is up to date.
------------------------------------------------------------
test/unit/math/mix/fun/mdivide_right_test --gtest_output="xml:test/unit/math/mix/fun/mdivide_right_test.xml"
Running main() from lib/benchmark_1.5.1/googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from MathMixMatFun
[ RUN      ] MathMixMatFun.mdivideRight
[       OK ] MathMixMatFun.mdivideRight (924 ms)
[----------] 1 test from MathMixMatFun (924 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (924 ms total)
[  PASSED  ] 1 test.
```

**Comment by rok-cesnovar** [comment]
The first question would be how am I seeing 1s and you are seeing 36 and 67 seconds. My machine has a 5+ years old i7

**Comment by mcol** [comment]
I had -O0 in make/local. Without that I get 2.7 secs for both tests (this happens on a 10+ years old server). I'm glad to see that this is not an issue anymore (and perhaps it was not one in the first place).
