### ISSUE TITLE
doc and tests for "garbage" values in sparse matrices

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#172]
Krzysztof said that the reason there's a redundant argument in the sparse matrix representations (`z`) is because of how Eigen handles so-called "garbage" values.

* [ ] document how "garbage" values are used

* [ ] add tests that match the doc to make sure they work as intended

If these are already there, could you just point out to me where?  I couldn't find them.

**Comment by syclik** [comment]
I believe pull request #174 fixed this. If it didn't, please reopen.
