### ISSUE TITLE
doxygen math broken

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1721]
## Description

For example,

https://mc-stan.org/math/d4/d84/namespacestan_1_1math.html#ac35268da23d7a78c8877b4cf38f30f19

has mathematical documentation that isn't getting rendered into MathJax.

We should audit the entire library to make sure the math is being rendered properly.  But any progress fixing anything is an accepable PR.

#### Current Version:
v3.1.0

**Comment by mcol** [comment]
I've loaded that page in Firefox and opened the web console. This is what's reported:
```
Blocked loading mixed active content "http://cdn.mathjax.org/mathjax/latest/MathJax.js"
namespacestan_1_1math.html
Blocked loading mixed active content "http://cdn.mathjax.org/mathjax/latest/MathJax.js"
namespacestan_1_1math.html
Loading failed for the <script> with source “http://cdn.mathjax.org/mathjax/latest/MathJax.js”.
namespacestan_1_1math.html:31:1
```
According to [this developer.mozilla.org page](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content) it may be enough to change the `http` links to `https`.

I don't know if this is the whole story, but it's worth a try. This path is set from `doxygen/doyxgen.cfg`, but opening a PR for that will cause hours of useless tests...
