### ISSUE TITLE
Add multinomial_logit

### ISSUE THREAD

**Issue by demodw** [stan-dev/math#1742]
#### Summary:

Add a function that matches the existing `bernoulli_logit` and  `categorical_logit`.
#### Description:

This would add a convenience function usable in multi-outcome logistic regression problems. For models with larger data sets it would add a significant speedup, given that the current `multinomial` function has to be called every single iteration, since it currently only accepts a single vector. 
#### Current behavior

Assume there are N data points and K different outcomes, y is a NxK matrix of integers, beta is a K vector with some combination of covariates and predictors for each outcome,

```
for (n in 1:N) {
    ...
    y[n] ~ multinomial(softmax(beta))
}
```
#### Wanted behavior

`y ~ multinomial_logit(beta)`

In this case beta would be a NxK matrix with some combination of covariates and predictors for each outcome.
#### Additional Information:

I could not find any open issues for this missing feature. Also, I am not sure if this should be added as an issue to the stan-dev/math repository.
#### Current Version:

v2.9.0

**Comment by rok-cesnovar** [comment]
Helping @mcol clean up stan issues. Feel free to close if any of this is irrelevant now.

**Comment by bob-carpenter** [comment]
This should be included in Stan.  So please don't close.
