### ISSUE TITLE
Make ODE integrator fail if precision is not reachable

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#179]
The current ODE integrator uses the dense_output scheme of odeint. This schemes may run into an infinite loop if the requested parameters to solve an ODE for make the ODE system too stiff, i.e. the integrator will end up in a never ending loop.

Now, odeint also offers the controlled_stepper interface which does trigger a thrown execption whenever too many attempts are needed in the seek for a small enough step-size. This is behavior makes the integrator robust against extreme parameter values tried out mostly in early phases of sampling.

This should solve issue #52 to some degree, i.e. the integrator is still a RK45 (non-stiff), but will be robust against extreme parameter draws and gracefully fail intstead of locking up Stan.

**Comment by bob-carpenter** [comment]
This is a good idea.  Daniel and I never figured out how to get the lower-level interfaces working.  The code's modular enough that it should be doable.  I'm assigning to Daniel for 3.0, but it'd be nice to get this in sooner rather than later if the new integrators aren't coming on line soon.

**Comment by wds15** [comment]
Yes, it would be great to have this possibly in a 2.8.1 or 2.9.0 whatever your plans are. It makes a huge difference for users, really. No more freezing of Stan due to the ODE integrator locking up. This patch is critical for anyone wanting to do ODE integration in Stan. The need for a new integrator is much relaxed now that the RK45 is robust. I am curious to try this with Michaels just filed coupled ode system patch.

I just filed a pull request, hope this is good to go in.

**Comment by bob-carpenter** [comment]
We'll review it and either fix it or get it in ASAP.

We probably won't release a 2.9.0 for another couple months,
at which point we should have a bunch new features.

Of course, this fix is probably going to be incompatible
with Michael's fix, since it's all in the same code.

Should we just go with this one?  Or what?  Michael's also asked
me to look at his patch.

- Bob

**Comment by wds15** [comment]
Hi!

This patch is compatible with michael one at least i did not get any merge conflicts and to my understanding michael edited the coupled system while i changed the integrate ode function. Have a look at the odeint doc for the difference in a dense output and a controlled error stepper. To my understanding the dense output uses interpolation and gives you back an object which you can query at any time point while the controlled error stepper only controls the precision and nothing more. As we need the solution at fixed time points there not much of a difference, i think.

And yes, getting this thing earlier rather than later will make all stan ode users very happy. For me  this patch is making the integrator simply robust which is a critical property - viewed differently stan has been affected by a bug in the dense output scheme all along, which is now being circumvented. But please take a careful review of it, this must be correct by all means.

**Comment by bob-carpenter** [comment]
Great that there's no conflict.  Of course, we have to figure
out what's wrong with Michael's merge.  I know we need this patch.
We've known that all along, but never figured out how to do it.
In any case, we probably won't do another official release for a
couple of months.

- Bob

**Comment by wds15** [comment]
The earlier users get this the less frustrated ode users you get on stan-users.

I did find this out by chance when browsing for reasons i forgot through the odeint controlled stepper sources where i saw a maxtries variable - this caught my attention and i am glad it works.

Not sure whats wrong with michaels patch, but if we can really reduce ad by a factor of n, then that's great. Right now things are a lot slower with the new coupled system, for unkown reasons.

**Comment by wds15** [comment]
See here:

https://github.com/headmyshoulder/odeint-v2/issues/173

in short: odeint does not have a way to throw an exception when there is too much work. It only has a concept to throw an exception if it cannot find a step-size within 1000 subsequent tries. Hence, to get close to the desired behavior of a robust integrator which throws an exception when the system gets stiff is to adaptively integrate between time-points. The down-side is that now the dt step size is re-adjusted many times, on the up-side Stan does not hang any more on many problems.

... with this patch the coupled_ode_observer.hpp could be removed...

**Comment by wds15** [comment]
The current active pull request for this should be closed (and the branch can be removed). The respective branch with a -2 as postfix implements what should be done (as discussed with the author of odeint). It currently only lacks the feature to set the maximal number of steps allowed depending on the time-span being integrated and a fixed density of allowed number of steps per dt (as suggested on the mailing-list).

Sorry for those iterations, but this is the result of a long discussion with the odeint author who is by now expanding odeint accordingly.

**Comment by wds15** [comment]
With boost 1.60 this fix is now trivial to do as the max_step_checker concept was introduced in the new odeint library. I am initiating a new pull request for this.
