### ISSUE TITLE
upgrade scalar metaprograms to recognize complex types

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1792]
## Description

Complex numbers are to be considered as scalars in programs like `is_stan_scalar`.  

The biggest consequence is that the underlying scalar type of a matrix might be a complex type rather than a real type, so that we have to go a level deeper to pull out the underlying real types.  

I'm introducing a bunch of metaprograms as part of the complex functions pull request which can be used as replacements for other return type calculations.

It may help to work from the ordering of types by assignability, which is determined by these proper assignments for all real types `T`.

```
double = int
complex<T> = double
complex<T> = T
var = double
fvar<T> = double
```

The matrix types should be covariant, so that if `U` is assignable to `V`, then `matrix<U, R, C>` should be assignable to `matrix<V, R, C>`.  Same for `std::vector`. But C++ itself isn't covariant and we don't allow matrices of `int`.

#### Current Version:
v3.1.0

**Comment by WardBrian** [comment]
I believe this can be closed, `is_stan_scalar` was updated in #1917 and the rest of the metaprograms have been updated as we have added more complex support
