### ISSUE TITLE
Generalise Eigen inputs for adj_jac_apply

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#1808]
## Description
```adj_jac_apply``` currently only works for ```Eigen::Matrix<T, R, C>```, by generalising it to work with any Eigen inputs, the framework can then be used with ```Eigen::Array``` types or other Eigen expressions (e.g. ```softmax(m.diagonal())```).

#### Current Version:
v3.1.0

**Comment by rok-cesnovar** [comment]
adj_jac_apply was removed so we can close this.
