### ISSUE TITLE
"reduce_sum" parallel facility

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#1815]
## Description
For the purpose of running reverse mode autodiff using parallelism the `reduce_sum` function has been designed, see https://github.com/stan-dev/design-docs/blob/master/designs/0017-reduce_sum.md

This new function will allow to evaluate mapping a function to elements of an array and the results are then reduced through summing the results. Specifying this with `reduce_sum` will allow to run this operation in parallel.

## Example

Please refer to the design document.

## Expected Output

Results should be the same, we just get them faster whenever we can use multiple threads.

#### Current Version:
v3.1.0

**Comment by rok-cesnovar** [comment]
Reopening because we need to rearrange the arguments. Reasons were outlined in this discussion https://discourse.mc-stan.org/t/can-we-have-unnormalised-densities-in-user-functions/14333/17
