### ISSUE TITLE
Unify clang-format versions on Jenkins workers if possible

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1822]
## Description
It seems that some Jenkins workers have clang-format 5.0.0 while some have version 6.0.0

Example can be seen in https://github.com/stan-dev/math/pull/1821 if you look at the commit messages:

`[Jenkins] auto-formatting by clang-format version 6.0.0 (tags/google/…`

and

`[Jenkins] auto-formatting by clang-format version 5.0.0-3~16.04.1 (ta…`

These versions seem to differ in some details. One of the most annoying ones is that
6.0.0 is fine with

`  inline load_<T&> deep_copy() const& { return load_<T&>(a_); }`

while 5.0.0 insists on a space between const and &.

@serban-nicusor-toptal Can we unify this to a common version on all workers that run the 
`Clang-format` stage.

#### Current Version:
v3.1.0

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar 
I'm on it, will make sure everything has `6.0.0`

**Comment by rok-cesnovar** [comment]
Thanks!

**Comment by serban-nicusor-toptal** [comment]
`clang-format` is now version `6.0.0` on ec2 instances.
Please let me know if any issue arise, thanks.

**Comment by rok-cesnovar** [comment]
That was lightning fast. Thanks!
