### ISSUE TITLE
Update to Eigen 3.3.7

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#1831]
## Description

It looks like we are still on Eigen 3.3.3 while RcppEigen has moved up to 3.3.7. The changelog is [here](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.7), mostly small bugfixes

Is there anything upstream that would goof or is it cool to update this?

#### Current Version:
v3.1.0

**Comment by wds15** [comment]
We always try to match rcppeigen...good catch.
