### ISSUE TITLE
rng for discrete latent states in hmm

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/math#1846]
## Description
This feature complements the hmm lpdf, see issue #1648.

When fitting a hidden Markov model, we marginalize out the discrete latent states. The proposed functions allows us to (i) recover the discrete states in the generated quantities block, and (ii) calculate their marginal probabilities.

For **feature requests**:

Following closely the signature for the lpdf function, a call to the rng function looks as follows:
```
x = hmm_latent_rng(log_omegas, Gamma, rho, rng);
```
and returns an `std::vector<int>` of discrete states.

To compute the marginal probabilities -- that is, not accounting for correlation between the hidden states --, we use
```
eta = hmm_latent_marginal_probs(log_omega, Gamma, rho);
```

#### Current Version:
v3.1.0

**Comment by charlesm93** [comment]
Tagging @vianeylb, @betanalpha, and @bob-carpenter .

**Comment by bob-carpenter** [comment]
I can review this one, too.

**Comment by charlesm93** [comment]
My understanding, based on this [post on the Stan forum](https://discourse.mc-stan.org/t/advice-for-testing-probabilistic-code/9451), is that we use a hypothesis test (e.g. chi-squared, Kolmogorov, ...) to check whether the rng functions work.

Where are these tests located in the math repo? I looked for Bernoulli and couldn't find anything using an rng. Do we put the deterministic tests (testing for exceptions) under unit, and the hypothesis test under prob?

**Comment by bob-carpenter** [comment]
They're in:

`test/unit/math/prim/prob/bernoulli_test.cpp`

It's all a lot more complicated than when I last saw it.
