### ISSUE TITLE
Cleanup boost headers

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1850]
## Description

There are some files where include boost headers but they could be replaced safely with std ones.

This reduces compile time significantly enough (A cleanup of these cases in math/stan/cmdstan) that it makes this worthwile.

Examples:

stan/math/prim/fun/LDLT_factor.hpp with shared_ptr
stan/math/prim/fun/boost_policy.hpp includes error_handling that is not used.

#### Current Version:
v3.2.0

**Comment by SteveBronder** [comment]
Nice! Also looking in the stan library we do things like

```
#include <boost/type_traits/is_arithmetic.hpp>
```

I'll look at those

**Comment by rok-cesnovar** [comment]
Beat you too it :) https://github.com/stan-dev/stan/pull/2914
