### ISSUE TITLE
Add Google Benchmark as a library

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#1852]
## Description

At the Math library, we want to do more benchmarking. We should add Google Benchmark to the `lib/` folder.

#### Current Version:
v3.2.0

**Comment by syclik** [comment]
When adding this, please update: https://github.com/stan-dev/math/wiki/Updating-Libraries/

**Comment by syclik** [comment]
I have an open branch that has added the benchmark library. Running into a little problem getting the `GOOGLETEST_PATH` to be set up correctly. We might have to use the latest version to make this work (instead of the last tag).

**Comment by rok-cesnovar** [comment]
Cool! 

We really need to step up our game in terms of perf. benchmarking. The stan-level needs a tune up mostly in terms of models and input data sizes and we certainly could use performance benchmarking on the function level.

**Comment by SteveBronder** [comment]
Should we add another dependency here vs moving the [`perf-math`](https://github.com/seantalts/perf-math) repo to stan-dev? This should probs go through the checklist for adding dependencies to the math library. How would we utilize this? I could see it being nice for PRs where we have a separate `benchmarks` file with benchmark scripts associated with PRs

https://github.com/stan-dev/math/wiki/Checklist-for-adding-a-dependency-to-the-Math-library

**Comment by syclik** [comment]
Status: I ran into massive problems trying to include this (after spending a couple hours). Our Google Test is out of date enough where it doesn't work with the tagged version of Google Benchmark, so that needs to be upgraded first.

More below:

> We really need to step up our game in terms of perf. benchmarking.

@rok-cesnovar, definitely! If we want Math to get faster (and not slower), we need to be accurately measuring what happens. And actively. By including this into Math, we can start encouraging it.


> Should we add another dependency here vs moving the [`perf-math`](https://github.com/seantalts/perf-math) repo to stan-dev?

@SteveBronder, I think we should move this into Math for a few reasons:

1. Making it easier for Math devs to benchmark. The `perf-math` repo includes Google Benchmark because it wasn't included in Math. I realize this will cause multiple copies of the library if we continue with full clones, but we already have that problem with Eigen, Google Test, Boost, etc. (If we want to properly solve that problem, we can create a new repo--or two--for dependencies and include that as a submodule.)
2. We can start building out a benchmark in the Math library. We really could use this as we're considering changes to the autodiff stack. I think it makes sense that this happens inside the library itself.
3. This would make it easier to include benchmark tests from any of Stan ecosystem that relies on Math. They would have access to Google Benchmark.

That said, we still need something like perf-math. Having Google Benchmark inside Math doesn't really help with the use case of comparing directly across different implementations. Especially if they require completely different build instructions or rely on different libraries. And a lot of what's tested there is meant to show differences between two implementations, which isn't necessarily what we want to maintain as a benchmarking suite to show the speed of different parts of the Math library.

> https://github.com/stan-dev/math/wiki/Checklist-for-adding-a-dependency-to-the-Math-library

Thanks for bringing that up. I'll update the top-level comment when I get a chance.

**Comment by wds15** [comment]
Somehow I feel uncomfortable to include yet another library if that is not directly being used. Ok... shame on me... I did include Sundials & the TBB... my thought is just that the perf-math repo approach was a good one; at least for me.

Options:
- move/copy perf-math to the stan repo (which we should anyways, I think)
- have a make target which triggers download and install of the google benchmark lib (maybe this should be done in general?)
- reconsider the cmake-ified Stan-math - I really wonder what the status of that is
- Create a Dockerfile for this purpose? It would limit testing to Linux, but better than nothing. Cross-platform testing would still be needed, of course.

But if everyone is just fine to integrate that library permanently... so be it. Maybe in the cmdstan releases we prune this out, for example.

**Comment by syclik** [comment]
Pruning in a release is really easy using git archive. So... I don't think
that's going to be an issue.

What we want to do is to include it so it can be used. This is similar to
how we introduced Sundials, TBB, and CppLint. Now those are used all the
time. But the first step is to include before implementing a solution with
it.

There are so many opportunities for making Math faster. And we can't do it
without better guidance on how to do performance engineering. It's 946 kb
on disk... if having a copy of that makes it easier on the devs, we should
probably just include it. =)

**Comment by syclik** [comment]
But... we can't take action on this yet. This is blocked until we update
Google Test.
