### ISSUE TITLE
Calling nested gradient in reverse mode sweep can cause segfaults

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#1855]
## Description

Calling nested gradients in the reverse mode sweep can cause segfaults.

This happens when ```ChainableStack::instance_->var_stack_``` needs to reallocate itself.

You can make the bug happen with this code (put it in test somewhere):
```
#include <gtest/gtest.h>
#include <test/unit/math/rev/fun/util.hpp>
#include <stan/math/rev/core.hpp>
#include <stan/math/rev/fun/sin.hpp>

namespace stan {
namespace math {

class test_vari : public vari {
 public:
  explicit test_vari() : vari(0.0) {
  }

  virtual void chain() {
    stan::math::nested_rev_autodiff nested;

    // Add enough vars to make the the var_stack_ vector reallocate                                                                                                                                                
    int N_new_vars = ChainableStack::instance_->var_stack_.capacity() + 1;

    var total = 0.0;
    for (int i = 0; i < N_new_vars; ++i) {
      total += i;
    }

    total.grad();
  }
};

}
}

TEST(AgradRev, grad_in_reverse_mode) {
  using stan::math::var;

  var total = 0.0;
  for (int i = 0; i < 2; ++i) {
    total += i;
  }

  var test_var(new stan::math::test_vari());

  test_var.grad();
}
```

#### Current Version:
v3.2.0

**Comment by bob-carpenter** [comment]
What's the use case for nested autodiff within `chain()`?

**Comment by bbbales2** [comment]
It's the reason we didn't have adjoint ODEs two/three years ago :P. To do that you solve an ODE in the reverse pass and you need to be able to get Jacobians and stuff.

**Comment by bob-carpenter** [comment]
@bbbales2 Thanks for clarifying.  And I'm OK with the change now that I understand why it's there.  

Is there an efficiency reason we couldn't compute that ODE in the forward pass and save the results?

**Comment by wds15** [comment]
yes, we want to get adjoint ODE solving going. Apparently then we need the AD system during the reverse pass. The adjoint ODE methods is far more efficient when you have more states and/or more parameters when compared to the forward thing we do now which scales badly.

**Comment by betanalpha** [comment]
> 
> Is there an efficiency reason we couldn't compute that ODE in the forward pass and save the results?

See Section 1 of https://arxiv.org/abs/2002.00326 <https://arxiv.org/abs/2002.00326>, in particular the last equation.

The efficiency of the adjoint method requires that we need only integrate the one-dimensional 
system in the second term which requires knowing the adjoint delta.  If one wanted to precompute 
anything without knowing delta then one would have to compute \int dt df/dpsi which are exactly 
the costly sensitivities.
