### ISSUE TITLE
fix includes for header test (failing on g++ 4.4)

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#186]
Ashley Ford reports that test-headers fails on g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16):

```
g++ -I . -isystem lib/eigen_3.2.4 -isystem lib/boost_1.58.0 -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -pipe   -c -O0 -include stan/math/prim/arr/meta/container_view.hpp -o /dev/null test/dummy.cpp
In file included from ./stan/math/prim/arr/meta/container_view.hpp:4,
                 from <command-line>:0:
./stan/math/prim/scal/meta/container_view.hpp: In member function ‘typename stan::scalar_type<T>::type stan::math::container_view<stan::math::dummy, T2>::operator[](int) const’:
./stan/math/prim/scal/meta/container_view.hpp:82: error: ‘out_of_range’ is not a member of ‘std’
make: *** [stan/math/prim/arr/meta/container_view.hpp-test] Error 1
```

* [ ] fix this by including `<stdexcept>`
* [ ] figure out how the header test can be passing elsewhere without including `<stdexcept>` 

I added a Stan issue to thank Ashley:  https://github.com/stan-dev/stan/issues/1617#issuecomment-144526306

**Comment by bgoodri** [comment]
`make test-headers` is passing for me at the moment with g++-4.4 even though the includes for container_view.hpp do not `#include <stdexcept>`. But it does not seem to throw any exceptions (any more?). So perhaps this issue can be closed.
