### ISSUE TITLE
Add additional stiff or non-stiff ODE solvers

### ISSUE THREAD

**Issue by wallyxie** [stan-dev/math#1870]
## Description
See [prior discussion](https://discourse.mc-stan.org/t/stan-differential-equation-functionality-development-priorities/14906/12) on the Stan Discourse. Opening an issue here to make it more formal. To keep Stan in-step with the development of other PPL platforms that have the advantage of being able to import separate differential equation packages from their native languages. An initial improvement that would be part of the greater goal of bolstering Stan's overall differential equation capability would be the inclusion of additional solvers. There certainly does not need to be as many as in the standard set by DifferentialEquations.jl, but including one or two more non-stiff solvers and one more stiff solver would give folks trying to do inference on ODE systems, which seems to be more and more a part of the work done in various fields, more options. 

Edit: In light of the fact that the Adams-Moulton method is now documented, I agree with @wds15 that we do not need more non-stiff solvers (though more options does not hurt if there is time for it!). However, inclusion of an auto-switching algorithm that solves both stiff and non-stiff equations would be a good goal in my opinion to benefit users who have less knowledge about the stiffness of the system, or just want to plug and play with their ODE system (Edit 3: see @yizhang-yiz's discussion in the previously linked Stan Discourse thread about caveats with auto-switching). Needing to add a new function for each new solver also makes things a little clunkier, so as part of the efforts to add additional ODE solvers, having one ODE function in which the solver is chosen as an argument would be nice. 

Not able to assign myself this point because of other more pressing commitments, so if someone is able to take the initiative on this, they would be greatly welcome to do so.

**Comment by yizhang-yiz** [comment]
I don't see how this issue would be actionable. Conflating various solvers into one place simply because they all bear the name of "differential equations" doesn't help seek resolution. For example SDE is completely different ball game when it comes to model fitting.

Most Stan issues are small and actionable, for the sake of sanity of developers and reviewers.

**Comment by wallyxie** [comment]
@yizhang-yiz Got it, yeah, I understand. I'll go ahead and edit the initial discussion to just be about additional ODE equation solvers to make it more tractable.

**Comment by wallyxie** [comment]
I can continue pruning the initial post to continue to make it more tractable and actionable (perhaps limiting it to just adding another stiff ODE solver), so do let me know if there is more editing I should do to get it into form that is more reasonable.

**Comment by yizhang-yiz** [comment]
Closing for the moment for lack of action. Future milestone can be added if a new solver is requested with actually application cases.
