### ISSUE TITLE
max_num_steps definition inconsistent between integrate_ode_rk45 and integrate_ode_bdf

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#1876]
## Description

The boost max step checker (used for the rk45) is for all the steps used in an integration: https://www.boost.org/doc/libs/1_73_0/libs/numeric/odeint/doc/html/boost/numeric/odeint/max_step_checker.html

The CVODES max step checker (used in bdf) is for just the steps from one output solution to the next (search for "CVodeSetMaxNumSteps" [here](https://computing.llnl.gov/sites/default/files/public/cvs_guide.pdf)).

#### Current Version:
v3.2.0

**Comment by wds15** [comment]
I don't think we need to fix this - documenting it would be sufficient in my opinion here. After all we expose the functionality of other libraries.

**Comment by bbbales2** [comment]
Eh, it probably doesn't matter too much, but I think we should clarify it.

Someone the other day was suggesting a minimum stepsize for Stan, and I was going to tell them about `max_num_steps`, but then I realized I didn't know the actual definition of `max_num_steps`!

Anyhow I made a change to the new code to make this be the same between cvodes and Boost: https://github.com/stan-dev/math/blob/cb602adc434e0d73caaa27eebcb32b893b0e05cd/stan/math/prim/functor/ode_rk45.hpp#L179

I didn't add a test for this, so maybe it's not fixed anyway.

**Comment by wds15** [comment]
The boost thing is not for all, but only between observer calls. So I think it is like cvodes already if I read the doc correct.

**Comment by bbbales2** [comment]
Oh, how did you figure this out? I have trouble with Boost docs.

**Comment by bbbales2** [comment]
Oh "Additionally, the user can provide an __observer to analyze the state during time evolution, and a max_step_checker to throw an exception if too many steps are taken between observer calls (i.e. too small step size)" (https://www.boost.org/doc/libs/1_73_0/libs/numeric/odeint/doc/html/boost_numeric_odeint/odeint_in_detail/integrate_functions.html), you are right, I will close this.
