### ISSUE TITLE
Implement LambertW

### ISSUE THREAD

**Issue by Christopher22** [stan-dev/math#1880]
## Description
Lambert W is a function having a "myriad of applications" (according to the boost authors). Exposing the in great detail specified, performance-optimized, and well-tested function from boost to Stan might be useful in many domains (i.e. https://discourse.mc-stan.org/t/adding-lambert-w-transforms-to-stan/13906/3). I will start doing this.

#### Current Version:
v3.2.0

**Comment by bob-carpenter** [comment]
This'd be great.  The main thing to worry about is that each argument be independently differentiable (or marked as `data` in stanc3 and in the doc).  The autodiff testing framework should make testing of the autodiff versions straightforward.  Also, it's OK to start by just autodiffing the algorithm, though ideally we'd find good iterative algorithms for all the relevant partials.  Let us know if you need more help navigating the Stan code base or practices.
