### ISSUE TITLE
Errors thrown from ODE solvers are runtime errors. They should probably be domain_errors

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#1887]
## Description

The Boost RK45 max_step_checker throws runtime errors: https://www.boost.org/doc/libs/1_73_0/libs/numeric/odeint/doc/html/boost/numeric/odeint/max_step_checker.html

The CVODES solvers throw runtime errors: https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_flag_sundials.hpp

Can we change these to domain errors? We'd change the boost one by just reimplementing our own max_step_checker (which would be relatively easy).

The reason I am asking is because right now if you accidentally get a bad initialization on your ODE, the runtime errors will make Stan give up and not try different initial conditions and you get an error like:
```
Unrecoverable error evaluating the log probability at the initial value.
Exception: Max number of iterations exceeded (500). (in 'lv3.stan', line 18, column 4 to column 28)
Exception: Max number of iterations exceeded (500). (in 'lv3.stan', line 18, column 4 to column 28)
```

In reality all that is happened is you've fed a crazy initial condition into the ODE solver and it gave up the solve, and you should just try another one. Same as if you get NaNs or something in another situation.

The logic for this is in here: https://github.com/stan-dev/stan/blob/develop/src/stan/services/util/initialize.hpp#L111 . With domain errors we retry, and with runtime errors (or any other kind of error), we just bail.

I don't think we necessarily want to start ignoring runtime errors in that initialization. Most of those are probably index out of bounds and stuff that should blow up (hence I made this issue in Math).

#### Current Version:
v3.2.0

**Comment by wds15** [comment]
Sounds like a reasonable change to me. I would support that rationale.

**Comment by syclik** [comment]
Yeah, go for it!
