### ISSUE TITLE
Binary vectorisation framework

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#1890]
## Description

We currently have a framework for applying unary scalar functions to containers, and containers of containers (```apply_scalar_unary```), but we don't have a similar implementation for binary scalar functions.

I've worked up an ```apply_scalar_binary``` framework which will work with combinations of scalars, eigen objects/expressions, ```std::vectors```, and ```std::vectors``` of these. The code is up on [this branch](https://github.com/stan-dev/math/compare/develop...andrjohns:feature/scalar_binary).

For example, given the following code:
```
template <typename T1, typename T2>
inline auto binary_log_loss(T1 y, const T2& y_hat) {
  return apply_scalar_binary<T1, T2>::apply(
      y, y_hat, [&](const auto& v, const auto& v_hat) {
        return v ? -log(v_hat) : -log1m(v_hat);
      });
}
```
The following signatures are available
```
binary_log_loss(int, double)
binary_log_loss(int, VectorXd)
binary_log_loss(VectorXi, VectorXd)
binary_log_loss(VectorXi, double)
binary_log_loss(VectorXi, MatrixXd.diagonal()); // Or other expression/type
binary_log_loss(std::vector<int>, double)
binary_log_loss(int, std::vector<double>)
binary_log_loss(std::vector<int>, std::vector<double>)
```
The containers can also be nested, so ```std::vector<VectorXd>``` or ```std::vector<std::vector<double>>```inputs can also be also be used

I need to add documentation to the framework, and look at working out a binary equivalent of the ```expect_unary_vectorized``` autodiff testing framework, then this will be ready for more eyes. 

#### Current Version:
v3.2.0

**Comment by andrjohns** [comment]
The unary framework actually already works with expression templates, since [unaryExpr is used](https://github.com/stan-dev/math/blob/19f5f25bf9de1d267c92522d68eccfd0d73e12d0/stan/math/prim/meta/apply_scalar_unary.hpp#L63) and the input templating will accept any eigen types

**Comment by andrjohns** [comment]
Oh, you meant the testing framework, not apply_scalar_unary

**Comment by andrjohns** [comment]
@bob-carpenter @bbbales2 Can I get an opinion on something with the autodiff testing framework?

I'm working up the methods for testing the vectorised binary functions, but they're taking oddly long to run. At the moment the tests basically comprise:
```
  expect_ad(tols, f, VectorXd, VectorXd);
  expect_ad(tols, f, VectorXd, double);
  expect_ad(tols, f, double, VectorXd);
  expect_ad(tols, f, std::vector<VectorXd>, std::vector<VectorXd>);
  expect_ad(tols, f, std::vector<VectorXd>, double);
  expect_ad(tols, f, double, std::vector<VectorXd>);
  expect_ad(tols, f, std::vector<std::vector<VectorXd>>, std::vector<std::vector<VectorXd>>);
  expect_ad(tols, f, std::vector<std::vector<VectorXd>>, double);
  expect_ad(tols, f, double, std::vector<std::vector<VectorXd>>);
```

And that's taking a bit under 7 minutes to run. Is this expected for these kinds of inputs and I should just cut back the number of combinations to test, or does this seem like a bigger issue? 

The branch with the vectorised binary framework [is here](https://github.com/stan-dev/math/compare/develop...andrjohns:feature/scalar_binary), the added binary test framework [is here](https://github.com/stan-dev/math/compare/develop...andrjohns:feature/scalar_binary#diff-18ac55695b4cd9dda6bdc2c6f6e4ae70), and call in the mix test [is here](https://github.com/stan-dev/math/compare/develop...andrjohns:feature/scalar_binary#diff-ee9864f74e831f4b06b8ae350dd37194)

Thanks!

**Comment by bob-carpenter** [comment]
My advice is to use shorter vectors.  The tests test all inputs vs. all outputs for derivatives.  That starts getting big at higher orders.  The other option is to do some kind of reduction on the output.  That is, something like a sum of the outputs, which reduces the combinatorics but still tests derivatives indirectly.

**Comment by andrjohns** [comment]
Ah that makes sense, will do thanks

**Comment by andrjohns** [comment]
With the merge of #2005, all binary functions are now vectorised (hooray!). Will close this issue and start adding signatures.
