### ISSUE TITLE
Fwd definition of beta function not called by distributions

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#1908]
## Description
Currently, the ```beta``` function in the distribution tests only works with ```fvar<T>``` inputs through autodiff-ing the ```prim``` definition, not through calling the ```fwd``` definition.

## Example
This can be verified by restricting the ```prim``` inputs to be arithmetic:
```
template <typename T1, typename T2,
          require_all_arithmetic_t<T1, T2>* = nullptr>
inline return_type_t<T1, T2> beta(const T1 a, const T2 b) {
  using std::exp;
  return exp(lgamma(a) + lgamma(b) - lgamma(a + b));
}
```

And calling a distribution test which uses the ```beta``` function:
```
make -j16 test/prob/neg_binomial_2/neg_binomial_2_cdf_log_00000_generated_ffv_test
```
Which returns:
```
./stan/math/prim/prob/beta_lcdf.hpp:97:27: error: no matching function for call to ‘beta(const T_partials_return&, const T_partials_return&)’
   97 |         = stan::math::beta(alpha_dbl, beta_dbl);
```
When the input types are:
```
T_location = stan::math::fvar<stan::math::fvar<stan::math::var> >; T_precision = stan::math::fvar<stan::math::fvar<stan::math::var> >;
```

#### Current Version:
v3.2.0

**Comment by andrjohns** [comment]
The failing code belongs to the ```beta_lcdf``` header, and this section specifically:
```
    const T_partials_return betafunc_dbl
        = stan::math::beta(alpha_dbl, beta_dbl);
```
The namespace qualifier on beta is needed here as one of the input parameters is also called ```beta```. However, it looks like this is inhibiting the proper lookup of the ```fwd``` definition. If I rename the ```beta``` parameter to ```beta_param``` and remove the namespace qualifier from ```beta```, as  in:
```
    const T_partials_return betafunc_dbl = beta(alpha_dbl, beta_dbl);
```
Then the distribution tests compile without issue.

**Comment by bob-carpenter** [comment]
Thanks for the explanation---now I see why you called it `_param`---to separate from the function name.
