### ISSUE TITLE
stack_alloc_speed_test.cpp requires 5GB of RAM

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1910]
The stack_alloc_speed_test.cpp test here: https://github.com/stan-dev/math/blob/develop/test/unit/math/memory/stack_alloc_speed_test.cpp
requires 5GB of RAM to run, which is not really a huge requirement but prevents us from using less powerfull testing instances like the ones Github Actions uses. 

The free instance has 7GB, some of it goes to the OS and such and we are unable to pass this test on such an instance 

Is it actually necessary to allocate as much stack? Could we tests with half that? If n ran to 66000 that would allocate 2GB of RAM.

#### Current Version:
v3.2.0

**Comment by bob-carpenter** [comment]
Should be fine to run it with less.  The main issue is to make sure it handles crossing the allocation block boundaries without bugs.

**Comment by rok-cesnovar** [comment]
Ok, thanks!
