### ISSUE TITLE
Add Lee Sarmanov Bivariate Beta distribution to STAN?

### ISSUE THREAD

**Issue by BiostatQian** [stan-dev/math#194]
Could the STAN team please add the Lee Sarmanov Bivariate Beta distribution to STAN?

The LS BB density is explained by equations (12)-(13)-(14) in the attached image.

<img width="770" alt="ls_bb_snapshot" src="https://cloud.githubusercontent.com/assets/9919060/10747493/03456946-7c13-11e5-9384-a2b938469a04.png">

**Comment by bob-carpenter** [comment]
What's the motivation?  I doubt we're going to get to this
one any time soon unless someone volunteers an implementation.

You can use Stan's built-in function language to implement
it directly, though:

```
functions {
  /**
   * y outcome is 2-vector
   * a, b prior counts positive 2-vectors
   * omega a scalar meeting the constraints in (14)
   */
  real ls_bi_beta_log(vector y, vector a, vector b, real omega) {
    return beta_log(y, a, b)
      + log1p(omega 
              * (x[1] - a[1] / (a[1] + b[1]))
              * (x[2] - a[2] / (a[2] + b[2])));
  }
}
```

If you want omega to be a parameter, you'll have to declare it with
those upper and lower bounds.  Then you can use it in the model block as

```
  y ~ ls_bi_beta(a, b, omega);
```

or

```
  increment_log_prob(ls_bi_beta_log(y, a, b, omega));
```

- Bob

**Comment by QianSZhangBiostat** [comment]
Motivation: Need it for research.

Thanks Bob for the STAN code. 

Seems like I'll have to look at that STAN manual more closely if I want to use STAN.

**Comment by bgoodri** [comment]
I'm closing this issue, but there is another distribution the beta marginals that is already easy to work with in Stan:
https://www.brown.edu/academics/public-health/research/evidence-based-medicine/sites/brown.edu.academics.public-health.research.evidence-based-medicine/files/uploads/constructions_08Sep2014.pdf

**Comment by BiostatQian** [comment]
Why is this easier to work with in STAN, when the density in equation (2.3) is not in closed form? Wouldn't you still have to write STAN code for the probability density, and somehow incorporate an integral into that code?

**Comment by bgoodri** [comment]
You want to use a Dirichlet prior over U11, U10, and U01 as in equation (2.1) and construct X and Y using equation (2.2) as transformed parameters.  You don't need to evaluate equation (2.3).

**Comment by BiostatQian** [comment]
Thanks! Sorry that was obvious.

**Comment by syclik** [comment]
@BiostatQian, I'm locking this issue. If you have further questions, please ask on the user list.
