### ISSUE TITLE
OpenCL async Jenkins CI

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1940]
## Description

We currently have 2* machines that run OpenCL tests: 
- Mac with an AMD GPU
- Linux with an NVIDIA GPU

The issue is that one of the 2 machines support async OpenCL execution and the other one does not. We had 2 occasions where a PR passed on the non-async machine but then develop failed on the async one. Which is annoying and unnecessary burden on the Jenkins with a bugfix PR, additional inconvenience to other developers unaware of this situation, etc.

So when changes are made in the `/opencl` subfolder we should make sure that tests run on both an async GPU machine as well as non-async GPU machine. Given that these tests take ~10 minutes which means this does not increase the burden on Jenkins by much but it increases the test coverage a lot.

I honestly never know which machine is async and which one is not. The machine on which [these tests](https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/develop/734/pipeline) ran (and failed) is the async one.

My idea for this issue is: 
- add a "gpu-async" label to the async machine and "gpu-no-async" label to the other one
- add logic to Jenkins to run 2 tests (one for each label) if a change is made in `/opencl`, otherwise just run 1 tests with the "gpu" label that both these machines have.
- (optional) add "gpu-async" Jenkins parameter that we could tick when running a job with 
parameters (similar to "withRowVector" [here](https://jenkins.mc-stan.org/job/Math%20Pipeline/job/PR-1933/build?delay=0sec))

Open to other solutions off course.

*There will be a third one on the Windows machine in Ljubljana (we already tried once but Jenkins did not like it, will try again soon).

#### Current Version:
v3.2.0

**Comment by rok-cesnovar** [comment]
cc @serban-nicusor-toptal 

This is not something urgent, rather something to do if you run out of tasks :)

I am not sure who else has permissions to add labels to Jenkins agents, so I am assigning you here, if you dont mind.

**Comment by serban-nicusor-toptal** [comment]
`gelman-linux` is async, `gelman-mac` is no-async.

I've added the respective labels to them, if you ever need to know what GPUs we have /machine you can take a look [here](https://github.com/stan-dev/ci-scripts/blob/master/docs/agents.md)
Will create a PR with the requested changes to the Jenkinsfile, if you need help with setting up the new machine let me know!

**Comment by rok-cesnovar** [comment]
Thanks! I will start setting up the GPU on the new machine once I stop working remotely full-time. This very likely won't be before the end of summer, but I might go to the office earlier. We will see. Thanks again for the help!

**Comment by serban-nicusor-toptal** [comment]
Quick question, what should happen when you tick `gpu-async` parameter ? We run both sync/async ?

**Comment by rok-cesnovar** [comment]
Yes, exactly.

**Comment by serban-nicusor-toptal** [comment]
Hey @rok-cesnovar just to double check, I don't have an `open-cl` directory in the root of math, did you mean [lib/opencl_2.2.0](https://github.com/stan-dev/math/tree/develop/lib/opencl_2.2.0) ?

**Comment by rok-cesnovar** [comment]
Hey, I meant the test/math/opencl folder. But I see you already figured it out. Will review first thing tomorrow. Thanks!!

**Comment by rok-cesnovar** [comment]
Re-opening this to track the issue of running on the gelman-group-linux machine that seems to be unable to find the device. close once resolved.
