### ISSUE TITLE
Memory leak in Newton solver

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/math#1950]
## Description
There's a possibility of leaking memory in `kinsol_solve.hpp` when solution process throws exception before destructing `nv_x` & `scaling` vector.

## Example
Here the destruction
https://github.com/stan-dev/math/blob/59fafbe1b4a392952df02a5f1b58b1f83fd5fe61/stan/math/rev/functor/kinsol_solve.hpp#L126-L127

is at the end of KINSOL solution processes. Since of previous ` check_flag_` calls could throw exception and exit early, hence large amount of memory could be leaked.

## Expected Output
No leaking. Potentially by `catch`ing the exception and cleaning up.

#### Current Version:
v3.2.0

**Comment by SteveBronder** [comment]
You could put all those into a class and then have the destructor for the class call these. So when that object goes out of scope the destructors are called even if an exception is made.

**Comment by yizhang-yiz** [comment]
Yes. That's another option, as what I did for FP solver. I'll leave the decition to @charlesm93.

**Comment by yizhang-yiz** [comment]
This has been fixed.
