### ISSUE TITLE
ODE performance enhancements

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1958]
This issue was imported from the stan-dev/math wiki page "Parallel Asynchronous ODE Integration", which has since been removed.

This page just documents a possible performance increase for the ODE system. In hierarchical ODE based Stan models  we often integrate many ODEs, each with different parameter sets. Parallelizing this with `map_rect` is a great way to speed this up, but it is very tedious to program.  Here is an idea which would do the parallelization of the many integrate ode calls in full automation at a little overhead cost.

When we integrate N states and have M parameters, then the number of ODE equations needed to solve depends on the sensitivities requested. In the worst case of requiring the sensitivities wrt to the initial state and the parameters we end up with

- N ODEs for the base system
- N*N ODEs for the initials
- N*M ODEs for the parameters

... which is often a lot more than just the base ODE system.

However, we can in Stan build the AD tape in an asynchronous way:

- Upon calling a new `integrate_ode_async` we compute the solution to the base system only.
- Once the base system is ready we can return a `adj_jac_vari` instance immediately; without yet having available the sensitivities.
- The solution to the sensitivity system is performed **asynchronously** while the Stan program proceeds.
- During the reverse sweep of reverse mode AD, the respective nodes in the AD tree have to wait for the sensitivity calculations to finish.

This pattern will allow to run all coupled ode systems integrations in the background with full parallelism.

On a small toy example with N=2 states and M=4 parameters I get on my system an integration time of 1750ms for the full system with all sensitivities while the base system can be integrated in just 300ms (see below). Using this approach the 300ms would be wasted resources as the base system is solved int the coupled ode system run with sensitivities as well. This amounts to a wasted 17% of the resources, but with increasing N and M the sensitivity system quickly explodes quadratically in size. Thus, the wasted resource fraction becomes quickly very small.

The upside of this approach is that ODE solving becomes in full automation parallel without any user interaction.

Toy example:

```cpp
#include <stan/math/rev/mat.hpp>
#include <boost/random.hpp>
#include <stan/math/prim/scal/prob/lognormal_rng.hpp>
#include <gtest/gtest.h>
// very small michaelis menten example
#include <test/unit/math/rev/arr/functor/coupled_mm.hpp>
#include <test/unit/util.hpp>
#include <vector>

// test which triggers the too much work exception from odeint
TEST(StanOde_tooMuchWork_test, cvodes_coupled_mm) {
  coupled_mm_ode_fun f_;

  boost::ecuyer1988 rng;

  // initial value and parameters from model definition

  double t0 = 0;

  std::vector<double> ts_long;
  ts_long.push_back(1E10);

  std::vector<double> ts_short;
  ts_short.push_back(1);

  std::vector<double> data;

  std::vector<int> data_int;

  typedef stan::math::var scalar_type;

  for (std::size_t i = 0; i < 1000; i++) {
    stan::math::start_nested();

    std::vector<scalar_type> theta_v(4);

    theta_v[0] = stan::math::lognormal_rng(1, 2, rng);
    theta_v[1] = stan::math::lognormal_rng(-1, 2, rng);
    theta_v[2] = stan::math::lognormal_rng(-1, 2, rng);
    theta_v[3] = stan::math::lognormal_rng(-2, 2, rng);

    std::vector<scalar_type> y0_v(2);
    y0_v[0] = stan::math::lognormal_rng(5, 2, rng);
    y0_v[1] = stan::math::lognormal_rng(-1, 2, rng);

    std::vector<std::vector<scalar_type> > res = stan::math::integrate_ode_bdf(
        f_, y0_v, t0, ts_long, theta_v, data, data_int, 0, 1E-10, 1E-10, 10000);

    stan::math::grad(res[0][0].vi_);

    stan::math::recover_memory_nested();
  }

  stan::math::print_stack(std::cout);

  stan::math::recover_memory();
}

TEST(StanOde_tooMuchWork_test, cvodes_coupled_mm_prim) {
  coupled_mm_ode_fun f_;

  boost::ecuyer1988 rng;

  // initial value and parameters from model definition

  double t0 = 0;

  std::vector<double> ts_long;
  ts_long.push_back(1E10);

  std::vector<double> ts_short;
  ts_short.push_back(1);

  std::vector<double> data;

  std::vector<int> data_int;

  typedef double scalar_type;

  for (std::size_t i = 0; i < 1000; i++) {
    //stan::math::start_nested();

    std::vector<scalar_type> theta(4);

    theta[0] = stan::math::lognormal_rng(1, 2, rng);
    theta[1] = stan::math::lognormal_rng(-1, 2, rng);
    theta[2] = stan::math::lognormal_rng(-1, 2, rng);
    theta[3] = stan::math::lognormal_rng(-2, 2, rng);

    std::vector<scalar_type> y0(2);
    y0[0] = stan::math::lognormal_rng(5, 2, rng);
    y0[1] = stan::math::lognormal_rng(-1, 2, rng);

    std::vector<std::vector<scalar_type> > res = stan::math::integrate_ode_bdf(
        f_, y0, t0, ts_long, theta, data, data_int, 0, 1E-10, 1E-10, 10000);

    //stan::math::grad(res[0][0].vi_);

    //stan::math::recover_memory_nested();
  }

  //stan::math::print_stack(std::cout);

  stan::math::recover_memory();
}

```

**Comment by bbbales2** [comment]
I don't think it would be easy to decouple the regular solves and the sensitivity solves the way the ODEs are set up now. @wds15 is this your proposal? Mind if we axe it?

**Comment by wds15** [comment]
The idea is to solve the system without sensitivities on the forward sweep and send the solve with the sensitivities into a background thread. This way you solve twice the system without sensitivities, but you solve the big ode system with sensitivities in parallel with other stuff which is ongoing. My main application I had in mind is a hierarchical model with many patients. This way you would automatically run the bulk of the computational effort in parallel in full automation.

Since we have now reduce_sum there is less of a need for this... still, doing automatic parallelization is sweet... but we can Drop this... fine with me.

**Comment by bbbales2** [comment]
> This way you solve twice the system without sensitivities, but you solve the big ode system with sensitivities

An extra difficulty is that you'd need to implement some sort of checkpointing for the original forward solution (you might need it at more or less points than specified by the output).

Gonna close it cause we've got other ways of parallelizing.
