### ISSUE TITLE
parallel reduce sum

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#1959]
Transferred from wiki page "Parallel reduce sum", which no longer exist.

# Introduction

This document is meant to facilitate development of the `reduce_sum` command, which provides a general facility for running the sum reduce operation over elements created by evaluating a user provided function on a potentially large set of items. The key benefit of using the new command is parallel evaluation with the Intel TBB for the cases of primitive evaluation or reverse mode autodiff.

The targeted usage in a Stan user program is conceptually like:

```stan
functions {
   real user_lpdf(int start, int end, real[] sub_slice,
                 real[] shared_arg1, ..., int[] shared_argN) {
      // calculate the lpdf for the sub-slice of data given in
      // sub_slice;  shared arguments can be subsetted according to start
      // and end index;  for example, if only group means of subsets
      // of the data are needed as given by start...end
      return slice_lpdf;
   }
}
...

model {
   target += reduce_sum(user_lpdf, sliced_argument,
                        shared_arg1, ..., shared_argN);
   // the above is equivalent to
   // target += user_lpdf(1, size_of(slice_argument), sliced_argument,
   //                     shared_arg1, ..., shared_argN);
}
```

The exact slicing is not controlled by the user, but instead by the Intel TBB scheduler which controls what chunks of works are being executed.

For the discussion describing how this design evolved, see [Parallel autodiff v3](https://discourse.mc-stan.org/t/parallel-autodiff-v3/12474).

# Stan Language

The `reduce_sum` targets the Stan signatures as

```stan

// f is the reducer function
real f(int start, int end, sliced_type sub_slice_container, ...);

// parallel reduce
real reduce_sum(real(int, int, sliced_type, ...) f,
                sliced_type large_container, int grainsize, ...);

```

So the user passes in a reducer function `f`, a grainsize (telling the TBB what is a sensible blocking size),  a large container over which the reduce is performed and shared arguments of any Stan admissible type. Currently the restriction used for the `slice_type` is that it must be an array which may contain any other type. So these are admissible for the `sliced_type`:

- `real[num_jobs]`
- `int[num_jobs]`
- `real[num_jobs,nested_dimension]`
- `matrix[rows, cols][num_jobs]`
- `vector[rows][num_jobs]`
- `row_vector[cols][num_jobs]`

Thus we allow about anything for the `slice_type`, but excluding `vector`, `row_vector` or `matrix`.

The shared arguments in `...` can be arbitrary many and these can be of any type.

# Example Stan Program

Here is an example Stan program which performs inference for a hierarchical Poisson model. The program simulates its own data and calculates the likelihood with different ways of parallelism which is control by the `method` switch part of the data:

- `method=0`: Using parallel reduce TBB with given grainsize
- `method=1`: Using reduce function without parallelization
- `method=2`: Using parallel grouped reduce TBB with grainsize. This version is more efficient than method 0, but a bit more cumbersome to read.
- `method=3`: Using grouped reduce function without parallelization
- `method=4`: Using map_rect
- `method=5`: Simple serial evaluation

Note that the grainsize is a tuning parameter for the Intel TBB which controls the minimal chunking size.

Example model:

```stan
functions {
  // runs reduce over the index range start to end. Mapping from
  // data-index set to group indices pre-stored in gidx
  real hierarchical_reduce(int start, int end, int[] y_slice, real[] log_lambda_group, int[] gidx) {
    return poisson_log_lpmf(y_slice| log_lambda_group[gidx[start:end]]);   
  }

  // runs reduce over the index range start to end. Mapping from
  // data-index set to group indices pre-stored in gidx
  real hierarchical_grouped_reduce(int start, int end, real[] log_lambda_group_slice, int[] y, int[] gsidx) {
    real lp = 0.0;
    int terms = end - start + 1;
    for(i in 1:terms) {
      int gstart = gsidx[start + i - 1];
      int gend = gsidx[start + i] - 1;
      lp += poisson_log_lpmf(y[gstart:gend]| log_lambda_group_slice[i]);
    } 
    return lp;
  }

  // map-rect alterantive
  vector mr_reduce(vector beta, vector log_lambda, real[] xr, int[] xi) {
    real lp = poisson_log_lpmf(xi| log_lambda[1]);
    return [lp]';
  }
}
data {
  int<lower=0> N;
  int<lower=0> G;
  int<lower=0> grainsize;
  int<lower=0,upper=5> method;
} 
transformed data {
  real true_log_lambda = log(5.0); 
  real true_tau = log(10)/1.96;
  int y[N*G];
  int yg[G,N];
  real xr[G,0];
  int gidx[N*G]; 
  int gsidx[G+1]; 
  int start[G];
  int end[G];
  int group[G];
  vector[0] theta_dummy;

  print("Simulating problem size: G = ", G, "; N = ", N);
  if (method == 0) {
    print("Using parallel reduce TBB with grainsize = ", grainsize);
  } else if (method == 1) {
    print("Using reduce function without parallelization.");
  } else if (method == 2) {
    print("Using parallel grouped reduce TBB with grainsize = ", grainsize);
  } else if (method == 3) {
    print("Using grouped reduce function without parallelization.");
  } else if (method == 4) {
    print("Using map_rect.");
  } else if (method == 5) {
    print("Using serial evaluation only.");
  }

  for(g in 1:G) {
    real lambda_group = lognormal_rng(true_log_lambda, true_tau);
    int elem = 1;
    group[g] = g;
    start[g] = (g-1) * N + 1;
    end[g] = g * N;
    gsidx[g] = start[g];
    gsidx[g+1] = end[g]+1;
    for(i in start[g]:end[g]) {
      y[i] = poisson_rng(lambda_group);
      yg[g,elem] = y[i];
      gidx[i] = g;
      elem += 1; 
    }
  }
}
parameters { 
  real log_lambda;
  real<lower=0> tau; 
  vector[G] eta;
}
model {
  real log_lambda_group[G] = to_array_1d(log_lambda + eta * tau);
  //vector[G] log_lambda_group_vec = to_vector(log_lambda_group) ;
  real lpmf = 0;

  if (method == 0) {
    lpmf = reduce_sum(hierarchical_reduce, y, grainsize, log_lambda_group, gidx);
  } else if (method == 1) {
    lpmf = hierarchical_reduce(1, N*G, y, log_lambda_group, gidx);
  } else if (method == 2) {
    lpmf = reduce_sum(hierarchical_grouped_reduce, log_lambda_group, grainsize, y, gsidx);
  } else if (method == 3) {
    lpmf = hierarchical_grouped_reduce(1, G, log_lambda_group, y, gsidx);
  } else if (method == 4) {
      vector[1] log_lambda_group_tilde[G];
      for(g in 1:G)
        log_lambda_group_tilde[g,1] = log_lambda_group[g];
      lpmf = sum(map_rect(mr_reduce, theta_dummy, log_lambda_group_tilde, xr, yg));
  } else if (method == 5) {
      lpmf = poisson_log_lpmf(y| log_lambda_group[gidx]);
  }

  target += lpmf;
  target += normal_lpdf(log_lambda|0,1);
  target += normal_lpdf(tau|0,1);
  target += normal_lpdf(eta|0,1);
}
generated quantities {
  real msq_log_lambda = square(true_log_lambda - log_lambda);
  real msq_tau = square(true_tau - tau);
}
```

# Things Left Todo

Add the stanc3 interface so we can test this in a larger setting

**Comment by rok-cesnovar** [comment]
We can close this one, this was done. It is good that we have this saved somewhere in the unlikely case we need it sometime in the future.
