### ISSUE TITLE
Generalizing error checks to containers of containers

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#1962]
## Description

For the variadic ODEs pull, I needed to be able to call `check_finite` on containers of containers. That'd be things like `std::vector<std::vector<T>>`, etc.

The difficulty is the `domain_error` check_finite functions don't have pretty prints defined for things with more than one index.

For instance, if you have the Stan variable:
```
real a[5, 6, 7];
```

And the element at index `(1, 2, 3)` is infinite, you might want the check_finite function to tell you this. That isn't supported right now with `check_finite`. Only single indices are supported.

I guess there are three options here:
1. Don't check user-defined data arguments to ODEs (and I dodge this issue entirely)

2. Recursively check for non-finite values but don't print debugging index info (this is the solution I implemented as a prototype [here](https://github.com/stan-dev/math/blob/40ba7a8186cbec9c3bf52ef1f2658f1578fd6216/stan/math/prim/err/check_finite.hpp#L119)

3. Recursively check for non-finite values and print the full debugging index info somehow

I guess does anyone have strong feelings for what we should do here?

I think I've convolved two questions together here: what we should do for variadic arguments in ODEs, and what we should do long term to support checks like this.

If we decide we want to do the fancier checks, then I'll probably just remove the checks from the ODE functions (they aren't necessary -- the variadic arguments passed to the ODE solvers are advertised as pass-through -- I don't think we need to be checking them), and clean this issue up to remove the variadic ODE stuff from it.

If we decide to go with simpler checks, then I'll make the changes to `check_finite` as part of the variadic ODEs pull request.

#### Current Version:
v3.2.0

**Comment by rok-cesnovar** [comment]
@nhuurre recently had to refactor the [check_matching_dims](https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_matching_dims.hpp#L86) for containers of containers.

```cpp
    const int size_1 = 5;
    const int size_2 = 4;
    const int size_3 = 3;
    std::vector<std::vector<std::vector<double>>> a(size_1);
    for (int i=0;i<size_1;i++) {
        a[i].resize(size_2);
        for(int j=0; j < size_2; j++) {
            a[i][j].resize(size_3);
        }
    }
    std::vector<std::vector<std::vector<double>>> b(size_1);
    for (int i=0;i<size_1;i++) {
        b[i].resize(size_2);
        for(int j=0; j < size_2; j++) {
            b[i][j].resize(6);
        }
    }
    stan::math::check_matching_dims("f", "a", a, "b", b);
```
produces
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  f: a (5, 4, 3) and b (5, 4, 6) must match in size
```

I feel this is much more informative than just a general "must match in size". However, checking dims is much faster and simple to do so not sure this is helping.

I would say 3 and don't run checks in ODE if they are unnecessary.

**Comment by nhuurre** [comment]
I think this is a duplicate of issue #1635

**Comment by rok-cesnovar** [comment]
Oh, right. Also, https://github.com/stan-dev/math/pull/1798 will make check_finite and friends work for nested containers.

**Comment by bbbales2** [comment]
@nhuurre @rok-cesnovar thanks for the links. Yeah this looks like a duplicate, and I'm happy someone has already found a way to fix this :D.
