### ISSUE TITLE
Add function for applying function to each element of a tuple

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#1972]
## Description

If we have a tuple:

```
auto tuple = std::make_tuple(a, b, c, d);
```

Then there are at least two current situations in the variadic ODE code ([here](https://github.com/stan-dev/math/blob/7a42c5a7f98ca67c4199e1ea0237ac3864670c36/stan/math/rev/functor/cvodes_integrator.hpp#L214) and [here](https://github.com/stan-dev/math/blob/7a42c5a7f98ca67c4199e1ea0237ac3864670c36/stan/math/rev/functor/coupled_ode_system.hpp#L147) zero_adjoints wouldn't need to be variadic, and might be removable all together) where it would be convenient to apply a function over all elements of a tuple.

So the function would be something like:
```
for_each(tuple, myfunc);
```

And that would be equivalent (taking `tuple` to be the one defined above) to the code:
```
myfunc(a);
myfunc(b);
myfunc(c);
myfunc(d);
```

Presumably this will come up as we do more and more variadic things.

This is different from apply which makes one function call with all elements of the tuple as arguments (```myfunc(a, b, c, d)```)

@SteveBronder has some code for this here: https://gist.github.com/SteveBronder/410f7127f8be9dced2b1915765fd8644

#### Current Version:
v3.2.0

**Comment by t4c1** [comment]
Anything wrong with apply https://github.com/stan-dev/math/blob/develop/stan/math/prim/functor/apply.hpp ?

If you need something a bit more general we also have index_apply https://github.com/stan-dev/math/blob/develop/stan/math/prim/meta/index_apply.hpp.

**Comment by bbbales2** [comment]
This is different from apply cause this does `f(a)`, `f(b)`, etc., instead of `f(a, b, ...)`.

I vaguely remember when I wrote [this](https://github.com/stan-dev/math/blob/7a42c5a7f98ca67c4199e1ea0237ac3864670c36/stan/math/rev/functor/cvodes_integrator.hpp#L214) there was some C++17 way to do it, but the `apply` version is what we got and it's not the cleanest.

**Comment by t4c1** [comment]
`index_apply` can handle this case. So do we need another similar function?

**Comment by bbbales2** [comment]
Nope, we don't need another thing.

How do I do it with index_apply?

It looks like the index is passed as an argument. Can I use constexpr and stuff to pass that as the template argument to `std::get`?

**Comment by t4c1** [comment]
```
auto tuple = std::make_tuple(a, b, c, d);
auto result = index_apply<std::tuple_size<decltype(tuple)>::value>([](auto... Is){
    myfunc(std::get<Is>(tuple)...);
}
```
I am not sure what do you mean about constexpr, but that should handle your use case.

**Comment by bbbales2** [comment]
Oh I wasn't sure if the `auto... Is` arguments could be used as arguments to `std::get`, but I guess if they can then that is simple enough.

**Comment by t4c1** [comment]
Yeah, looks a bit like dark magic (and I wrote that :) ). I guess that `auto...` is deduced into a series of `constexpr size_t` arguments.

**Comment by bbbales2** [comment]
Oh I tried this. This is doing something different.

This does:
```
myfunc(a, b, c, d);
```

I want:
```
myfunc(a);
myfunc(b);
myfunc(c);
myfunc(d);
```

**Comment by t4c1** [comment]
Ok than you can do:
```
index_apply<std::tuple_size<decltype(tuple)>::value>([](auto... Is){
    std::initializer_list<int>{
        (f(std::get<Is>(tuple)),0)...
    }});
```
Getting all the parenthesis and braces right can be a bit of a challenge ;) . Btw in this case you can also use regular apply.

**Comment by bbbales2** [comment]
Yeah I think that's close to what is written now:

```
apply(
        [&](auto&&... args) {
          std::vector<int> unused_temp{
              0, (check_finite(function_name, "ode parameters and data", args),
                  0)...};
        },
        args_tuple_);
```

(Came from: https://stackoverflow.com/a/17340003)

This is verging on a bit dirty and so I do like a new function here.

**Comment by SteveBronder** [comment]
I agree `index_apply` etc can do this but I think having a generic operator like `for_each` would be nice for this use case. The `for_each` I have there can also handle binary ops over two containers

**Comment by t4c1** [comment]
I see. Another suggestion (and this time I am not sure it is better than what you are proposing myself) is to just add a no-op function that can accept arbitrary arguments. That would be a bit less clean but a bit more general.

**Comment by t4c1** [comment]
I think we would still need the comma trick to deal with void returns tho.

**Comment by WardBrian** [comment]
https://github.com/stan-dev/math/blob/develop/stan/math/prim/functor/for_each.hpp
