### ISSUE TITLE
Investigate randomly failing threading test

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#1996]
This issue was reported by @syclik 

On a [PR](https://github.com/stan-dev/math/pull/1994) that only touched docs, we have a reduce_sum test failure: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1994/1/pipeline

```
[       OK ] StanMathPrim_reduce_sum.sum (0 ms)
[ RUN      ] StanMathPrim_reduce_sum.threading
test/unit/math/prim/functor/reduce_sum_test.cpp:256: Failure
Expected: (uniques.size()) > (1), actual: 1 vs 1
test/unit/math/prim/functor/reduce_sum_test.cpp:266: Failure
Expected: (uniques.size()) > (1), actual: 1 vs 1
[  FAILED  ] StanMathPrim_reduce_sum.threading (2 ms)
[----------] 33 tests from StanMathPrim_reduce_sum (7 ms total)
```

We have not had a develop fail with this error, I have not seen on my PRs, maybe others have.

**Comment by rok-cesnovar** [comment]
If I understand this test correctly it would also fail in the event that one thread would do all the work? Which I suspect is going on there.

```cpp
std::vector<int> threading_test_global;
struct threading_test_lpdf {
  template <typename T1>
  inline auto operator()(const std::vector<T1>&, std::size_t start,
                         std::size_t end, std::ostream* msgs) const {
    threading_test_global[start] = tbb::this_task_arena::current_thread_index();

    return stan::return_type_t<T1>(0);
  }
};

TEST(StanMathPrim_reduce_sum, threading) {
  threading_test_global = std::vector<int>(10000, 0);
  stan::math::reduce_sum_static<threading_test_lpdf>(threading_test_global, 1,
                                                     nullptr);

  auto uniques = std::set<int>(threading_test_global.begin(),
                               threading_test_global.end());

  EXPECT_GT(uniques.size(), 1);

  threading_test_global = std::vector<int>(10000, 0);

  stan::math::reduce_sum<threading_test_lpdf>(threading_test_global, 1,
                                              nullptr);

  uniques = std::set<int>(threading_test_global.begin(),
                          threading_test_global.end());

  EXPECT_GT(uniques.size(), 1);
}
```

If I change the start of the test to force it to use one thread,
```
TEST(StanMathPrim_reduce_sum, threading) {
  set_n_threads(1);
  tbb::task_scheduler_init& tbb_init = stan::math::init_threadpool_tbb();
  threading_test_global = std::vector<int>(10000, 0);
  stan::math::reduce_sum_static<threading_test_lpdf>(threading_test_global, 1,
                                                     nullptr);
```
 it fails with the same error. So the test is problematic in that it relies on multiple threads having free resources. Which is not necessarily true and can cause random fails.

**Comment by wds15** [comment]
The test is there to make sure that the TBB code did really run in different threads. So if the TBB decides to dispatch the test code to only one thread, then the test will fail. Maybe the test needs to change or we even drop the test.

The reason why the test is there is that in an earlier version of reduce_sum we forgot to enable the parallel code. So everything calculated just fine, but always only serially. This test is there to ensure that we actually use multiple threads here.

**Comment by rok-cesnovar** [comment]
Running this test separately with no other tests running might decrease the chances of it failing randomly, but still no guarantee. So might be best to remove it. 

We do need to check that we are running things with multiple threads in map_rect, reduce_sum somehow though.
