### ISSUE TITLE
Unable to build cmdstan if bash is not at /bin/bash

### ISSUE THREAD

**Issue by richardfergie** [stan-dev/math#1997]
**Describe the bug**
`install_cmdstan()` fails with the following

```
* Latest CmdStan release is v2.24.0
* Installing CmdStan v2.24.0 in /home/fergie/.cmdstanr/cmdstan-2.24.0
* Downloading cmdstan-2.24.0.tar.gz from GitHub...
* Download complete
* Unpacking archive...
* Building CmdStan binaries...
cp bin/linux-stanc bin/stanc
make: /bin/bash: Command not found
make: *** [make/stanc:61: bin/stanc] Error 127

Warning message:
There was a problem during installation. See the error message(s) above.
```

**To Reproduce**
Run `install_cmdstan` on a system where bash is not at /bin/bash

**Expected behavior**
Should use /usr/bin/env bash to correctly load bash

**Other information
Changing line 128 in stan/lib/stan_math/make/libraries in the to read 
```
SHELL = /usr/bin/env bash
```
makes it work.

I can't figure out where that file is in this repository otherwise I would submit a patch along with this issue

**Comment by richardfergie** [comment]
Great! Thank you

https://github.com/richardfergie/math/blob/develop/make/libraries#L128 is what the change looks like when it works for me.

I don't really know how to setup the necessary tests for this so I won't submit a pull request for now

**Comment by rok-cesnovar** [comment]
For such a simple change you don't need to verify anything locally. Just open a pull request and our CI will run the tests. 

But if you do not wish to bother with that, I can apply your patch to an open PR already dealing with some minor compile flag stuff. Will make sure to give the proper credit in that case. Let me know. And thanks again!
