### ISSUE TITLE
MPI tests rebuild when nothing has changed; also breaks on rebuild

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#1999]
## Description

When building tests with MPI, boost is rebuilt every time make is called with the test target. When boost is rebuilt for the second time, it will break the ability to link against the tests.

Looking at `make/libraries`, it looks like it expects a few `.so` files to exist, but they aren't generated. This will trigger a rebuild each time.

## Example

1. First add MPI settings to `make/local`.
2. Run `./runTests.py test/unit/math/prim/functor/mpi_parallel_call_test.cpp`; this should work
3. Run `./runTests.py test/unit/math/prim/functor/mpi_parallel_call_test.cpp` again; this will fail.

## Expected Output

On the second call to`./runTests.py test/unit/math/prim/functor/mpi_parallel_call_test.cpp` this should just run the test, but not rebuild it.

#### Current Version:
v3.3.0

**Comment by rok-cesnovar** [comment]
The PR that fixed this introduced a "makefile race condition" in that the boost script gets called twice if make is called with -j. 



```
$(BOOST)/stage/lib/libboost_serialization.so $(BOOST)/stage/lib/libboost_mpi.so: $(BOOST)/user-config.jam
	@mkdir -p $(dir $@)
	cd $(BOOST); ./bootstrap.sh
        ...
```

This should be 

```
$(BOOST)/stage/lib/libboost_serialization.so :$(BOOST)/stage/lib/libboost_mpi.so 
$(BOOST)/stage/lib/libboost_mpi.so: $(BOOST)/user-config.jam
	@mkdir -p $(dir $@)
	cd $(BOOST); ./bootstrap.sh
        ...
```

**Comment by rok-cesnovar** [comment]
This caused some issues on Jenkins with MPI tests. For example: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-1944/7/pipeline

**Comment by syclik** [comment]
Me fault. I think I introduced this. Those two dependencies are generated
by the same step.

It looks like more recent versions of make actually account for this
properly with a different syntax. (I don’t think it’s part of our existing
make version.)

https://www.gnu.org/software/make/manual/html_node/Multiple-Targets.html
