### ISSUE TITLE
gaussian_dlm:  Does C0 really need to be positive-definite? 

### ISSUE THREAD

**Issue by elbamos** [stan-dev/math#2017]
## Description
`gaussian_dlm_obs_lpdf` checks that C0 (the initial state covariance matrix) is positive-definite. (https://github.com/stan-dev/math/blob/develop/stan/math/prim/prob/gaussian_dlm_obs_lpdf.hpp#L100) 

I think it should be sufficient that C0 is positive semi-definite.  This enables (or simplifies, if there's a way of doing this I didn't think of) the construction of some models.  

In my use case, I'm working with a local linear trend model with an intercept (delta_t+1 = alpha + beta(delta_t - alpha) + nu). 

## Expected Output
I would replace lines 100 and 243 of https://github.com/stan-dev/math/blob/develop/stan/math/prim/prob/gaussian_dlm_obs_lpdf.hpp with:
`check_pos_semidefinite(function, "C0", C0);`

**Comment by elbamos** [comment]
@bbbales2 Yes. C0 could be a zero matrix (i.e., the model samples m0 from some distribution external to the dlm), C will still converge to the same place.  (I haven't proven this, but I've tested it.)

I'm not going to say its impossible for someone to come up with a combination of C0, W, and V that causes Q to not be invertible, but I'm not seeing how.

**Comment by bbbales2** [comment]
Oh okay I'll look at this
