### ISSUE TITLE
Create var_value conversion functions and helper metaprograms for stanc3

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2045]
## Description

We discussed `var_value` stanc3 stuff this morning with @t4c1 and a couple of stuff popped up that would need to be done to simplify the transition to var_value in stanc3.

- [ ] conversion function between `var_value<Matrix<double>>` and `Eigen<var>`
- [ ] UDF return type helper metaprogram. Example:

```cpp
template <typename T0__, typename T1__, typename T2__>
std::conditional_t<
  is_any_var_vt<is_eigen, T0__, T1__, T2__>::value, 
  var_value<Eigen::Matrix<double, -1, -1>>
  Eigen::Matrix<stan::promote_args_t<T0__, T1__, T2__>, -1, -1>
>
foo(const T0__& a,
    const T1__& b,
    const T2__& c, std::ostream* pstream__) {
```
meaning that if any input is var_value the return will be a var_value (if matrix/vector/row_vector).

#### Current Version:
v3.3.0

**Comment by rok-cesnovar** [comment]
Do we have a metaprogram that does something like:

If T is double (or not-var essentially, but always a "scalar type"), then set the type as Eigen<T>, otherwise, set it to var_value<Eigen<double>>

**Comment by t4c1** [comment]
This is for local variables in log_prob for the case it is called with non-var arguments, right? I think we can go without such a metaprogram by having compiler generate `using var_value_vector = std::conditional_t<is_var<Argument>::value, var_value<Eigen::VectorXd>>, Eigen::VectorXd>;` (and same for matrix and row vector) and than use this when it determines `var_value` should be used.

**Comment by rok-cesnovar** [comment]
> This is for local variables in log_prob for the case it is called with non-var arguments, right?

Yeah, any non-data variable in a model. Those are all defined in log_prob yes. 

Your idea sounds good to me. Will close and add your comment to the stanc3 issue.
