### ISSUE TITLE
Compound Operations Fail in Test Suite

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2049]
## Description

Not sure if this is a bug or I'm not using the test suite as intended, but using a lambda in the test suite that calls two stan math functions that then return an eigen type causes a segfault

## Example

See the branch here where I added a test for adding two softmax functions

```
git pull
git checkout fix/test-compound-expressions
./runTests.py ./test/unit/math/test_ad_test.cpp
```

```cpp
TEST(test_unit_math_test_ad, test_ad_compound) {
  Eigen::VectorXd x(4);
  x << 1.9, 0.3, 0.3, 1.7;
  auto g = [](const auto& u) { return stan::math::softmax(u) + stan::math::softmax(u); };
  stan::test::expect_ad(g, x);
}
```

This segfaults like 

```
./test/unit/math/test_ad_test --gtest_output="xml:./test/unit/math/test_ad_test.xml"
Running main() from lib/benchmark_1.5.1/googletest/googletest/src/gtest_main.cc
[==========] Running 11 tests from 4 test suites.
[----------] Global test environment set-up.
[----------] 4 tests from test_unit_math_test_ad
[ RUN      ] test_unit_math_test_ad.test_ad_unary
[       OK ] test_unit_math_test_ad.test_ad_unary (3 ms)
[ RUN      ] test_unit_math_test_ad.test_ad_compound
./test/unit/math/expect_near_rel.hpp:33: Failure
The difference between x1 and x2 is 0.18168221099616086, which exceeds tol_val, where
x1 evaluates to 0.18168221099616086,
x2 evaluates to 4.9053545536249167e-310, and
tol_val evaluates to 9.0841105498080429e-12.
expect_near_rel_finite in: expect_near_rel; requite items x1[i] = x2[i]: expect_ad_helper

Segmentation fault (core dumped)
./test/unit/math/test_ad_test --gtest_output="xml:./test/unit/math/test_ad_test.xml" failed
```

This happens for the few functions I've ran (you can try it with `columns_dot_product`) as well.

@bbbales2 said this has something to do with `eval()` functions existing in `stan::math` and `stan::test::internal` but I tried replacing the calls explicitly with both and had no dice. Also it may just be my laptop but trying to debug this on gdb just runs forever. 

## Expected Output

compound test passes

#### Current Version:
v3.3.0

**Comment by SteveBronder** [comment]
Also if you pull out the actual values everything seems fine so I think this is just something in the test suite

**Comment by bbbales2** [comment]
I retract my previous statement about the two evals in `stan::test::internal` and `stan::math`. Not sure the difference matters.

Changing the test to this make stuff work though:

```cpp
auto f = [](const auto& x) {
  return (stan::math::softmax(x) + stan::math::softmax(x)).eval();
};
```

**Comment by t4c1** [comment]
The issue here is that each softmax call returns a matrix. These two matrices are than used in addition, which takes the arguments by reference. `g` returns auto, so the addition pbject is returned, not evaluated yet. When `g` returns the temporary matrices get deleted. When `expect_ad` evaluates the returned expression that evaluation references temporary matrices, that were already deleted and everything blows up.

If you really want to return expression you need to use `Holder` to extend the lifetime of the temporaries.

**Comment by bbbales2** [comment]
Okay so in effect the softmaxes don't matter and this code:

```cpp
auto f = [](const auto& x) {
  return stan::math::softmax(x) + stan::math::softmax(x);
};
```

Turns into:

```cpp
auto f = [](const auto& x) {
  return H + K;
};
```

where H and K are two matrices. f now returns an expression for the sum of H and K, but H and K get deleted after the return statement is evaluated (they're just temporaries)?

**Comment by SteveBronder** [comment]
Ahhh icic thanks for clearing that up! I'll close this since this is not an issue with the testing suite
