### ISSUE TITLE
namespace for apply in adj_jac_apply

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#2059]
## Description

@JamesYang007 reports in [their own repo readme](https://github.com/JamesYang007/ADBenchmark)) that there is an issue with `math/stan/math/rev/functor/adj_jac_apply.hpp` on line 513 and suggests adding a `stan::math::` qualifier to the use of `apply` to avoid conflict with C++17.

## Expected Output

Compilation in C++17 on GCC 10 without having to hand tweak the code. 

#### Current Version:
v3.3.0

**Comment by SteveBronder** [comment]
idt this is an us thing because I compile with c++17 on gcc-10 pretty regularly, it sounds somewhere in the benchmarks someone imports all of std with a (`using namespace std`). If we do this then we should do it for anything we've back-ported from C++17

**Comment by JamesYang007** [comment]
Ah it's very possible one of the other third-party libraries I'm benchmarking with does that.

**Comment by rok-cesnovar** [comment]
adj_jac_apply was removed so we can close this.
