### ISSUE TITLE
Replace top-level 'using' with localized versions

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/math#207]
Following Bob and Daniel's suggestion to remove namespace-level includes:
- [x] scrape for top-level 'using' statements with:  grep -R 'using' --before-context=5 --after-context=5 ./stan/math | grep 'namespace' --after-context=7 > /tmp/stray-using.txt
- [x] for each file:
  - [x] remove namespace-level 'using' statements
  - [x] replace function level 'using' when name is used two or more times.
  - [x] otherwise explicitly specify namespace.
- [x] pass all math tests

**Comment by betanalpha** [comment]
If we’re good enough on the indentation you might also want to scrape
with grep ‘^    using’ to catch using statements in the second namespace.
