### ISSUE TITLE
deprecate log_determinant_ldlt

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#2071]
## Description

Is there any reason to not deprecate `log_determinant_ldlt`?

`log_determinant_spd` uses an ldlt decomposition internally anyway (https://github.com/stan-dev/math/blob/develop/stan/math/rev/fun/log_determinant_spd.hpp#L32) and neither is exposed at Stan interface level (https://mc-stan.org/docs/2_24/functions-reference/linear-algebra-functions-and-solvers.html).

@bgoodri 

#### Current Version:
v3.3.0

**Comment by bgoodri** [comment]
Go ahead.

**Comment by bbbales2** [comment]
Ah, I misunderstood what it does. It accepts LDLT_factor objects so it's something different. I'm gonna leave it.
