### ISSUE TITLE
Who is yashikno?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2077]
## Description

Sorry for the silly Q but is @yashikno a jenkins bot to merge develop to branches that need it? I see them making merge commits like 6643736c58b66afca22840363dad305a9f11f1d5 . I assume this is a bot to update branches automajically but wanted to make a quick sanity check

#### Current Version:
v3.3.0

**Comment by syclik** [comment]
No idea. It's weird because that activity isn't listed on the user page.

(It's not a silly Q.)

**Comment by rok-cesnovar** [comment]
I also wondered that but never bothered to ask :)

**Comment by SteveBronder** [comment]
Looking at their commit history it's all just merge commits

https://github.com/stan-dev/math/commits?author=yashikno

It looks like it's a bot, @syclik do they have any level of privileges? I think they would need to be a maintainer in order to commit to someones branch

It seems like in other repos they've made meaningful commits in the past so I'm a little confused lol

**Comment by syclik** [comment]
Maybe it's a GitHub bug?

Our log commits show this:
![image](https://user-images.githubusercontent.com/425751/92808634-e9fd9280-f389-11ea-9f26-1d0c2bcd6118.png)

It's our Jenkins bot. Maybe there's a key collision with the bot account and a different account and that's why we're seeing this? Or perhaps there's a weird email lookup going on?

**Comment by syclik** [comment]
I sent a note to GitHub support. I'll report back when I hear back.

**Comment by syclik** [comment]
I got a note back. It's as I suspected: it's due to the email address that's in the git commit. Full details here: https://support.github.com/ticket/personal/0/830278 (I don't know if everyone can see this.)

There are a couple links Peter from support sent:
- https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user
- https://help.github.com/articles/changing-author-info

At the very least, we should change the bot's information for future commits.

**Comment by SteveBronder** [comment]
Cool cool cool what email should we point Jenkins to? Then I think this can close

**Comment by rok-cesnovar** [comment]
The e-mail for the Stan buildbot is stan-buildbot at googlegroups. I think we can use the same one.

**Comment by syclik** [comment]
Is that the outgoing email? If it is, then use that one. (It could be
mc.stanislaw@gmail.com if not.)

**Comment by rok-cesnovar** [comment]
I am not sure where this error is. If we look here: https://github.com/stan-dev/math/blob/develop/Jenkinsfile#L98, the email is set. 

@serban-nicusor-toptal would you know where the "Jenkins" user with the email nobody@nowhere is used? The user "Stan Jenkins" is fine, the one that just says "Jenkins" should also have the email set.

**Comment by syclik** [comment]
I would guess it’s the git config setting for email address on the machine.

**Comment by serban-nicusor-toptal** [comment]
Hey, I've checked on each machine and all of them have:
```
:~$ git config --list
user.email=mc.stanislaw@gmail.com
user.name=Stan Jenkins
```
Plus on the math job we enforce the user and email before every push.
```
git config --global user.email "mc.stanislaw@gmail.com"
git config --global user.name "Stan Jenkins"
```
It also doesn't match any of the commit message we use in the math pipeline ( [1](https://github.com/stan-dev/math/blob/develop/Jenkinsfile#L421), [2](https://github.com/stan-dev/math/blob/develop/Jenkinsfile#L101) ) example of a [commit](https://github.com/stan-dev/math/commits?author=stan-buildbot) from Jenkins.

I'll try to track down what is triggering that and where is it running. I took a look into our jenkins users and jobs and I didn't find anything related to that username/email.

**Comment by syclik** [comment]
Any luck? Yes, it's weird. Hopefully no one is rewriting history on these commits. I'm just going to guess that it has to do with some weird config.

**Comment by serban-nicusor-toptal** [comment]
Hey, from my part no. I've checked Jenkins and most of our git repositories that are tied to Jenkins, didn't find any reference in the jobs/configs to `nobody@nowhere` or `yashinko`.

**Comment by SteveBronder** [comment]
I think we can close this now
