### ISSUE TITLE
Using fixed-size Eigen types

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#2078]
## Description
It's generally mentioned in the Eigen doc that using fixed-size Eigen types for smaller objects will generally be more performant (mentioned [here](https://eigen.tuxfamily.org/dox/group__TutorialMatrixClass.html#title8) and [here](http://tudat.tudelft.nl/tutorials/basics/externalLibraries/eigen.html#fixed-size-vs-dynamic-size)), since the fixed-size matrix gets allocated on the stack and can be explicitly unrolled.

Where the dynamically-sized matrix would be declared as:
```
Eigen::Matrix<double, -1, -1> mat(4,4);
```
The fixed-size matrix is declared as:
```
Eigen::Matrix<double, 4, 4> mat;
```

However, given the templated nature of Stan, it's hard to know in advance whether a matrix should be instantiated as fixed- or dynamic-size. To get around this, we could create a new typedef that instantiates to fixed or dynamic, depending on the dimension size:
```
template <int D>
struct dim {
    enum { value = (D > 4 ? Eigen::Dynamic : D) };
};

template <typename T, int R, int C>
using stan_matrix = Eigen::Matrix<T, dim<R>::value, dim<C>::value>;
```

But I might be misunderstanding things here. @t4c1 does this make sense?

#### Current Version:
v3.3.0

**Comment by SteveBronder** [comment]
I think most of the math library can support fixed size matrices now? Feel free to open again if false
