### ISSUE TITLE
Make apply_vector_unary `var<mat>` friendly

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#2098]
## Description

`apply_vector_unary` does not currently work with `var<mat>` or `std::vector<var<mat>>` arguments.

The two functions of concern are the reverse mode specializations of `log_sum_exp` and `log_softmax`.

The hidden extra piece of this is that we also need the test framework to be able to test `std::vector<var<mat>>` types (it does not do this currently).

I think an appropriate implementation of log_softmax is (based off the implementation [here](https://github.com/stan-dev/math/blob/6b3495cf9ada9b38e0199057446a1df3afcc1caa/stan/math/rev/fun/log_softmax.hpp)):
```cpp
template <typename T,
          require_any_t<conjunction<is_std_vector<T>,
                                    is_var<scalar_type_t<T>>>,
                        is_rev_matrix<T>>* = nullptr>
inline auto log_softmax(const T& x) {
  return apply_vector_unary<ref_type_t<T>>::apply(
      to_ref(x), [](const auto& alpha) {
        check_nonzero_size("log_softmax", "alpha", alpha);

        const auto& alpha_col = as_column_vector_or_scalar(alpha);
        const auto& alpha_val = to_ref(value_of(alpha_col));
        const auto& theta = to_ref(alpha_val.array() - alpha_val.maxCoeff());
        arena_t<Eigen::VectorXd> res_val
            = theta.array() - log(theta.exp().sum());

        arena_t<plain_type_t<decltype(alpha)>> res = res_val;
        auto alpha_arena = to_arena(alpha_col);

        reverse_pass_callback([alpha_arena, res, res_val]() mutable {
          const auto& res_adj = to_ref(res.adj());
          alpha_arena.adj()
              += res_adj - (res_adj.sum() * res_val.array().exp()).matrix();
        });

        return plain_type_t<decltype(alpha)>(res);
      });
}
```

To implement tests for this, add in addition to every line like this in `test/unit/math/mix/fun/log_softmax_test.cpp`:
```
stan::test::expect_ad(f, x0);
```

an additional test line like this:

```
stan::test::expect_ad_matvar(f, x0);
```

#### Current Version:
v3.3.0

**Comment by bbbales2** [comment]
@andrjohns any chance I could recruit you for this?

**Comment by bbbales2** [comment]
I can help with the tests if you want to update the `apply_vector_unary` thing.

**Comment by andrjohns** [comment]
Yeah for sure, I'll take a run at this on the weekend

**Comment by SteveBronder** [comment]
Wanted to make sure this was clear, for `apply_vector_unary<var<matrix>>` I think we only want to apply over the vector while the `var<matrix>` should not be looped into

**Comment by SteveBronder** [comment]
i.e. it's more like a `vector<var>` than a `vector<matrix>`

**Comment by andrjohns** [comment]
Thanks Steve! @bbbales2 I've got this working with ```var<mat>``` types and passing tests. Lemme know if it starts failing with ```std::vector<var<mat>>``` types in the testing.

Branch: https://github.com/stan-dev/math/compare/develop...andrjohns:feature/issue-2098-vec_unary_var_mat
