### ISSUE TITLE
Duplicated non-empty checks

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2125]
We have two equivalent checks that check whether the container has no elements:

- check_nonzero_size https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_nonzero_size.hpp
- check_nonempty https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_nonempty.hpp

Of the two, the latter can easily be removed because:
- it is not used anywhere
- it has no tests
- only works for `Eigen::Matrix`

#### Current Version:
v3.3.0

**Comment by syclik** [comment]
Thanks! Just for a sanity check, it’s not used in Stan directly or generated by stanc?

**Comment by rok-cesnovar** [comment]
Yes, its only mentioned in https://github.com/stan-dev/math/blob/develop/stan/math/prim/err/check_nonempty.hpp and https://github.com/stan-dev/math/blob/develop/stan/math/prim/err.hpp

Not used in stanc.

**Comment by syclik** [comment]
Awesome! Thanks for checking and confirming!
