### ISSUE TITLE
Vectorise ordered_logistic_rng and categorical_rng

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#2132]
## Description

A request has come through [over on the forums](https://discourse.mc-stan.org/t/ordered-logistic-rng-vectorization/18446) to vectorise the ```ordered_logistic_rng``` function. ```categorical_rng``` was also incidentally mentioned, it's not vectorised either so might as well do that for consistency.

A (very rough untested) example below shows how we could just use the ```*_seq_view``` functions to implement this:
```
template <typename T_eta, typename T_c, class RNG,
          require_t<disjunction<is_vector<T_eta>, 
                                conjunction<is_std_vector<T_C>,
                                            is_vector<value_type_t<T_c>>>>>
inline std::vector<int> ordered_logistic_rng(const T_eta& eta, const T_c& c, RNG&) {
  scalar_seq_view<T_eta> eta_vec(eta);
  vector_seq_view<T_c> cut_vec(c);

  int ret_size = max_size(eta, c);

  std::vector<int> rng_return(ret_size);
  for (int i = 0; i < ret_size; ++i) {
    rng_return[i] = ordered_logistic_rng(eta_vec[i], cut_vec[i], rng);
  }

  return rng_return;
}
```

#### Current Version:
v3.3.0

**Comment by t4c1** [comment]
All the RNGs are actually implemented that way.

**Comment by andrjohns** [comment]
Huh, right you are. Well that keeps things simple for me at least!

**Comment by rok-cesnovar** [comment]
Closing in favor of the general RNG issue: https://github.com/stan-dev/math/issues/2658
