### ISSUE TITLE
Add OpenCL distributions

### ISSUE THREAD

**Issue by t4c1** [stan-dev/math#2152]
## Description

Add OpenCL implementations of distribution functions. Most of these can be implemented using kernel generator. Some might need kernel generator to support some new element-wise functions.

Since they are used most I will start with `lpdf`s and `lpmf`s, as those are most used. `cdf`s, `lcdf`s and `lccdf`s can wait.

## Example
```
matrix_cl<int> y;
matrix_cl<double> theta;
var lp  = bernoulli_lpmf(y, theta);
```

## Expected Output
Same as Eigen implementations, but faster.

#### Current Version:
v3.3.0

**Comment by wds15** [comment]
Will these be faster on the CPU as well?

**Comment by t4c1** [comment]
We will see. I expect most of them to be a tiny bit slower, but some to be faster.

**Comment by t4c1** [comment]
Now all simple to implement `lpmf` and `lpdf` functions are in. Remaining distribution functions will have to wait until I also add everything from `prim/fun` that is not too much work.

**Comment by t4c1** [comment]
Now we also have PRs open or merged for all `cdf`, `lccdf` and `lcdf` functions that were not too complicated to implement. I skipped some distributions that depend on functions that require 1000 lines of code or more (at least boost implementations are huge). If somebody volunteers to implement any of these functions in OpenCL or finds a significantly shorter implementation, I can implement the distributions depending on it. 

These functions and distribution are:
 - inc_beta: beta, beta_binomial, beta_proportion, binomial, neg_binomial, neg_binomial_2, student_t
 - gamma_p / gamma_q:  chi_square, gamma, inv_chi_square, inv_gamma, poisson, scaled_inv_chi_square
 - owens_t: skew_normal

**Comment by rok-cesnovar** [comment]
Cool! Thanks!!

I would say we close this issue once all the open PRs are merged and make a new one for those remaining (l)(c)cdfs (or edit the top-level comment to reflect this - though I think editing history is not ideal).
