### ISSUE TITLE
speedup reduce_sum

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#2165]
## Description

The current `reduce_sum` implementation can benefit from using the var's for the shared arguments more efficient in a way avoid too many copies.

## Example

Things should just run as before, just faster.

## Expected Output

Same as before.

#### Current Version:
v3.3.0

**Comment by rok-cesnovar** [comment]
@wds15 this one was closed with #2162 right?

**Comment by wds15** [comment]
Yeah, done that. Thanks.
