### ISSUE TITLE
test bernoulli_logit extreme values

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#218]
Make sure all branches in the internal logic for extreme values are returning correct values and gradients.  Should also test `binomial_logit`.

(context is that @bgoodri & @jgabry found instabilities with ADVI that went away with direct inv_logit call)

**Comment by bgoodri** [comment]
specifically it is the ll_bern_lp function in 
https://github.com/stan-dev/rstanarm/blob/master/exec/bernoulli.stan

**Comment by bob-carpenter** [comment]
Ben's function is no longer included in the file, so you need to track down this:

https://github.com/stan-dev/rstanarm/blob/master/inst/chunks/bernoulli_likelihoods.stan

to find the definition of `ll_bern_lp`:

```
real ll_bern_lp(vector eta0, vector eta1, int link, int[] N) {
    if (link < 1 || link > 5) 
      reject("Invalid link");
      
    if (link == 1) { // logit
      target += logistic_lccdf(eta0 | 0, 1);
      target += logistic_lcdf( eta1 | 0, 1);
    }
    else if (link == 2) {  // probit
      target += normal_lccdf(eta0 | 0, 1);
      target += normal_lcdf( eta1 | 0, 1);
    }
    else if (link == 3) {  // cauchit
      target += cauchy_lccdf(eta0 | 0, 1);
      target += cauchy_lcdf( eta1 | 0, 1);
    }
    else if(link == 4) {  // log
      target += log1m_exp(eta0);
      target += eta1;  // already in log form
    }
    else if(link == 5) {  // cloglog
      target += log1m_exp(-exp(eta1));
      target += -exp(eta0);
    }
    return target();
  }
```

But I don't see the relevance---it doesn't call any of our functions.  That's an odd function in that it works through side effects on target (which may already be nonzero when it's called?) and then returns the target value.  Not sure why there's a return at all here.

**Comment by bob-carpenter** [comment]
I just ran a bunch of informal tests and everyting's fine with log odds as low as -10000 or as high as 10000.  If there's a specific problem someone has with a reproducible example, please reopen.
