### ISSUE TITLE
check_matching_dims with std::vector<Eigen>

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#2207]
I am trying to use the new offset & multiplier feature with nested vector in array data structures. The stanc3 compiler does indeed give me a C++ file, but then I get a compiler error.

Compiler error:

```
In file included from stan/src/stan/model/model_header.hpp:13:
/Users/sebi/work/cmdstan-2.25.0/stan/src/stan/model/model_base_crtp.hpp:191:50: error: no matching member function for call to 'log_prob'
    return static_cast<const M*>(this)->template log_prob<true, true>(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
../partial-warmup/poisson3.hpp:147:3: note: in instantiation of member function
      'stan::model::model_base_crtp<poisson3_model_namespace::poisson3_model>::log_prob_propto_jacobian' requested here
  ~poisson3_model() final { }
  ^
../partial-warmup/poisson3.hpp:491:14: note: candidate template ignored: substitution failure [with propto__ = true, jacobian__ = true, T__ = stan::math::var_value<double,
      void>]
  inline T__ log_prob(std::vector<T__>& params_r__,
             ^
../partial-warmup/poisson3.hpp:1021:15: note: candidate function template not viable: requires at most 2 arguments, but 3 were provided
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
              ^
12 errors generated.
make: *** [../partial-warmup/poisson3] Error 1
```

[poisson3_data_R.txt](https://github.com/stan-dev/stanc3/files/5572330/poisson3_data_R.txt)

[poisson3_stan.txt](https://github.com/stan-dev/stanc3/files/5569659/poisson3_stan.txt)

The problematic offset & multiplier is for `z_1`.

Thanks for looking into this!

(my ambition is to automate this stuff with brms... which could be a big deal possibly/maybe/hopefully)

**Comment by rok-cesnovar** [comment]
It also compiles if I replace the require here
https://github.com/stan-dev/math/blob/d47c331a693a3d5ebc4453360743b9353a8e3ed1/stan/math/prim/err/check_matching_dims.hpp#L26

to 
```cpp
template <typename T1, typename T2, require_all_std_vector_t<T1, T2>* = nullptr>
inline void check_matching_dims(const char* function, const char* name1,
                                const T1& y1, const char* name2, const T2& y2) {
```
Though I think makes `check_matching_dims` not work with scalars. Not a problem for this model but it possibly is a problem in general? Maybe?
