### ISSUE TITLE
Parallel automatic differentiation

### ISSUE THREAD

**Issue by ibab** [stan-dev/math#222]
Is there currently a way of performing automatic differentiatio in parallel?
Something like the following would be amazing:

```cpp
#include <stan/math.hpp>

int main() {

    stan::math::var result = 0;
    stan::math::var x = 3;

    #pragma omp declare reduction (+ : stan::math::var : omp_out += omp_in )
    #pragma omp parallel reduction(+ : result) shared(x)
    for (int i = 0; i < 10; i++) {
        result += x * x;
    }

    std::cout << result.val() << std::endl;
    result.grad();
    std::cout << x.adj() << std::endl;

    return 0;
}
```

But unfortunately, this fails with
```
*** Error in `./simple': free(): invalid next size (fast): 0x00007faa380008c0 ***
zsh: segmentation fault (core dumped)  ./simple
```
while the single-threaded version works.

**Comment by bob-carpenter** [comment]
No, the code has two serious race conditions on the global expression graph. 

But, if we could somehow factor the expression graph into independent subexpressions, we could build up in parallel and then lock on integration and we could evaluate the chain rule ("backprop") in parallel, too.  

It's on our radar, but we probably won't get to it for years unless we get someone eager to dive into the C++ who understands cross-platform parallel coding (C++11 would help a bit, I think).

We have much more hope that we can parallelize our matrix operations under the hood for parallelism speedups --- that's where much of the work is in complex models.

I'm trying to keep the issues to concrete tasks, not long-term to-do lists, so I'm going to close this issue.  I added a note to our long-term to-do list:  https://github.com/stan-dev/stan/wiki/Longer-Term-To-Do-List

**Comment by ibab** [comment]
Thanks for the detailed response.
Parallelizing reverse mode differentiation seems to be significantly more difficult than I thought.
