### ISSUE TITLE
MSVC 2015 Template Ctor Deduction Fail

### ISSUE THREAD

**Issue by ashmsuhsl** [stan-dev/math#225]
**cl version: 19.00.23506
stan version: 2.9.0**

Using a Stan model containing statements such as:

`sigmaCL ~ cauchy(0,2.5);`

and compiling a CmdStan executable with the generated hpp file produces:

> Error	C2664	'stan::VectorView<const T_y,true,false>::VectorView(stan::VectorView<const T_y,true,false> &&)': cannot convert argument 1 from 'const Eigen::Matrix<double,-1,1,0,-1,1>' to 'const double &'

In generated code, a typical statement giving rise to it is:

`lp_accum__.add(cauchy_log<propto__>(sigmaCL, 0, 2.5));`

In the Stan density function library code, lines such as this propagate the problem:

`VectorView<const T_y> y_vec(y);`

The workaround for my model was to add this:

```
#ifdef  _MSC_VER
		template <int R, int C, int O, int MR, int MC>
		explicit VectorView(const Eigen::Matrix<scalar_t, R, C, O, MR, MC>& m) : x_(&m(0)) { }
#endif
```

at line 90 in VectorView.hpp.

I'm afraid my C++ skills are rusty by more than a decade, and so my knowledge of explicit ctors, variadic templates, etc. is non-existent. I can't tell whether this is a defect in MSVC, Stan, neither, or both.

**Comment by bob-carpenter** [comment]
Thanks for the report.  Any idea why the three extra template
parameters for matrix make a difference?  And that error report
is perplexing as there's no && anywhere in stan/math/prim/scal/meta/VectorView.hpp
and they don't give you the template instantiation for T.

This is definitely only a problem for MSVC.

If sigmaCL is a matrix, you'll get a parser error.

If sigmaCL is a vector or row vector, it works fine
elsewhere.

I could compile and run this model.

```
parameters {
  row_vector[3] u;
  vector[3] v;
}
model {
  u ~ cauchy(0, 25);
  v ~ cauchy(0, 25);
}
```

WARNING:  you don't want to run the above model because the posterior
means for u and v don't exist so convergence monitoring and other
expectation calculations will fail (this is just an issue with the Cauchy,
not with Stan's sampling).

**Comment by ashmsuhsl** [comment]
That was a good spot (plus I should have read the message more carefully!) of MSVC's use of an Rvalue reference and it might be at issue. See this for a similar error:

http://stackoverflow.com/questions/4033964/c0x-rvalue-reference-template-argument-deduction

Again, Rvalue references and std::forward are new to me and I'm unsure whether this is applicable here. Without a few month's worth of intense refresher in the latest C++ developments, I'm out of my depth.

In my model, both normal_log and cauchy_log give rise to the issue. Some parameters are declared as `vector<lower=0>[1]` and some as `real<lower=lower,upper=upper>`. When I use Rtools for the compilation, the model compiles without issue.

Here's the full text of one of the errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'stan::VectorView<const T_y,true,false>::VectorView(stan::VectorView<const T_y,true,false> &&)': cannot convert argument 1 from 'const Eigen::Matrix<double,-1,1,0,-1,1>' to 'const double &'	pkpd-nuts	C:\source\3rd\cmdstan-2.9.0\stan_2.9.0\lib\stan_math_2.9.0\stan\math\prim\scal\prob\cauchy_log.hpp	82	
```

**Comment by bob-carpenter** [comment]
Thanks for digging deeper.  No idea how to fix this.  Maybe
someone who knows C++ and MSVC 2015 quirks can help out.

**Comment by bob-carpenter** [comment]
@ariddell  Any idea if this is fixed and being tested in the tests you're running for MSVC?

**Comment by ariddell** [comment]
I'm not sure what's going on here either. PyStan's test suite gets run on Windows -- I believe it's just MSVC 2015 (no older versions).

**Comment by bob-carpenter** [comment]
Should be OK then.  Or we'll find out when we get more tests.  Thanks.

**Comment by bob-carpenter** [comment]
As of Stan 2.11 all of these constructors are explicit, so I'm going to close.
