### ISSUE TITLE
`log_softmax` of a row vector returns a vector

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#2269]
## Description

When I do `log_softmax` of a row vector I get back a vector.

This:

```cpp
TEST(MathRev, row_vector_log_softmax) {
  Eigen::RowVectorXd r(3);

  r << 1.0, 2.0, 3.0;

  stan::math::promote_scalar_t<stan::math::var, Eigen::RowVectorXd> rv(r);

  std::cout << stan::math::test::type_name<decltype(stan::math::log_softmax(rv).eval())>() << std::endl;
}
```

prints:

```cpp
stan::math::test::type_name() [Arg = const Eigen::Matrix<stan::math::var_value<double, void>, -1, 1, 0, -1, 1> &
```

I ran into this testing against the `varmat` implementation (which returns a row vector for a row vector input).

I know that a lot of our vectorization stuff converts to a column vector internally, so I'm not sure if this is intentional or a bug.

So that's my question, intentional or a bug?

#### Current Version:
v3.4.0

**Comment by bbbales2** [comment]
Whoops, I shoulda kept reading the code, this looks like a bug: https://github.com/stan-dev/math/blob/develop/stan/math/rev/fun/log_softmax.hpp#L83 . I'll fix this in my pull.

**Comment by rok-cesnovar** [comment]
The only expose log_softmax signature is 

`vector log_softmax(vector)`

so I would say that is a bug that never surfaced.

**Comment by rok-cesnovar** [comment]
This was addressed at some point. The following test passes:

```cpp
TEST(MathMatrixPrimMat, log_softmax_test) {
  using stan::math::log_softmax;
  stan::math::vector_d v0(2);
  v0 << -1.0, 1.0;
  stan::math::vector_d res0 = log_softmax(v0);
  stan::math::row_vector_d v1(2);
  v1 << -1.0, 1.0;
  stan::math::row_vector_d res1 = log_softmax(v1);
  stan::math::vector_v v2(2);
  v2 << -1.0, 1.0;
  stan::math::vector_v res2 = log_softmax(v2);
  stan::math::row_vector_v v3(2);
  v3 << -1.0, 1.0;
  stan::math::row_vector_v res3 = log_softmax(v3);
}
```
