### ISSUE TITLE
Bound constrain behavior at infinity

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#2291]
## Description

Right now with lb_constrain when the lower constraint is set to negative infinity, we switch in an unconstrained transform.

I don't think this behavior is correct since we allow the lower bounds to change.

The transform for lower bound > -infinity is:
```
c(u) = exp(u) + l;
```

for constrained variable `c`, unconstrained variable `u` and lower bound `l`.

The transform when `l == -infty` is:

```
c(u) = u;
```

If we think of `c` as a function of `u`, I don't see how as we take `l -> -infinity` the first function turns in to the second. These are two different transformations, and I can see this trick working if the constraints are constant, but not since we allow them to change.

The jacobians would be similarly weird.

@bob-carpenter, @bgoodri what do you think?

Code is [here](https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/lb_constrain.hpp#L35)

#### Current Version:
v3.4.0

**Comment by SteveBronder** [comment]
If it's for user's that utilize these methods I wonder if we could/should write something like `lb_constrain_finite()` etc. that does not do these checks. Then Stan / stanc3 can use those

**Comment by bbbales2** [comment]
We've decided to keep this behavior for now. I'd still like to remove it in the future (if there becomes a way to optionally define contraints, or parameters, or some way around this)
