### ISSUE TITLE
Template aliases for var_value matrices

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2298]
## Description

To simplify Stanc3 code gen for varmat we need additional template aliases. Specifically when generating the code in `log_prob<T__>`
we need a template alias that would create `Eigen::VectorXd` (a vector of doubles) in case T__ is double, and `var_value<Eigen::VectorXd>` when we call `log_prob<var>`.

Something like this for `vector`:

```cpp
template <typename T__>
using var_value_vector = std::conditional_t<
                     stan::is_var<T__>::value,
                     stan::math::var_value<Eigen::VectorXd>,
                     Eigen::VectorXd>;
```

But we also need it for row_vector and matrix.

#### Current Version:
v3.4.0

**Comment by SteveBronder** [comment]
Would you mind if it's a bit wordier like

```
template <typename T__>
using conditional_var_vector = std::conditional_t<
                     stan::is_var<T__>::value,
                     stan::math::var_value<Eigen::VectorXd>,
                     Eigen::VectorXd>;
```

We probably want `var_value_vector` to actually be a `var_value<Eigen::VectorXd>`

**Comment by rok-cesnovar** [comment]
Yes definitely!
