### ISSUE TITLE
benchmark sparse vs. dense multiplication

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/math#231]
rstanarm has an [issue](https://github.com/stan-dev/rstanarm/issues/76) for switching dense/sparse parameterization based on characteristics of the input matrix but we never did a detailed comparison.  Compare sparse/dense multiplication speed for:

- [ ] sparsity %
- [ ] row vs column sparsity
- [ ] 

The real interest is in when the two become interchangeable in terms of performance.

**Comment by bob-carpenter** [comment]
This isn't an issue for stan-dev/math as it's not something that would go into the library, but be external.
