### ISSUE TITLE
Add lambertw function from Boost

### ISSUE THREAD

**Issue by spinkney** [stan-dev/math#2310]
First issue with adding the lambert W stuff discussed at [adding lambert w transforms to stan](https://discourse.mc-stan.org/t/adding-lambert-w-transforms-to-stan/13906).

We can wrap the lambert w function from boost at 

https://github.com/boostorg/math/blob/develop/include/boost/math/special_functions/lambert_w.hpp

**Comment by SteveBronder** [comment]
This was done in #1182! It should be exposed all the way up in Stan as well. Though it could be good to add specific matrix specializations then this could also use the new `var<matrix>` type


I think all we would need to do is make [this](https://github.com/stan-dev/math/pull/1882/files#diff-3dc5ecc5549a27a0e9ffc4cc8a30f17eda11bde796111ae97ec48579d412e36aR80) into `require_std_vector_t<>` so it works on containers. Then write a version accepting matrices [here](https://github.com/stan-dev/math/pull/1882/files#diff-be3183c655994e179d1875294bce988ebf34db4155280b6b76a5cee2afbc4cab) that uses `reverse_pass_callback` to do all the adjoints at once.

**Comment by spinkney** [comment]
The link for #1182 takes me to issue #50 boolean functions and I started to think I really don't understand lambert W. Anyway, the other links you supplied do take me to the right PR and that's awesome!!

**Comment by rok-cesnovar** [comment]
Yeah its #1882 :)

**Comment by SteveBronder** [comment]
lol whups srry!

**Comment by SteveBronder** [comment]
But yeah if you want to start writing this stuff up in Stan first you should have everything you need! If not, then we will add stuff!

**Comment by spinkney** [comment]
Like @SteveBronder said, this is already implemented!
