### ISSUE TITLE
poisson_binomial is missing support for deprecated suffices

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2317]
## Description

The poisson_binomial distribution currently has Stan Math support for 

poisson_binomial_lpmf
poisson_binomial_lccdf
poisson_binomial_lcdf
poisson_binomial_rng

but before we can expose it in Stanc3 we need to add support for the deprecated suffices as well:

poisson_binomial_log
poisson_binomial_ccdf_log
poisson_binomial_cdf_log

This should just be  calls the non-deprecated suffix version. See https://github.com/stan-dev/math/blob/develop/stan/math/prim/prob/poisson_ccdf_log.hpp

#### Current Version:
v3.4.0

**Comment by dirmeier** [comment]
Ciao Rok,
my bad, wasn't aware that those are still needed. I'll add them tomorrow! 

Cheers,
S

**Comment by rok-cesnovar** [comment]
Hey Simon, no need to apologize! 

If you add them tomorrow I can make sure they get added to stanc3 for the release. Thanks!
