### ISSUE TITLE
Feature freeze for Stan 2.26 

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2327]
The feature freeze is now in effect for the Stan/Cmdstan 2.26 release and only bug-fixes should be merged until this issue is closed. 

There is an outstanding question whether we should bump the major version of Math to 4.0 due to the changes in the LDLT_factor interface (https://github.com/stan-dev/math/pull/2315#issuecomment-761581647) - changes in this PR: https://github.com/stan-dev/math/pull/2266

I dont mind bumping the major version for Math so if those more familiar with the changes suggest a major bump I think we should do it. We have a week to decide.

Any thoughts @syclik @bbbales2 @wds15 @t4c1 @SteveBronder @yizhang-yiz et al?

cc: @serban-nicusor-toptal 

Thanks!

**Comment by bbbales2** [comment]
Bump bump!

**Comment by syclik** [comment]
+1 for the bump! (Now that versions have drifted, we could follow semantic
versioning without having to worry about special cases.)

**Comment by rok-cesnovar** [comment]
Ok cool. If no one comes forward with some valid reasoning why not to bump, the release version should be 4.0 for Stan Math. 

Stan/CmdStan proceed as normal (2.26).
