### ISSUE TITLE
fix costs for Eigen NumTraits

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#233]
We need to specialize traits for sizes and costs of operations.  As is, they're all wrong for all of our autodiff types. See:

http://eigen.tuxfamily.org/dox/structEigen_1_1NumTraits.html

for what they should be.

Right now, there's a rather random set of includes of `NumTraits`:

```
~/cmdstan/stan/lib/stan_math(feature/issue-202-vectorize-all)$ grep -R NumTraits stan/
stan//math/fwd/mat/fun/Eigen_NumTraits.hpp:  struct NumTraits<stan::math::fvar<T> > {
stan//math/fwd/mat/fun/Eigen_NumTraits.hpp:      return 1e-12;  // copied from NumTraits.h values for double
stan//math/fwd/mat/fun/typedefs.hpp:#include <stan/math/fwd/mat/fun/Eigen_NumTraits.hpp>
stan//math/mix/mat/fun/typedefs.hpp:#include <stan/math/fwd/mat/fun/Eigen_NumTraits.hpp>
stan//math/prim/mat/fun/Eigen.hpp:#include <Eigen/src/Core/NumTraits.h>
stan//math/rev/core/matrix_vari.hpp:#include <stan/math/rev/mat/fun/Eigen_NumTraits.hpp>
stan//math/rev/mat/fun/Eigen_NumTraits.hpp:  struct NumTraits<stan::math::var> {
stan//math/rev/mat/fun/Eigen_NumTraits.hpp:      return 1e-12;  // copied from NumTraits.h values for double
stan//math/rev/mat/fun/grad.hpp:#include <stan/math/rev/mat/fun/Eigen_NumTraits.hpp>
stan//math/rev/mat/fun/multiply.hpp:#include <stan/math/rev/mat/fun/Eigen_NumTraits.hpp>
stan//math/rev/mat/fun/tcrossprod.hpp:#include <stan/math/rev/mat/fun/Eigen_NumTraits.hpp>
stan//math.hpp:#include <stan/math/rev/mat/fun/Eigen_NumTraits.hpp>
```

We can deal with the include order issues by brute force (rather than by converting functions to struct calls) by breaking out includes for product of

```
{ prim, rev, fwd, mix } x { scal, arr, mat }
```

The current `stan/math.hpp` is `(rev, mat)`.

**Comment by syclik** [comment]
@bob-carpenter, I'm working through this now. It'll simplify some of the work we need to do for #187.

For `stan::math::var` the `NumTraits` specialization gets much cleaner where the only thing we need to do are plug in values for:
- `ReadCost`
- `AddCost`
- `MulCost`

For double, each of those are defined as 1.
Does this seem right for `stan::math::var`?
 - `ReadCost = 2 * NumTraits<double>::ReadCost`  (I'm not sure if this is higher)
 - `AddCost = 2 * NumTraits<double>::AddCost`
 - `MulCost = 3 * NumTraits<double>::MulCost + 2 * NumTraits<double>::AddCost`

I feel like I'm missing something. I'll need to do the same for `fvar`.

**Comment by bob-carpenter** [comment]
Is there an explanation somewhere of what these are
supposed to be?  I'm not sure what ReadCost is.

For var, the costs are significantly higher because
there are memory allocation costs.  I don't think we
need to count the reverse mode interpreted steps, 
and the forward mode costs are just like those for double:

* add just does a single addition going forward
* multiply just does a single multiplication in forward 

For fvar<double>, I get 3 multiply and one add.

  (a * b) = a * b
  (a * b)' = a' * b + a * b'

For addition, I get two adds:

  (a + b) = a + b
  (a + b)' = a' + b'

Then for fvar<var> it'd be the same again, but for fvar<fvar<var>> it's
a lot more involved.

- Bob

**Comment by syclik** [comment]
Thanks!

The explanation is in the Eigen doc: http://eigen.tuxfamily.org/dox/structEigen_1_1NumTraits.html

I'm quoting the relevant part here:

> Enum values ReadCost, AddCost and MulCost representing a rough estimate of the number of CPU cycles needed to by move / add / mul instructions respectively, assuming the data is already stored in CPU registers. Stay vague here. No need to do architecture-specific stuff.

So, rough estimate of CPU cycles needed to move a `stan::math::var`.

For `fvar<double>`, I'm guessing it should be something like:
- `ReadCost = ??`
- `AddCost = 2 * NumTraits<double>::AddCost`
- `MulCost = 3 * NumTraits<double>::MulCost + NumTraits<double>::AddCost`

I'm guessing for `fvar<var>`, we can just replace the template type of `double` with `var`, so:
- `ReadCost = ??`
- `AddCost = 2 * NumTraits<var>::AddCost`
- `MulCost = 3 * NumTraits<var>::MulCost + NumTraits<var>::AddCost`

And `fvar<fvar<var>>`, I'm guessing we can just the `var` with `fvar<var>` and it should work out?

I think the last question here is how much the `ReadCost` is.

**Comment by bob-carpenter** [comment]
What is a move in this context?  Is 3.3 going to depend on
the C++11 move semantics?  Or is it just a copy constructor?
If it's copy, both var and fvar<T> for any T is just twice
the cost to copy a double (or pointer).

**Comment by syclik** [comment]
I don't think this is dependent on C++11. Maybe just a copy constructor. I think it's used to do calculations on unrolling loops.
