### ISSUE TITLE
Model failing to compile in CmdStan 2.25

### ISSUE THREAD

**Issue by juandiazmart** [stan-dev/math#2330]
I am trying to compile a Stan file in CmdStan 2.25. It works perfectly until it hits "Compiling pre-compiled header ". 

`error: ‘profile_map’ in namespace ‘stan::math’ does not name a type
 stan::math::profile_map& get_stan_profile_data() {
             ^
cc1plus: warning: unrecognized command line option ‘-Wno-ignored-attributes’
cc1plus: warning: unrecognized command line option ‘-Wno-ignored-attributes’`

The same model is compiled without any issues in cmdstanR.

**Comment by rok-cesnovar** [comment]
Hi, do you mean that you are using a cmdstan clone?

In that case make sure you have updated the submodules as well.
Run this in CmdStan folder:
```
make clean-all
git checkout develop
git pull
make stan-update
make build -j4
```
and then try again.

**Comment by juandiazmart** [comment]
It worked.

Thank you very much
