### ISSUE TITLE
Add boost::odeint's Cash-Karp integrator

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/math#2334]
## Description
This issue is spawned out of the benchmark in #2326 , where additional integrators from odeint & arkode was evaluated. In particular, `boost::odeint`'s Cash-Karp method(`ckrk`) that has better stability shows to be an potential addition to our integrators.

## Example
WIP branch: `cash_karp_ckrk`.

- further benchmark based  on runing 4-chain sampling using 10 random seeds in each model.
####  lokta-volterror
In this model `ckrk` has 4 chains "stuck", indicated by much greater # of leapfrogs. Plots below excludes those chains.
![summary_lv_model](https://user-images.githubusercontent.com/33104304/105651750-8bced900-5e6c-11eb-9608-5523d2e9d575.png)
#### SIR
![summary_sir_model](https://user-images.githubusercontent.com/33104304/105651760-8d989c80-5e6c-11eb-88ed-c43987e9d259.png)
#### mildly-stiff Van del Pol oscillator
![summary_vdp_model](https://user-images.githubusercontent.com/33104304/105651762-8ec9c980-5e6c-11eb-8cc9-7c7ccbf3d737.png)

- describe the expected behavior if the feature exists
Same as `rk45`: `ode_ckrk(...)` with implementation based on boost::odeint.

## Expected Output
Same integrator output but potentially more efficient when parameter sampled causes the system to be stability-constrained.

#### Current Version:
v3.4.0

@bbbales2 @wds15

**Comment by bbbales2** [comment]
That seems better. What is different between the two? Is this a choice that someone could make or is it always guess and check?

**Comment by yizhang-yiz** [comment]
@bbbales2 
`ckrk` has a greater stability region than `rk45` so it's more stable, and it's designed for problems with large derivatives and/or rapid oscillations. So it suits better for ODEs that could be sampled into mild stiffness(the SIR & Van del Pol example above). For non-stiff problem it could cause slow down by trying too hard on parameters that could be right-out rejected(the Lotka-Volterra example).
