### ISSUE TITLE
Math docs are down?

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2349]
## Description

Going to 

https://mc-stan.org/math/

Should take us to the math docs but it looks like the link doesn't exist anymore?

#### Current Version:
v4.0.0

**Comment by syclik** [comment]
I see it too... is it a dns thing?

**Comment by rok-cesnovar** [comment]
Maybe the website didnt build, though I guess then doxygen would fail as well.

**Comment by rok-cesnovar** [comment]
Back online. Closing.
