### ISSUE TITLE
OpenCL runtime error with inv_gamma_lpdf

### ISSUE THREAD

**Issue by rmcminds** [stan-dev/math#2351]
A script that compiles and runs fine in serial is compiled fine with opencl, but throws this error at runtime:

> Unrecoverable error evaluating the log probability at the initial value.
> Exception: binary_operator+: Rows of a (2861) and rows of b (1) must match in size (in 'file.stan', line 285, column 8 to column 86)
> Exception: binary_operator+: Rows of a (2861) and rows of b (1) must match in size (in 'file.stan', line 285, column 8 to column 86)

At issue is the following signature:

`lp += inv_gamma_lpdf(row_vector | scalar, scalar);`

I can get the script to run with opencl using this modified version:

`lp += inv_gamma_lpdf(to_vector(row_vector) | rep_vector(scalar, size(row_vector)), rep_vector(scalar, size(row_vector)));`

Version 4.0.0

**Comment by t4c1** [comment]
I can confirm the bug. Actually we forgot to test OpenCL implementations with `row_vector`s. So they won't work with combinations of `vector` and `row_vector` arguments. Some of them, `inv_gamma_lpdf` included, won't even work wit combinations of `row_vector` and `scalar` arguments. Ouch.

I will try to fix that as soon as possible. Meanwhile the simplest workaround that should work is to call `inv_gamma_lpdf(to_vector(row_vector) | scalar, scalar)`.
