### ISSUE TITLE
Create top-level includes

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#236]
From Bob:
We can deal with the include order issues by brute force (rather than by converting functions to struct calls) by breaking out includes for product of
    
 ```
{ prim, rev, fwd, mix } x { scal, arr, mat }
```

The current `stan/math.hpp` is `(rev, mat)`.

**Comment by syclik** [comment]
Bob, what should we call the 12 files?

**Comment by syclik** [comment]
Does something like this work? stan/math_prim_scal.hpp

Or stan/math/prim_scal.hpp?

**Comment by bob-carpenter** [comment]
Yes, I think that would be good.

All of our errors turned out to be due to something else, though,
so this isn't a high priority, at least for me.

**Comment by syclik** [comment]
I'll just go out and fix it. It should have been fixed months ago.

Have a preference? If not, I'll do the second and we can change it later if
necessary.


Daniel

**Comment by bob-carpenter** [comment]
I prefer paths to long names with underscores.

- Bob
