### ISSUE TITLE
Issues with Integrations tests

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2361]
@serban-nicusor-toptal in the last few days the Integration tests keep getting interrupted: https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/detail/downstream_tests/2626/pipeline

Also see https://jenkins.mc-stan.org/blue/organizations/jenkins/Stan/activity

Is there something we can do about this? I understand this way of using AWS is cheaper and I dont mind the occasional kick out of the instances, but it seems like maybe 1 out of 10 runs finishes.

**Comment by serban-nicusor-toptal** [comment]
Hey, that looks quite bad. It started lately so I assume lots of usage and we may get outbid. May it be possible to get stuck during integrations on linux ? This can happen if RAM fills up but I think min. 60 GB should be enough right ?
I will look into it and also try to get machines from other regions or other types to have a bigger pool.

**Comment by rok-cesnovar** [comment]
> It started lately so I assume lots of usage

Yes, we are definitely keeping Jenkins warm the last few days.

> This can happen if RAM fills up but I think min. 60 GB should be enough right ?

Not really with "-j 15". The huge models with 1500 calls to distributions can eat up to 10GB of RAM and if we are unlucky we compile 15 of those in parallel...

Lets first decrease parallel a bit first? I guess more RAM is costly?

**Comment by serban-nicusor-toptal** [comment]
It's `~$0.316/hr` versus `~$0.320/hr` for `60 GB` versus `120 GB`.

**Comment by rok-cesnovar** [comment]
Well in that case, lets go for 120GB cause it will finish faster and will be cheaper in total. We can play around what parallel (-j) value to choose, but -j15 should work fine..

**Comment by serban-nicusor-toptal** [comment]
There's a build on the instances so I'll wait until it's done. I Will change it and reply here, let's see how it goes.
Thanks for the heads up.

**Comment by rok-cesnovar** [comment]
I think you can safely shut down those as it is very likely they will get the same error.

**Comment by rok-cesnovar** [comment]
By the looks of it, this has been resolved.

**Comment by rok-cesnovar** [comment]
Thanks Nic!

**Comment by serban-nicusor-toptal** [comment]
Besides the RAM I've also increased our instance pool to around 32 different machine types so I hope we won't get outbid anymore. If anything else pops please let me know so I investigate further.
I'm sorry for the trouble caused in the past few days.
