### ISSUE TITLE
uniform_rng() does not return uniformly generated values

### ISSUE THREAD

**Issue by spinkney** [stan-dev/math#2369]
The following program is supposed to return uniform values on 0,1. However it appears to return something like a normal distribution centered around 0.5.

Reproduced on 2.25 and 2.26.0rc1

```
data {
  int N;
}
parameters {
  real y;
}
model {
  y ~ std_normal();
}
generated quantities {
   real uni_out[N];
   
  for(n in 1:N)
    uni_out[n] = uniform_rng(0, 1);
}
```

![image](https://user-images.githubusercontent.com/23704057/108061835-e05a1400-7026-11eb-921b-5e9557787c03.png)

**Comment by andrjohns** [comment]
I can't replicate this with RStan 2.26:
```
uni_rng = "functions { real stan_uniform_rng(real l, real u) {return uniform_rng(l,u);}}"

rstan::expose_stan_functions(rstan::stanc(model_code=uni_rng))

hist(sapply(1:500,function(x){stan_uniform_rng(0,1)}))
```

Returns:

![1daca444-0678-4774-9451-e8e5030824cd](https://user-images.githubusercontent.com/27717896/108063420-28fce600-7096-11eb-93e4-eeb9ca220681.png)

**Comment by spinkney** [comment]
Interesting, can you try it using just stan
```
fp <- file.path("uni_range.stan")
mod_uni <- cmdstan_model(fp, force_recompile =T)
mod_uni_out <- mod_uni$sample(
  data = list(N = 500),
  chains = 2,
  parallel_chains = 2
)

hist(mod_uni_out$summary("uni_out")$mean)
```

**Comment by rok-cesnovar** [comment]
Ah, I missed this before when we discussed this. The mean is supposed to be around 0.5 for uniform_rng so this is fine?

**Comment by andrjohns** [comment]
I think this might be because you're plotting the means of the uniform draws across the iterations, which for a uniform(0,1) approaches 0.5 as N approaches infinity:
```
uni_rng = "functions { real stan_uniform_rng(real l, real u) {return uniform_rng(l,u);}}"

rstan::expose_stan_functions(rstan::stanc(model_code=uni_rng))

mean_out = sapply(1:500,function(x){mean(sapply(1:500,function(x){stan_uniform_rng(0,1)}))})

hist(mean_out)
```

![1daca444-0678-4774-9451-e8e5030824cd](https://user-images.githubusercontent.com/27717896/108064116-2ea6fb80-7097-11eb-8133-d92443598394.png)

**Comment by spinkney** [comment]
hahahaha, CLT to the front
