### ISSUE TITLE
ODE testing cleanup

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#2395]
## Description

The ODE tests are kinda getting unwieldy. For instance, if we found a bug in `ode_adams_tol`, then we'd also want to check all the other `ode_*` interfaces as well.

These are the `.cpp` files in the rev tests (and a lot of these are quite large and contain lots of duplicate code):

```
test/unit/math/rev/functor/integrate_ode_adams_rev_test.cpp  test/unit/math/rev/functor/integrate_ode_cvodes_grad_rev_test.cpp
test/unit/math/rev/functor/integrate_ode_rk45_tooMuchWork_test.cpp
test/unit/math/rev/functor/integrate_dae_test.cpp
test/unit/math/rev/functor/integrate_ode_bdf_prim_test.cpp
test/unit/math/rev/functor/integrate_ode_rk45_grad_test.cpp
test/unit/math/rev/functor/integrate_ode_std_vector_interface_adapter_test.cpp
test/unit/math/rev/functor/integrate_ode_adams_prim_test.cpp
test/unit/math/rev/functor/integrate_ode_bdf_rev_test.cpp
test/unit/math/rev/functor/integrate_ode_rk45_rev_test.cpp
test/unit/math/rev/functor/ode_adams_prim_test.cpp
test/unit/math/rev/functor/ode_adams_tol_rev_test.cpp
test/unit/math/rev/functor/ode_bdf_tol_prim_test.cpp
test/unit/math/rev/functor/ode_rk45_tol_rev_test.cpp
test/unit/math/rev/functor/ode_adams_rev_test.cpp
test/unit/math/rev/functor/ode_bdf_prim_test.cpp
test/unit/math/rev/functor/ode_bdf_tol_rev_test.cpp
test/unit/math/rev/functor/ode_store_sensitivities_test.cpp
test/unit/math/rev/functor/ode_adams_tol_prim_test.cpp
test/unit/math/rev/functor/ode_bdf_rev_test.cpp
test/unit/math/rev/functor/ode_rk45_rev_test.cpp
```

There are effectively 4 ode functions now. There's the `integrate_*` interfaces with and without tolerances, and there's the `ode_*` interfaces with and without tolerances. There's also some overlap in what the old `integrate_*` and new `ode_*` tests test.

It would be useful to simplify the testing to make these functions more manageable.

#### Current Version:
v4.0.1

**Comment by bbbales2** [comment]
Also there are these three files which are very close to one another:

```
test/unit/math/rev/functor/util_rk45.hpp
test/unit/math/rev/functor/util_cvodes_bdf.hpp
test/unit/math/rev/functor/ode_test_util.hpp
```

**Comment by yizhang-yiz** [comment]
I'll add that the existing tests do quite some boilerplating and make adding new ones difficult. I used `ode_test_util.hpp` instead of `util_` files for #2336 and will expand it to the other integrators' tests.
