### ISSUE TITLE
Document is_vector_like; update tests

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#241]
#### Summary:
`stan/math/prim/mat/meta/is_vector_like.hpp` needs documentation.

#### Description:
This returns true: `stan::is_vector_like<Eigen::MatrixXd>::value`. Add documentation.

#### Current Version:
v2.9.0

**Comment by syclik** [comment]
Turns out this isn't a bug -- the function needs doc.

**Comment by bob-carpenter** [comment]
Agreed.  I was confused by this at one point, too.
