### ISSUE TITLE
OpenCL GPU Platform set to null on Math tests

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#2411]
## Description

This looks like a bug in how the tests are being run (null is used as the OpenCL platform and device): https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2358/25/pipeline/151/

It looks like on a previous run this was not the case: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2358/24/pipeline/151

This was in regards to the pull here: https://github.com/stan-dev/math/pull/2358 . I just restarted the tests in case this was random.

#### Current Version:
v4.0.1

**Comment by rok-cesnovar** [comment]
This happens at random with the new temporary AWS GPU instances we are using until the Columbia-located computer come back.

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal can you check why the GPU instances are not spun up?

**Comment by rok-cesnovar** [comment]
This one is waiting for 16 hours: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/develop/1090/pipeline

Or is this just because we have limited this to the cheaper instances?

**Comment by serban-nicusor-toptal** [comment]
Hey it's because the total amount of EC2 we spin up is limited and there are more linux than usual so the limit is reached.
I will increase that limit now.

**Comment by serban-nicusor-toptal** [comment]
Weird, that error shouldn't happen anymore. I've hardcoded those values in the instance itself so when it boots up it has those env vars.

**Comment by rok-cesnovar** [comment]
Thanks, will close then.

**Comment by rok-cesnovar** [comment]
Happened again: https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2414/8/pipeline/151

Its currently happening a lot actually. Not sure what changed.

**Comment by rok-cesnovar** [comment]
Fixed now it seems! Thanks!
