### ISSUE TITLE
[FR] No bounds checks when NDEBUG flag is set

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2420]
## Description

From [#853](https://github.com/stan-dev/stanc3/issues/853) in stanc3 we recently reverted a check where the compiler actually avoided bounds checks on single indexing functions. This can have a pretty bad performance hit so I think now would be a good time to do something like #2255 where when NDEBUG is set bounds checks are a no-op. This is a standard no debug flag in C++ and is used by boost, eigen, and the standard library to turn off bounds checking. So I think its reasonable that if a user has it set they expect to not have these checks

## Example

```cpp
// in macro.hpp
#ifdefine NDEBUG
#ifndef STAN_NO_RANGE_AND_SIZE_CHECK
#define STAN_NO_RANGE_AND_SIZE_CHECK return
#endif
#else
#ifndef STAN_NO_RANGE_AND_SIZE_CHECK
#define STAN_NO_RANGE_AND_SIZE_CHECK
#endif
#endif

// in check_ranges.hpp
inline void check_range(const char* function, const char* name, int max,
                        int index, int nested_level, const char* error_msg) {
  STAN_NO_RANGE_AND_SIZE_CHECK;
  //... rest of body
}
```

## Expected Output

Bounds checks are not turned on

#### Current Version:
v4.0.1

**Comment by bbbales2** [comment]
Closed by #2423

**Comment by rok-cesnovar** [comment]
@SteveBronder @bbbales2 so I need to set 

CXXFLAGS += -DSTAN_NO_RANGE_CHECKS 

and that escapes the range and size checks only?

**Comment by bbbales2** [comment]
I don't think there's a guarantee that we are turning off every range and size check, but we're hopefully turning off enough that it counts performance-wise.

**Comment by bbbales2** [comment]
And yeah, it's only range and size checks. All value checks should still be there.

**Comment by rok-cesnovar** [comment]
Cool cool. 

I would add a makefile helper so that STAN_NO_RANGE_CHECKS=true adds `CXXFLAGS += -DSTAN_NO_RANGE_CHECKS`. I hate the CXXFLAGS += syntax :) Alo makes it much easier to add it as a cpp_options.

**Comment by bbbales2** [comment]
> Alo makes it much easier to add it as a cpp_options.

Oh whoops, I thought this was somehow done automagically. I'll add to my list for today and if I don't get to it I'll open an issue for later.

**Comment by rok-cesnovar** [comment]
Sure thing. For STAN_THREADS for example we do this: https://github.com/stan-dev/math/blob/9895be8ee0a27a9c7935cf19345d76fcbc85a69d/make/compiler_flags#L282
