### ISSUE TITLE
Clang sanitizer error with tbb

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2428]
## Description

Adding the following to CXXFLAGS in make/local and running the profiling test (though I'm pretty sure this would fail with any test related to the tbb) gives an undefined behavior warning from the sanitizer

```
CXXFLAGS+=-fsanitize=undefined,address,leak -g -fno-omit-frame-pointer 
```

```bash
./runTests.py -j32 test/unit/math/rev/core/profiling_threading_test
```

Full err output [here](https://gist.github.com/SteveBronder/249599a85b5e9f52484567a84a0f386f) with the big bits being 

```
lib/tbb_2019_U8/include/tbb/parallel_reduce.h:173:19: runtime error: member call on address 0x7f44453d3cc0 which does not point to an object of type 'tbb::task'
0x7f44453d3cc0: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lib/tbb_2019_U8/include/tbb/parallel_reduce.h:173:19 in 
lib/tbb_2019_U8/include/tbb/task.h:735:9: runtime error: member call on address 0x7f44453d3cc0 which does not point to an object of type 'tbb::task'
0x7f44453d3cc0: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lib/tbb_2019_U8/include/tbb/task.h:735:9 in 
lib/tbb_2019_U8/include/tbb/parallel_reduce.h:174:31: runtime error: member call on address 0x7f44453d3cc0 which does not point to an object of type 'tbb::task'
0x7f44453d3cc0: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lib/tbb_2019_U8/include/tbb/parallel_reduce.h:174:31 in 
```

and 

```
Direct leak of 2592 byte(s) in 9 object(s) allocated from:
    #0 0x4cff8d in operator new(unsigned long) (/home/steve/stan/origin/math/test/unit/math/rev/core/profiling_threading_test+0x4cff8d)
    #1 0x4de385 in stan::math::AutodiffStackSingleton<stan::math::vari_base, stan::math::chainable_alloc>::init() /home/steve/stan/origin/math/./stan/math/rev/core/autodiffstackstorage.hpp:125:19
    #2 0x4de2c2 in stan::math::AutodiffStackSingleton<stan::math::vari_base, stan::math::chainable_alloc>::AutodiffStackSingleton() /home/steve/stan/origin/math/./stan/math/rev/core/autodiffstackstorage.hpp:93:44
    #3 0x4d9446 in std::_MakeUniq<stan::math::AutodiffStackSingleton<stan::math::vari_base, stan::math::chainable_alloc> >::__single_object std::make_unique<stan::math::AutodiffStackSingleton<stan::math::vari_base, stan::math::chainable_alloc> >() /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/unique_ptr.h:962:34
    #4 0x4d7850 in stan::math::ad_tape_observer::on_scheduler_entry(bool) /home/steve/stan/origin/math/./stan/math/rev/core/init_chainablestack.hpp:46:29
    #5 0x7f4448f37508 in tbb::internal::observer_list::do_notify_entry_observers(tbb::internal::observer_proxy*&, bool) (/home/steve/stan/origin/math/lib/tbb/libtbb.so.2+0x29508)
```

This looks like it might be a tbb or sanitizer issue?

https://github.com/oneapi-src/oneTBB/issues/140

https://github.com/RcppCore/RcppParallel/issues/36#issuecomment-520493210

## Expected Output

No UB or leaks

#### Current Version:
v4.0.1

**Comment by SteveBronder** [comment]
If this is a dependency issue then maybe we shouldn't run the sanitizer with tests that need to use STAN_THREADS

**Comment by SteveBronder** [comment]
Also ugh looking at this it looks one oneTBB uses cmake now so if updating tbb is the answer to this we have a whole swarm of stuff to do

**Comment by bbbales2** [comment]
Like all future TBBs are cmake? Like the next time we upgrade we gotta deal with this somehow?

**Comment by SteveBronder** [comment]
If onetbb is where we get new versions from then I think so :-/

https://github.com/oneapi-src/oneTBB

**Comment by wds15** [comment]
We should probably not upgrade for a while given that RcppParallel is using an outdated version... unless you move the PR you started. Is that PR dead by now or what is missing there? Updating the TBB is not so urgent, but it would be good.

As a compromise @adamhaber made our sources compatible with an external TBB.

**Comment by rok-cesnovar** [comment]
I dont think we will require cmake, I recently tried 2011.1.1 on Linux and worked fine without requiring any additional steps.

> made our sources compatible with an external TBB.

That was @hsbadr :)

**Comment by rok-cesnovar** [comment]
But I agree, we should not upgrade until Rcppparallel upgrades.

**Comment by wds15** [comment]
@hsbadr sorry for confusing credits here. Thanks @rok-cesnovar for correcting.

**Comment by bbbales2** [comment]
There was also this: https://github.com/stan-dev/math/issues/2203

And then there is this: https://github.com/stan-dev/math/issues/1749

Not sure if either thing is relevant but seems like they could be.

**Comment by SteveBronder** [comment]
^^I think those are relevant. imo I think we can update to 2021.3 and keep backwards compatibility with the version on RcppParallel.

**Comment by SteveBronder** [comment]
I think this should be fine with the tbb version bump
