### ISSUE TITLE
Problem with `print(vec * vec')`

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#2435]
#### Summary:

The original report is [here](https://discourse.mc-stan.org/t/eigen-assertion-error-on-cmdstan-ubuntu/21401)

The model:

```stan
data {
  int N;
  vector[N] x_inner;
}
model {
  print(x_inner * x_inner');
}
```

Compiles but produces a runtime error:

```
outer: stan/lib/stan_math/lib/eigen_3.3.9/Eigen/src/Core/Product.h:168: Eigen::ProductImpl<Lhs, Rhs, Option, Eigen::Dense>::Scalar Eigen::ProductImpl<Lhs, Rhs, Option, Eigen::Dense>::coeff(Eigen::Index, Eigen::Index) const [with Lhs = Eigen::Matrix<double, -1, 1>; Rhs = Eigen::Transpose<const Eigen::Matrix<double, -1, 1> >; int Option = 0; Eigen::ProductImpl<Lhs, Rhs, Option, Eigen::Dense>::Scalar = double; Eigen::Index = long int]: Assertion `(Option==LazyProduct) || (this->rows() == 1 && this->cols() == 1)' failed.
Aborted (core dumped)
```

This model works however:

```stan
data {
  int N;
  vector[N] x_inner;
}
model {
  matrix[N, N] outer = x_inner * x_inner';
  print(outer);
}
```

It seems like it's probably an issue with `stan_print` (code [here](https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/stan_print.hpp)) not working with expressions.

#### Current Version:
v2.26.1

**Comment by bbbales2** [comment]
Oof I added code to the expressions tests and it doesn't catch this problem. I guess it's something specifically with the lazyProduct.

**Comment by t4c1** [comment]
`print` should `to_ref` Eigen expressions before iterating over them. `Eigen::Product` does not have `.coeff`.

**Comment by bbbales2** [comment]
Cool will put a fix up for this then.
