### ISSUE TITLE
multi_normal_cholesky slow for non-autodiff covariance

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#2438]
## Description

`multi_normal_cholesky` computes the inverse of the cholesky factor. This is unnecessary if the covariance is not an autodiff type, because that's what the inverse is needed for.

#### Current Version:
v4.0.1

**Comment by wds15** [comment]
Ui, how embarrassing... I looked a long time ago at this piece of code, but never thought about the prim only case... great catch.

**Comment by bbbales2** [comment]
@spinkney called this problem out a few weeks back: https://discourse.mc-stan.org/t/multivariate-normal-cholesky-optimization/20911 and then I was benchmarking some stuff last night and it was being annoyingly slow so figured it was worth doing.

**Comment by spinkney** [comment]
(accidentally closed, using github app on my phone for the first time)
