### ISSUE TITLE
Documentation incoherent with releases

### ISSUE THREAD

**Issue by mboisson** [stan-dev/math#2495]
The documentation says: 
 Stan Math depends on four libraries:
Boost (version 1.75.0): Boost Home Page
Eigen (version 3.3.9: Eigen Home Page
SUNDIALS (version 5.7.0): Sundials Home Page
Intel TBB (version 2020.3): Intel TBB Home Page
These are distributed under the lib/ subdirectory. Only these versions of the dependent libraries have been tested with Stan Math.

yet, once you extract the latest release (4.0.1), it includes
boost 1.72.0
sundials 5.6.1
tbb_2019_U8

so... which is it ?

**Comment by rok-cesnovar** [comment]
Hi, 

are you referring to: https://github.com/stan-dev/math#required-libraries
If so, that refers to the libraries that are in the develop versions of Stan Math (develop branch). 

For the release you need to look at documentation of the release, which is on the release branch: https://github.com/stan-dev/math/tree/v4.0.1#required-libraries

And that correctly states: 

Boost (version 1.72.0): Boost Home Page
Eigen (version 3.3.9: Eigen Home Page
SUNDIALS (version 5.6.1): Sundials Home Page
Intel TBB (version 2019_U8): Intel TBB Home Page

FYI, there will also be a release later today.

**Comment by mboisson** [comment]
ah, I see, thanks. 

Any documentation about how to not used the vendored dependencies ? We already have all of those installed on our cluster.

**Comment by SteveBronder** [comment]
There's no docs on how to use nonvendored dependencies but you can start by swapping out the paths to the dependencies below

 https://github.com/stan-dev/math/blob/develop/make/libraries#L11

>  installing stuff multiples times just should not be needed.

Why so? I don't think it's reasonable to expect a package to work with every previous / future versions of dependencies, which is what you end up supporting if you default to the system versions. + the libraries are a few mb in size.

**Comment by mboisson** [comment]
> Why so? I don't think it's reasonable to expect a package to work with every previous / future versions of dependencies, which is what you end up supporting if you default to the system versions. + the libraries are a few mb in size.

Because we already have a few thousands of builds. We can install different versions if they are absolutely needed, but we should not need to install twice the same version with the same options, ever.

**Comment by wds15** [comment]
Nope…also boost contains some rare bugs, which we fix…and macOS also deploys fat binaries with most stuff included.

**Comment by mboisson** [comment]
Those rare bugs should be contributed back upstream.

**Comment by wds15** [comment]
They are contributed back! It just takes time for the turn around.

**Comment by mboisson** [comment]
Ok. So... any patch we should be aware of, on top of boost, sundials, tbb or eigen, before we try to use our already existing versions ?

**Comment by wds15** [comment]
Easiest is to diff against the libs.

**Comment by rok-cesnovar** [comment]
If you will be using the just released Stan Math, there actually are no required changes in the downstream libraries.

The only change apart from pruning unnecessary files (examples and unused subpackages of the library) from the downstream libraries is removing prints from Sundials https://github.com/stan-dev/math/blob/develop/lib/upgrade-sundials.sh#L122
This is required for CRAN releases of rstan and can be ignored if you will not be dealing with CRAN.

You can see the rest of the upgrade scripts here: https://github.com/stan-dev/math/tree/develop/lib

**Comment by rok-cesnovar** [comment]
For Stan Math 4.0.0. there was at least this one https://github.com/stan-dev/math/pull/2342

There are changes made to the GTest library but that one is not used outside of Stan Math development.

**Comment by mboisson** [comment]
Thanks.  One last question, and I know this is diverting from the first issue. 

A typical software on Linux would build and install through something like : 
1. configure step: configure/cmake
2. build step: make
3. install step: make install

STAN does not seem to follow this pattern. I understand the configure step is done by editing makefile files. However, step 3 is pretty crucial, it should copy some binaries, libraries and header files into an installation prefix. Since you do not provide such an install step (as far as I've seen), what is expected to be copied in which directory in order to have a working installation ?

**Comment by wds15** [comment]
The cmdstan thing is meant to be used in-place. We do not have a `make install`. So you install the cmdstan somewhere and then do

cd cmdstan-path
make path-to-mymodel/model.stan

done.

**Comment by mboisson** [comment]
Ok, thanks. From that, I conclude it is not meant to be installed centrally for many users. I will tell my user that they should install it themselves.

**Comment by wds15** [comment]
on our cluster it is installed centrally and we have a simple wrapper provided which cd's into the directory and builds the model.

**Comment by SteveBronder** [comment]
I think the main thing is that idk any folks in our group that specialize in that tooling and know what is needed to set stan math up in a centralized place. The math library itself is header only, though during compilation it needs linked to TBB for parallel processing. If you have users that have that need then we would welcome a PR to help set these processes up.

**Comment by mboisson** [comment]
It is usually very easy. Executables go in `<prefix>/bin`, shared objects go in `<prefix>/lib64`, headers go in `<prefix>/include`, and environment variables such as `PATH`, `LIBRARY_PATH` and `CPATH` are set for the compiler to find them.

**Comment by andrjohns** [comment]
I like the idea that it should be able to be installed centrally, so I've started looking into it. I think it would be good to be able to use distribution-provided libraries in the first instance (i.e., `libeigen3-dev`), and be able to package it as `.deb` for installation and distribution (since I'm mostly familiar with debian-based distros, but the rest should be on the roadmap).

It won't be ready any time soon, but just flagging that I'll be working on it

**Comment by wds15** [comment]
The hard bit is to comfort developers who are "dump" wrt to install things and also users...

**Comment by andrjohns** [comment]
Yeah that's why it would be good to get to a point where a user/admin could just run `apt install cmdstan` and be good to go. Then we can let the package manager check that the system has a sufficient version of the c++ compiler and libraries, and also automate updates

I've got it to the point where I can compile `cmdstan` and the `bernoulli` model using only distribution libraries/binaries:

 - Boost: `libboost-all-dev`
 - Eigen: `libeigen3-dev`
 - TBB: `libtbb-dev`
 - Sundials: `libsundials-dev`
 - OpenCL: `opencl-headers`
 - Rapidjson: `rapidjson-dev`
 - CLI11: Single header file to be downloaded from github

No proper testing yet, but the bernoulli model compiles and runs.

**Comment by wds15** [comment]
We also have Mac devs... no apt there, but macports or home-brew. Ideally, we get the install feature going without changing the current dev system. There were good reasons to have these fat git repos with the libs and changing this opens another wormhole (the cmake efforts tried to switch to Conan, a source package manager).... and this is a deep wormhole as it looks to me given how many times that was attempted to change... but it would be good to make progress, of course.

**Comment by andrjohns** [comment]
The approach at the moment is a flag in `make/local` which requests system libraries when building/compiling instead the stan-provided ones. So everything stays the same unless that flag is set. 

I'd envision the packaging process as just a script that runs over the latest cmdstan release, so it would be more post-processing the existing system rather than reinventing the wheel

**Comment by andrjohns** [comment]
But that's further down the line once I figure out how to do it all

**Comment by mboisson** [comment]
I don't think you should paint yourself into a corner and support specifically apt-get/macport/brew/etc... Instead, just add a "make install" target that does the right thing. 

For the detection of existing libraries, CMake or Configure (autotools) can be used for it.
