### ISSUE TITLE
sort_asc allows NaN input

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#253]
#### Summary:

`sort_asc()` and `sort_desc()` on a structure that contains `NaN` does not behave consistently.

* [x] break into following and include each in relevant header
    * [ ] `prim/arr/fun/sort_asc.hpp`
    * [ ] `prim/arr/fun/sort_desc.hpp`
    * [ ] `prim/mat/fun/sort_asc.hpp`
    * [ ] `prim/mat/fun/sort_desc.hpp`
* [x] remove `rev` and `fwd` sort files and includes in relevant headers
* [ ] throw exception if `NaN` found

Can leave tests as is.

#### Reproducible Steps:

There's no ordering imposed for `NaN`, so no need.

#### Current Output:

Undefined.

#### Expected Output:

Throw exception. 

#### Current Version:
v2.11.0

**Comment by randommm** [comment]
This problem came when we were adding nan tests: https://github.com/stan-dev/stan/commit/369121d2da69464460a0ec946b9c7e4b6c2f767f#commitcomment-7443051

**Comment by syclik** [comment]
Thanks for digging that up. What should we do? I would prefer if we checked and failed on nan input.

**Comment by bob-carpenter** [comment]
I think checking and failing on NaN input is the
right thing to do.  +/- infinity should be OK.  And
we only need a specialized test if the input type is
not an integer.
