### ISSUE TITLE
multi_student_t_choleskey [FR] with derivatives

### ISSUE THREAD

**Issue by spinkney** [stan-dev/math#2537]
Here's an example of `multi_student_t_cholesky`

```stan
functions {
  // note z is already 0 centered
    real multi_student_t_cholesky_lpdf(matrix z, matrix L, real nu) {
    int p = cols(z);
    int N = rows(z);
    row_vector[N] Q = columns_dot_self(mdivide_left_tri_low(L, z'));
    real lp = N * ( lgamma( (p + nu) / 2) -
                    lgamma(nu / 2) - 0.5 * p * log(nu) - 0.5 * p * log(pi()) -
                    sum(log(diagonal(L))));

    return lp - sum( 0.5 * (nu + p) * log1p(Q / nu) );
  }
}
data {
  int<lower=1> p;
  int<lower=1> n;
  matrix[n, p] y;
}
parameters {
  vector<lower=0>[p] sigma;
  vector[p] mu;
  real<lower=2> nu;
  cholesky_factor_corr[p] L;
}
model {
  mu ~ normal(0, 5);
  nu ~ exponential(1);
  sigma ~ exponential(1);
  L ~ lkj_corr_cholesky(1);

  {
    matrix[n, p] y_norm;

    for (i in 1:p)
      y_norm[, i] = y[i] - mu[i];

    y_norm ~ multi_student_t_cholesky(diag_pre_multiply(sigma, L), nu);
  }
}

```
I've attached my stab at the gradient calculations. Let me know if you find any errors or if I've done something off (not an expert at matrix derivatives!) [gradient_student_t_cholesky.pdf](https://github.com/stan-dev/math/files/6823784/gradient_student_t_cholesky.pdf)

**Comment by spinkney** [comment]
The derivatives are a bit different than in the attached document. Because the cholesky factor is always lower triangular, the derivative is constrained to the space of lower triangular matrices. That is, there will never be pertubations in the upper triangular region.

The derivatives then are 

```julia
# p is the dimension of L
t1 = x - mu
L_solve = inv(L) * t1
mahab = L_solve * L_solve'

j1 = Diagonal(-1 ./ diag(L)) 
j2 = 2 * j1 *mahab * (1 /nu)
j3 = (-0.5 * (nu + p)) / (1 + mahab / nu )

j1 +  j2 * j3
```

**Comment by bob-carpenter** [comment]
Can you express this as an adjoint times Jacobian that doesn't sum two matrices and create a diagonal matrix?  That's what we need for efficient implementations.  Actually rendering the Jacobian in memory is unscalable.  Sorry if that was obvious!

**Comment by spinkney** [comment]
I think it would look something like 

```julia
x_minus_mu = x - μ
dinv_L = 1 ./ diag(L)
inv_L_val = inv(L)              # matrix_partials_t inv_L_val = mdivide_left_tri<Eigen::Lower>(value_of(L_ref));
half = inv_L_val * x_minus_mu   # triangular matmul
scaled_diff = half' * inv_L_val
scale_val = (1 + p / nu) / (1 + half' * half / nu) 

# this part can be looped over and added to the partial
# without creating the matrix
mat_out = tril(inv_L_val' * half * half') * scale_val

# can subtract this diag value in the loop above
mat_out[diagind(mat_out)] .-= dinv_L
mat_out
```

**Comment by spinkney** [comment]
For my notes, the derivative of the mv student t wrt to nu is
```
0.5 * (digamma((p + nu) / 2) - 
        digamma(nu / 2) - 
        p/nu - 
        log1p(G / nu) + 
        (nu + p) * (G / (nu^2 + G * nu)))
```
where `p` is the dimension and `G = (z - μ)' * inv(L * L') * (z - μ)`

**Comment by bob-carpenter** [comment]
I find https://matrixcalculus.org super useful for calculating derivatives.  As long as the base case is right, using the `mix` test and the autodiff testing framework will let you test all the higher-order derivatives.

The implementation will be in terms of adjoint-gradient products.  That is, for a function `y = f(x1, x2, ..., xN)`, you need to evaluate

```cpp
xn.adjoint += y.adjoint * d.y/d.xn
```

**Comment by spinkney** [comment]
@bob-carpenter yes to matrixcalculus.org. But it doesn't allow you to put in triangular matrix constraints so the derivatives wrt to a lower-triangular matrix are wrong since it assumes that the upper triangle can be perturbed. We know that a cholesky factor will never have pertubations in the upper triangle so this constraint needs to be taken into account. Took me a while to get the right gradient b/c of this

**Comment by bob-carpenter** [comment]
Ah, yes.  You said that before and I forgot.  I shouldn't have because it took a while to get all this right in our other triangular derivatives.  Blame it on Monday morning :-).

**Comment by spinkney** [comment]
@bob-carpenter how does Stan's current AD framework handle triangular matrix constraints? In Julia they have a specialization for triangular matrices, is that the same in Stan? Otherwise, how does Stan "know" that the matrix is triangular constrained?
