### ISSUE TITLE
Failure on develop

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2539]
## Description

Looking at the current log I'm seeing an out of resources error.

```
Actual: it throws std::system_error with description "results_cl.assignment: clEnqueueNDRangeKernel CL_OUT_OF_RESOURCES: Unknown error -5".
```

https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/develop/1184/pipeline#step-198-log-1938

That seems like an odd error to happen during `clEnqueueNDRangeKernel` and from the docs it seems like there are 3 places it can happen

> global_work_size

>    Points to an array of work_dim unsigned values that describe the number of global work-items in work_dim dimensions that will execute the kernel function. The total number of global work-items is computed as global_work_size[0] *...* global_work_size[work_dim - 1].

>    The values specified in global_work_size + corresponding values specified in global_work_offset cannot exceed the range given by the sizeof(size_t) for the device on which the kernel execution will be enqueued. The sizeof(size_t) for a device can be determined using CL_DEVICE_ADDRESS_BITS in the table of OpenCL Device Queries for clGetDeviceInfo. If, for example, CL_DEVICE_ADDRESS_BITS = 32, i.e. the device uses a 32-bit address space, size_t is a 32-bit unsigned integer and global_work_size values must be in the range 1 .. 2^32 - 1. Values outside this range return a CL_OUT_OF_RESOURCES error.

> Errors

> CL_OUT_OF_RESOURCES if there is a failure to queue the execution instance of kernel on the command-queue because of insufficient resources needed to execute the kernel. For example, the explicitly specified local_work_size causes a failure to execute the kernel because of insufficient resources such as registers or local memory. Another example would be the number of read-only image args used in kernel exceed the CL_DEVICE_MAX_READ_IMAGE_ARGS value for device or the number of write-only image args used in kernel exceed the CL_DEVICE_MAX_WRITE_IMAGE_ARGS value for device or the number of samplers used in kernel exceed CL_DEVICE_MAX_SAMPLERS for device.

> CL_OUT_OF_RESOURCES if there is a failure to allocate resources required by the OpenCL implementation on the device. 

I tried running this locally but couldn't replicate the error?

#### Current Version:
v4.1.0

**Comment by rok-cesnovar** [comment]
@t4c1 any ideas?

To me it seems like a too big work-group that the CPU cant handle? It seems that the CPU OpenCL tests did not run on the PR (https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/PR-2512/8/pipeline). Not really sure why not.

@SteveBronder There is now an additional issue that popped up on the threading tests after the unary varmat PR got merged:https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/develop/1187/pipeline/155

```
In file included from test/unit/math/rev/fun/eigenvalues_sym_test.cpp:1:

In file included from ./stan/math/prim.hpp:12:

In file included from ./stan/math/prim/err.hpp:4:

In file included from ./stan/math/prim/err/check_2F1_converges.hpp:6:

In file included from ./stan/math/prim/fun/fabs.hpp:6:

./stan/math/prim/functor/apply_scalar_unary.hpp:67:33: error: implicit instantiation of undefined template 'stan::math::apply_scalar_unary<stan::math::log_fun, stan::math::var_value<double, void>, void>'

        [](scalar_t x) { return apply_scalar_unary<F, scalar_t>::apply(x); });

                                ^

./stan/math/prim/functor/apply_scalar_unary.hpp:75:33: note: in instantiation of member function 'stan::math::apply_scalar_unary<stan::math::log_fun, Eigen::Matrix<stan::math::var_value<double, void>, -1, -1, 0, -1, -1>, void>::apply' requested here

      apply_scalar_unary<F, T>::apply(std::declval<T>()))>;

                                ^

./stan/math/prim/fun/log.hpp:51:10: note: in instantiation of template class 'stan::math::apply_scalar_unary<stan::math::log_fun, Eigen::Matrix<stan::math::var_value<double, void>, -1, -1, 0, -1, -1>, void>' requested here

  return apply_scalar_unary<log_fun, Container>::apply(x);

         ^

test/unit/math/rev/fun/eigenvalues_sym_test.cpp:21:45: note: in instantiation of function template specialization 'stan::math::log<Eigen::Matrix<stan::math::var_value<double, void>, -1, -1, 0, -1, -1>, nullptr, nullptr, nullptr>' requested here

  auto logdet = stan::math::sum(stan::math::log(w));

                                            ^

./stan/math/prim/functor/apply_scalar_unary.hpp:40:8: note: template is declared here

struct apply_scalar_unary;
```

**Comment by t4c1** [comment]
Yeah I bet #2512 is the PR that caused it, as I was messing with local sizes in it. I thought it should not change anything for any existing kernels, but mistakes happen. I will look into this error later today. 

Anyway we really need to fix that CPU tests randomly not running. They have already let 2 errors slip into develop.

**Comment by rok-cesnovar** [comment]
Yeah, I agree. @serban-nicusor-toptal does https://github.com/stan-dev/math/blob/develop/Jenkinsfile#L171 only check the last commit compared to the previous one? If that is the case that might be why. It should be checking PR-branch vs develop.

**Comment by serban-nicusor-toptal** [comment]
Hey, I think we're good as it checks changes against target branch, in our case it'll be develop.
You can check that here: https://github.com/stan-dev/jenkins-shared-libraries/blob/master/src/org/stan/Utils.groovy#L64
Please let me know if there's anything I should change!

**Comment by SteveBronder** [comment]
@t4c1 should we revert the PR that caused the OpenCL error till you sort out #2541?

**Comment by t4c1** [comment]
No need. The fix is already working, it just needs to pass tests on Jenkins again before we merge it.

**Comment by SteveBronder** [comment]
Opening this back up (or I can make a new one). Seeing a new error with the OpenCL CPU tests

```
[----------] 4 tests from OpenCLPrim (822 ms total)
[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (822 ms total)
[  PASSED  ] 4 tests.
Segmentation fault (core dumped)
test/unit/math/opencl/rev/add_test --gtest_output="xml:test/unit/math/opencl/rev/add_test.xml" failed
```

I'm getting this locally as well.

https://jenkins.mc-stan.org/blue/organizations/jenkins/Math%20Pipeline/detail/develop/1194/pipeline#step-191-log-2728

**Comment by t4c1** [comment]
Aaand CPU tests failed to run again. Should we make them always run, at least until someone figures out how to make the current arrangement reliable?

Anyway this new error seems unrelated to the previous one. Hard to say anything definitive, as I can not reproduce it locally.

**Comment by SteveBronder** [comment]
^ I'd rather have them always run for now until we can figure out why they are not sometimes. @t4c1 I can reproduce the above on my desktop but only have access to my laptop atm which I need to figure out how to setup opencl on. I think we should do the revert revert scheme until we can get that debugged and working.
