### ISSUE TITLE
extend apply_scalar_{unary, binary} to complex numbers

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#2547]
## Description

In order to get complex numbers to work, we need `apply_scalar_unary` and `apply_scalar_binary` to be templated for them for all of the vectorized functions.  This requires working down to the macros in `require_generics.hpp`.

We need a`require_stan_scalar_complex` to parallel `require_stan_scalar_real`, which involves working down to `require_generics.hpp`.

For all of the doc, we have to decide whether to take "scalar" to mean real or integer, or to also include complex as it does in mathematics.

#### Current Version:
v4.1.0

**Comment by SteveBronder** [comment]
I think I figure this out this week. Mostly we need to change the templates to accept complex types and setup the vectorized tests to also check complex types. We'll need to do the same thing for `apply_scalar_binary` as well

**Comment by bob-carpenter** [comment]
@SteveBronder --- this week would be awesome.  We need it to support the code gen for complex functions like abs(z).  It all depends on the template functions `apply_scalar_XXX`. complex number code gen for basic functions.  The complex language stuff is largely working, but not the generic vectorized function calls, and we need this for an easy path to launch complex numbers. An alternative might be to not allow vectorization of complex functions.

**Comment by bob-carpenter** [comment]
closed with #2549
