### ISSUE TITLE
Feature Request: Inverse error function

### ISSUE THREAD

**Issue by soga-denken** [stan-dev/math#2558]
## Description
This is a feature request to add an inverse error function. An inverse error function is used in the quantile of a normal distribution. I also need this function for a special probability distribution I set up.

The function is available in boost at 
https://www.boost.org/doc/libs/1_74_0/libs/math/doc/html/math_toolkit/sf_erf/error_inv.html

The derivative is defined at https://mathworld.wolfram.com/InverseErf.html

## Example

This is a sample implementation.

```
#ifndef STAN_MATH_PRIM_FUN_INV_ERF_HPP
#define STAN_MATH_PRIM_FUN_INV_ERF_HPP

#include <stan/math/prim/meta.hpp>
#include <stan/math/prim/functor/apply_scalar_unary.hpp>
#include <boost/math/special_functions/erf.hpp>

namespace stan {
namespace math {

/**
 * Structure to wrap inv_erf() so it can be vectorized.
 *
 * @tparam T type of variable
 * @param x variable
 * @return Inverse Error function of x.
 */
struct inv_erf_fun {
  template <typename T>
  static inline T fun(const T& x) {
    using boost::math::erf_inv;
    return erf_inv(x);
  }
};

/**
 * Returns the elementwise inv_erf() of the input,
 * which may be a scalar or any Stan container of numeric scalars.
 *
 * @tparam T type of container
 * @param x container
 * @return Inverse Error function applied to each value in x.
 */
template <
    typename T,
    require_all_not_nonscalar_prim_or_rev_kernel_expression_t<T>* = nullptr,
    require_not_var_matrix_t<T>* = nullptr>
inline auto inv_erf(const T& x) {
  return apply_scalar_unary<inv_erf_fun, T>::apply(x);
}

}  // namespace math
}  // namespace stan

#endif

```

#### Current Version:
v4.1.0

**Comment by rok-cesnovar** [comment]
Thanks @soga-denken for the feature request, example code and links to the derivatives. A very detailed issue request!

The prim implementation you write is already ready, this is just missing the rev implementation (the derivative). For that I suggest just copying https://github.com/stan-dev/math/blob/develop/stan/math/rev/fun/erf.hpp and changing the relevant parts and adding a few tests.

I labeled this a good first issue as this is a nice and easy introductory issue to the world of Stan Math.

**Comment by soga-denken** [comment]
Hi, @rok-cesnovar,

Thank you for your quick reply. After posting the code, I realized that my inv_erf implementation lacks an error handling for the case `x <= -1` and `x>= 1`. In addition, `boost::math::erf_inv(x)` returns an overflow error instead of an infinity when `x` is very close to 1.

Should I handle these errors in inv_erf_fun? If so, here is my implementation.

```
struct inv_erf_fun {
  template <typename T>
  static inline T fun(const T& x) {
    using boost::math::erf_inv;
    if(x > 1 or x < -1){
      return NOT_A_NUMBER;
    }else if(x >= 1 - EPSILON){
      return INFTY;
    }else if(x == -1 + EPSILON){
      return NEGATIVE_INFTY;
    }
    return erf_inv(x);
  }
};
```

Is this what the stan developers expect?

**Comment by rok-cesnovar** [comment]
Yeah, something along those lines. See [here](https://github.com/stan-dev/math/blob/02dc560b022f328f917af80a1b9b7f1feb249ee4/stan/math/prim/fun/log1m_exp.hpp#L50).

I would avoid testing for exact equality with floating point values (stuff like `x == -1 + EPSILON`) in favor of testing for an interval.

**Comment by soga-denken** [comment]
Hi, @rok-cesnovar,

Thank you for your quick reply. I did a little experiment and realized that 1 - EPSILON = 1. So, it does not need `x >= 1 - EPSILON`.

I have another question. I implemented an inv_erf in fwd. I thought I need to write a test code for it but in fwd/test/fun folder, there is no test code for a function such as an error function. 
Should I write a test code for an inv_erf in fwd or is it automated somehow?

**Comment by rok-cesnovar** [comment]
> I implemented an inv_erf in fwd

An implementation in fwd can currently not be used in Stan, as forward mode is currently just available in Stan Math in C++. In order for this function to be supported in Stan it needs an implementation in rev. We definitely welcome a fwd implementation though as well.

The erf tests are done here: https://github.com/stan-dev/math/blob/develop/test/unit/math/mix/fun/erf_test.cpp
They are done with our mix mode testing framework that tests rev, fwd and mix mode. 

For those tests to work a function needs both a rev and fwd mode implementation. If there is only rev implementation the tests are found in https://github.com/stan-dev/math/tree/develop/test/unit/math/rev/fun

**Comment by soga-denken** [comment]
Hi, @rok-cesnovar,

Thank you for your quick reply. I think I got the necessary information to implement inv_erf.
It may take one or two weeks to get approval from my employer.

**Comment by wds15** [comment]
just as a comment: you should not check consistency with boost definitions, but rather stan math. So how overflow is handled is something I would check with other similar functions in math. I don't know the answer in this case.

**Comment by spinkney** [comment]
Do you just want inv Phi? It can be converted to inv_erf by 

Inv_phi(p) = sqrt (2) inv_erf( 2p -1)

There's an issue for making that faster

**Comment by bob-carpenter** [comment]
Although we can handle the inverse error function as described by @spinkney, I think that's the only inverse CDF that we implement other than the logistic.

As to making things go faster, that's usually a tradeoff for accuracy.  We would consider fast approximations for inclusion---we already have that for the error function itself.  Not every use of HMC or optimization requires maximum precision.

Stan follows the C++ standard library, where functions like exponentiation just overflow or underflow.  For example, `exp(1000)` returns infinity, and `exp(-1000)` returns 0.

**Comment by spinkney** [comment]
Btw I have 2 versions of inv erf written in Stan. Not sure about the level of accuracy. Boost is prob better but this can allow you to write what you want now until this gets implemented.
 https://github.com/spinkney/helpful_stan_functions/blob/main/functions/special/inv_erf.stan

**Comment by soga-denken** [comment]
Hi, @spinkney,

Thank you for your information! That's what I needed.
I think this is a duplicate of #2555, so I close this issue.

Thank you very much for your help.
