### ISSUE TITLE
Generalized inverse should work for less than full rank symmetric matrices

### ISSUE THREAD

**Issue by spinkney** [stan-dev/math#2576]
## Description
The generalized inverse implementation reverts to the regular inverse when the input matrix is symmetric. However, the regular inverse will result in NaN's when the matrix is less than full rank.

I can add a check using FullPivLU when the matrix is invertible. Interestingly, checking with ldlt `isPositive()` does not work. See https://godbolt.org/z/3fx6o6Gcv. 

What is the preferred way to find if a symmetric matrix is full rank in Stan-math?

## Example
```r
stan_code <- "
functions {
 matrix ginv_stan (matrix A) {
    return generalized_inverse(A);
  }
}
"

A <-matrix(c(4, 4, -2,
             4, 4, -2,
             -2, -2, 10), nrow=3, ncol=3, byrow=TRUE)

ginv_stan(A)

           [,1] [,2]      [,3]
[1,]        Inf -Inf       NaN
[2,]       -Inf  Inf       NaN
[3,] 0.05555556    0 0.1111111

 MASS::ginv(A)
           [,1]       [,2]       [,3]
[1,] 0.06944444 0.06944444 0.02777778
[2,] 0.06944444 0.06944444 0.02777778
[3,] 0.02777778 0.02777778 0.11111111
```
## Expected Output
A matrix without NaNs. Note that the generalized inverse is not unique so I don't expect it to equal the `ginv()` from `MASS`.

**Comment by bob-carpenter** [comment]
Where is `generalized_inverse` used?  It doesn't look like it's exposed through the language.  It might not need to deal with lower-rank inputs.

**Comment by spinkney** [comment]
It's in the language since 2.26. I'm curious specifically about the case of symmetric low-rank matrices so I hope this gets merged.

I updated the PR so that the ldlt decomp only happens once. Using the fact that if the input is low rank the multiplication of the input by itself will be the same rank as the input.

**Comment by bob-carpenter** [comment]
Weird.  I couldn't find it by Google search on our docs, but did find it locally in our doc source.
