### ISSUE TITLE
Add stub functions for certain std:: functions

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/math#2611]
This is related to https://github.com/stan-dev/stanc3/issues/997 / https://github.com/stan-dev/stanc3/pull/1011

There are several functions which we don't define in stan::math but rather use std:: (or don't qualify them at all) for when the argument is only reals or ints. As far as I can tell, these are:

- [ ] pow
- [ ] fmod
- [ ] atan2
- [ ] min, max (the versions that accept 2 scalars, not the ones for arrays etc)
- [x] ceil

It would be great to redirect these within the library, so we can codegen all functions as fully qualified, e.g. `stan::math::pow`.

We may also need more definitions for `norm` and `pow` of complex numbers, see [this log](https://jenkins.mc-stan.org/blue/rest/organizations/jenkins/pipelines/stanc3/branches/PR-1011/runs/4/nodes/192/steps/213/log/?start=0) for what currently fails

**Comment by WardBrian** [comment]
@rok-cesnovar have you had a chance to look at this yet?

**Comment by rok-cesnovar** [comment]
Yes, I am in the process of making a script to generate the tests mentioned above. I can fix the functions first if this is blocking you though. That can be done quick.
