### ISSUE TITLE
Missing RNGs for most GLM implementations

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/math#2614]
## Description
We currently have [`bernoulli_logit_glm_rng`](https://github.com/stan-dev/math/blob/92075708b1d1796eb82e3b284cd11e544433518e/stan/math/prim/prob/bernoulli_logit_glm_rng.hpp) implemented, however for other GLMs, the RNG functions are not implemented (e.g. `normal_id_glm_rng`, `poisson_log_rng`, `neg_binomial_2_log_glm_rng`). Unless that's intetional, it might be nice to support those as well.

## Expected Output

The RNGs return a vector/array of the correct type and size (as inferred from the parameters).

#### Current Version:
v4.2.1

**Comment by bob-carpenter** [comment]
I agree with @martinmodrak that these should be added.  

I think the vectorized returns should be arrays to be in keeping with our other functions no matter what the arguments are.  That is, we don't implement `vector normal_rng(vector, vector)`, but `array[] real normal_rng(reals, reals)` where `reals` is any container and one of the args has to be a container.

**Comment by rok-cesnovar** [comment]
I am going to close this issue in favor of a more general issue on missing RNG functions: https://github.com/stan-dev/math/issues/2658

> I think the vectorized returns should be arrays to be in keeping with our other functions no matter what the arguments are. That is, we don't implement vector normal_rng(vector, vector), but array[] real normal_rng(reals, reals) where reals is any container and one of the args has to be a container.

I agree, just noting that we do have a few rngs that return vectors:

```stan
dirichlet_rng(vector) => vector
multi_normal_cholesky_rng(vector, matrix) => vector
multi_normal_cholesky_rng(row_vector, matrix) => vector
multi_normal_cholesky_rng(array[] vector, matrix) => array[] vector
multi_normal_cholesky_rng(array[] row_vector, matrix) => array[] vector
multi_normal_rng(vector, matrix) => vector
multi_normal_rng(row_vector, matrix) => vector
multi_normal_rng(array[] vector, matrix) => array[] vector
multi_normal_rng(array[] row_vector, matrix) => array[] vector
multi_student_t_rng(real, vector, matrix) => vector
multi_student_t_rng(real, row_vector, matrix) => vector
multi_student_t_rng(real, array[] vector, matrix) => array[] vector
multi_student_t_rng(real, array[] row_vector, matrix) => array[] vector
```
