### ISSUE TITLE
matrix exponential failing at extreme values

### ISSUE THREAD

**Issue by cdriveraus** [stan-dev/math#2615]
In the following case, the matrix exponential function is returning NaN when it should be returning zero. Ideally such cases wouldn't need to exist, but can occur either due to poor initialization / priors, or as in the case that drove me to look at this, a particularly large time step in a form of differential equation model. R code demonstrates:

```
library(rstan)
library(expm)
A=matrix(c(-3.3228,1.2242,0.533302,-4.04844),byrow=T,2)
dt=800
Adt = expm(A * dt)

st <-'
data{
matrix[2,2] A;
real dt;
}
transformed parameters{
matrix[2,2] Adt = matrix_exp(A * dt);
}
'
sm=stan_model(model_code=st)
sf <- sampling(sm,iter=0,chains=0,data=list(A=A,dt=dt))
constrain_pars(sf,numeric())

```

**Comment by rok-cesnovar** [comment]
Moved it to Math. Note that there are 2 matrix_exp issues open already, I am not sure if they are related in any way with this one: 

https://github.com/stan-dev/math/issues/2529 and https://github.com/stan-dev/math/issues/1146

**Comment by yizhang-yiz** [comment]
I promised to take a look but got been recently. I should be able to dig a bit later this week.

**Comment by yizhang-yiz** [comment]
The issue is caused by the overflow in `cosh` and `sinh` function calls in `matrix_exp_2x2` https://github.com/stan-dev/math/blob/20224ff479ca557a82a7ea3c5446d301a7d85825/stan/math/prim/fun/matrix_exp_2x2.hpp#L38

**Comment by cdriveraus** [comment]
I see yeah, switching to a 3x3 matrix (with independent 3rd row / col) gives the correct results, so this fix makes sense...
