### ISSUE TITLE
Migrate Jenkins to Flatiron Institute

### ISSUE THREAD

**Issue by serban-nicusor-toptal** [stan-dev/math#2623]
## Description

Migrating our entire Jenkins (not the server itself just the jobs) to Flatiron Institute.
We are trying to do it in parallel so we avoid any CI degradation on our side but things may happen so please keep in mind that if something goes wrong unexpectedly during this period it might be because of that so please feel free to message me on Github/Slack/Forum so I can quickly solve it.

Current steps to follow:

- [x] Refactor Jenkinsfile for new machine tags, docker, environment variables ( env vars that were tied to a machine ( OPENCL, PARALLEL, CXX ) will now be tied to the job itself.
- [x] Dockerize all the Linux steps, mac if will work fine, and windows will probably stay the same
- [x] Push Docker images to stanorg ( optionally automate this process in ci-scripts as we did for stanc3 to keep the math repo clean )
- [x] Add and test Github webhooks
- [x] Install any missing Jenkins plugin
- [x] Add any missing configuration like Shared Library, Groovy Parsers ...
- [x] Ensure end-to-end CI functionality
- [x] Do the switch

## Expected Output

We expect to have math CI run in parallel on Flatiron Institute Jenkins before we do the switch.

#### Current Version:
v4.2.1

**Comment by rok-cesnovar** [comment]
Thanks Nic and I am guessing @bob-carpenter and @WardBrian for setting this up at Flatiron. We should not forget to thank Flatiron in release annoucements.

**Comment by serban-nicusor-toptal** [comment]
Also many thanks to @dylex for helping me with setting up Jenkins on the Flatiron side and of course @rok-cesnovar for always answering my questions!

**Comment by bob-carpenter** [comment]
It'd be great to thank Flatiron Institute for the cycles.  I'm just introducing people.  @WardBrian understood enough of our current CI setup to talk to @dylex here at Flatiron, and then @dylex and @serban-nicusor-toptal have taken it from there.  Let me know if you need more help on this end administratively.

**Comment by serban-nicusor-toptal** [comment]
We've migrated our CI jobs to Flatiron Institute Jenkins today! For now, it seems to run smooth, there might be some issues so I'll keep a close eye on it for a few days.
I've also moved the gelman instances there (win, linux, osx) and the oldimac, it seems to be a bit slow on the windows instances queue and I want to ask @bob-carpenter if we're supposed to still be using AWS instances or discontinue it ? If we can still do, I can move those too so we can still leverage scaling instances when needed for win/linux.

**Comment by serban-nicusor-toptal** [comment]
A more detailed update related to what we talked in the meeting:
- [stanc3 ](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FStanc3/detail/PR-1122/3/pipeline/) compile tests seems to take ~3hours now, this one we can split into multiple jobs and run it in parallel to reduce build time I will ask @WardBrian for help and review.
- [math ](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/develop/4/pipeline/211) distribution tests take now around 21 hours (still running, ~16 hours in our CI), expressions tests ~9 hours (This is weird, not sure why it's 9x more than our CI, will investigate), GPU tests ~2 hours(same time as before), threading 2h 14m (almost same as before),  windows headers ~5h ( this one I will move to use only our gelman-windows machine which should reduce the time by half )  

For now, only the above seems to be the most impacted jobs that we need to fine-tune before Monday so the 2.29.1 release will be smooth. I wanted to ask @rok-cesnovar maybe you have an idea how to improve distributions tests and expressions tests in math, I will also need to fiddle around with `-j` since our cores/executors are less.

**Comment by WardBrian** [comment]
This is tiny, but we also need to update badges like the ones in the stanc3 README, which link to mc-stan still

**Comment by dylex** [comment]
Re macOS, at FI we're a bit constrained to keep things updated so our macOS builder will keep updating going forward, too, so probably best not to rely on its version too closely.

**Comment by serban-nicusor-toptal** [comment]
I can add it to the CI rather than keep it manual, will create a PR for it later today.
