### ISSUE TITLE
Issue with TBB if there is a system installed TBB

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2624]
## Description

This may be fixable with makefile as is right now, I am just unaware of how to do this.

If you have a system-installed TBB that is newer than the one we currently use, the system-installed TBB can get picked up when compiling, resulting in issues like the following: 

`/usr/bin/ld: error: undefined symbol: tbb::internal::task_scheduler_observer_v3::observe(bool)`

This error pops up because task_scheduler_observer_v3 is not present in newer version.

Is there a way to ignore the system installed without having to go and handle the PATH variable or anything like that?

#### Current Version:
v4.2.1

**Comment by wds15** [comment]
closed by #2627
