### ISSUE TITLE
wrong TBB picked up at runtime

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#2626]
## Description
On our cluster we have a very old TBB installed and it gets picked up at runtime leading to a segfault.

## Example

This is really hard to reproduce, but on our prod system it is possible to have a different setting for LD_LIBRARY_PATH and so on during build and during executing. This lead to segfaults under the running environment as the wrong system TBB was picked up and rpath was ignored.

The solution is to force the linker to pickup the right libraries via:

https://stackoverflow.com/questions/52018092/how-to-set-rpath-and-runpath-with-gcc-ld

## Expected Output

Things should just work.

#### Current Version:
v4.2.1

**Comment by rok-cesnovar** [comment]
Is this related to https://github.com/stan-dev/math/issues/2624 ? I would guess we have the same issue there.

**Comment by wds15** [comment]
Oh yes... that's the same problem as it looks to me.

**Comment by wds15** [comment]
Closed by #2627
