### ISSUE TITLE
Add fwd implementation for Phi_approx

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/math#265]
#### Summary:
Because the primitive version of Phi_approx is templated, the fwd and mix cases can be currently handled. However, in order to vectorize the function, we will need to implement the fwd version.

#### Description:
We need to create `stan/math/fwd/scal/fun/Phi_approx.hpp` to handle the fwd and mix cases when we untemplate the primitive version.

#### Reproducible Steps:
I found this while trying to vectorize the function.

#### Current Output:
There are two implementations of Phi_approx: one in `stan/math/prim/scal/fun` and one in `stan/math/rev/scal/fun`.

#### Expected Output:
There will be three implementations of Phi_approx: one in `stan/math/prim/scal/fun`, one in `stan/math/rev/scal/fun`, and one in `stan/math/fwd/scal/fun`.

#### Current Version:
v2.9.0

**Comment by bob-carpenter** [comment]
Please don't do this.  Instead, you should figure out how to get the vectorization to work with what it has.  

You don't list here what the problem is with not having the fwd and rev versions.
