### ISSUE TITLE
Consistency of tangent access for `fvar` vs `Eigen` containers for `fvar`

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#2650]
## Description

When accessing the adjoints for `var` types, the same member function is used for both scalars and containers:
```cpp
double adjoint = var.adj();
Eigen::VectorXd adjoint_vec = var_vec.adj();
```

But for `fvar` types, the `tangent()` member is used for scalars while the `d()` member is used for containers:
```cpp
T adjoint = fvar.tangent();
Eigen::Matrix<T, -1, 1> tangent_vec = fvar_vec.d();
```

I think we should be using a consistent member for `fvar` scalars and `fvar` containers. 

#### Current Version:
v4.2.1

**Comment by bob-carpenter** [comment]
I agree this would be nice to fix.
