### ISSUE TITLE
Add rev implementation for log_inv_logit.hpp

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/math#266]
#### Summary:
Because the primitive version of log_inv_logit.hpp is templated, the rev and mix cases can be handled. However, in order to vectorize the function, we need to add a rev implementation for the function.

#### Description:
We need to create `stan/math/rev/scal/fun/log_inv_logit.hpp` so that we can untemplate `stan/math/prim/scal/fun/log_inv_logit.hpp`.

#### Reproducible Steps:
I found this while trying to vectorize the function by running this command in Terminal: 
```
locate ./ "/log_inv_logit.hpp"
```
While it returned results from the R header folder, I could compare to see if they matched those in the actual directory.

#### Current Output:
There are implementations in `stan/math/prim/scal/fun/` and `stan/math/fwd/scal/fun/`.

#### Expected Output:
There should be implementations in `stan/math/prim/scal/fun/`, `stan/math/fwd/scal/fun/`, and `stan/math/rev/scal/fun/`.

#### Current Version:
v2.9.0

**Comment by bob-carpenter** [comment]
Please don't do this.  Instead, get the vectorization working with templated base classes.
