### ISSUE TITLE
Expand grad_2F1 to calculate gradients for all inputs

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#2663]
## Description

The only blocker to implementing and exposing a `hyper_2F1` function is that the `grad_2F1` function only calculates gradients for two of the inputs (a1 and b1). The function should be expanded to also calculate the gradients for a2.

The implementation should be fairly simple, as it follows the same calculation as the gradients for a1.

#### Current Version:
v4.3.0

**Comment by spinkney** [comment]
I'll take a stab at this next week. Thanks for pointing it out!

**Comment by spinkney** [comment]
That's the `F32` function not `grad_F32`. In order to make this template how do I handle the fact that it's a `void` output for the return_type?

**Comment by spinkney** [comment]
@andrjohns in #2510 you have a much better implementation of `grad_pFq`, is there a reason why you need this `grad_2F1`? I have a pr in for expanding the types but I think it's better to just use your `grad_pFq`.

**Comment by andrjohns** [comment]
The `grad_2F1` is actually much faster than the `grad_pFq` and is much better behaved around when the gradients get very small. In the `pFq` PR there's a test commented out which the `2F1` tears through while the `pFq` gets stuck
