### ISSUE TITLE
Define scalar-matrix multiplication for complex types

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/math#2671]
## Description

Currently, `stan::math::multiply` fails when one argument is an `std::complex<double>` and the other type is and Eigen matrix (either of double or of complex).

## Example

```C++
Eigen::Matrix<std::complex<double>, -1, -1> gq_c_matrix =
    Eigen::Matrix<std::complex<double>, -1, -1>::Constant(N, N,
        std::numeric_limits<double>::quiet_NaN());
Eigen::Matrix<std::complex<double>, -1, -1> cmat =
    Eigen::Matrix<std::complex<double>, -1, -1>::Constant(N, N,
        std::numeric_limits<double>::quiet_NaN());
std::complex<double> z =
    std::complex<double>(std::numeric_limits<double>::quiet_NaN(),
        std::numeric_limits<double>::quiet_NaN());
stan::model::assign(gq_c_matrix, stan::math::multiply(cmat, z),
    "assigning variable gq_c_matrix");
```

The failure message specifically mentions `/stan/math/prim/core/operator_multiplication.hpp`

## Expected Output
I would expect this to work. For reference, compiling a multiplication call between `double` and `Eigen::Matrix<std::complex<double>, -1, -1>` works as expected.

#### Current Version:
v4.3.0

**Comment by WardBrian** [comment]
Looking at https://github.com/stan-dev/math/blob/develop/stan/math/prim/core/operator_multiplication.hpp it's fairly obvious why this fails, since I don't think `*=` will work when one of them is a matrix. I'm sure there is some sort of memory-usage magic reason this function doesn't just delegate to the normal `operator*`?

**Comment by bob-carpenter** [comment]
This is the standard recommendation for implementing `operator*` in terms of `operator*=` (and similarly for the others).  See, for example [this tutorial on cppreference](https://en.cppreference.com/w/cpp/language/operators), section "Binary arithmetic operators".  I've never quite understood why they do it that way around.

**Comment by bob-carpenter** [comment]
> I don't think *= will work when one of them is a matrix.

So I guess the question is why it works for `double` matrices but not `complex`.

**Comment by WardBrian** [comment]
We don't define our own overloads for `operator*` for double or matrix, only for `std::complex`, so I think it's following completely different code paths for the case where one of them is a double and the other isn't. I've done a bit more testing and found it also fails when doing multiplication between `stan::math::var_value<double>` and a complex matrix

@SteveBronder yesterday suggested that this should be an easy enough fix if we define another overload for `stan::math::multiply`, but that it will help if we expand expression testing (see #2676)
