### ISSUE TITLE
Vectorized versions of get_real, get_imag

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/math#2675]
We should consider adding the following family of signatures:

`get_real(complex_matrix) => matrix`, `get_imag(complex_matrix) => matrix`,  etc (same idea for complex_vector, complex_row_vector).

The type promotion exposed in stanc3 shouldn't make it strictly necessary to expose functions like `to_complex(matrix, matrix) => complex_matrix` but these may also be useful.

**Comment by bob-carpenter** [comment]
+1 to adding these functions.  And yes, it looks like we can wrap  `Eigen::real()` and `Eigen::imag()`.
