### ISSUE TITLE
Stan signature expression tests should support complex numbers

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/math#2676]
Some math tests are triggered off the output of signatures from stanc. These were never updated to include complex numbers as a scalar, and particularly with complex_matrix etc coming we should add this.

See: 
https://github.com/stan-dev/math/blob/01dd2e7487236880bfc7282119d1355fdfd9dc48/test/sig_utils.py#L15-L27

This will need to add mappings for complex (`std::complex<SCALAR>`) and similar for the container types

**Comment by WardBrian** [comment]
@rok-cesnovar would you be able to look into this?

**Comment by rok-cesnovar** [comment]
For sure. 

These were never updated because we only needed expressions tests for Eigen types and there was no support for eigen complex types yet.

**Comment by WardBrian** [comment]
Great, thanks! This will also make the adding of more math signatures for the complex types in stanc much easier in the future

**Comment by SteveBronder** [comment]
@rok-cesnovar did you check out https://github.com/stan-dev/math/pull/2434 for this? Might be easy to override that and produce complex types instead of var mat types

**Comment by rok-cesnovar** [comment]
Thanks. Havent yet, currently focused mostly on getting https://github.com/stan-dev/math/pull/2670 to run so we get the patch release out.

**Comment by WardBrian** [comment]
No real rush on this, definitely after the patch is great
