### ISSUE TITLE
Jenkins needs clang-format installed

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2681]
## Description

[see log here](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/PR-2583/4/pipeline/14#step-32-log-7)
```
+ clang-format --version
/home/jenkins/workspace/Stan_Math_PR-2583@tmp/durable-7feb3ffc/script.sh: line 4: clang-format: command not found
```

I think the flatiron jenkins server needs to have clang-format installed on it

#### Current Version:
v4.3.0

**Comment by serban-nicusor-toptal** [comment]
Argh I probably didn't see it because it's not failing with exit code 0.
I'm on it!

**Comment by serban-nicusor-toptal** [comment]
clang-format added to the docker image.

```
clang-format --version
clang-format version 10.0.0-4ubuntu1
```
