### ISSUE TITLE
Make `arena_allocator` usable in std containers like `unordered_map` and others

### ISSUE THREAD

**Issue by cpp977** [stan-dev/math#2683]
## Description
The current `arena_allocator` cannot be used in c++ standard containers which are more complex than `std::vector` as for example `std::unordered_map`. There is a missing constructor for *rebinding* (see Additional info below):

```
template<typename U>
arena_allocator(const arena_alocator<U>& other);
```

## Example
The following does currently not compile:
```
#include <unordered_map>
#include "stan/math.hpp"

int main()
{
    std::unordered_map<int, int, std::hash<int>, std::equal_to<int>, stan::math::arena_allocator<std::pair<const int, int>>> m;
    m.insert(std::make_pair(1,1));
}
```
The compilation error is very lengthy because of missing concepts in c++17. But it basically tells that there is missing the respective constructor for `arena_allocator`.

## Expected Output
Compilation should be successful.

## Possible fix:
Add this to arena_allocator:
```
  arena_allocator() = default;

  arena_allocator(const arena_allocator& rhs) = default;

  template <class U>
  arena_allocator(const arena_allocator<U>& rhs) {}
```

## Additional info
See this SO discussion on custom allocators for std containers: 
https://stackoverflow.com/questions/64790174/stdunordered-map-with-custom-allocator-local-allocator-does-not-compile

#### Current Version:
v4.3.1

**Comment by SteveBronder** [comment]
Yes this would be nice! I don't have the bandwidth to do this atm but if you want to make a PR I'm happy to review. I think we just need to define all of the members and constructors like [`std::allocator`](https://en.cppreference.com/w/cpp/memory/allocator)

**Comment by SteveBronder** [comment]
Most of them should be simple since that allocator is just a wrapper around the stan's global stack allocator

**Comment by cpp977** [comment]
Yes it is sinple because the class is just a wrapper. The only constructor which is missing is the one described above. With this added, the class can be used as a replacement for `std::allocator`. I would like to submit a PR and I already have a fork with the change, however so far I did not look into the test suite of stan. But I can do und then run the tests before submitting the PR. It is probably also worth to add a test for the std containers with the `arena_allocator`.

**Comment by SteveBronder** [comment]
Yes our tests in `rev/core` should help you see what to do here

**Comment by spinkney** [comment]
@rok-cesnovar should we close this?

**Comment by rok-cesnovar** [comment]
Indeed, thanks!
