### ISSUE TITLE
Extension operands_and_partials to 8 edges

### ISSUE THREAD

**Issue by Franzi2114** [stan-dev/math#2698]
## Description
As I want to add a function with 8 known partials to the stan-math library (#2682), I had to extend the `operands_and_partials` routine such that it can work with 8 instead of 5 partial derivatives.

## Example
It is possible to fill up to 8 edges for `operands_and_partias`:
`ops_partials.edge8_.partials`= ...

## Questions
- [x] Do I have to set up an own Pull Request for this? Or can it go together with the Pull Request for the new function?
- [x] Which tests are required for this purpose before I ask can for the Pull Request?

#### Current Version:
v4.3.2

**Comment by bob-carpenter** [comment]
> can it go together with the Pull Request for the new function?

Yes.

> Which tests are required 

Value tests and then derivative tests for the function.  I'm not sure how `operands_and_partials` is tested itself, but you can follow whatever tests are already there.

**Comment by SteveBronder** [comment]
I think at the point we have 8 edges it might be good to turn the impl into having an underlying `std::tuple` just holding all the edges we need

**Comment by Franzi2114** [comment]
> I think at the point we have 8 edges it might be good to turn the impl into having an underlying `std::tuple`

Yeah, maybe that makes sense. But I would suggest that somebody does it at a later point of time since right now, the new 7-parameter function works with those few changes I did. And @bob-carpenter agreed to bring these changes in the same Pull Request as the new 7-parameter function. The change of the underlying structure sounds a bit more complex.

**Comment by Franzi2114** [comment]
This was done in PR #2833.
