### ISSUE TITLE
Wishart Cholesky parameterization

### ISSUE THREAD

**Issue by spinkney** [stan-dev/math#2705]
We can add the Cholesky parameterization on both X and Sigma or just on Sigma

In cpp we'd use LDLt so we don't have to `add_diag`.
```stan
  real wishart_cholesky_a_lpdf(matrix X, real n, matrix L) {
    int P = rows(L);
    real lp = (n - P - 1) * sum(log(diagonal(cholesky_decompose(add_diag(X, 1e-7)))));
    
    // normalizing constant
    // lp -= 0.5 * (n * P) * log2() + lmgamma(P, 0.5 * n);
     lp -= 0.5 * sum(diagonal(mdivide_left_tri_low(L, mdivide_left_tri_low(L, X)')));

    return lp - n * sum(log(diagonal(L)));
  }
  
   real wishart_cholesky_b_lpdf(matrix Lx, real n, matrix L) {
    int P = rows(L);
    real lp = (n - P - 1) * sum(log(diagonal(Lx)));
    matrix[P, P] LinvLx = mdivide_left_tri_low(L, Lx);
    
     // normalizing constant
    //  lp -= 0.5 * (n * P) * log2() + lmgamma(P, 0.5 * n);
    lp -= 0.5 * sum(diagonal(crossprod(LinvLx)));

    return lp - n * sum(log(diagonal(L)));
  }
```
The results equal to what the `CholWishart` R package has

```R
library(rethinking)
> L <- t(chol(rlkjcorr(1, 8, eta = 0.1)))
> Lx <- t(chol(rlkjcorr(1, 8, eta = 0.1)))

> dWishart(x = tcrossprod(Lx), df = 9, Sigma = tcrossprod(L), log = TRUE)
[1] -443.0111
> wishart_cholesky_a_lpdf(X = tcrossprod(Lx), n = 9, L = L)
[1] -443.0111
> wishart_cholesky_b_lpdf(Lx = Lx, n = 9, L = L)
[1] -443.0111
```

**Comment by bob-carpenter** [comment]
Neat.  That's really clean and should be OK to autodiff through in a direct C++ translation.  You can simplify even further replacing sum(diagonal(...)) with trace(...), which should have better autodiff properties.

I think we only need the "b" version.  The important case is where the variant is a Cholesky factor because that's the efficient data structure for covariance matrix parameters.

Can you figure out the adjoint-Jacobian update rule?  That is, let 

```
lp = wishart_cholesky_b_lpdf(Lx, n, L)
```

and figure out how to update `Lx.adjoint` and `L.adjoint` given `lp`, `Lx`, `L`, and `lp.adjoint`.

**Comment by spinkney** [comment]
I'll see if I can work out those adjoints. As for the `crossprod`, we can get rid of it because that matrix is lower triangular. In cpp we can use a lower triangular type to store and then a lower triangular multiply.

The updated version would be
```stan
   real wishart_cholesky_b_lpdf(matrix Lx, real n, matrix L) {
    int P = rows(L);
    real lp = (n - P - 1) * sum(log(diagonal(Lx)));
    matrix[P, P] LinvLx = mdivide_left_tri_low(L, Lx);
    
     // normalizing constant
    //  lp -= 0.5 * (n * P) * log2() + lmgamma(P, 0.5 * n);
    lp -= 0.5 * trace(multiply_lower_tri_self_transpose(LinvLx));

    return lp - n * sum(log(diagonal(L)));
  }
```

**Comment by bob-carpenter** [comment]
> we can use a lower triangular type to store and then a lower triangular multiply.

Thanks @spinkney.

Given that we only need the diagonal elements, it'll be a lot more efficient in memory to do this

```stan
for (p in 1:P)
  lp -= 0.5 * dot_product(LinvLx[p, 1:p]);
```

It might be faster to transpose `LinvLx` first because otherwise we're pulling out rows in a non-memory efficient manner.

**Comment by spinkney** [comment]
@bob-carpenter the b version needs a change of variables if we want to use this directly on Lx. 

```stan
real wishart_cholesky_b_lpdf(matrix Lx, real n, matrix L) {
    int P = rows(L);
    matrix[P, P] LinvLx = mdivide_left_tri_low(L, Lx);
    
    // normalizing constant
    lp -= P * log2() * (1 - 0.5 * n)  + lmgamma(P, 0.5 * n);

    for (p in 1:P) {
        lp -= 0.5 * dot_self(LinvLx[p, 1:p]) + n * log(L[p, p]) - (n - p) * log(Lx[p, p]);
    }

    return lp;
}
```
That's from slide 36 of https://www.maxturgeon.ca/w20-stat7200/slides/wishart-distribution.pdf. I believe that the normalizing constant in that presentation is wrong (it should have |\Sigma|^{n/2})
