### ISSUE TITLE
Add fwd mode for log1m_inv_logit.hpp

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/math#271]
#### Summary:
To vectorize `log1m_inv_logit.hpp`, we need to add a rev mode function.

#### Description:
We need to add rev mode function for `log1m_inv_logit.hpp`.

#### Reproducible Steps:
I found it while trying to vectorize the function.

#### Current Output:
There currently only is `log1m_inv_logit.hpp` in `stan/math/prim/scal/fun` and `stan/math/fwd/scal/fun`. The prim version is templated to handle the rev cases.

#### Expected Output:
There is versions of `log1m_inv_logit.hpp` in `stan/math/prim/scal/fun`, `stan/math/rev/scal/fun`, and `stan/math/fwd/scal/fun`.

#### Current Version:
v2.9.0

**Comment by bob-carpenter** [comment]
Rolled into #347
