### ISSUE TITLE
Update to Boost 1.78.0

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#2711]
## Description

Boost 1.79 was released in April, we are still at 1.75. We should try to keep up and upgrade.

Release notes for all version since 1.75: 
- https://www.boost.org/users/history/version_1_79_0.html
- https://www.boost.org/users/history/version_1_78_0.html
- https://www.boost.org/users/history/version_1_77_0.html
- https://www.boost.org/users/history/version_1_76_0.html

#### Current Version:
v4.3.2

**Comment by bgoodri** [comment]
There is nothing in the release notes for 1.79 about changes to Boost Math,
so I think 1.78 would be fine for now.
