### ISSUE TITLE
Add rev mode for logit.hpp

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/math#272]
#### Summary:
The logic function does not have a rev mode version, which we need to vectorize it.

#### Description:
Add a reverse mode version of logit.

#### Reproducible Steps:
I found it while trying to vectorize logit. Specifically, I used locate to do so.

#### Current Output:
There is a version of logit in `stan/math/prim/scal/fun/` and `stan/math/fwd/fun/`. The primitive version is templated.

#### Expected Output:
There is a version of logit in `stan/math/prim/scal/fun/`, `stan/math/rev/scal/fun/`, and `stan/math/fwd/fun/`.

#### Current Version:
v2.9.0

**Comment by bob-carpenter** [comment]
Why do you need a reverse version to template it?  The base version should work if instantiated.  Is there a problem with the basic implementation problem that prevents that?

It's OK to include reverse mode for logit either way --- it's good to have.

**Comment by bob-carpenter** [comment]
Rolled into #347
