### ISSUE TITLE
brew install stan-math

### ISSUE THREAD

**Issue by ankane** [stan-dev/math#2723]
Hi, it'd be great to add Stan Math (and eventually CmdStan) to Homebrew, so Mac users can install it with:

```sh
brew install stan-math
```

I've created [a formula](https://github.com/Homebrew/homebrew-core/pull/99934), but it requires patching, and Homebrew prefers patches to be accepted upstream. The two issues are:

1. Allowing system dependencies - #2659
2. `--disable-new-dtags` (in `make/compiler_flags`) errors with `unknown option` with Apple Clang

If these can be addressed, I think we can move things forward.

**Comment by WardBrian** [comment]
+1 to `--disable-new-dtags` needing to change, we also are patching it on the Conda version of cmdstan

**Comment by ankane** [comment]
Latest PR for 1: #2834
