### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ankane** [stan-dev/math#2724]
Hi, just fyi, the second link in the readme (for [Apache 2.0 License Evaluation](https://github.com/stan-dev/math/wiki/Apache-2.0-License-Evaluation)) is broken.

https://github.com/stan-dev/math/blob/e0884615b80182965f78cbf21cfe044d7b170e3b/README.md?plain=1#L21

This link is broken in the [Stan readme](https://github.com/stan-dev/stan/blob/0d7d1ec64ebc7244b35734e9aa9863ab4c2e9cb4/README.md?plain=1#L38) as well.

Edit: The contributing link is broken as well. https://mc-stan.org/math/contributing.html

Edit 2: Same with Sundials. The updated link is https://computing.llnl.gov/projects/sundials

**Comment by rok-cesnovar** [comment]
Thanks  @ankane, should be addressed by #2735

**Comment by ankane** [comment]
Thanks @rok-cesnovar!
