### ISSUE TITLE
Eigenvalues for non-symmetric matrix

### ISSUE THREAD

**Issue by nikunj410** [stan-dev/math#2733]
I was wondering if Stan developers are working on including a function to calculate eigenvectors and eigenvalues for a non-symmetric matrix. I realize that this feature exists for a symmetric matrix with real eigenvalues. I am assuming that since the support for complex vectors and matrices is going to be released in version 2.30, complex eigenvalue for a non-symmetric matrix should soon follow?

**Comment by WardBrian** [comment]
This has been implemented for real-valued matrices (see https://github.com/stan-dev/stanc3/pull/1192), but is still needed for when the input matrix is itself complex

**Comment by bob-carpenter** [comment]
Yes, @nikunj410, we should have general complex eigendecomposition in either the next release (2.30) or the one after.   We just finished adding 1D and 2D FFTs and inverses for 2.30 this week and general eigendecomposition is next.
