### ISSUE TITLE
remove <math.h> includes

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#277]
#### Summary:

Include `<cmath>` instead of `<math.h>` for the C++11 functions.  This obviously has to be staged after we start requiring C++11. 

#### Description:

math.h imports into top-level namespace `::` whereas `cmath` imports into `std::`.

~/cmdstan/stan/lib/stan_math((bbe2de0...))$ grep -R "math.h" stan
* [ ] stan/math/fwd/scal/fun/acosh.hpp:#include <math.h> C++11 only
* [ ] stan/math/fwd/scal/fun/asinh.hpp:#include <math.h>  C++11 only
* [ ] stan/math/fwd/scal/fun/atanh.hpp:#include <math.h> C++11 only
* [ ] stan/math/fwd/scal/fun/cbrt.hpp:#include <math.h> C++11 only
* [ ] stan/math/fwd/scal/fun/erf.hpp:#include <math.h> C++11 only
* [ ] stan/math/fwd/scal/fun/erfc.hpp:#include <math.h> C++11 only
* [ ] stan/math/fwd/scal/fun/expm1.hpp:#include <math.h>  C++11 only
* [ ] stan/math/fwd/scal/fun/fma.hpp:#include <math.h>  C++11 only
* [ ] stan/math/fwd/scal/fun/fmax.hpp:#include <math.h>  C++11 only
* [ ] stan/math/fwd/scal/fun/fmin.hpp:#include <math.h>  C++11 only
* [ ] stan/math/fwd/scal/fun/hypot.hpp:#include <math.h>  C++11 only
* [ ] stan/math/fwd/scal/fun/round.hpp:#include <math.h>  C++11 only
* [ ] stan/math/fwd/scal/fun/trunc.hpp:#include <math.h>
* [ ] stan/math/prim/scal/fun/fdim.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/acosh.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/asinh.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/atanh.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/cbrt.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/erf.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/erfc.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/expm1.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/fma.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/hypot.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/owens_t.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/round.hpp:#include <math.h>
* [ ] stan/math/rev/scal/fun/trunc.hpp:#include <math.h>

#### Reproducible Steps:

Just look at the source.

#### Current Version:
v2.9.0

**Comment by syclik** [comment]
The difficulty here is that not all of the functions in `math.h` were in `cmath` until C++11. Our Windows builds don't have C++11 enabled, so I'm going to use the boost versions for these includes, unless anyone sees a problem with it.

**Comment by bob-carpenter** [comment]
That's what you have to do until we go to C++11.

**Comment by syclik** [comment]
Yup. I'm already on it.

There's some silliness in boost's implementation. `std::erf(NaN) = NaN` using C++11 cmath. `boost::math::erf(NaN) = 1` using boost. Fun.

**Comment by bob-carpenter** [comment]
this was fixed as part of #370
