### ISSUE TITLE
jacobian returns wrong results in some situations

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#278]
#### Summary:
The jacobian function returns in special situations the wrong gradients.

#### Description:
The jacobian function in Stan uses the nested AD system to calculate gradients. As such the

set_zero_all_adjoints_nested(); 

function is used. Apparently, this leads to wrong results if the AD stack was never initialized before. So results are wrong if no stan::math::var was declared before the jacobian call. Replacing calls to set_zero_all_adjoints_nested();  with set_zero_all_adjoints(); seem to make the bug go away.

#### Reproducible Steps:

I am sending a cpp file to the dev list which shows the issue. When one uncomments the dummy definition of a var instance, then results are correct.

#### Current Output:
Current output depends on what happened before the call as described.

#### Expected Output:
Results  should not depend on a first declaration of a dummy variable.

#### Additional Information:
Reported on stan-users from Oleg Shirokobrod.

#### Current Version:
develop

**Comment by bob-carpenter** [comment]
My bad for not checking this closer on the first commit.

`recover_memory_nested()` calls need to be matched to `start_nested()` calls as in `stan/math/rev/mat/functor/gradient.hpp`.   It's just like `malloc` and `free` or `new` and `delete`.

@wds15  Please make these issues self contained by including all necessary code.  You can just cut-and-paste it into a code block.

**Comment by bob-carpenter** [comment]
Hmm.  After I wrote the comment, the top-level issue text disappeared.


```
#include <Eigen/Dense>
#include <iostream>
#include <iomanip>
#include <stan/math.hpp>

struct test_jac_functor
{
    template <typename T>
    inline
    Eigen::Matrix<T, Eigen::Dynamic, 1> operator()(const Eigen::Matrix<T, Eigen::Dynamic, 1>& x) const
    {
        assert(x.size() == 2);
        Eigen::Matrix<T, Eigen::Dynamic, 1> y(3);
        y(0) = pow(x(0), 1./3.) * exp(-x(1) / 3.);
        y(1) = (x(0) + 5.0 * x(1)) / (pow(x(0), 1./3.) * exp(-x(1) / 3.)); // y(1) = (x(0) + 5.0 * x(1)) / y(0)
        // y(2) = x(0) * x(1) - y(0) - y(1)
        y(2) = x(0) * x(1) - pow(x(0), 1./3.) * exp(-x(1) / 3.) - (x(0) + 5.0 * x(1)) / (pow(x(0), 1./3.) * exp(-x(1) / 3.));

        return y;
    }
};


int main()
{
  // without the dummy declaration, the jacobian is wrong below; maybe
  // using the nested AD system (which is used in the jacobian)
  // without initializing the AD system leads to wrong results?
  //stan::math::var dummy;
  //dummy = 1;

    test_jac_functor f;

    Eigen::VectorXd x(2);
    x << 2.0, 3.0;
    Eigen::VectorXd fx;
    Eigen::MatrixXd jac_fx(3, 2);

    stan::math::jacobian(f, x, fx, jac_fx);

    Eigen::VectorXd y(3);
    y(0) = std::pow(x(0), 1. / 3.) * std::exp(- x(1) / 3.);
    y(1) = (x(0) + 5. * x(1)) / y(0);
    y(2) = x(0) * x(1) - y(0) - y(1);

    Eigen::MatrixXd jac(3, 2);

    jac(0, 0) = std::pow(x(0), -2. / 3.) * std::exp(- x(1) / 3.) / 3.;
    jac(0, 1) = -std::pow(x(0), 1. / 3.) * std::exp(- x(1) / 3.) / 3.;

    jac(1, 0) = 1. / y(0) - (x(0) + 5. * x(1)) * jac(0, 0) / (y(0) * y(0));
    jac(1, 1) = 5. / y(0) - (x(0) + 5. * x(1)) * jac(0, 1) / (y(0) * y(0));

    jac(2, 0) = x(1) - jac(0, 0) - jac(1, 0);
    jac(2, 1) = x(0) - jac(0, 1) - jac(1, 1);


    std::cout << "Analytical values:" << std::endl;
    std::cout << "y(" << x(0) << ", " << x(1) << ") = " << std::endl;
    std::cout << std::setprecision(16) << y << std::endl;

    std::cout << "dy_i/dx_j(" << x(0) << ", " << x(1) << ") = " << std::endl;
    std::cout << std::setprecision(16) << jac << std::endl;


    std::cout << "Autodiff values:" << std::endl;
    std::cout << "y(" << x(0) << ", " << x(1) << ") = " << std::endl;
    std::cout << std::setprecision(16) << fx << std::endl;

    std::cout << "dy_i/dx_j(" << x(0) << ", " << x(1) << ") = " << std::endl;
    std::cout << std::setprecision(16) << jac_fx << std::endl << std::endl << std::endl;

    return 0;
}
```

**Comment by bob-carpenter** [comment]
I went and looked at the actual implementation and it does have `start_nested()`.  No idea why transposing the output produces an issue;  were there changes other than reordering the output?

**Comment by wds15** [comment]
Hi Bob!

The change which seems to cause this problem is going from (old)

`set_zero_all_adjoints();
`
to

`set_zero_all_adjoints_nested();
`

In the patch which corrected for the transposition I started to use the _nested version of set_zero_all_adjoints. If you replace the set_zero_all_adjoints_nested(); with set_zero_all_adjoints(); then all is fine again which is why I am suspecting some issue there.

BTW, I had to adjust the test in test/unit/math/rev/mat/fun/jacobian.hpp to also declare a dummy variable like I explained in the other thread. I guess that got lost.

So if someone could check the set_zero_all_adjoints_nested() function which apparently does not work correctly for the case when the AD stack is empty. This would be my diagnosis from this.

Thanks for reediting the issue, I tried to drop the cpp file here, but this is not possible. Code blocks are of course even better. Next time.

**Comment by bob-carpenter** [comment]
Thanks. That should help diagnose what's going on. I reassigned to myself.  I'll try to also check that the Hessians and other higher-order derivatives are doing the right thing, because they also use nesting.

Using `set_zero_all_adjoints()` isn't improper, just inefficient when you're doing nesting;  so at worst, we can go back to that for now if there's not a deeper fix before the next release.

**Comment by wds15** [comment]
Thanks Bob for taking over. Yes, we can simply use the `set_zero_all_adjoints()` in the jacobian function. Should I start this branch by reconfiguring the test I was referring to such that it will now fire a failure? Then you could take over and either fix the `set_zero_all_adjoints_nested()` or switch to `set_zero_all_adjoints()` in the jacobian function. Makes sense?

**Comment by syclik** [comment]
Yes, that would help a lot. Thanks!

**Comment by wds15** [comment]
Ok, you got it. The test

`test/unit/math/mix/mat/functor/autodiff_test.cpp`

on the branch `bugfix/issue-278-jacobian-nested` now fails.

**Comment by wds15** [comment]
I am confused that the travis run is ok. On my machine I get 

```
test/unit/math/mix/mat/functor/autodiff_test.cpp:135: Failure
Value of: J(1,0)
  Actual: -5
Expected: -9
[  FAILED  ] AgradAutoDiff.jacobian (0 ms)
```

when runing `./runTests.py test/unit/math/mix/mat/functor/autodiff_test.cpp`

**Comment by bob-carpenter** [comment]
I have a hunch as to what's going on, and will try to fix
it today.

- Bob
