### ISSUE TITLE
Expose variadic arguments for algebra_solver

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/math#2818]
## Description
The algebraic solvers, `algebra_solver_newton` and `algebra_solver_powell` aren't using variadic arguments. Most of the code seems to be already there but it is all wrapped in a function that still uses the strict function signature. We need to create the following updated signatures:

- `algebra_solver_newton(f, x0,  ...)`
- `algebra_solver_tol_newton(f, x0, scaling_step_size, function_tolerance, max_num_steps, ...)`
- `algebra_solver_powell(f, x0, ...)`
- `algebra_solver_tol_powell(f, x0, relative_tolerance, function_tolerance, max_num_steps, ...)` 

Open question: should we keep the `relative_tolerance` tuning parameter used for Powell's method? Right now, the two solvers have slightly different choices of tuning parameters, which has to do with the underlying algorithms they use. I think that's fine but it might be confusing to the user.

#### Current Version:
v4.4.0

**Comment by WardBrian** [comment]
The variadic interface would completely subsume the original, correct? I only ask because we currently have a technical restriction in Stanc where a variadic function cannot have non-variadic overloads

**Comment by charlesm93** [comment]
My plan is to only variadic arguments for `algebra_solver_powell` and `algebra_solver_newton` but keep the non-variadic `algebra_solver` for backward compatibility. The latter is a function we intend to deprecate, so I guess you'd need a warning message to that effect when compiling the Stan program.

But no, no overloading for variadic functions.

**Comment by WardBrian** [comment]
I don’t think my question was clear, we currently already have an exposed function called `algebra_solver _newton` with arguments`function algebra_system, vector y_guess, vector theta, data array[] real x_r, array[] int x_i ` - this is strictly a subset of the signatures a variadic version of this would allow, right? So any pre-existing usage of this function should be able to become the variadic version without any changes to the model

**Comment by charlesm93** [comment]
Thanks for clarifying. Yes, you're right. We actually won't break backwards compatibility. I got a little bit mixed up: in stan-math we do break backwards compatibility because we have to reposition the `std::ostream* const msgs` argument. But I now realize this "backwards breaking" won't propagate to the Stan language.

**Comment by charlesm93** [comment]
`stan-math` PR is in. Once this gets reviewed and merged, we can handle the Stan language. And *then* will properly clean up the doc.
