### ISSUE TITLE
Add tuple-returning versions of special functions

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/math#2845]
## Description

Tuple language support (https://github.com/stan-dev/stanc3/pull/1100) is nearing a point where I think this is worthwhile

Stan Math has many sets of functions which are often called together and could re-use computation if we return multiple items. For example, `eigenvalues` and `eigenvectors` are two functions for which a complementary function called `eigendecompose` which returned `std::tuple<Eigen::VectorXd, Eigen::MatrixXd>` would result in only half as much computation being required.

I believe some special care is needed to allow return-value-optimization in functions returning tuples, but perhaps `forward_as_tuple` is sufficient. 

## Example

Off the top of my head, here are some groups of functions which could use this treatment. 

- [ ] `eigenvalues` and `eigenvectors`
- [ ] `eigenvalues_sym` and `eigenvectors_sym`
- [ ] `qr_thin_Q`, `qr_thin_R`
- [x] `qr_R`, `qr_Q`
- [ ] `singular_values`, `svd_U`, and `svd_V`
- [ ] `complex_schur_decompose_t`, `complex_schur_decompose_u`
- [ ] `csr_extract_w`, `csr_extract_v`, and `csr_extract_u`

**Comment by nikunj410** [comment]
I work on matrix population models. Often we require both the right and left eigenvector of the matrix. Tupes would be a great way to get all that information in one go. Something like [complex_vector eigenvalues, complex_matirx right_eigenvector, complex_matirx left_eigenvector]
