### ISSUE TITLE
Testing: decrease impact of distribution tests on CI hardware

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/math#2872]
Recent Jenkins runs have been failing due to disk space, see e.g. [develop/139](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FMath/detail/develop/139/pipeline). 

@dylex informed me that the math workspaces were taking up nearly 1.2TB of disk space on the CI machines at Flatiron. It seems that this is a combination of us not cleaning up after ourselves properly and a recent increase in space per run, possibly due to #2864.

To mitigate this, we should both:

1. Properly clean up workspaces and discuss a policy to delete older ones automatically. This would unfortunately make the logs from old CI runs inaccessible after the chosen amount of time (suggestions from @dylex on how to implement this would be great).
2. Investigate why the increase in space happened, AND/OR consider moving the full run of the distribution tests to something which happens not on every merge but weekly/on a schedule

Pinging @rok-cesnovar and @serban-nicusor-toptal for thoughts and help

**Comment by rok-cesnovar** [comment]
Distribution disk space has always been kind of a problem (https://github.com/stan-dev/math/issues/397 - though this is on a completely different level size wise).

What uses the most space? Logs or executables? I imagine the created source tests files don't consume as much space?

**Comment by WardBrian** [comment]
I believe it is the object files, @dylex can confirm

**Comment by dylex** [comment]
The bulk of the space was `test/prob/{skew_normal,pareto_type_2,...}/*_generated_vv_test.o` files, a few thousand of them, each about 35M.

**Comment by WardBrian** [comment]
We kill any previous builds when we fire up a new one in PRs, but we intentionally exempt `develop` from this. I am not sure this is always necessary, besides if two PRs get merged close in time and we want to be absolutely certain we can determine which one failed (and this wouldn't be obvious from the test failure itself)?
