### ISSUE TITLE
refactor odeint integrator

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#288]
#### Summary:
Refactor odeint integrator to use new objects as ode_model and decouple_ode_states.

#### Description:
Rewrite odeint integrator using new components form CVODES branch.

#### Reproducible Steps:
None

#### Current Output:
None

#### Expected Output:
None

#### Additional Information:
Provide any additional information here.

#### Current Version:
develop

**Comment by syclik** [comment]
@wds15, I'm not convinced that this is the right way to make the code simpler, but I could be convinced.

Can you write down what you're trying to accomplish, why, and what this does to get us there? I looked at the way you had implemented `ode_model` and `decouple_ode_states` and I think it makes it harder to follow, not easier.

**Comment by wds15** [comment]
I will write up a bit of math (with LaTeX) and post it on the stan-dev list. This will make it a lot easier to explain it, I hope. To me, this is the only way which makes sense from a math point of view (ode_model). The decouple_ode_states I don't care so much about it, but it is a logic step.

**Comment by syclik** [comment]
@wds15, thanks!
