### ISSUE TITLE
Failure to build TBB when using GCC 13

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/math#2889]
## Description

First reported on the [forums](https://discourse.mc-stan.org/t/cmdstan-installation-fails-on-linux-issue-with-tbb/31125). Compiling with GCC13 yields

```
../tbb_2020.3/include/tbb/task.h:300:20: error: declaration of ‘tbb::task& tbb::internal::task_prefix::task()’ changes meaning of ‘task’ [-Wchanges-meaning]
```

TBB has an upstream (1-line) fix for this issue: https://github.com/oneapi-src/oneTBB/pull/833

We should either apply this patch to our vendored copy or update TBB. I'm not sure which route is preferred. 

#### Current Version:
v4.5.0

**Comment by WardBrian** [comment]
This change is one of three which have been made to the `tbb_2020` branch of oneTBB since the release of 2020.3 (what we use):

https://github.com/oneapi-src/oneTBB/compare/2020_U3...tbb_2020

We could reasonable incorporate all of them. I think oneTBB has fully moved on, so I don't expect these will ever make it into a "release" unless we'd be willing to jump up to the newer TBB versions (which we already support thanks to @hsbadr, at the moment behind an `#ifdef TBB_INTERFACE_NEW`)

**Comment by WardBrian** [comment]
RCppParallel applied this patch manually in January https://github.com/RcppCore/RcppParallel/commit/cdc74280f79dc68e44ba30f1f4162e976992f100

It seems like they're still using 2019.8. The 2020.3 we use is backwards compatible with this, but the newer 2021 versions (which are also when the name changed to "oneTBB") are not.

**Comment by rok-cesnovar** [comment]
The problem with oneTBB versions is that they switched to cmake I think.

**Comment by WardBrian** [comment]
I think the simplest thing to do is just do what Rcppparallel did and patch the issue in our vendored copy, sidestepping any questions about newer versions.

This currently only seems to affect gcc 13, but if I understand the original PR filed against TBB, this diagnostic is a requirement by C++23 so probably other compilers would start to complain over time

**Comment by wds15** [comment]
Sounds great.
