### ISSUE TITLE
Feature request: Incomplete beta function  

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#29]
_From @jzelner on February 14, 2014 14:59_

It would be great if the incomplete beta function was available in addition to the regular beta function. 

_Copied from original issue: stan-dev/stan#562_

**Comment by syclik** [comment]
_From @bob-carpenter on February 14, 2014 15:22_

Boost not only has incomplete beta (looks like there are four varieties), it also has a derivative,

http://erikerlandson.github.io/algorithm/libs/math/doc/html/math_toolkit/sf_beta/beta_derivative.html

**Comment by syclik** [comment]
_From @betanalpha on February 14, 2014 16:22_

Only one component of the gradient — the others are super nasty.
I implemented them for some of the CDFs but they aren’t going
to be close to computationally efficient.

**Comment by syclik** [comment]
_From @jzelner on February 14, 2014 16:30_

Just to provide a little bit of context in case it's helpful, I was hoping
to implement a continuous version of the binomial distribution as a way of
approximating a binomially distributed latent-variable where n*P < 1, so
that the normal approximation to the binomial doesn't hold.

The paper showing the derivation of the continuous binomial I'm working off
of is available here:

http://arxiv.org/pdf/1303.5990v1.pdf

It also includes a similarly useful continuous Poisson.

Thanks!

-Jon

**Comment by syclik** [comment]
_From @randommm on February 18, 2014 4:44_

This might be of help: http://www.jstatsoft.org/v03/i01 and https://gist.github.com/randommm/9064753

**Comment by bob-carpenter** [comment]
Exists in Stan 2.11 as `inc_beta`, so closing.
