### ISSUE TITLE
Rename integrate_ode to integrate_ode_rk45 and integrate_ode_cvode to integrate_ode_bdf

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#292]
#### Summary:
For v2.10, we want to rename:
- `integrate_ode` to `integrate_ode_rk45`
- `integrate_ode_cvode` to `integrate_ode_bdf`

#### Additional Information:
The Stan library will need to change. See stan-dev/stan#1886.

#### Current Version:
v2.9.0

**Comment by betanalpha** [comment]
It should be "bdf", the standard acronym for "backwards differentiation formula".

**Comment by syclik** [comment]
yeah... I caught it after I created the issues. They've all been fixed on
the two issues.

On Tue, May 3, 2016 at 3:15 PM, Michael Betancourt <notifications@github.com
> wrote:

> It should be "bdf", the standard acronym for "backwards differentiation
> formula".
>

**Comment by wds15** [comment]
This is great.

@syclik : You could consider to make the test

math/test/unit/math/rev/arr/functor/integrate_ode_tooMuchWork_test.cpp

run a lot faster. In that test we check that the too much work exception is thrown inside the integrate_ode function. The test is time-consuming right now as I had no way to reduce the default 1E6 admissible steps. So just reducing that number to 10 within the test should make the test run a lot faster and do the same work for us.

Just a thought.

**Comment by bob-carpenter** [comment]
Is there a reason this isn't a pull request yet?  I'm coding against it for the related Stan issue, which I won't be able to push until this is pushed.

**Comment by syclik** [comment]
No good reason. My first stab at it was wrong. I'll make it a pull request asap.

**Comment by syclik** [comment]
Fixed with #293.
