### ISSUE TITLE
Aliasing issue in OpenCL `assignment_impl`

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#2942]
## Description

Given the following test of addition of the same matrix together we get the wrong adjoints. This is caused by an aliasing issue, the inputs adjoint is reassigned instead of readded to the adjoints of the input.

```c++
TEST(OpenCLPrim, add_aliasing) {
  stan::math::matrix_d d1(3, 3);
  d1 << 1, 2, 3, 4, 5, 6, 7, 8, 9;
  using stan::math::matrix_cl;
  using stan::math::var_value;
  using stan::math::var;
  using varmat_cl = var_value<matrix_cl<double>>;
  varmat_cl d11 = stan::math::to_matrix_cl(d1);
  // Add the same matrix as the left and right hand side
  var res = stan::math::sum(stan::math::add(d11, d11));
  res.grad();
  // Get back adjoints
  Eigen::MatrixXd grad_res = stan::math::from_matrix_cl(d11.adj());
  stan::math::recover_memory();
  Eigen::Matrix<var, -1, -1> d_host = d1;
  // Same op as above but on the host
  var res_host = stan::math::sum(stan::math::add(d_host, d_host));
  res_host.grad();
  Eigen::MatrixXd grad_res_host = d_host.adj();
  std::cout << "OpenCL Adjoints: " << std::endl;
  std::cout << grad_res << std::endl;
  std::cout << "CPU Adjoints: " << std::endl;
  std::cout << grad_res_host << std::endl;
}
```

```
OpenCL Adjoints: 
1 1 1
1 1 1
1 1 1
CPU Adjoints: 
2 2 2
2 2 2
2 2 2
```

The issue here is in the `+=` operator of `adjoint_result`, where internally the `assignment_impl` is generating code. When the below code generates the OpenCL code, it does not know that the left and right hand side are the same matrix

```c++
template <typename T_a, typename T_b,
          require_all_prim_or_rev_kernel_expression_t<T_a, T_b>* = nullptr,
          require_any_var_t<T_a, T_b>* = nullptr,
          require_any_not_stan_scalar_t<T_a, T_b>* = nullptr>
inline auto add(T_a&& a, T_b&& b) {
  arena_t<T_a> a_arena = std::forward<T_a>(a);
  arena_t<T_b> b_arena = std::forward<T_b>(b);

  return make_callback_var(
      value_of(a_arena) + value_of(b_arena),
      [a_arena, b_arena](vari_value<matrix_cl<double>>& res) mutable {
        adjoint_results(a_arena, b_arena) += expressions(res.adj(), res.adj());
      });
}
```

Below is the generated OpenCL code with comments to show what is happening and where the issues are. The the very last two lines `var2_global` is being reassigned where it should be readded 

```opencl
/**
 * A kernel for the equivalent of Matrix += Matrix
 * @param[in/out] var2_global Pointer to array of doubles representing matrix
 * @param[in] var2_rows Rows of var2
 * @param[in] var2_view Whether the matrix is upper or lower triangular or plain
 * @param[in] var3_global Pointer to array of doubles representing matrix
 * @param[in] var3_rows Rows of var3
 * @param[in] var3_view Whether the matrix is upper or lower triangular or plain
 */
kernel void calculate(__global double* var2_global, int var2_rows, int var2_view,
    __global double* var3_global, int var3_rows, int var3_view){
    // Get the global ids for the cell we are working in
    int i = get_global_id(0);
    int j = get_global_id(1);
    // If var2 is lower or upper triangular and this cell is 
    //  not in the range of work, assign it a value of zero
    //  Otherwise assign it the value of var2 the cell works with
    double var2 = 0; 
    if (!((!contains_nonzero(var2_view, LOWER) && j < i) || (!contains_nonzero(var2_view, UPPER) && j > i))) {
        var2 = var2_global[i + var2_rows * j];
    }
    // Same for var3
    double var3 = 0; 
    if (!((!contains_nonzero(var3_view, LOWER) && j < i) || (!contains_nonzero(var3_view, UPPER) && j > i))) {
        var3 = var3_global[i + var3_rows * j];
    }
    // Make a temporary storing value of var2 + var3
    double var1 = var2 + var3;
    // Assign temp to var2
    var2_global[i + var2_rows * j] = var1;
    // PROBLEM HERE: Do the same thing
    double var4 = var2 + var3;
    var2_global[i + var2_rows * j] = var4;
}
```

```opencl
kernel void calculate(__global double* var2_global, int var2_rows, int var2_view,
    __global double* var3_global, int var3_rows, int var3_view){
    // Get the global ids for the cell we are working in
    int i = get_global_id(0);
    int j = get_global_id(1);
    var2_global[i + var2_rows * j] += var3;
    var2_global[i + var2_rows * j] += var3;
}
```

@t4c1 I'm going through the OpenCL codegen right now picking apart where/how I could get something like the above. I think the pattern I'd to generate would be something like the below where the output is just `+=`'d into and not stored as part of the temporaries leading to an assignment. I'm having trouble reading in the `+=` operator on how the codegen is happening here. Any tips or time you can take to look at this would be appreciated!

```opencl
kernel void calculate(__global double* var2_global, int var2_rows, int var2_view,
    __global double* var{N}_global, int var{N}_rows, int var{N}_view){
    // Get the global ids for the cell we are working in
    int i = get_global_id(0);
    int j = get_global_id(1);
    // Get the scalar for each input op
    double var{N} = 0; 
    if (!((!contains_nonzero(var3_view, LOWER) && j < i) || (!contains_nonzero(var3_view, UPPER) && j > i))) {
        var{N} = var{N}_global[i + var{N}_rows * j];
    }
    // Perform operations on each scalars
    double var{M} = OP(var{1:N}...);
    // Assign result to output
    var2_global[i + var2_rows * j] += var{M};
    // Assign next result to output
    double var{J} = OP(var{1:N}...);
    var2_global[i + var2_rows * j] += var{J};
}
```

I think adjoint accumulation is the only place where this is an issue. It's an issue in any place that's possible to have aliasing in the multi assignment, but for Stan's purposes that only really happens in the adjoint accumulation. An easy fix would just be to take anywhere we do a multi assign in adjoint ops and break it up into two separate kernels

```
adjoint_results(a_arena) += expressions(res.adj());
adjoint_results(b_arena) += expressions(res.adj());
```

## Expected Output

Adjoint accumulation is aliasing safe on for OpenCL

#### Current Version:
v4.7.0

**Comment by SteveBronder** [comment]
I'm going to sort out more of this tmrw but the base issue is here where the lhs is being used on both sides. I need to modify that to something like 

https://github.com/stan-dev/math/blob/develop/stan/math/opencl/rev/adjoint_results.hpp#L49


```
            auto nonscalars = std::make_tuple(std::make_pair(
                std::get<Is_nonscal>(nonscalars_tmp).first,
                    std::get<Is_nonscal>(nonscalars_tmp).second)...);
```

And then I _think_ I can write a `plusequals_impl` sort of like `assignment_impl` that just does `+=` instead of `=`

**Comment by t4c1** [comment]
I think this can be fixed without defining a new operation by changing the order of the operations in a multi result kernel. Instead of first doing all right hand side operations and than all left hand side and assignments, it could do all operations for the first assignment first and than all for the second one and so on. I think this will be simpler and more general to other operations.

**Comment by SteveBronder** [comment]
I think I get what you mean. I'll look into how we construct things in `parts` to see if I can modify it to do first op then second op instead of all rhs ops then all lhs ops.

**Comment by t4c1** [comment]
You are right, I misread the code the first time. I did not see that the the generated code actually assigns to the same variable twice. Yeah, what you are suggesting is probably the simplest way to handle that, but you will probably need to separately handle all compound assignment operators. Alternatively you could try to do something general by manipulating the maps with already generated expressions when a left hand side expression is repeated, but that will likely be harder to design.
