### ISSUE TITLE
linspaced_array returns int, but should return real

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#3022]
## Description

The `linspaced_array` function returns integers when it should return real numbers.

Thanks to [Rodrigo Silva](https://discourse.mc-stan.org/u/Rodrigo_Silva) for reporting on the forums.

## Example

```stan
transformed data {
  array[5] real y = linspaced_array(5, 1.1, 5.5);
  print("y = ", y);
}
```

Output is:

```
Chain [3] y = [1,2,3,4,5]
```

## Expected output

```
y = [1.1,2.2,3.3,4.4,5.5]
```

#### Current Version:
v4.8.1

**Comment by WardBrian** [comment]
It seems like this was introduced in https://github.com/stan-dev/math/pull/2312/commits/c3226b072c85606ecf8660a81bd1a368a2693859 as a result of a misread review comment

The tests never directly assign this to `std::vector<double>`, but I'm still surprised they compiled.
