### ISSUE TITLE
Question: documentation or publication about varmat (var<mat>)

### ISSUE THREAD

**Issue by MaxSagebaum** [stan-dev/math#3047]
I could not find a better conntact to the stan-math library developers. So please excuse me if I overlooked something.

By browsing the developer documentation (https://mc-stan.org/math/md_doxygen_2contributor__help__pages_2reverse__mode__types.html) I just found a reference to the `varmat` or (`var_value<Matrix>`) matrix implementation of stan-math library. I could not find any other references, documentation or publications about this topic. 

So I wanted to ask if there is some?

**Comment by SteveBronder** [comment]
Wow thank you for pointing this out. There absolutely should be! I'll put this on my todo list soon

**Comment by MaxSagebaum** [comment]
You are welcome. ;)
