### ISSUE TITLE
Reconsider Makefile including config from `$HOME`

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/math#3088]
## Description
Stan's makefiles include custom configuration from a couple locations. 

The first is `make/local`, and this is what we document and recommend using.

The second is a sub-directory of `$HOME`:
https://github.com/stan-dev/math/blob/4c626fddcdaba37c988190f805b2fff3f80e80dc/makefile#L14

This can cause issues [when HOME has a space in the path](https://discourse.mc-stan.org/t/cmdstan-path-has-not-been-set-yet-windows-cmdstanr-0-8/35398/7?u=wardbrian) (found by @andrjohns)

I don't think we document this file anywhere, and I also think that allowing a global config like this is probably a bad idea in general. 

#### Current Version:
v4.9.0

**Comment by SteveBronder** [comment]
idk anyone that uses this so I'm pretty for removing it
