### ISSUE TITLE
speed up log determinant calculation

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#31]
_From @bob-carpenter on April 2, 2014 0:25_

Kyle Foreman reports on stan-users:

```
...the log_determinant of the dense matrix was substantially slower in Stan than R. Last time I tried it in Stan was in December so maybe things have changed, but at that time the log determinant of a 2000x2000 matrix took on the order of 100x longer to compute in Stan than R.

I was computing it in the transformed data block, at 1000 samples of p (which is the only parameter that the log determinant varies by, and is constrained [0,1)). That way I only have to do it once (well, 1000 times, but just during initialization), and in the model block can then simply do a linear interpolation of the log determinant based on the value of parameter p. 
```

Maybe there's a better algorithm than what we're using?  Looks like we can use Cholesky decomposition in LDLT if the matrix is positive definite.

_Copied from original issue: stan-dev/stan#613_

**Comment by syclik** [comment]
_From @kforeman on April 2, 2014 0:58_

Here's a quick R script that demonstrates the issue:
```
# simulate precision matrix
    library(stats)
    n <- 1000
    S <- rWishart(1, n+1, diag(n))[,,1]

# calculate log determinant in R
    system.time(ldet_R <- determinant(S, logarithm=TRUE)$modulus[[1]])
    print(ldet_R)

# stan code for just calculating determinant
    stan_code <- '
        data {
            int n;
            matrix[n,n] S;
        }
        transformed data {
            real ldet_stan;
            ldet_stan <- log_determinant(S);
            print(ldet_stan);
        }
        parameters {
            real x; // stan errors out without something here
        }
        model {
        }
    '

# compile model in advance so it doesn't factor into timing
    library(rstan)
    set_cppo('fast')
    m <- stan_model(model_code=stan_code)

# run a single iteration
    system.time(
        sampling(
            m,
            chains=1,
            iter=1,
            data=list(n=n,S=S)
        )
    )
```
The R version takes 0.34s vs 28.19s for Stan. (MBPr 13" 2013)

If I remove the ```log_determinant()``` step from the Stan model it takes 0.26s for data transfer etc, so subtract that off and Stan is still about 100x slower than R.

**Comment by syclik** [comment]
Kyle,

I just ran it on my MacBook Pro Retina 2012 and got these numbers:
R - 0.275
Stan - 0.434

I'm using clang++, rstan 2.2.0, R 3.0.3.

What are you on?


Daniel

**Comment by syclik** [comment]
_From @kforeman on April 2, 2014 5:38_

rstan 2.1.0
R 3.0.2
g++ from Apple LLVM version 5.1, clang-503.0.38 (OSX 10.9.1)

I guess g++ on this particular system is the issue. I didn't realize it
before, but it looks like even the latest Xcode developer tools come from
the badly outdated gcc 4.2.x series.

I now compile and run all my models from the command line on a unix cluster
for exactly this reason, so I know I'm using the compiler and library
versions I want. But I switch back to rstan on my local machine when
writing snippets/tutorials to share since that's what most of my colleagues
run.

I'll have to look into updating my local machine so as to not lead anyone
astray - terribly sorry if I started any wild goose chases!

**Comment by syclik** [comment]
_From @betanalpha on April 2, 2014 7:36_

It’s worth repeating — don’t ever compute the determinant straight up.
Cholesky and then compute the log determinant from the diagonal elements;
it’s much faster and more stable.  The functions may be smart enough to
do this but it’s not guaranteed (I don’t think Eigen does this by default, for example).

**Comment by syclik** [comment]
_From @mbrubake on April 4, 2014 15:37_

Our log_determinant function could be a bit smarter than it is, so it's
worth looking into this at some point.

Also, to Michael's point, we have a log_determinant_spd function which uses
the Cholesky factorization.  log_determinant uses a QR factorization.



On Wed, Apr 2, 2014 at 3:36 AM, Michael Betancourt <notifications@github.com

**Comment by bgoodri** [comment]
I don't think there is any action here.
