### ISSUE TITLE
lub_constrain log abs derivative might be wrong?

### ISSUE THREAD

**Issue by acertain** [stan-dev/math#3103]
https://github.com/stan-dev/math/blob/develop/stan/math/prim/constraint/lub_constrain.hpp implements ladj as `log(b-a) - |x| + 2*log1pexp(-|x|)`. I was implementing the same in julia and I derived it as `log(b-a) + x - 2*log1pexp(x)`:

![image](https://github.com/user-attachments/assets/f592509a-3a54-4109-9be0-1a08f0cec9eb)

**Comment by nhuurre** [comment]
[Line 110](https://github.com/stan-dev/math/blob/9b1f08be7e76c6468fc2fcf2f75d641a619ae349/stan/math/prim/constraint/lub_constrain.hpp#L109-L110) implements `log(b-a) - |x| - 2*log1p_exp(-|x|)` which is equal to your formula when `x < 0`.
When `x > 0` it's
```
 log(b-a) - |x| - 2*log1p_exp(-|x|)
= log(b-a) - x - 2*log1p_exp(-x)
= log(b-a) - x - 2*log( 1+exp(-x) )
= log(b-a) - x - 2*log( exp(-x)*(exp(x)+1) )
= log(b-a) - x - 2*( log(exp(-x)) + log(exp(x)+1) )
= log(b-a) - x - 2*(-x) - 2*log1p_exp(x)
= log(b-a) + x - 2*log1p_exp(x)
```
as expected.

I think it's written with the absolute value to avoid potential loss of precision. Adding a small correction (`2*log1p_exp(-|x|)`) to a large term (`|x|`) always gives an accurate result, but adding two large terms can suffer from rounding errors. This level of caution seems unnecessary to me: the result is always order of `|x|` so there's no real risk of [catastrophic cancellation](https://en.wikipedia.org/wiki/Catastrophic_cancellation); rounding errors can only change the least significant bit or two.

**Comment by acertain** [comment]
Oh, thanks for the help
