### ISSUE TITLE
rename probability functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#320]
#### Summary:

Rename probability functions to match the language definitions.
#### Description:
- [ ] `_log` to  `_lpdf` or `_lpmf`
- [ ] `_log_cdf` to `_lcdf`
- [ ] `_log_ccdf` to `_lccdf`

This will hugely simplify the code generation component of Stan.
#### To Do
- [ ] Rename functions
  - [ ] Update function name
  - [ ] Update documentation
  - [ ] Update file name
  - [ ] Update tests
- [ ] Figure out how to test distributions (might not need to change the generated code)
- [ ] Update makefile appropriately
#### Current Version:

v2.10.0

**Comment by syclik** [comment]
Do we need to worry about backwards compatibility here?

- `normal_log()` should be renamed to `normal_lpdf()`
- Do we need to keep a `normal_log()` function that's deprecated that calls `normal_lpdf()`; if so, how do we deal with deprecation?

**Comment by bob-carpenter** [comment]
We need to maintain backward compatibility until Stan 3.0.  
At that point, I can do the do-si-do in stan-dev/stan to get
rid of the _log suffixes in the math lib and the language.

For now, we should add a doxygen command for each of the _log
forms:

  @deprecated ---how to replace it---

along with the @param etc.  See:

  https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmddeprecated

**Comment by syclik** [comment]
Thanks. That makes sense.
