### ISSUE TITLE
integer division by zero isn't caught

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#321]
_From @bob-carpenter on July 25, 2016 19:39_

#### Summary:

Integer divide by zero throws an uncaught exception.

#### Description:

Running this crashes RStan:

```
library(rstan)

mc <- '
parameters {real theta;}
model {
  target += 1/0;
}
'
sm <- stan_model(model_code = mc)
post <- sampling(sm, show_messages = FALSE)
```

I'm reporting in Stan because in the command refactor, we'll be catching this in Stan itself.

#### Reproducible Steps:

See above.

#### Current Output:

Crashes with `Floating point exception: 8

#### Expected Output:

Informative error message.

#### Additional Information:

Originally reported by @davharris on RStan tracker in issue https://github.com/stan-dev/rstan/issues/316

#### Current Version:
v2.10.0

_Copied from original issue: stan-dev/stan#1974_

**Comment by syclik** [comment]
The problem is in math:
https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/fun/divide.hpp#L25

This line has undefined behavior:
```
return std::div(x, y).quot;
```

I didn't realize it threw an exception outside of the `stdexcept` types. Any suggestions on how to fix this call?

**Comment by syclik** [comment]
_From @bob-carpenter on July 25, 2016 21:57_

Overload for int and check for zero in denominator?

Do you know what it does throw?  If so, you could catch
and rethrow.

- Bob

**Comment by syclik** [comment]
The internet is saying check for 0, so that's the fix I'll apply.

**Comment by bob-carpenter** [comment]
Why use div(x, y).quot rather than (x / y)?  We don't
need the remainder and I'd think it'd be slower to create
a struct with both and then just pull the quotient out.

And that second y in the domain_error could be replaced
with 0.   Always better to use constants than variables.

    inline int divide(const int x, const int y) {
      if (unlikely(y == 0))
        domain_error("divide", "denominator is", y, "");
       return std::div(x, y).quot;
    }

I was really just curious.  I can't imagine anything we
do with integer division will make much of a difference
given that it's rare and fast no matter how we do it.

- Bob

**Comment by syclik** [comment]
Honestly, I have no idea why it was implemented this way. I wanted to get a quick fix in, so I left the code and trapped the div by 0. 

We could easily replace it.
