### ISSUE TITLE
Add test for multiple translation units

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#328]
#### Summary:
We should check that new changes to the math library allow it to be compiled in multiple translation units.

#### Description:
We have a use case of the math library being compiled in multiple translation units and then linked. We fixed the math library with #311. We should continue to test that this is allowed going forward.

#### Reproducible Steps:
Not sure yet. Will need to look at @rgiordan's code in #311.

#### Current Output:
Compiles.

#### Expected Output:
Compiles in the future.

#### Current Version:
v2.11.0

**Comment by syclik** [comment]
@rgiordan mind sending over the actual calls that are called within the command line? I'm not familiar with CMake and its magic.

So... something like:
```
clang++ -I . -isystem lib/eigen_3.2.8 -isystem lib/boost_1.60.0 -isystemlib/cvodes_2.8.2/include -Wall -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DNO_FPRINTF_OUTPUT -pipe -Wno-unknown-warning-option -Wno-unused-function -Wno-tautological-compare -Wno-c++11-long-long -Wsign-compare -Wno-unused-local-typedef -ftemplate-depth=256    -O3 lib/gtest_1.7.0/src/gtest_main.cc ...
```

Once I know what steps need to happen, I'll add a test.

**Comment by rgiordan** [comment]
Sure!  Something like the below should do the trick using the source?.cpp
files foundin the StanHeaderExample repo
<https://github.com/rgiordan/StanHeaderExample>.  Obviously, set
GIT_REPO_LOC to wherever the headers are found on the test system.


GIT_REPO_LOC=/home/rgiordan/Documents/git_repos/

for SOURCE in source1.cpp source2.cpp; do
echo "Compiling "$SOURCE
/usr/bin/c++ \
-DStanHeaderExample_EXPORTS -O3 -DNDEBUG -fPIC -std=c++11 -Wno-deprecated \
-I${GIT_REPO_LOC}/math \
-I${GIT_REPO_LOC}/math/lib/eigen_3.2.8 \
-I${GIT_REPO_LOC}/math/lib/boost_1.60.0 \
-o ${SOURCE}.o -c ${SOURCE}
done

echo "Linking"
/usr/bin/c++ -fPIC -O3 -shared -Wl,-soname,libStanHeaderExample.so \
-o libStanHeaderExample.so \
source1.cpp.o source2.cpp.o

**Comment by syclik** [comment]
@rgiordan do you happen to get warnings like: "the table of contents is empty"?

**Comment by syclik** [comment]
Btw, I'm not getting issues linking when I use `ar` directly to link a static library. I can't get your example to work as-is. I'll try again later.

**Comment by rgiordan** [comment]
No, I don't get that warning.  I'll try the static linker when I get a
moment a little later.  In the meantime, if you get it to work and don't
need me to follow up please let me know.

**Comment by rgiordan** [comment]
What ar command are you using exactly?  Sorry, I'm not an expert in this
stuff.

When I, for example, define Function2 in source1.cpp so that there is an
obvious clash with the definition of Function2 in source2.cpp, then the
linker command

```
/usr/bin/c++  -fPIC -O3 -DNDEBUG  -shared
-Wl,-soname,libStanHeaderExample.so \
-o libStanHeaderExample.so \
source1.cpp.o source2.cpp.o
```

...fails, but the archive command

```
ar -rcs source.a source1.cpp.o source2.cpp.o
```

...does not.  So this ar command, at least, is not testing the problem.
But maybe you were doing something different.
