### ISSUE TITLE
Clean up math library

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#331]
#### Summary:
I'm finding a lot of `using stan::math::*;` inside the code base. I'm in the middle of implementing a bunch of other stuff and wanting to change this. I figured I should put all the cosmetic changes that don't affect behavior on one branch.

#### Description:
Clean up code.

#### Current Version:
v2.11.0

**Comment by bob-carpenter** [comment]
That's redundant now that everything's inside of the `stan::math` namespace.  Could you list the other changes as you make them so it's easier to review?

**Comment by syclik** [comment]
Will do! This will be a completely cosmetic fix, but it'll help me as I
move forward with other issues.
