### ISSUE TITLE
Bernoulli RNG throws exceptions too aggressively

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/math#332]
#### Description:
Describe the issue as clearly as possible.

Right now the ```bernoulli_rng``` function throws an exception if the input probability is 0 or 1, even though the actual generator can handle those cases fine.

#### Reproducible Steps:

Try evaluating ```stan::math::bernoulli_rng(0, rng)``` or ```stan::math::bernoulli_rng(1, rng)```.

#### Current Output:

```stan::math::bernoulli_rng: Probability parameter is {0/1}, but must be between (0, 1)```

#### Expected Output:

```{0/1}```, depending on the input probability.

#### Additional Information:

The call to ```check_bounded(function, "Probability parameter", theta, 0, 1);``` should just be replaced with 

      check_less_or_equal(function, "Probability parameter", theta, 1.0);
      check_greater_or_equal(function, "Probability parameter", theta, 0.0);

as in ```binomial_rng.hpp```.

#### Current Version:
v2.11.0

**Comment by betanalpha** [comment]
I take it back -- it looks like ```check_bounded``` is indeed inclusive and those tests run fine.  Instead I was seeing a probability that was some epsilon above 1 due to floating point precision that triggered the exception.  That said, it would make sense to change the error message to ```[lower, upper]``` to make that more clear.  I can make a new issue if anyone thinks that's relevant.

**Comment by bob-carpenter** [comment]
You can just patch it at the same time and submit a pull
request.  Should be easier to just fix it than try to
communicate what you want to someone else.

- Bob
