### ISSUE TITLE
Remove unnecessary comments and commented code

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#335]
#### Summary:
There are unnecessary comments floating around the code base and chunks of commented code. Both should be removed.

#### Additional Information:
Here's an example:
```c++
template <typename T1, typename T2, int R, int C> Eigen::Matrix<typename boost::math::tools::promote_args<T1, T2>::type, R, C> elt_divide(const Eigen::Matrix<T1, R, C>& m, T2 s) { 
  return divide(m, s); 
  // TODO(carp): divide(m, s); 
} 
```

#### Current Version:
v2.11.0

**Comment by bob-carpenter** [comment]
Fixed with pull request #360
