### ISSUE TITLE
Rename stan::math::domain_error to throw_domain_error

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#339]
#### Summary:

Rename functions that throw exceptions. 
#### Description:

Rename our math functions so it's clearer what it does. In certain places we have to fully qualify the name due to the one in std still being in scope. 
#### Current Version:

v2.11.0

**Comment by mcol** [comment]
I have patches for this if it's still wanted.

**Comment by rok-cesnovar** [comment]
Yes, please! :)
