### ISSUE TITLE
add reverse() function for arrays and vectors

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#344]
#### Summary:

`reverse(x)` should return the elements of x in reversed order.
#### Description:

This allows, for example, a decreasing vector type by reversing an increasing one.
#### Current Version:

v2.11.0

**Comment by bob-carpenter** [comment]
Marco --- I assigned you to this because you wrote most of the other shape and order wrangling functions.  If you don't want to do it, please just unassign yourself.  No rush, I gave it a target milestone of Future.

**Comment by linwangidd** [comment]
Hello. May I know if the "reverse(x)" function still not available in current version of Rstan?

**Comment by bob-carpenter** [comment]
Correct.  Nobody's implemented it.  It should be an easy first issue as it doesn't interact with anything else and it's a simple algorithm.

**Comment by bob-carpenter** [comment]
P.S.  Almost any program using `reverse` outside of transformed data (where it'll only occur once) should probably be reshaped so that's not necessary.
