### ISSUE TITLE
elementwise versions of unary functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#347]
#### Summary:

There are functions like `log2()` and `log1p()` that are still not vectorized for elementwise application to containers.

#### Description:

All of our unary functions should be vectorized.  Review the index of the manual and make sure every unary function is vectorized.  Here are the ones for this issue:

* [x] `acosh`
* [x] `asinh` (?)
* [x] `atanh`
* [x] `exp2`
* [x] `log1m_inv_logit`
* [x] `log1p`
* [x] `log2`
* [x] `log_inv_logit`
* [x] `logit`
* [x] `Phi_approx`
* [x] `trigamma`
* [x] `trunc`

#### Current Version:
v2.11.0

**Comment by bob-carpenter** [comment]
See #202, which was only partially completed.

**Comment by bob-carpenter** [comment]
See also #272 for `logit()`  and #271 for `log1m_inv_logit`

**Comment by bob-carpenter** [comment]
This was blocked before due to ambiguous functions.  It's fixed with a judicious application of namespace qualifications and Boost `enable_if` and `disable_if` qualifications.  Now that I have `log1p` working I should be able to knock off the rest in no time.  It will not require reverse-mode specializations as suggested in #272 and #271 (now closed).

**Comment by MatsuuraKentaro** [comment]
Stan manual v2.17 says `pow` is not vectorized yet. Do you have a plan?

**Comment by bob-carpenter** [comment]
Yes, but it's going slowly.  We should just vectorize that function (and the ^ syntax to go with it) rather than trying the general solution which Rayleigh Lei is working on.
