### ISSUE TITLE
Specialized gradients for cov_exp_quad

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/math#353]
#### Summary:

Compute gradients for cov_exp_quad.

#### Description:

Add rev/mat/fun/cov_exp_quad.hpp to the library.
Return gradients with respect to:

- [ ] length-scale
- [ ] amplitude
- [x] amplitude and length-scale

#### Current Version:
v2.11.0

**Comment by rtrangucci** [comment]
@syclik and I decided to focus on the more common scenarios where length-scale and/or amplitude are vars rather than the less common scenario where the inputs are vars.

**Comment by rtrangucci** [comment]
@bob-carpenter @syclik As I code this up, I can't help but think we'd benefit from introducing a few new matrix types to the math library. If we introduced symmetric matrices and lower triangular matrices, we'd be able to take advantage of optimizations for matrix and array operations that Eigen provides for both scenarios (selfadjointView() for symmetric matrices, and triangularView() for lower triangular matrices). 

With all that being said, I'd like to talk through potentially adding a matrix var type, with values stored as a member double matrix and adjoints stored as a member double matrix, but whose values are allocated in our arena. As it stands, it seems like we're copying values and adjoints far too many times (think about a cov_exp_quad -> cholesky_decompose -> multiply -> sum) and should be able to store one pointer to a matrix vari rather than n^2 pointers to varis.

**Comment by betanalpha** [comment]
> With all that being said, I'd like to talk through potentially adding a matrix var type, with values stored as a member double matrix and adjoints stored as a member double matrix, but whose values are allocated in our arena. As it stands, it seems like we're copying values and adjoints far too many times (think about a cov_exp_quad -> cholesky_decompose -> multiply -> sum) and should be able to store one pointer to a matrix vari rather than n^2 pointers to varis.
> 

+1

**Comment by syclik** [comment]
@rtrangucci, do you think we'll want to implement a specialized version for var inputs? If so, could you create an issue for that?
