### ISSUE TITLE
Reduce overpromotion in rev/mat/fun/multiply.hpp

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/math#355]
#### Summary:

multiply(real, matrix) potentially overpromotes either argument from double to var
#### Description:

Specialize the multiply(real, matrix) explicitly for the scenario where either argument is a double.
#### Current Version:

v2.11.0

**Comment by syclik** [comment]
@thelseraphim, do you have a few free cycles? Can you tackle this? I think this should have a huge impact on everyone's runtime.

**Comment by bob-carpenter** [comment]
This is a big one if anyone wants to work on it.  @rtrangucci --- this one's up your alley.
