### ISSUE TITLE
Update cholesky_decompose to use inplace decomposition per Eigen 3.3

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/math#359]
#### Summary:

Rewrite cholesky_decompose to perform decompostion inplace.
#### Description:

Current cholesky_decompose creates a new matrix, L_factor, requiring its own memory, in the LLT decomposition.

Current code:

```
Eigen::Matrix<double, -1, -1> L_A(value_of_rec(A));
Eigen::LLT<Eigen::MatrixXd> L_factor
= L_A.selfadjointView<Eigen::Lower>().llt();
check_pos_definite("cholesky_decompose", "m", L_factor);
L_A = L_factor.matrixL();
```

Using Eigen 3.3 this can be avoided, with something like:

```
Eigen::Matrix<double, -1, -1> L_A(value_of_rec(A));
Eigen::LLT<Eigen::Ref<Eigen::MatrixXd> > L_factor(L_A);
check_pos_definite("cholesky_decompose", "m", L_factor);
```

Outlined here: http://eigen.tuxfamily.org/dox-devel/group__InplaceDecomposition.html
#### Additional Information:

Clearly requires that RcppEigen moves up to Eigen3.3 before we implement this feature.
#### Current Version:

v2.11.0

**Comment by syclik** [comment]
This was closed with #549.
