### ISSUE TITLE
check_greater etc. for two vector views

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#366]
#### Summary:

Both Pareto and Wiener distributions require an inequality between two arguments, so this can't be done with test framework and leads to ad hoc code duplication inside the density definitions.
#### Description:

Create comparison tests in the test framework that make `VectorView`s that require two arguments to stand in a relation.  I'm not quite sure how to do this and report the errors properly (the containers should print container index but non-containers shouldn't).  As is, the comparison is between a single argument with a vector view and a fixed bound (e.g., 0).

Then apply it to both the Pareto and Wiener distributions.

Ideally, this would also get pushed through the probability function test framework.  It would require a complete set of arguments to be tested for invalidity rather than argument-by-argument as it is now.
#### Current Version:

v2.11.0

**Comment by syclik** [comment]
Although this issue still exists, I'm closing the issue. I'm tagging it with the label `wasn't fixed` so we can find it later if we need.
