### ISSUE TITLE
Add rev multiply upgrade to v2.12.0 release notes

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/math#388]
#### Summary:

We should call attention to the fact that reverse mode multiply(matrix, matrix), multiply(matrix, vector), and multiply(vector, vector) received significant speedups in 2.12.

#### Description:

Change `RELEASE-NOTES.txt`

#### Current Version:
v2.12.0

**Comment by bob-carpenter** [comment]
Indeed!

To make the release notes, I just go through the
pull requests in reverse chronological order back
to the last release.  Looking at commits is too
confusing.  

- Bob

**Comment by syclik** [comment]
I tend to look at the titles of the issues and closed pull requests *for the milestone*. I look into the details when it's unclear from the titles. (I've looked at almost every issue and PR, so I tend to remember enough details for a summary based on title.)

For anyone following along, please tag issues with milestones and labels if possible.
