### ISSUE TITLE
Still have multiple definitions when including Stan headers in several source files

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#394]
#### Summary:

There are many linker errors when trying to build a shared object out of compiled Stan programs, as in R packages that use the rstanarm build process, which currently glues all the C++ files together before compiling to avoid this problem. This was only partially fixed in #311 .

#### Description:

There are many linker errors when trying to build a shared object out of compiled Stan programs, as in R packages that use the rstanarm build process, which currently glues all the C++ files together before compiling to avoid this problem. This was only partially fixed in #311 .

#### Reproducible Steps:

Try to build rstanarm without this workaround.

#### Current Output:

[linker_errors.txt](https://github.com/stan-dev/math/files/478257/linker_errors.txt)

#### Expected Output:

Successful package build

#### Current Version:
v2.12.0

**Comment by syclik** [comment]
@bgoodri, can you spell out instructions on how to reproduce? Bob and I are going to talk about this tomorrow. (It takes me a while figuring out what I need and how to call it, so if you have instructions, that would be really useful.)

**Comment by bgoodri** [comment]
https://github.com/stan-dev/stan/issues/1149#issuecomment-192535899

**Comment by syclik** [comment]
@bgoodri, I verified this issue. It's not in math anymore. It's in Stan and RStan. I'll create new issues there.
