### ISSUE TITLE
reduce distribution test disk space

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#397]
#### Summary:

Distribution tests can't run on my notebook because they require more than 60GB of disk space.   Reduce memory requirements.
#### Reproducible Steps:

Run distribution tests and check disk space before and after.
#### Current Output:

Crash due to running out of disk space.
#### Expected Output:

Run all the way through.
#### Current Version:

v2.12.0

**Comment by seantalts** [comment]
As @bgoodri, compiling distribution tests into maybe folder-level executables with ThinLTO should significantly save disk space and reduce compilation time. This seems like something exciting to look into.

**Comment by bgoodri** [comment]
Exciting is not the word I would have used, but it should be done. Also,
with g++, you can pass -flto=jobserver to the linker and it will use
multiple cores to link the shared object after compiling but not
unoptimizing the C++ files.

**Comment by rok-cesnovar** [comment]
Closing in favor of https://github.com/stan-dev/math/issues/2613
