### ISSUE TITLE
Add a choose(n, k) function

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#400]
#### Summary:
There is no `int choose(int n, int k)` function.

#### Description:
In Stan programs, you have to declare things like
`matrix[(N * (N - 1)) / 2, K] X;`
which throws a parser warning for integer division. It would be better to have
`matrix[choose(N, 2), K] X;`

#### Reproducible Steps:

Parse 
```
data {
  int<lower=0> N;
}
transformed data {
  matrix[(N * (N - 1)) / 2, 3] X;
}
model {}
```

#### Current Output:

```
DIAGNOSTIC(S) FROM PARSER:
Warning: integer division implicitly rounds to integer. Found int division: (N * (N - 1)) / 2
 Positive values rounded down, negative values rounded up or down in platform-dependent way.
```

#### Expected Output:

That is the expected output, but the expected output is stupid.

#### Current Version:
v2.12.0

**Comment by bob-carpenter** [comment]
Added with pull request #401
