### ISSUE TITLE
elementwise divide(scalar, matrix), divide(scalar, vector), and divide(scalar, row_vector)

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#405]
#### Summary:

I think it'd be nice to allow

```
vector[3] a;
vector[3] b = 4 / a;
```

where it'd be defined elementwise and similarly for matrices.  This would then get pushed up to the Stan language as an operator.

Also a function `inv(vector)` where `inv(v) = 1 / a`.  
#### Current Version:

v2.12.0

**Comment by bgoodri** [comment]
I think we also need inv(vector), which would be equivalent to 1 / vector.

**Comment by bob-carpenter** [comment]
@bgoodri  Good idea. Added to the summary above.

**Comment by bob-carpenter** [comment]
We could also have double `c` version of `c / v` test `c == 1` and use `inv(v)`.

**Comment by rok-cesnovar** [comment]
All these statements compile on develop:

```stan
    vector[3] a;
    row_vector[3] a1;
    vector[3] b = 4 ./ a;
    vector[3] c = a ./ 4;
    vector[3] d = inv(a);
    row_vector[3] e = 4 ./ a1;
    row_vector[3] f = a1 ./ 4;
```

Closing.
