### ISSUE TITLE
Remove const from primitive function arguments

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#408]
#### Summary:
For any function arguments with `const` modifiers to primitive types, we want to remove the `const` modifier.

#### Description:
The `const` modifier doesn't do anything here.

#### Additional Information:
This won't alter any behavior. This will just clean up the code base a bit and make it more consistent.

#### Current Version:
v2.12.0

**Comment by bgoodri** [comment]
Why the opposition to const? I was taught by a guy who wrote the C++ code in pacemakers to const things to prevent the compiler from letting you accidentally assign to them inside the function and to signal to the reader that those things are not modified by the function.

**Comment by thelseraphim** [comment]
I think the point is we're passing them by value anyway, so const doesn't do anything for us. Daniel finished the changes here:

https://github.com/stan-dev/math/pull/409

**Comment by bob-carpenter** [comment]
Exactly.

- Bob
