### ISSUE TITLE
implement derivatives of remaining matrix functions

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#41]
_From @PeterLi2016 on August 8, 2014 19:39_

This will speed up matrix distributions and stability of the derivatives.

For instance, all the mdivide_ functions and the trace_ functions.

_Copied from original issue: stan-dev/stan#836_

**Comment by bob-carpenter** [comment]
This issue isn't specific enough, so I'm closing.  Basically, we should have matrix derivatives everywhere possible.
