### ISSUE TITLE
cholesky_decompose for reverse-mode is returning a reference to a local variable in upper-triangular elements of the matrix

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#415]
#### Summary:
The reverse-mode implementation of `cholesky_decompose` is returning a matrix with `vari` pointers that are pointing to a local variable which falls out of scope.

#### Description:
This is where the vari is created locally:
https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/fun/cholesky_decompose.hpp#L147

Here's where the pointer to the local variable is used:
https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/fun/cholesky_decompose.hpp#L158

When the `vari` is accessed, like in a matrix multiply, the `vari` would have fallen out of scope. This could cause a seg fault or just wrong answers.

One solution is to replace line 147 with:
`vari* dummy = new vari(0.0, false);`

and replace line 158 with:
`L.coeffRef(k, j).vi_ = dummy;`

There may be a better solution.

#### Reproducible Steps:
This is really hard to reproduce since it's returning a reference to a local variable. I was able to reproduce it on my machine on branch: `feature/0187-eigen-3.3` running:
```
./runTests.py test/unit/math/rev/mat/fun/cholesky_decompose_test.cpp
```

But... this isn't guaranteed to fail. It runs fine with optimization set at 0 or if I throw in print statements.

#### Additional Information:
This bug may exist in other matrix functions. I believe we should sweep over them all to make sure we don't have pointers to local variables.

I'm tagging @rtrangucci and @mbrubake because they should know about this bug.

@rtrangucci, can you help me walk through the reverse mode and try to eliminate this if we can find any other instances?

Thanks @bob-carpenter for helping me track this down.

#### Current Version:
v2.12.0

**Comment by syclik** [comment]
Maybe we can add a test to check that every `vari*` is on one of the stacks. 

I think we can also add the 0 value to the no chain stack preemptively and use that.

**Comment by bob-carpenter** [comment]
@syclik  Did you say you found other instances?  

This one was tricky to track down.  The print statements causing differing behavior was the clue that it was something optimization-related.

**Comment by syclik** [comment]
I did a quick search, but I haven't found anything.

I'm adding an ability for us to catch this. I'll update our tests to make
sure everything is on the stack. I'm hoping it's just cholesky_decompose.

**Comment by rtrangucci** [comment]
Yikes, I'm sorry about introducing this bug. I'll fix it ASAP.

I can also walk through the reverse mode with you to find other instances.


Rob

**Comment by syclik** [comment]
should be soon.

**Comment by syclik** [comment]
I've already fixed it on a branch. Just review the code when I'm done.

**Comment by rtrangucci** [comment]
Sounds good


Rob
