### ISSUE TITLE
beta_rng returning NaN values

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#419]
#### Summary:

In some cases for small inputs, `beta_rng` returns NaN values.
#### Description:

It should never return NaN.  We should just underflow or overflow or whatever.

See:  https://en.wikipedia.org/wiki/Beta_distribution#Generating_beta-distributed_random_variates

My guess is that both gamma variates are 0, because it's the only way to get NaN if you generate X and Y according to a gamma and then return (X / (X + Y)).
#### Reproducible Steps:

```
parameters {
  real y;
}
model {
  y ~ normal(0, 1);
}
generated quantities {
  real alpha;
  real beta;
  alpha = 1e-10;
  while (alpha < 1e10) {
    beta = 1e-10;
    while (beta < 1e10) {
      real z;
      z = beta_rng(alpha, beta);
      if (is_nan(z))
        print("alpha = ", alpha, "; beta = ", beta);
      beta = beta * 10;
    }
    alpha = alpha * 10;
  }
}
```
#### Current Output:

```
alpha = 1e-10; beta = 1e-09
alpha = 1e-10; beta = 1e-08
alpha = 1e-10; beta = 1e-07
alpha = 1e-10; beta = 1e-06
alpha = 1e-10; beta = 1e-05
alpha = 1e-10; beta = 0.0001
alpha = 1e-09; beta = 1e-10
alpha = 1e-09; beta = 1e-09
alpha = 1e-09; beta = 1e-08
alpha = 1e-09; beta = 1e-07
alpha = 1e-09; beta = 1e-06
alpha = 1e-09; beta = 1e-05
alpha = 1e-09; beta = 0.0001
alpha = 1e-08; beta = 1e-10
alpha = 1e-08; beta = 1e-09
alpha = 1e-08; beta = 1e-08
alpha = 1e-08; beta = 1e-07
alpha = 1e-08; beta = 1e-06
alpha = 1e-08; beta = 1e-05
alpha = 1e-08; beta = 0.0001
alpha = 1e-08; beta = 0.001
alpha = 1e-07; beta = 1e-10
alpha = 1e-07; beta = 1e-09
alpha = 1e-07; beta = 1e-08
alpha = 1e-07; beta = 1e-07
alpha = 1e-07; beta = 1e-06
alpha = 1e-07; beta = 1e-05
alpha = 1e-07; beta = 0.0001
alpha = 1e-07; beta = 0.001
alpha = 1e-06; beta = 1e-10
alpha = 1e-06; beta = 1e-09
alpha = 1e-06; beta = 1e-08
alpha = 1e-06; beta = 1e-07
alpha = 1e-06; beta = 1e-06
alpha = 1e-06; beta = 1e-05
alpha = 1e-05; beta = 1e-10
alpha = 1e-05; beta = 1e-09
alpha = 1e-05; beta = 1e-08
alpha = 1e-05; beta = 1e-07
alpha = 1e-05; beta = 1e-06
alpha = 1e-05; beta = 1e-05
alpha = 1e-05; beta = 0.0001
alpha = 1e-05; beta = 0.001
alpha = 0.0001; beta = 1e-10
alpha = 0.0001; beta = 1e-09
alpha = 0.0001; beta = 1e-07
alpha = 0.0001; beta = 1e-06
alpha = 0.0001; beta = 1e-05
alpha = 0.0001; beta = 0.0001
alpha = 0.0001; beta = 0.001
alpha = 0.001; beta = 1e-09
alpha = 0.001; beta = 1e-08
alpha = 0.001; beta = 1e-07
alpha = 0.001; beta = 1e-06
alpha = 0.001; beta = 1e-05
alpha = 0.001; beta = 0.0001
alpha = 0.001; beta = 0.001
```
#### Expected Output:

Nothing printed.
#### Current Version:

v2.12.0

**Comment by bob-carpenter** [comment]
@thelseraphim:  I assigned this to you because you've been mucking about in the RNG code recently.  If you do'nt want to do it, just unassign yourself and assign it to me and I'll take a look.

**Comment by bgoodri** [comment]
If both shape parameters of the beta distribution approach zero at the same rate, then the beta distribution converges to a Bernoulli with probability 0.5.

**Comment by thelseraphim** [comment]
Ok, so there is a slight mathematical issue here in addition to the underflow problem, and it has some history. If alpha and beta were allowed to actually be zero, we would be sampling from the improper Beta(0,0) distribution, this thing was apparently considered by Haldane who wanted to use this distribution to represent complete ignorance.

Unfortunately, if we had a random variable x on (0,1) which was distributed with pdf proportional to x^{-1}(1-x)^{-1} we would find that logit(x) was a uniformly distributed real number. Not so nice!

I'd love to fix this but I don't actually know what answer we should give, short of doing something really silly like draw a Unif([-L,L]) for some huge L and take inverse logit. Would we be ok with that approximation? It isn't going to put enough mass at the endpoints but actually nothing will.

Sorry for the radio silence on this issue till now.

**Comment by thelseraphim** [comment]
From this perspective we ought to behave the same here as we do if someone tries to sample a normal with overflowingly large scale parameter. What happens?

**Comment by syclik** [comment]
We draw really large numbers.

**Comment by thelseraphim** [comment]
I guess it is nice to give people the illusion that they're getting samples from the specified distribution, but if we're sampling from what is effectively an improper distribution, we're giving them answers that are at best arbitrary. Is there a way we could warn here?

There's a human problem here, which is that if we let our random number generators fail, people are going to see missing data and try to model that. This sounds like a nightmare to me, and very difficult to automate.

But is it better to give them arbitrary answers? Sounds like up to now the policy is to always return a number, which is just meaningless for bad choices of parameters. I actually like returning NaN in this case, but not for the stupid 0/0 reason.

**Comment by bgoodri** [comment]
Returning even one `NaN` from generated quantities messes up posterior means, R-hat, etc. In this case, the limiting distribution of the beta is a proper Bernoulli distribution. It is like drawing from a Poisson when the second parameter to a negative binomial overflows. So I don't see a problem except that we don't really know that the shape parameters are approaching zero at the same rate so we just have to pretend.

**Comment by thelseraphim** [comment]
You know, a little messing around with this and I basically agree with you though I'd like to know exactly what kind of convergence that is. The situation is actually that if a and b are comparable near zero the Beta(a,b) is approximately Bernoulli(a/(a+b)). I'll try to return that

**Comment by bob-carpenter** [comment]
The right thing to do (in that it matches both the standard
library functions and Boost) is to return the overflowed
or underflowed or rounded value, then set a static flag that there
was an overflow error (this is what std lib does and Boost can
be configured to do) or throw an overflow exception (Boost can
alternatively be configured to do this).

For the beta, the rounding points are 0 and 1.

If we try drawing from something like lognormal_rng(-10000, 1), then
we will probably get rounding to 0 in the draws, not an error.  

With:

generated quantities {
  real z_low;
  real z_high;
  z_low = lognormal_rng(-10000, 1);
  z_high = lognormal_rng(10000, 1);
}

I get the expected rounding to 0 and overflow to +infinity:

        mean se_mean   sd  2.5%   25%   50%   75% 97.5% n_eff Rhat
z_low   0.00    0.00 0.00  0.00  0.00  0.00  0.00  0.00    50  NaN
z_high   Inf     NaN  NaN   Inf   Inf   Inf   Inf   Inf    50  NaN

- Bob

**Comment by bgoodri** [comment]
Does Theorem 1 and the appendix of
http://ww2.amstat.org/publications/jse/v12n2/zhu.pdf help?

**Comment by bgoodri** [comment]
If we believe both shape parameters are approaching zero at the same rate,
then the realization should be 0 or 1 each with probability 0.5.

**Comment by bob-carpenter** [comment]
Right, and if they're different, don't they converge to to
Bernoulli(alpha / (alpha + beta))?  That's the only way to
get the mean right.  I don't know where the cutoff is where
we'd want to kick over.  

In R, even at alpha = beta = 0.001, we get:

> print(rbeta(1, 0.001, 0.001), digits=15)
[1] 3.04663389213028e-166

> print(rbeta(1, 0.001, 0.001), digits=15)
[1] 5.56268464626986e-312

> print(rbeta(1, 0.001, 0.001), digits=15)
[1] 1

This is because you can't get nearly as close to 1 as you can get
to 0 (roughly 1e-15 vs. 1e-300 or so).   We need complementary beta 
RNGs for this (easy given the symmetry)!

The case we need to look out for in using the gamma generators
for A / (A + B) is the case where A + B == 0;  nothing else should
return NaN.  But I'm not sure how to do this --- do we try the
gamma strategy and then do something else if there are numerical
issues?

**Comment by sakrejda** [comment]
+1 that seems to be the right way to go. K

**Comment by bob-carpenter** [comment]
I think you may have missed the discussion on the mailing list.
But you came to the same conclusion as Ben, that we need the
mean of the Beta as the parameter for the Bernoulli, which 
is a / (a + b).

I also mentioned that we can get a lot closer to 0 (about 1e-300)
with double-precision floating point than to 1 (about 1 - 1e-15).
So we have a bit more latitude when a << b in Beta(a, b).

I'm not sure what the right thing to do numerically.  We'd like
to return values near 0 or 1 if possible.  So maybe generate with
the gamma then if that produces NaN go to the Bernoulli?

I think we want to discourage people from mucking around down
at Beta(1e-4, 1e-4) anyway.  So maybe a warning in the doc would
help, too.  

- Bob

**Comment by bob-carpenter** [comment]
But they're not approaching zero at all.  We're just trying
to deal with rounding error.  For example if someone just
fixes data a = 1e-4 and b = 1e-6, we want a 1/100 chance of
generating a 1, I think, and a 99/100 chance of generating
a zero.  But what I'm confused about is that because this one's
skewed toward zeros, we might be able to get away without the
Bernoulli approximation for some draws.  Or maybe if it were
a = 1e-3 and b = 1e-5.

**Comment by bgoodri** [comment]
I think to get a NaN out, both a and b have to underflow to 0 or a has to
overflow to infinity. Whether we are numerically stable with extreme values
that do not underlow or overflow is a somewhat different issue.

**Comment by bob-carpenter** [comment]
> On Oct 25, 2016, at 3:15 PM, bgoodri <notifications@github.com> wrote:
> 
> I think to get a NaN out, both a and b have to underflow to 0 or a has to
> overflow to infinity.

Right, where a and b here are the gamma draws, not the parameters.
If both are zero, we need to call the Bernoulli.  

If a is zero and b not zero, return 0 by rounding.

If a is infinity and b is finite, return 1 by rounding.

If a and b are both zero, return the Bernoulli draw.

I think that makes sense.

**Comment by thelseraphim** [comment]
You know what the really right answer is here? we should defer to our dirichlet rng, which has no such underflow problems. It lives in log-world. Any objection to doing that?

**Comment by bob-carpenter** [comment]
Fewer implementations floating around would be great.  I
should've realized we had that because I think I'm the one
who revised the Dirichlet implementation.

**Comment by saudiwin** [comment]
This is way late, but I've been doing some work with the beta distribution with discrete bounds using ordinal cutpoints. You can see the paper here: https://osf.io/preprints/socarxiv/2sx6y/.

Basically, I think you could use the same approach here, except the cutpoints are fixed at the limit of machine precision. With a fixed probability you get the overflow/underflow or the Beta distribution/floating point precision highest/lowest limit. 

It strikes me that this problem is fundamental to using floating point precision with the Beta distribution. It really should be all done on the log scale.
