### ISSUE TITLE
Remove unnecessary using statements from vectorized functions

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/math#426]
#### Summary:

Some of the functions vectorized in #202 have an unnecessary using `stan::math::` statement that can be removed.
#### Description:

See above.
#### Reproducible Steps:

Look in the code. If it's including a function defined in `stan/math/prim/scal/fun/` and has an using `stan::math::` statement, remove the using statement.
#### Current Output:

The using statement is there.
#### Expected Output:

The using statement should be removed.
#### Additional Information:

Provide any additional information here.
#### Current Version:

v2.12.0

**Comment by bob-carpenter** [comment]
This is a much bigger issue.  When you're in a namespace, you don't need the namespace qualification.  I'll go through and get rid of all the using statements of the form `using stan::math::X;` and all the qualifications `stan::math::`.

**Comment by syclik** [comment]
Closing. This was fixed with #1155.
