### ISSUE TITLE
neg_binomial_2_lpmf returns positive values when phi is very large (~1e15)

### ISSUE THREAD

**Issue by KariOlson** [stan-dev/math#428]
#### Summary:
I've noticed neg_binomial_2_lpmf sometimes returns values > 0. These would correspond to pmf > 1 (which is not possible).  It seems to occur only when phi is a very large number (on the order of 1e15).

#### Description:
When neg_binomial_2_lpmf returns positive values, constraints are violated, samples are rejected.  Sometimes very large phi occur due to random initialization or during sampling.

#### Reproducible Steps:
R script and Stan model for a reproducible example are attached.  
[negBin2_error.stan.txt](https://github.com/stan-dev/math/files/562885/negBin2_error.stan.txt)
[negBin2_error.r.txt](https://github.com/stan-dev/math/files/562886/negBin2_error.r.txt)

4 inits are given showing that large phi generates errors. This model is cut down from a more complex model so some choices may seem odd (like checking lpmf > 0 or calculating log prob of data in the transformed parameters section).

#### Current Output:
Reject statement is activated in chains initialized with large phi showing lmpf value calculated (and inputs).

#### Expected Output:
Never execute this reject with Y, mu, and phi all well-defined.

#### Additional Information:
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] MASS_7.3-45        shinystan_2.2.1    shiny_0.13.2       plyr_1.8.3         rstan_2.12.1       StanHeaders_2.12.0 ggplot2_2.1.0     

#### Current Version:
v2.12.0

**Comment by thelseraphim** [comment]
I've just reproduced this bug on my side in pure cmdstan. It's definitely some kind of overflow problem with ultra-large values of phi. I agree that it should never happen, I'll try to track it down. Thanks for the report!

**Comment by thelseraphim** [comment]
(by the way, recalling that phi is inverse overdispersion, if you know phi is going to be ultra-large you're in the limiting regime where you could just replace this thing by a poisson(mu). Of course you can't always know that in advance, and this is still a bug.)

**Comment by KariOlson** [comment]
right, a poisson would be a better model in that case... I've tried it many revisions of this model ago and found that the poisson had some significant issues in the larger context (and usually phi is not this large). I'm not initializing with large phi intentionally in my model, just using it to create reproducibility of the error.
