### ISSUE TITLE
densities for (inverse) Wishart over Cholesky factors

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#43]
_From @bob-carpenter on September 19, 2014 21:57_

It would be more efficient to have densities that can be used like

```
cholesky_factor_cov[K] L;
L ~ wishart_cholesky(..,L0);
Sigma <- L * L';
```

Where `Sigma` would then have a Wishart density and `L0` would be the cholesky factor of the parameter. 

_Copied from original issue: stan-dev/stan#1037_

**Comment by syclik** [comment]
_From @bgoodri on September 19, 2014 23:25_

This is explained on page 142 on the Stan manual. We just need a C++
implementation that calls normal_log(), chi_squared_log(), and makes an
easy change-of-variables for the diagonal elements.

**Comment by spinkney** [comment]
closing duplicate of #2714 and #2710
