### ISSUE TITLE
vectorize _rng functions

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#45]
There are two ways to vectorize these.

#### Multiple I.I.D. draws

Add number of draws as first argument and generate multiple returns, e.g.,

```
vector[5] x = normal_rng(5, 0, 1);
```

#### Vectorized Parameters

Add vectorized versions of existing RNG functions, e.g., `normal_rng(mu, sigma)` where the variables `mu` and `sigma` would be either scalars or sequences such that if they were both sequences, they have the same shape.  This is going to require some template metaprogramming to compute return type and also some expression templates for vector-like views of the arguments.  This would allow us to have things like:

```
vector[3] mu = { 1, 2, 3 };
real sigma = 2.5;
vector[3] y_sim = normal_rng(mu, sigma);
```

A decision has to be made about return type and possible argument combinations.  Would we allow `normal_rng(vector, row_vector)`, and if so, what is the return type?

For multivariate distributions, we'd allow arrays of the input type `T` as `std::vector<T>` and we'd return `std::vector<R>` where `R` is the return type.

**Comment by bob-carpenter** [comment]
Would also be good if the vectorized RNGs would accept vector arguments like `dnorm` in R and broadcast the smaller ones.  We already have the `VectorView` framework in place for this.  With vector arguments, we don't need a redundant numerical argument, so there are really two extensions:

* vector argument(s)

* number of repetition arguments with scalars

The second is much easier as it's basically just a bunch of loops.

**Comment by bob-carpenter** [comment]
For example, for the normal distribution, we would want to support these three signatures in Stan:

```
vector normal_rng(vector mu, real sigma);
vector normal_rng(real mu, vector sigma);
vector normal_rng(vector mu, vector sigma);
```
with broadcasting of the scalar to a vector.

Then we could also have
```
vector normal_rng(int N, real mu, real sigma);
```
to generate N draws with a single pair of parameters.

**Comment by bbbales2** [comment]
I opened a pull req. to get started on this: https://github.com/stan-dev/math/pull/573 . Hopefully I didn't go too far off the beaten path.

**Comment by bob-carpenter** [comment]
I didn't realize you were working on this, as I just suggested to someone else that they work on it.  I'll try to fish out your email and respond that way as I don't know the other person's GitHub handle, so I can't call it out here.

**Comment by bob-carpenter** [comment]
I will take a look when I get a chance, but I'm getting bombarded by people wanting me to look over code these days.

**Comment by bbbales2** [comment]
Haha, I wasn't working on it till yesterday -- it's no problem if the pull I made gets replaced. I was just getting annoyed at having to write for loops for things that in the model were nicely vectorized so I figured I'd give it a go.

**Comment by rok-cesnovar** [comment]
@bbbales2 We can close this one right?

**Comment by bbbales2** [comment]
I think so.
