### ISSUE TITLE
Clean up code in stan/math/prim/mat/fun/matrix_exp_pade.hpp

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#456]
#### Summary:
`stan/math/prim/mat/fun/matrix_exp_pade.hpp` isn't quite up to our C++ style.

#### Description:
From @bob-carpenter referring to L22: https://github.com/stan-dev/math/blob/a64c69c13e597db40d6dcff6c9d2241228fcaac7/stan/math/prim/mat/fun/matrix_exp_pade.hpp#L22
> I didn't catch this the first time, but I really don't like this style of declaring a variable `result` way up here and then not using it until line 31.  It should be declared and defined both on line 31.  It also saves constructing a matrix that's never used (the nullary constructor gets called in the first declaration without a definition, though `Eigen::Matrix` is minimal compared to `std::vector` in its default constructor).

#### Current Version:
v2.13.0

**Comment by charlesm93** [comment]
I'm also renaming the variable `result` `pade_approximation`.
