### ISSUE TITLE
better out of bounds message on size zero arrays

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#458]
_From @bob-carpenter on November 24, 2016 4:28_

#### Summary:

Out of bounds messages are confusing for size zero (and arguably other) arrays.

#### Reproducible Steps:

```
transformed data {
  int N;
  real x[N];
}
model {
  x[1] ~ normal(0, 1);
}
```

#### Current Output:

When sampling through CmdStan:

```
Exception thrown at line 6: []: accessing element out of range. index 1 out of range; expecting index to be between 1 and 0; index position = 1x
```

#### Expected Output:

instead of "between 1 and 0" say "less than or equal to array size = 0".  

Also, get rid of that `x` that seems to be riding along.

#### Current Version:
v2.12.0

_Copied from original issue: stan-dev/stan#2129_

**Comment by bob-carpenter** [comment]
I started changing this to the following, but I'm going to take @syclik's advice and kick this one over to him.

```
 message << function << ": accessing element out of range."
              << " index " << index << " out of range;"
              << " expecting index >= 1 and index <= size = " << max
```

**Comment by syclik** [comment]
@bob-carpenter, from the original bug report, the `x` is the name of the variable. Any suggestions on how we can incorporate the variable name into the message?

**Comment by bob-carpenter** [comment]
You could either drop it into the generic message, or in the case of size zero entries, it could just say `error indexing empty container x` in the case where the size is zero.

```
message << function << ": accessing element out of range in variable: " << name_of_x << ";"
              << " index " << index << " out of range;"
              << " expecting index >= 1 and index <= size of " << name_of_x << " = " << max << "." 
              << std::endl;
```
I think there's some inconsistency throughout the code with whether we have `std::endl` at the end of all of our error messages or if we add them later.
