### ISSUE TITLE
invalid partial specialization in LDLT_factor

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#476]
#### Summary:

The development version of clang++ fails to compile Stan programs

#### Description:

In https://github.com/stan-dev/math/blob/develop/stan/math/prim/mat/fun/LDLT_factor.hpp#L56
`class template partial specialization is not more specialized than the primary template`
which is defined on line 13 of that file.

#### Reproducible Steps:

0. Install the development version of clang++
1. Try to compile a Stan program

#### Current Output:

> In file included from /usr/local/lib/R/site-library/rstan/include/rstan/rstaninc.hpp:3:
In file included from /usr/local/lib/R/site-library/rstan/include/rstan/stan_fit.hpp:18:
In file included from /usr/local/lib/R/site-library/StanHeaders/include/src/stan/model/test_gradients.hpp:6:
In file included from /usr/local/lib/R/site-library/StanHeaders/include/src/stan/model/log_prob_grad.hpp:4:
In file included from /usr/local/lib/R/site-library/StanHeaders/include/stan/math/rev/mat.hpp:11:
In file included from /usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat.hpp:28:
In file included from /usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/err/check_ldlt_factor.hpp:6:
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/LDLT_factor.hpp:56:11: error: class template partial specialization is not more specialized than the primary template
      [-Winvalid-partial-specialization]
    class LDLT_factor<T, R, C> {
          ^
/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/mat/fun/LDLT_factor.hpp:13:11: note: template is declared here
    class LDLT_factor;
          ^
1 error generated.

#### Expected Output:

None

#### Additional Information:

Tell me how to fix this because I'll have to release a new StanHeaders

#### Current Version:
v2.14.0

**Comment by bob-carpenter** [comment]
That template design's terrible.  Should be easy to fix.  The problem is that there's a forward declaration

```
template <typename T, int R, int C>
class LDLT_factor;
```

and then a declaration

```
template <int R, int C, typename T>
class LDLT_factor<T, R, C> {
  ...
```

It's all in the `stan::math` namespace, so this is easy to fix.

**Comment by bgoodri** [comment]
So, I can just get rid of the forward declaration?

**Comment by syclik** [comment]
Do we need to be up to date with the development version of clang++?

(if it's an easy fix, we should fix it; if we need to be up to date, then
we need to have some automated way of testing this. that said, I don't want
to code to a moving target.)

**Comment by bgoodri** [comment]
CRAN tests packages with all sorts of compilers that we don't test. I don't
think we even test with the latest released version of clang++. But this
particular compiler is not moving that much since it is scheduled for RC on
January 12.
