### ISSUE TITLE
appending arrays

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#481]
#### Summary:

Implement the function

```
T[] append(T[] a, T[] b);
```

That appends two arrays together.

#### Additional Information:

Once this is added here, create an issue in stan-dev/stan to add the signature, then do that to expose it to the modeling language.

#### Current Version:
v2.14.0

**Comment by seantalts** [comment]
What do you think about adding a tag for `newbie friendly` or something to help others trying to find a place to dig in? this seems like a good candidate from what I can tell.

**Comment by bob-carpenter** [comment]
We try to keep the discussion focused on the issue in our issues.  I'm moving this discussion to discourse.

**Comment by bbbales2** [comment]
Appending lists of real, int, vector, row_vector, and matrix types is in place.

Still need to enable appending lists of lists of all these types.

For instance, it should be possible to do:

```stan
vector[N] list1[M, L1];
vector[N] list2[M, L2];
vector[N] list3[M, L1 + L2] = append_array(list1, list2);
```

This should be possible based on previous discussion:
https://github.com/stan-dev/stan/pull/2343#issuecomment-313536628
https://github.com/stan-dev/stan/pull/2343#issuecomment-313697116
