### ISSUE TITLE
symmetrize function

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#482]
#### Summary:

Given how often users have to do this themselves, it seems like it'd be useful to have a function

```
/**
 * Return symmetric form of matrix with entries below the diagonal copied
 * into the above-diagonal positions.
 */
matrix symmetrize(matrix a) {
  if (rows(a) != cols(a)) reject("require square matrix");
  matrix[rows(a), cols(a)] b = a;
  for (i in 1:rows(a)) for (j in i + 1:cols(a)) a[i, j] = a[j, i];
}
```

An alternative would be to define the return as `0.5 * (x + x')` but that's a whole lot more work for autodiff and it won't work in the situation where we fill in the below-diagonal then call this function to complete.

#### Current Version:
v2.14.0

**Comment by betanalpha** [comment]
Given the ambiguity as to which triangle gets copied into which,
I’d recommend making the naming explicit, a la ```symmetrize_ld```
or ```symmetrize_up``` or the like.

**Comment by rok-cesnovar** [comment]
https://github.com/stan-dev/math/pull/2209 added `symmetrize_from_lower_tri()`. Do we leave the issue open for `symmetrize_from_upper_tri()` or is that a less common case that we dont need to add it?
