### ISSUE TITLE
promoter.hpp doc/refactor 

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/math#492]
#### Summary:
Doc and refactor file stan/math/prim/mat/fun/promoter.hpp into functions for scalar, array, and matrix types and add functions to appropriate director and add matrix builder function.

#### Description:

* Function stan/math/prim/mat/fun/array_builder.hpp should be in stan/math/prim/arr, but it depends on promoter.hpp.  Refactor/move functionality to appropriate stan/math directories.  

* Add proper documentation to promoter functions.

* Refactor tests, include files.

#### Current Version:
v2.14.0

**Comment by mcol** [comment]
This is now obsolete: promoter.hpp doesn't exist anymore and array_builder.hpp is in `stan/math/prim/arr/fun/`, so there's nothing to do.

**Comment by rok-cesnovar** [comment]
Thank @mcol! Closing.
