### ISSUE TITLE
cov_exp_quad uses ambiguous parameter names

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/math#495]
#### Summary:

`cov_exp_quad` uses ambiguous greek letters to describe its input parameters in error messages.

#### Description:

`cov_exp_quad` uses `sigma` for the marginal variance and `l` for the length scale which is somewhat non-standard, especially given the more recent notation that has been used in GP example models.  `sigma`, in particular, is highly overloaded in its use in these models.

We should add a more descriptive name, for example replacing the second argument of `check_positive("cov_exp_quad", "sigma", sigma);` with `marginal variance`.  Similarly, subbing in `length scale` for `l` in `check_positive("cov_exp_quad", "l", l);`.

#### Current Output:

```
Exception thrown at line 24: cov_exp_quad: sigma is 0, but must be > 0!
```

#### Expected Output:

```
Exception thrown at line 24: cov_exp_quad: marginal variance is 0, but must be > 0!
```

#### Current Version:
v2.14.0

**Comment by rtrangucci** [comment]
closed with #499

**Comment by jtimonen** [comment]
It think that using `marginal variance` in the error messages like
```
Exception: cov_exp_quad: marginal variance is -0.247557, but must be > 0!
```
is misleading because to my understanding `sigma` (or `alpha` as it is called in the stan reference manual) is the mardinal standard deviation, not marginal variance. On the other hand, why does `sigma` need to be restricted to be positive, when it will be squared anyway?

**Comment by bob-carpenter** [comment]
> On Nov 21, 2018, at 11:42 PM, Juho Timonen <notifications@github.com> wrote:
> 
> It think that using marginal variance in the error messages like
> 
> Exception: cov_exp_quad: marginal variance is -0.247557, but must be > 0!
> 
> is misleading because to my understanding sigma (or alpha as it is called in the stan reference manual) is the mardinal standard deviation, not marginal variance.

That looks right from the doc and we should fix it in the doc. The doc here is in both the math library and for the Stan language.

> On the other hand, why does sigma need to be restricted to be positive, when it will be squared anyway?

To avoid posterior multimodality.  The difference between sigma and -sigma is unidentifiable (unless you put a non-zero centered prior on it).  It will negatively impact sampling,  particularly adaptation (based on empirical posterior covariance, which will be much higher with multimodality), convergence diagnostics (which will see sigma and -sigma as answers that havne't converged) and posterior analysis (it'll overestimate posterior standard deviation for sigma, for example).
