### ISSUE TITLE
`mdivide_left_tri_low` incorrect argument dependent lookup

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/math#498]
#### Summary:

Calling `mdivide_left_tri_low` on a matrix of `vars` runs the `prim` version of `mdivide_left_tri` on the matrix, rather than the specialized reverse-mode version with analytic gradients.

#### Description:

`stan/math/prim/mat/fun/mdivide_left_tri_low.hpp`' is too generally templated, which leads to the incorrect version of `mdivide_left_tri` being matched.

#### Reproducible Steps:

I edited `stan/math/prim/mat/fun/mdivide_left_tri.hpp` to print when it was called, and then wrote a Stan model that should only match `stan/math/rev/mat/fun/mdivide_left_tri.hpp`.

#### Additional Information:

Oddly, it appears that the of the `rev` code is worse than that of the `prim` code. Optimizing the `rev` version should be a separate issue.

#### Current Version:
v2.14.0

**Comment by bob-carpenter** [comment]
That's also true of matrix multiply.  Our matrix multiply is slower than doing the prim version, but it's much more conservative in terms of memory usage.  I'm attributing it to our version not being properly blocked, which is probably what's going on here, too.

**Comment by rtrangucci** [comment]
I'm not sure that it's still true for matrix multiply. I can double check, but with my changes, I saw an order of magnitude increase in speed for A * B where both A and B were rev matrices.

**Comment by bob-carpenter** [comment]
@rtrangucci:  Could you rewrite this issue to clarify the distinction between `mdivide_left_tri` and `mdivide_left_tri_low`?  I don't see a file `rev/mat/fun/mdivide_left_tri_low.hpp`, so I'm not sure what you think should be getting called.

A couple other points:

* there's nothing wrong with the templating in `prim/mat/fun/mdivide_left_tri_low.hpp`.
* argument-dependent lookup just "uses" any definition found in the same namespace as the argument, which in this case includes the primitive version

Also, what's the difference between `mdivide_left_tri()` and `mdivide_left_tri_low()`?  There's no doc in `midivide_left_tri_low`.  And only `mdivide_left_tri_low` is exposed in the Stan language.

**Comment by rtrangucci** [comment]
@bob-carpenter the original version of the issue had a typo. The `prim/mat/fun/mdivide_left_tri_low.hpp` calls `mdivide_left_tri` internally. There are both `rev` and `prim` versions of `mdivide_left_tri`, but the  `rev` version doesn't get matched when `prim/mat/fun/mdivide_left_tri_low.hpp` is called on a matrix of `var`s

**Comment by bob-carpenter** [comment]
Thanks.  I'll try to tackle this.

**Comment by bob-carpenter** [comment]
The problem is that in `rev/mat/fun/mdivide_left_tri.hpp` we have

```
template <int TriView, int R1, int C1, int R2, int C2>
    inline Eigen::Matrix<var, R1, C2>
    mdivide_left_tri(const Eigen::Matrix<var, R1, C1>& A,  const Eigen::Matrix<var, R2, C2>& b)
```

whereas in `prim/mat/fun/mdivide_left_tri.hpp` we have:

```
template <int TriView, typename T1, typename T2,  int R1, int C1, int R2, int C2>
    inline  Eigen::Matrix<typename boost::math::tools::promote_args<T1, T2>::type, R1, C2>
    mdivide_left_tri(const Eigen::Matrix<T1, R1, C1> &A,
                     const Eigen::Matrix<T2, R2, C2> &b) {
```

The call from `prim/mat/fun/mdivide_left_tri_low.hpp` explicitly specifies the primitive version by calling

```
mdivide_left_tri<Eigen::Lower, T1, T2, R1, C1, R2, C2>(A, b);
```

No way to instantiate the reverse mode with that explicit call because it doesn't have the `T1` and `T2` template parameters.  There are two ways to fix this:

1.  Template Specialization: Make the reverse mode implementation specializations of the base template class in primitive;  that'd mean adding more template parameters.

2.  Overload: Drop the extra template parameters from the call in `mdivide_left_tri_low` leaving only `Eigen::Lower`.

I'm going with (2) because it's the less invasive change.  I'll submit a pull request ASAP.
