### ISSUE TITLE
host Doxygen API doc on mc-stan.org

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#500]
#### Summary:

The subject pretty much says it all.

#### Description:

The Doxygen doc is getting built, it's just not being hosted.

This should not turn into a doc cleanup or styling project, just hosting it as part of our release process.

#### Current Version:
v2.14.0

**Comment by syclik** [comment]
It's now hosted at http://mc-stan.org/math

**Comment by bob-carpenter** [comment]
Fantastic!  Thanks for getting this published.  

I'm about to embark on moving our manual to HTML.  I can follow your lead and put it here:

mc-stan.org/stan/

**Comment by seantalts** [comment]
You can thank @SteveBronder!

**Comment by syclik** [comment]
+1. It's all @SteveBronder!

**Comment by syclik** [comment]
and... @seantalts. I know he had to do work to get this done too.

**Comment by bob-carpenter** [comment]
Thanks, Steve and sorry for not noticing earlier.  I didn't look at the PR, just the merge notification.

**Comment by SteveBronder** [comment]
Np and ty to Sean for the help!
