### ISSUE TITLE
slow categorical_rng implementation

### ISSUE THREAD

**Issue by torsti** [stan-dev/math#503]
#### Summary:

The `categorical_rng` function is very slow for large N-simplexes, due to an unneccessary double loop.

#### Description:

The implementation of the categorical_rng function includes a [double loop](https://github.com/stan-dev/math/blob/aa311f3b329c96c8e47be85126ae9535be104b19/stan/math/prim/mat/prob/categorical_rng.hpp#L34-L37) which, unless I am mistaken, just calculates the cumulative sum of `theta`:

```C++
for (int i = 0; i < theta.rows(); i++) {
    for (int j = i; j < theta.rows(); j++)
        index(j) += theta(i, 0);
}
```

Replacing that with a single loop, or say a call to `cumulative_sum` will speed up the function tremendously for large N.

Additionally replacing the [iteration over the cumulative sum](https://github.com/stan-dev/math/blob/aa311f3b329c96c8e47be85126ae9535be104b19/stan/math/prim/mat/prob/categorical_rng.hpp#L39-L43) of `theta` with a binary search might also provide a small additional speed up.

#### Additional Information:

Just as an annectode: in a simulation model written in Stan, but using only transformed data and generated quantities, the program spent over 90% time (or rather`perf` samples) in `categorical_rng`. Replacing the implementation with a custom version without the double loop (but no binary search) cut down the runtime where the N-simplex was of order 10000, from hours to a few minutes only.

#### Current Version:
v2.14.0

**Comment by bob-carpenter** [comment]
Thanks much for testing and reporting this.  This should be easy to fix.  This would be a great project for someone wanting to get their feet wet with our dev process.

**Comment by torsti** [comment]
I thought so. I'm trying to get the hang of the dev process over at #504. Maybe I was a bit rash sending the pull request before waiting for a comment on the issue first, though...
