### ISSUE TITLE
functional/functor testing framework for first- and higher-order autodiff

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#51]
Develop an autodiff testing framework that will test autodiff implementations against existing `double` implementation using signatures like:

```
MatrixXd x = ...;
MatrixXd y = ...;
test_ad(multiply, x, y);
```

The test will make sure that `multiply` supplies appropriate values and derivatives as defined by the `double` implementation and finite differences.  Due to the inaccuracy of finite differences, we'll probably need an optional tolerance argument.

**Comment by syclik** [comment]
_From @betanalpha on November 19, 2014 20:17_

Stan-devs should check out my attempt at this in the Nomad repo.

**Comment by syclik** [comment]
_From @bob-carpenter on November 19, 2014 21:9_

It'd be nice if the tests were factored so that the
tests for functions didn't depend on the details of
the Nomad data structure.  

Rob and I just started doing this on a branch
for Stan, and if you have the autodiff.hpp implemented,
it should port to Nomad.

- Bob

**Comment by syclik** [comment]
_From @betanalpha on November 19, 2014 21:22_

What do you mean by Nomad data structure?
The test pattern in Nomad should work for any functor/functional setup, no?

**Comment by syclik** [comment]
_From @bob-carpenter on November 19, 2014 23:15_

I don't have the Nomad test code in front of me, but when Rob was
showing it to me, tests for functions involved the use of
Nomad data structures. 

I think it'll be easiest and most portable if the tests
only need to talk about our functions and double values.

This is the same point I was trying to make about defining
functions using structs.  If I remember correctly, Michael
completely disagreed, and the result is that definining functions
in Nomad requires tweaking Nomad data structures [as it does
in Stan 2.5].

Here's what the test for log1p looks like in the framework
we just roughed out (so far only testing first order, but
the call will be exactly the same when the rest is filled in):


```
#include <test/unit/agrad/agrad-functor-eq.hpp>

struct log1p_primitive {
  template <typename T>
  T operator()(const T& x) const {
    using ::log;
    return log(1 + x);
  }
};

struct log1p_stan {
  template <typename T>
  T operator()(const T& x) const {
    using stan::math::log1p;
    return log1p(x);
  }
};

TEST(stanMath, log1p_derivs) {
  using test_unit::expect_agrad_eq_unary;
  log1p_primitive f1;
  log1p_stan f2;
  expect_agrad_eq_unary(f1,f2,0.3);
}

// you would use this if log1p were defined to throw, but it's not

// TEST(stanMath, log1p_throws) {
//   using test_unit::expect_throws_unary;
//   log1p_stan f;

//   expect_throws_unary<std::domain_error>(f,-2.7);
// }
```

- Bob

**Comment by syclik** [comment]
_From @betanalpha on November 20, 2014 0:9_

https://github.com/stan-dev/nomad/blob/master/src/test/scalar/functions/smooth_functions/acos_test.cpp
https://github.com/stan-dev/nomad/blob/master/src/test/finite_difference.hpp

**Comment by syclik** [comment]
_From @bob-carpenter on November 20, 2014 3:3_

Cool --- this is great.  It's a more mature version of exactly what 
I was talking about!  Partly the rest of this is notes for Rob with
some suggestions embedded.

What we should do is refactor what we have in Stan to use the Nomad 
testing framework.

I like that it's done on vectors, but Rob and I hadn't
figured out how to resolve issues of mixed double and
var inputs.  I see that you've pushed that up to the
test functor, which is a neat solution:

  https://github.com/stan-dev/nomad/blob/master/src/test/scalar/functions/smooth_functions/atan2_test.cpp

Then you need to define multiple functors.  I don't offhand 
see a way that you could just define a single templated structure,
but it might be use putting some thought into.

You could avoid the hard coding of a single test value by adding the
double value as a member variable.  

Are you doing the double-double tests elsewhere?  I see that you don't have
a using statement in the test functors (it just uses argument-dependent
lookup).

I also like the addition of the name to the functor.  

You could get around the virtuality of base_functor::operator() if you 
use the "curiously recursive template pattern" --- it's what Eigen does
for its indexing operator overrides.  No big deal if it's only
used in tests, though I see it's defined outside the test framework.

I keep thinking that function pointers could get rid of the need to
define all the functors wrapping functions like acos, but the
problem is that you need the template instantiation.

- Bob

**Comment by rok-cesnovar** [comment]
This was close with #1256
