### ISSUE TITLE
printf from CVODES again

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#524]
#### Summary:

CVODES uses printf() statements

#### Description:

This is a bad idea for Stan in general and causes problems on CRAN

#### Reproducible Steps:

```
goodrich@T540p:/opt/stan/lib/stan_math/lib/cvodes_2.9.0$ grep -R -F -n -w "printf" .
```

#### Current Output:

```
./src/nvec_ser/nvector_serial.c:280:    printf("%35.32Lg\n", xd[i]);
./src/nvec_ser/nvector_serial.c:282:    printf("%19.16g\n", xd[i]);
./src/nvec_ser/nvector_serial.c:284:    printf("%11.8g\n", xd[i]);
./src/nvec_ser/nvector_serial.c:287:  printf("\n");
Binary file ./src/nvec_ser/nvector_serial.o matches
Binary file ./src/sundials/sundials_direct.o matches
./src/sundials/sundials_direct.c:316:    printf("\n");
./src/sundials/sundials_direct.c:320:        printf("%12Lg  ", DENSE_ELEM(A,i,j));
./src/sundials/sundials_direct.c:322:        printf("%12g  ", DENSE_ELEM(A,i,j));
./src/sundials/sundials_direct.c:324:        printf("%12g  ", DENSE_ELEM(A,i,j));
./src/sundials/sundials_direct.c:327:      printf("\n");
./src/sundials/sundials_direct.c:329:    printf("\n");
./src/sundials/sundials_direct.c:336:    printf("\n");
./src/sundials/sundials_direct.c:340:      for (j=0; j < start; j++) printf("%12s  ","");
./src/sundials/sundials_direct.c:343:        printf("%12Lg  ", a[j][i-j+A->s_mu]);
./src/sundials/sundials_direct.c:345:        printf("%12g  ", a[j][i-j+A->s_mu]);
./src/sundials/sundials_direct.c:347:        printf("%12g  ", a[j][i-j+A->s_mu]);
./src/sundials/sundials_direct.c:350:      printf("\n");
./src/sundials/sundials_direct.c:352:    printf("\n");
Binary file ./lib/libsundials_nvecserial.a matches
Binary file ./lib/libsundials_cvodes.a matches
```

#### Expected Output:

None

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.15.0

**Comment by bob-carpenter** [comment]
Should we fork and just get rid of the `printf` statements?  

Or can we somehow avoid compiling the files they're in?  Looks like "direct" might be some kind of command-line thing and presumably the serial one is for serializing vectors (which we also won't need).

**Comment by wds15** [comment]
I think direct refers to direct solvers and serial is for non-parallel execution. We need both.

**Comment by bob-carpenter** [comment]
Then the only solution I see is to fork CVODES and remove the printf statements in our versions.

**Comment by wds15** [comment]
Yep. This is what we have done in the past. I have possibly forgotten those patches when doing the 2.9.0 upgrade. I can take a look at this.

**Comment by wds15** [comment]
So I checked things and we have patched CVODES ourselves and these patches were originally applied to CVODES 2.8 and these were correctly propagated to the current 2.9.0. Essentially we have defined a

NO_FPRINTF_OUTPUT

macro which guards all calls to fprintf which directly print to stderr in the CVODES code. The quoted calls to printf are OK from my perspective as these are never called from us:

- ./src/nvec_ser/nvector_serial.c: This is in the N_VPrint_Serial function which we never call
- ./src/sundials/sundials_direct.c: These printf statements are in the PrintMat function which we also never call

@bgoodri : do you think thats safe to proceed as is or should we expand or add another NO_XPRINTF_OUTPUT?

From what I can tell is that all direct fprintf calls are taken out with the macro.

**Comment by bgoodri** [comment]
Yes, the NO_FPRINTF_OUTPUT worked previously I believed, which is why I was
surprised to see the problem come back. But it does not matter if we never
call the printf() functions; as long as the functions are in the shared
object CRAN complains. So, they need to get optimized away by the compiler
or we have to modify CVODES in the Stan repo.

**Comment by wds15** [comment]
could you take a look at the respective branch?

I have used the same macro name NO_FPRINTF_OUTPUT to if-def out those extra instances (which sometimes call printf instead of fprintf as the macro name may suggest). Adapting the macro name cause a number of required upstream changes as well so I left it as is.
