### ISSUE TITLE
gamma_p needs better derivatives

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/math#525]
#### Summary:
For reasonable values of it's arguments, gamma_p(a,z) can have very poor errors (`>>1e-5`, compared to values calculated using mathematica).  For parts of its range the current algorithm for `d(gamma_p)/da` in `stan/math/rev/scal/fun/gamma_p.hpp` can also appear to converge, but instead provide values orders of magnitude off from true values.

#### Description:
Summary [plots](https://drive.google.com/file/d/0B79jbAyfUdNNeUFDdnNQTFlwRE0/view?usp=sharing):
 - first plot is absolute error with current function (log 10)
 - second plot shows regions where different methods do best as well as the failure region (described as absolute error > 1e-5)
 - third plot is the minimum error with the best method for the region.

Here's some data:
```
set.seed(4201)

library(magrittr)
library(rstan)
library(dplyr)

J <- 5

N <- 20
shape <- 2
scale <- 1
rgamma_t <- function(n, shape, scale, max) {
  M <- rep(Inf, n)
  for (i in 1:n) {
    while(M[i] > max)
      M[i] <- rgamma(1, shape=shape, scale=scale)
  }
  return (M)
}
x_max <- 1
x_matrix <- replicate(J, rgamma_t(n=N, shape=shape, scale=scale, max=x_max))
```

Here's an inappropriate model that runs fine for this:

```
data {
  int N;
  vector<lower=0>[N] x;
}

parameters {
  real<lower=0> alpha;
  real<lower=0> beta;
}

model {
  target += gamma_lpdf(x | alpha, beta);
}
```

Here's the model that matches the data generation but (often) throws divergences:

```
data {
  int N;
  vector<lower=0>[N] x;
  vector<lower=0>[N] x_max;
}

parameters {
  real<lower=0> alpha;
  real<lower=0> beta;
}

model {
  target += gamma_lpdf(x | alpha, beta)
    - gamma_lcdf(x_max | alpha, beta);
}
``` 

Run script:

```

mg <- list()
for ( j in 1:1) {
  mg[[j]] <- rstan::stan(file='gamma.stan', data=list(N=N, x=x_matrix[,j]))
}

mgt <- list()
for ( j in 1:1) {
  mgt[[j]] <- rstan::stan(file='gamma-truncated.stan',
    data=list(N=N, x=x_matrix[,j], x_max=rep(x_max,N)))
}
```

After running the models look at trace plots and divergences (and autocorrelation).  Adding the truncation breaks things, divergences for larger a and z values which is where the current derivative series calculation diverges.

#### Reproducible Steps:
1) Clone: `https://github.com/sakrejda/math/tree/bugfix/issue-XXX-lower-incomplete-regularized-gamma-gradient`

2) Run `./runTests.py test/unit/math/rev/scal/fun/gamma_p_accuracy_test.cpp`

3) Examine the file `test-2.txt` in whatever directory you ran the test from.

#### Current Output:

See the plots linked above.

#### Current state:
- I implemented some alternative calculations (also on the branch), they do better in different regions, I think this will cover most of the fix.
- there's still a region with small `a` and small to moderate `z` where I need to implement an alternative calculation
- Still need to characterize exact cutoffs for branching to each implementation, although it's becoming obvious with the plots
- I have some code at the [Mathematica OpenCloud](https://www.wolframcloud.com/objects/86879aa3-c1cc-4265-9ab6-407ec35446ab) thing that I used to calculate test values but it's slow

Plots:
[d_gamma_p_da.pdf](https://github.com/stan-dev/math/files/937805/d_gamma_p_da.pdf)

#### Expected Output:
Errors on par with other math library functions.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.15.0

**Comment by sakrejda** [comment]
This is also relevant for d(gamma_q)/da but I don't know if the problem is as bad there.

**Comment by sakrejda** [comment]
Victory! 
[d_gamma_p_da.pdf](https://github.com/stan-dev/math/files/955767/d_gamma_p_da.pdf)

**Comment by wds15** [comment]
+1

**Comment by sakrejda** [comment]
Done.
