### ISSUE TITLE
ambiguous fvar template instantiation of ad_promotable with g++ 5.4.0

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#528]
#### Summary:
The unit tests are failing with g++ 5.4.0

#### Description:
I'm not sure what's happening, honestly. I'm not familiar with the code that is breaking. This just came up when trying to merge some new code into Stan. (see http://discourse.mc-stan.org/t/stans-runtests-py-src-test-unit-failing-with-g-works-with-clang/351, https://github.com/stan-dev/stan/pull/2285)

#### Reproducible Steps:
In Ubuntu 16.04 with g++ 5.4.0 (the default compiler)

`make test/unit/math/mix/mat/prob/categorical_test` (in the math repo)

Should fail

#### Current Output:
https://gist.github.com/bbbales2/0a2456d516bbe1200a4d1ee76b936656

#### Expected Output:
The tests to pass

#### Additional Information:
I had a dig around. I'm not sure what I'm doing (so don't interpret this as an actual fix), but this change seems to get rid of the error: 
https://github.com/bbbales2/math/commit/52de78ff69f7ab6a9cd00012a5b41826eaa1a3c8

It seemed like the compiler couldn't decide between using:

```
template <typename T>
    struct ad_promotable<T, T> {
      enum { value = true };
    };
```
with T = stan::math::fvar<stan::math::var>

 and

```
template <typename V, typename T>
    struct ad_promotable<V, fvar<T> > {
      enum { value = ad_promotable<V, T>::value };
    };

```
with V = stan::math::fvar<stan::math::var>, T = double
 
So I just made a type to specifically absorb two fvars. Maybe this is helpful in figuring out the problem. Again I'm not sure what I'm doing so don't interpret this as a fix.

#### Current Version:
v2.15.0

**Comment by bob-carpenter** [comment]
I'll take this one.  Should be fast, as in a few hours.

**Comment by bob-carpenter** [comment]
Also note that edited out mixed mode tests in `stan-dev/math/.travis.yml`
