### ISSUE TITLE
Refactor OperandsAndPartials

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#546]
#### Summary:
The intention here is to make the resulting class easier to understand and to add multivariate support.

**Comment by seantalts** [comment]
Copying from https://github.com/stan-dev/stan/issues/2252
* The class partials_variin OperandsAndPartials.hpp is redundant and should be replaced by including and using precomputed_gradients.hpp
* reuse d_xN in d_x(N+1) rather than recomputing
* replace all_varis allocation with direct calls to array_alloc rather than roundabout vari::operator new calls

**Comment by bob-carpenter** [comment]
Done with pull request #547
