### ISSUE TITLE
integrate_ode: bad_alloc in ODE model

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#548]
#### Additional information

`integrate_ode_bdf` does not handle errors properly. There are some errors from within the integrator that crashes CmdStan, which will probably crash R through RStan.

_From @virgile-baudrot on April 12, 2017 14:1_

#### Summary:
In functions for ode integration, the following code do not compile but do not return error as it could be expected but a "std::bad_alloc".

```
int nb_eq;    
real dydt[nb_eq];
```
#### Reproducible Steps:

A reproducible example with a slight modification of Harmonic Oscillator model (provided with the Manual):
[bad_alloc_ODE.tar.gz](https://github.com/stan-dev/stan/files/916732/bad_alloc_ODE.tar.gz)

#### Expected Output:
An error message

#### Current Version:
v2.14.0

_Copied from original issue: stan-dev/stan#2272_

**Comment by syclik** [comment]
_From @bob-carpenter on April 12, 2017 17:3_

Can you run other Stan models?

**Comment by syclik** [comment]
_From @virgile-baudrot on April 13, 2017 6:59_

Yes. I can run Harmonic Oscillator example (and others also), but without the "error" I introduced here with `nb_eq`.

**Comment by syclik** [comment]
_From @wds15 on April 13, 2017 12:30_

the Stan model is wrong... the nb_eq is never initialized inside the ODE RHS functor. The model should run ok with declaring

int nb_eq = 2;

inside the ODE RHS functor. Note that the variables in the data block are not globally available. You can use the x_i argument to pass integer data around.

That said, I haven't run the model, so the error message could possibly be improved.

**Comment by syclik** [comment]
_From @virgile-baudrot on April 13, 2017 15:27_

Yes. Actually, I did this mistake in the model, but had some difficulties to find the error because of the message.

**Comment by syclik** [comment]
_From @sakrejda on April 28, 2017 17:26_

Could we catch stuff when values are not initialized properly to give error messages?

**Comment by syclik** [comment]
I saw this in the wild not too long ago. Last I saw, it happened when some
of the returned dy_dt were NaN.

We certainly can stop this by adding more checks. We need to think through
how the error handling is propagated, but it can be handled. (I believe on
an earlier implementation there were checks in place. It's one of the
reasons I'm all for putting checks in place. It saves so much more headache
for users, devs, etc.)

Options:
1. we can probably checks to the functor that's generated
2. I think we can fix this in the integrate_* calls.

**Comment by syclik** [comment]
_From @bob-carpenter on April 28, 2017 18:21_

Is this the CVODES or Boost integrator?  Can we file an issue with them not to go bonkers when given NaN values?

We have lots of layers of wrappers where we could brute force the check.  Probably not a big performance overhead.

**Comment by syclik** [comment]
_From @wds15 on April 30, 2017 9:24_

I don't think that checking every ODE RHS evaluation is a good thing as it gets called really often and should add some performance overhead which all users have to pay always.

A good compromise is to call the ODE RHS in the integrate_* function with the initial state. Then we check if the initial dy_dt at t=t0 has the correct size and is not NaN. This would catch the reported case and probably about any other realistic ones which are the most common ones.

However, the even better solution would be to not rely on the user create a dy_dt which has the correct size inside the ODE RHS. Instead it would be better to have a design where Stan manages the dy_dt and the user only populates its values. This would avoid much of the ongoing copying and always ensure that dy_dt is of the right size.

**Comment by syclik** [comment]
> A good compromise is to call the ODE RHS in the integrate_* function with the initial state. Then we check if the initial dy_dt at t=t0 has the correct size and is not NaN. This would catch the reported case and probably about any other realistic ones which are the most common ones.

That may catch the reported case, but there's also an issue if the array is the correct size, but elements are `NaN`. Given users are defining functions, we should be safe.

> However, the even better solution would be to not rely on the user create a dy_dt which has the correct size inside the ODE RHS. Instead it would be better to have a design where Stan manages the dy_dt and the user only populates its values. This would avoid much of the ongoing copying and always ensure that dy_dt is of the right size.

What you're suggesting can't work with the current function implementation. That said, nothing is impossible, so if you have a proposal that makes sense, I'm sure we're all willing to hear it out.

> I don't think that checking every ODE RHS evaluation is a good thing as it gets called really often and should add some performance overhead which all users have to pay always.

I completely disagree. It's caused confusion and I'm sure some people have given up on ODEs due to a simple programming error because we don't have error reporting.

What I would suggest is that we do some real timing experiments. You would be surprised how cheap checking for `NaN` is relative to anything else. In fact, if you send me an example that you're happy with that takes more than a couple seconds, I can implement it and we can see how much time it takes.

**Comment by syclik** [comment]
_From @wds15 on May 2, 2017 7:42_

Well, I would be surprised if extra checks are for free (array bound checks are also disabled for a reason in std::vector or Eigen) - in a Stan run you get at the order of 10^6 integrations easily. Each integration sweep can easily again trigger 10^6 calls to the ODE RHS. That's a lot with about 10^12. Let me prepare an example to play with and we check the overhead.

Should we have a discussion in a meeting on a Stan default (with all checking) and a Stan "speed" mode (disabling all checks). The "speed" mode could only by activated with a switch called like "--give-me-all-speed-even-if-I-fool-myself"?

I know that the current design does not allow what I have suggested. I don't have a good solution at hand. The obvious approaches are by reference dy_dt arguments to the functor or a predefined dy_dt symbol which the user must populate inside the function. Neither approach is too elegant.

**Comment by syclik** [comment]
_From @bob-carpenter on May 3, 2017 3:48_

@wds15  Would you mind creating an issue or discourse thread for discussing your proposed unsafe mode?   It's off topic on this issue.  Thanks.

**Comment by syclik** [comment]
_From @bob-carpenter on May 3, 2017 3:50_

Back to the original point, we don't want to be throwing uncaught exceptions back to users at runtime or crashing their R sessions (at least until they've signed a waiver and we've given them keys to Ben and Sebastian's unsafe mode).

**Comment by bob-carpenter** [comment]
Just copying example out of @virgile-baudrot's original tar.gz form:

```
functions {
  real[] sho( real t,
              real[] y,
              real[] theta,
              real[] x_r,
              int[] x_i) {
      
      int nb_eq;
      
      real dydt[nb_eq];
      
      dydt[1] = y[2];
      dydt[2] = -y[1] - theta[1] * y[2];
      return dydt;
    }
}
data {
  int<lower=1> Tm;
  int<lower=1> nb_eq;
  
  real y[Tm,nb_eq];
  real t0;
  real ts[Tm];
}
transformed data {
  real x_r[0];
  int x_i[0];
}
parameters {
  real y0[2];
  vector<lower=0>[2] sigma;
  real theta[1];
}
model {
  real y_hat[Tm,2];
  sigma ~ cauchy(0,2.5);
  theta ~ normal(0,1);
  y0 ~ normal(0,1);
  y_hat = integrate_ode_rk45(sho, y0, t0, ts, theta, x_r, x_i);
  for (t in 1:Tm)
  y[t] ~ normal(y_hat[t], sigma);
}
```
and then the driver

```
ODE_data=list(
  Tm = 10,
  y0 = c(1,1),
  nb_eq=2,
  t0 = 0,
  ts = 1:10,
  y = structure(c(0.397095,-0.300526,-0.948297,-0.57433,-0.00316177,0.675424,0.703672,-0.0918871,-0.469737,-0.429309,
                  -0.853654,-0.696679,0.0545529,0.634292,0.772725,0.15645,-0.424857,-0.487648,-0.298427,0.16981),
                .Dim=c(10,2)),
  x_r = structure(c(0.397095,-0.300526,-0.948297,-0.57433,-0.00316177,0.675424,0.703672,-0.0918871,-0.469737,-0.429309,
                    -0.853654,-0.696679,0.0545529,0.634292,0.772725,0.15645,-0.424857,-0.487648,-0.298427,0.16981),
                  .Dim=c(10,2))
)

# FIT
fit_ODEs <- stan(file= "EDO_Harmonic_Oscilator.stan", data = ODE_data, iter = 2000, warmup=500,chains = 1)
```

**Comment by syclik** [comment]
Here are a few programs that require no data that have really bad behavior. I'm including some of the relevant output.

# Stan program 1

```stan
// wrong size
functions {
  real[] sho(real t, real[] y, real[] theta, real[] x_r, int[] x_i) {
    real dydt[0];
    return dydt;
  }
}
transformed data {
  int<lower=1> T = 10;
  real t0 = 0;
  real ts[T] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10.};
  real y[T,2] = { {0.397095, -0.853654},
                  {-0.300526, -0.696679},
                  {-0.948297, 0.0545529},
                  {-0.57433, 0.634292},
                  {-0.00316177, 0.772725},
                  {0.675424, 0.15645},
                  {0.703672, -0.424857},
                  {-0.0918871, -0.487648},
                  {-0.469737, -0.298427},
                  {-0.429309, 0.16981} };
  real x[0];
  int x_int[0];
}
parameters {
  real y0[2];
  vector<lower=0>[2] sigma;
  real theta[1];
}
model {
  real y_hat[T,2];
  sigma ~ cauchy(0,2.5);
  theta ~ normal(0,1);
  y0 ~ normal(0,1);
  y_hat = integrate_ode_bdf(sho, y0, t0, ts, theta, x, x_int);
  for (t in 1:T)
    y[t] ~ normal(y_hat[t], sigma);
}
```

## Output
Depends on the run. It will either crash or complete, but reject everything with an error pointing to the wrong line.

**CRASH**
```
Exception thrown at line 36: CVode failed with error flag -4
```

or

```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 33: cauchy_lpdf: Random variable[1] is nan, but must not be nan!
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
```


# Stan program 2
```stan
// NaN values
functions {
  real[] sho(real t, real[] y, real[] theta, real[] x_r, int[] x_i) {
    real dydt[2];
    dydt[1] = y[2];
    return dydt;
  }
}
transformed data {
  int<lower=1> T = 10;
  real t0 = 0;
  real ts[T] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10.};
  real y[T,2] = { {0.397095, -0.853654},
                  {-0.300526, -0.696679},
                  {-0.948297, 0.0545529},
                  {-0.57433, 0.634292},
                  {-0.00316177, 0.772725},
                  {0.675424, 0.15645},
                  {0.703672, -0.424857},
                  {-0.0918871, -0.487648},
                  {-0.469737, -0.298427},
                  {-0.429309, 0.16981} };
  real x[0];
  int x_int[0];
}
parameters {
  real y0[2];
  vector<lower=0>[2] sigma;
  real theta[1];
}
model {
  real y_hat[T,2];
  sigma ~ cauchy(0,2.5);
  theta ~ normal(0,1);
  y0 ~ normal(0,1);
  y_hat = integrate_ode_bdf(sho, y0, t0, ts, theta, x, x_int);
  for (t in 1:T)
    y[t] ~ normal(y_hat[t], sigma);
}
```

## Output
```
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception thrown at line 36: CVode failed with error flag -4
```

# Stan program 3
```
// log of a negative number
functions {
  real[] sho(real t, real[] y, real[] theta, real[] x_r, int[] x_i) {
    real dydt[2];
    dydt[1] = log(y[2]);
    dydt[2] = -y[1] - theta[1] * y[2];
    return dydt;
  }
}
transformed data {
  int<lower=1> T = 10;
  real t0 = 0;
  real ts[T] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10.};
  real y[T,2] = { {0.397095, -0.853654},
                  {-0.300526, -0.696679},
                  {-0.948297, 0.0545529},
                  {-0.57433, 0.634292},
                  {-0.00316177, 0.772725},
                  {0.675424, 0.15645},
                  {0.703672, -0.424857},
                  {-0.0918871, -0.487648},
                  {-0.469737, -0.298427},
                  {-0.429309, 0.16981} };
  real x[0];
  int x_int[0];
}
parameters {
  real y0[2];
  vector<lower=0>[2] sigma;
  real theta[1];
}
model {
  real y_hat[T,2];
  sigma ~ cauchy(0,2.5);
  theta ~ normal(0,1);
  y0 ~ normal(0,1);
  y_hat = integrate_ode_bdf(sho, y0, t0, ts, theta, x, x_int);
  for (t in 1:T)
    y[t] ~ normal(y_hat[t], sigma);
}
```

# Output
```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 38: CVodeGetSens failed with error flag -25
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
```

**Comment by syclik** [comment]
I think we need to add these to our tests. We should also add these with `integrate_ode_rk45` instead of `integrate_ode_bdf`. I'm not exactly sure where to add them to make most sense. They might belong in `math`.

@wds15, I've just added you to the assignee list. Hopefully you can look at this and figure out a way to trap the error from Sundials so we can report a nicer error message. Errors like these make it difficult to debug.

**Comment by syclik** [comment]
I just realized the original post had an error that should affect all our functions. @bob-carpenter, wouldn't that potentially be a problem everywhere? I wasn't able to trigger the `bad_alloc` exception, but I think it's very possible for this to happen.

**Comment by wds15** [comment]
The original post is probably more general than just ODE code.

Wrt to the error message from integrate_ode_bdf I agree that these are not the most informative ones, but they make it clear where the error has to come from. We are using a C library here which reports the errors using codes. These codes are all documented in the user manual of cvodes. I do think that all is fine; maybe we should add a note to our documentation. Should you want to translate the error codes, then this needs to be done here:

https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/functor/cvodes_utils.hpp

in the `cvodes_check_flag` function.

Still, I think that the message is fine as is. I am pretty sure that there are already tests in place for these cases - they simply check that an exception is fired, but not more.

**Comment by bob-carpenter** [comment]
@syclik --- is there a simple test case?  I can't see what the problem is with functions per se.

**Comment by bob-carpenter** [comment]
Is it just this causing problems:

```
int nb_eq;    
real dydt[nb_eq];
```


@mitzimorris:  what's up with initialization now?  Can this be fixed by replacing

```
foo a[N];
```

with

```
foo a[max(0, N)];
```

in the generated code for types `foo`?

**Comment by syclik** [comment]
The simple test case is the first one that I highlighted. That one crashes CmdStan. I'm pretty sure it'll crash R through RStan, but not absolutely sure.

**Comment by bob-carpenter** [comment]
First one where?  This doesn't crash RStan on my Mac:

```
functions {
  real foo(real x) {
    int a;
    real b[a];
    return x;
  }
}
parameters {
  real y;
}
model {
  foo(y) ~ normal(0, 1);
}
```

**Comment by bob-carpenter** [comment]
Is there a test case that doesn't involve calling the ODE solver?  I was asking because of the comment by @wds15 https://github.com/stan-dev/math/issues/548#issuecomment-299692435

**Comment by syclik** [comment]
@bob-carpenter, I'll try to come up with a separate example. I should be able to generate one.

**Comment by syclik** [comment]
@bob-carpenter, I can't get the `bad_alloc` exception to trigger. I tried to create a function that allocated a really large amount of memory, but it looks like the Mac will allow for it.

@virgile-baudrot, what operating system and what interface are you using?

**Comment by virgile-baudrot** [comment]
I'm on linux (ubuntu 4.4.0-75-generic - x86_64-pc-linux-gnu) and I use R (now R version 3.4.0 (2017-04-21), but when I posted the message, it's the previous one).

**Comment by syclik** [comment]
Thanks! That's helpful. I think we might be able to trigger a memory allocation limit either through R/RStan or maybe through Linux. 

Mind running something for me? Can you create a function that declares an int and print that int? It doesn't need to be within an ode. Something like:
real foo() {
  int N;
  print("N = ", N);
  return 0;
}

Thanks.

**Comment by virgile-baudrot** [comment]
Not sure about what you exactly wanted, but here is the output:

FOUND AT line 1: 
real func() {
  int N;
  print("N = ", N);
  return 0;
}
Error in checkForRemoteErrors(lapply(cl, recvResult))

**Comment by wds15** [comment]
I think this can be closed as we have now a size check of the ode rhs. Right? Or do we think that this issue is still required to keep track of?

**Comment by syclik** [comment]
@wds15, this is a different error than the size check. 

But, we haven't been able to reproduce, so closing the issue.

**Comment by syclik** [comment]
@virgile-baudrot, thanks! If it occurs again, mind reopening or creating a new issue? 

That last error message looked like it's coming from R/RStan, not Stan, but can't be certain remotely.
