### ISSUE TITLE
integrate_ode_bdf can provide non-sensical results

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#552]
#### Summary:
`integrate_ode_bdf()` may produce non-sensical results to the user.

#### Description:
A model with `integrate_ode_bdf()` may complete and return results which may be non-sensical. It may also error, depending on what's in memory.

This is also not reproducible. Run to run with the same seed differs because it's memory dependent.

#### Reproducible Steps:
From CmdStan, if you run this program with different seeds, you may end up with some that do not error.
```stan
functions {
  real[] sho(real t, real[] y, real[] theta, real[] x_r, int[] x_i) {
    real dydt[0];
    return dydt;
  }
}
transformed data {
  int<lower=1> T = 10;
  real t0 = 0;
  real ts[T] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10.};
  real y[T,2] = { {0.397095, -0.853654},
                  {-0.300526, -0.696679},
                  {-0.948297, 0.0545529},
                  {-0.57433, 0.634292},
                  {-0.00316177, 0.772725},
                  {0.675424, 0.15645},
                  {0.703672, -0.424857},
                  {-0.0918871, -0.487648},
                  {-0.469737, -0.298427},
                  {-0.429309, 0.16981} };
  real x[0];
  int x_int[0];
}
parameters {
  real y0[2];
  vector<lower=0>[2] sigma;
  real theta[1];
}
model {
  real y_hat[T,2];
  sigma ~ cauchy(0,2.5);
  theta ~ normal(0,1);
  y0 ~ normal(0,1);
  y_hat = integrate_ode_rk45(sho, y0, t0, ts, theta, x, x_int);
  for (t in 1:T)
    y[t] ~ normal(y_hat[t], sigma);
}
```

#### Current Output:
These are different outputs that happen with this program:

* Run completes. No error. Output looks ok. *THIS IS BAD*
* Run stops almost immediately with
```
Exception thrown at line 35: CVode failed with error flag -4
```

* Run is really, really slow. (I didn't run long enough to see if it ever finished)
* Run completes with `nan` in output. Odd thing is that it reports an error in the wrong part of the program (probably overwriting a piece of memory somewhere):
```
Iteration: 2000 / 2000 [100%]  (Sampling)
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception thrown at line 32: cauchy_lpdf: Random variable[1] is nan, but must not be nan!
If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
```

There may be a few other failure modes.

#### Expected Output:
Probably matching behavior from `integrate_ode_rk45()` will be good:
```
Exception thrown at line 35: coupled_ode_system: y (2) and dy_dt (0) must match in size
```

#### Additional Information:
@wds15, could you look at how to fix this? This is a serious bug since under some circumstances, it will produce results that a user may assume is ok.

#### Current Version:
v2.15.0

**Comment by wds15** [comment]
I can work on this. I think the issue is that wrong sizes are not cleanly enough being checked. I suggest to add a check which will once do the check, i.e. for the initial state inside the integrate_ode_bdf.

That would address this issue. Is this strategy OK with everyone?

**Comment by syclik** [comment]
Great. I think that's the right thing to do. We can assume that the ode function won't dynamically allocate size dependent on the iteration.

**Comment by bob-carpenter** [comment]
I don't think checking the size of an array every step will induce measurable overhead if we're already computing the derivatives and filling them.  So why only test once?  I'd really like to aim for a design that can't crash its environment---that's really unacceptable in my mind for an app.

**Comment by betanalpha** [comment]
We should test at the beginning of integrate_ode which wraps the
explicit integrator calls.  Inside integrate_ode the sizes should not
change no matter what crazy things the user might do so that should
be safe enough.

**Comment by syclik** [comment]
Should and can't are different things. I thought about it and realized that someone could have size dependent on parameter values. It would most certainly be an error, but it's possible. 

I'd say put in the check and time the difference between every step and just once up front. My guess is that it won't be measurable and if so, we keep it in so we can help users trap errors quicker.

**Comment by betanalpha** [comment]
Huh?  Are you talking about dynamic allocations within the input functor?

Even then it wouldn’t matter as the integration within integrate_ode is
all conditioned on the given value of theta, x_r, and x_i so one evaluation
of the functor will trigger any problems.

**Comment by syclik** [comment]
Gotta have some imagination! There is a way to dynamically set the size of the return array that's different from function call to function call. Not easy, but possible. It would definitely be a user error. A single function call won't always pick up on the error.

**Comment by betanalpha** [comment]
Example?  Non-determinism like this would screw up our entire code base.

**Comment by bob-carpenter** [comment]
I think what @syclik is imagining is

```
if (theta < 0.5) {
  real[2] x;
  ...
  return x;
} else {
  real[3] x;
  ...
  return x;
}
```

So we need to make sure the return of our ODE system function is the right size if it not being the right size will mess up CVODES in an unrecoverable way.

**Comment by syclik** [comment]
Thanks, Bob! Yes, something like that. It would clearly be an error, but I could see someone making a coding error as we have general includes. Someone (and this is a TERRIBLE idea) might want to have one ODE function that handles 2, 3, 4, 5 compartment models and wants to branch on an input. If this person makes a mistake and branches on the parameter value instead of some data element, this could happen and perhaps not that frequently.

@betanalpha, this doesn't screw up our entire code base. It only affects `integrate_ode_bdf()` because the output of the function is assigned to memory directly. It's why running a failing case repeatedly, even with the same seed, may have different behavior. There is a chance that this is unsafe. But once again, it shouldn't affect other things in the Stan language.

**Comment by wds15** [comment]
In the performance tests which I have done, I do show that with enough load on a CPU then these checks start to be visible. Remember that the ODE RHS is call really often... about 10^6 ode solves per Stan run at least and the same order of magnitude per solve for calls to the RHS.

Testing the size correctness in the integrate_ode_bdf function on the inital makes a lot of sense as only then a meaningful error message will be generated. Exceptions generated when the code is under the C library will be mangled due to the error handler which only returns error codes from CVODES.

So, first, I do not think that the obscure case is more than a theoretical possibility rather than something which will practically ever happen. Moreover, if a person thinks to be so clever to be able to branch inside the ODE RHS, then it is safe to assume that this is a skilled person knowing what he does.

My suggestion here:
1. Check the initial in the integrate_ode_bdf
2. Add some recommendations to the manual saying that one should always start with integrate_ode_rk45 (since starting non-stiff is really a very sane recommendation in ODE problems) and emphasize that the size of the returned dy_dt must never change.

The intended use case of the ODE RHS is so clear that I do not think that any person should ever wait even a second longer for their results.

I suggest to discuss the matter at a meeting and decide with the group.

**Comment by syclik** [comment]
We can discuss at the meeting, but this decision isn't going to be a democratic one. We are currently behaving really poorly with raw memory buffers that have been passed to an external C library. We're allowing users to inadvertently stomp on memory that doesn't belong to them. Speed is a second order concern. It's still a concern, but one we should address after we find a solution to this issue. 

My suggestion is to just check the size of the return at every iteration, preferably before writing to the memory buffer. I'm not suggesting checking the contents, just the size. I'd take the performance hit of 10^6 int comparisons per iteration over allowing users to overwrite memory causing both non-reproducible results and possible segmentation faults. I'm guessing we haven't seen those yet because the allocated memory for Sundials is sandwiched between chunks we allocate for our auto diff stack, but maybe it's time to understand where we are allocating that memory. (Perhaps there's a performance boost there somewhere.)

In the meantime, can you hunt down the place where the result of the C++ ode function is copying to the C buffer and put a check there? We can discuss further at the meeting or whenever you want to talk.

**Comment by sakrejda** [comment]
I'm with Daniel on this one (can't make the meeting).  10^6 size checks is
not much compared to crashing with obscure messages.  People will ditch
software for that reason alone (even if it "looks buggy") and if I had a
dime for every advanced user (me included) who shot themselves in the foot
and wasted hours trying to figure out why I'd be rich.  I don't understand
how it could be a measurable fraction of the run time and I'm pretty sure
we could cut it down.

**Comment by davidmanheim** [comment]
Note: I don't think this is fixed as of the current version of Stan.

**Comment by bob-carpenter** [comment]
This makes sense.  The deSolve package in R's bdf can also produce non-sensical results that don't respect specified error bounds.

Does someone have a suggestion on how to fix BDF?

**Comment by wds15** [comment]
the new variadic ode stuff improves a lot on the error messages, so maybe just wait for 2.24 where it should land
