### ISSUE TITLE
fvar testing framework

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#557]
#### Summary:

Create a test framework for functions based on legal arguments and values that will test all the derivative combinations.

#### Description:

There's an example already for unary vectorized functions.

Ideally, I'd like functions to look like this:

```
std::function<double(double,double)> f = ... some binding ...;
auto t = tester(f);

t.good(1, 1, 2);
t.good(2, 3, 5);

t.throw(NaN, 1.0, std::domain_error);

t.run();
```

I'm hoping that by using the test factory function `tester()` we can set up the tester via type inference;  otherwise we'll have to specify those arguments.  I only write out the `std::function` thing to show what it looks like---that should be auto-able too.

The implementation should lean on the higher-order functionals if possible to minimize specific autodiff logic in the test framework. 

It can go into the directory `mix` at the appropriate level of argument for the function and run tests all the way down.  The implementations will ideally be broken up in case we wind up with functions that will not implement forward-mode.

#### Current Version:
v2.15.0

**Comment by rok-cesnovar** [comment]
This is no longer an issue with the recently merged Automatic Differentiation Testing Framework. Closing.
