### ISSUE TITLE
lgamma returns NaN when given a negative integer but should return Inf

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#560]
#### Summary:

`lgamma(-1)` returns NaN, which is documented and what Boost does but stupid

#### Description:

The limit of the Gamma function as its argument approaches a non-negative integer is + / - infinity depending on whether you approach from the right or the left. The C++11 version of lgamma returns positive infinity, as does R. We should switch to the C++11 version of all these functions in cmath.

#### Reproducible Steps:

Evaluate lgamma at a non-positive integer

#### Current Output:

NaN

#### Expected Output:

inf

#### Current Version:
v2.15.0

**Comment by andrjohns** [comment]
Closed via #1080
