### ISSUE TITLE
von Mises distribution fails for kappa=0

### ISSUE THREAD

**Issue by mbrubake** [stan-dev/math#564]
#### Summary:
The von Mises distribution returns a non-finite value when kappa=0.  This should result in a uniform distribution and likely needs to be special cased.

#### Reproducible Steps:
The following model should produce a uniform distribution of test_var but instead, fails at initialization:

```
parameters {
    real test_var;
}
model {
    test_var ~ von_mises(0,0);
}
```

#### Current Output:
```
Initialization between (-2, 2) failed after 100 attempts. 
 Try specifying initial values, reducing ranges of constrained values, or reparameterizing the model.

```

#### Expected Output:
Should sample easily and produce a uniform distribution on test_var.

#### Current Version:
v2.15.0

**Comment by bgoodri** [comment]
I have this reworked on a branch

**Comment by bob-carpenter** [comment]
@bgoodri Is it a branch that you could turn into a pull request for this issue?  If not, is it a public branch?

**Comment by bgoodri** [comment]
Yeah, I can make push it as a public branch, but I still haven't
implemented your suggestions.

**Comment by mcol** [comment]
The example model now produces the following error (repeated 100 times for each chain):
```
Chain 1 Exception: von_mises_lpdf: Scale parameter is 0, but must be > 0!
```

If I remove the `check_positive_finite` line for `kappa`, then CmdStan reports:
```
Exception initializing step size.
Posterior is improper. Please check your model.
```
which is correct, I think, as `test_var` would be distributed uniformly over all reals. Changing the model to the following, it samples correctly:
```
parameters {
  real<lower=-5, upper=5> test_var;
}
model {
  test_var ~ von_mises(0,0);
}
```
So, am I correct in thinking that @bgoodri's changes to the Bessel functions has effectively fixed this (modulo the overly stringent check on kappa)?
