### ISSUE TITLE
Vectorize fma (fused-multiply-add)

### ISSUE THREAD

**Issue by aaronjg** [stan-dev/math#567]
#### Summary:
Please provide a short couple sentence summary.
Most of the composed functions have been vectorized, however fused-multiply add and some of the others that take two arguments only take reals. 

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
Thanks for putting this in as an issue.  I thought we had a general issue to vectorize all the scalar binary functions.  But I don't see it, so I'll leave this one here.

If someone wants to take them on one at a time before that, that would also work.  `pow` has been the most requested such function.

**Comment by aaronjg** [comment]
Just saw a post on discourse about this as well. Is it part of this issue? https://github.com/stan-dev/math/issues/202

**Comment by bob-carpenter** [comment]
Yes, #202 listed all the scalar functions at one point that might be vectorized.  `fma` has three arguments, so there'll be eight instantiations for each vectorized version in terms of autodiff types.

**Comment by rok-cesnovar** [comment]
fma has since been vectorized. These are the supported signatures:

```stan
  fma(real, real, real) => real
  fma(real, real, vector) => vector
  fma(real, vector, real) => vector
  fma(real, vector, vector) => vector
  fma(vector, real, real) => vector
  fma(vector, real, vector) => vector
  fma(vector, vector, real) => vector
  fma(vector, vector, vector) => vector
  fma(real, real, row_vector) => row_vector
  fma(real, row_vector, real) => row_vector
  fma(real, row_vector, row_vector) => row_vector
  fma(row_vector, real, real) => row_vector
  fma(row_vector, real, row_vector) => row_vector
  fma(row_vector, row_vector, real) => row_vector
  fma(row_vector, row_vector, row_vector) => row_vector
  fma(real, real, matrix) => matrix
  fma(real, matrix, real) => matrix
  fma(real, matrix, matrix) => matrix
  fma(matrix, real, real) => matrix
  fma(matrix, real, matrix) => matrix
  fma(matrix, matrix, real) => matrix
  fma(matrix, matrix, matrix) => matrix
```
