### ISSUE TITLE
C++11 build infrastructure

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#569]
#### Summary:

As of 2.17, we're going to allow C++11 (and parts of C++14).  For that we need:

* [ ] all the build infrastructure to be updated to C++11/C++14 support

It'd also be nice to have:

* [ ] wiki with list of supported features across compilers we support (or a pointer to versions of compilers we require and some secondary pointers to what they support)

#### Description:

Need to do this before using C++11/C++14.

#### Current Version:
v2.16.0

**Comment by seantalts** [comment]
Here's the first draft of a wiki I made during our C++11 meeting: https://github.com/stan-dev/stan/wiki/Supported-C---Compilers-and-Language-Features

**Comment by syclik** [comment]
@seantalts, should we close this issue? It looks like we're done.

**Comment by seantalts** [comment]
I think so too. Closing!

**Comment by bob-carpenter** [comment]
Great---does this mean we can have at C++ in our code now?

Is there anything in place to check that we don't exceed what's supported cross platform?

**Comment by seantalts** [comment]
We have had C++ in our code for a long time ;)

Math supports C++11 but the upstream makefiles aren't ready yet, so I wouldn't start adding it. Daniel has another PR in process to start using some implicit targets. Once that's in I'll go ahead and update my PR for the Stan repo makefiles to begin including the relevant parts of the math repo makefiles such that they also begin to support C++11.

The check has become a bit more complicated than it used to be - before we could rely on all compilers to reject C++11 code, but now we want to allow everything that is supported by GCC 4.9.3. So the obvious way to do that is to make everything compile under GCC 4.9.3, which is now the default gcc toolchain for our travis linux builds: https://github.com/stan-dev/math/blob/develop/.travis.yml#L21
