### ISSUE TITLE
length function doesn't work with scalar_seq_views

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#574]
#### Summary:
This function:
https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/length.hpp

Doesn't work with scalar_seq_views:
https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/scalar_seq_view.hpp

length(a_scalar_seq_view) returns 1, regardless of the length of the actual underlying seq view. I think there needs to be a scalar_seq_view specialization added to https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/length.hpp .

#### Reproducible Steps:
I found this issue when I was working on https://github.com/stan-dev/math/pull/573

The max_size function here (https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/meta/max_size.hpp) depends on the length function and was giving weird behavior.

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
It helps to tag these things.  This is a new feature, not a bug, right?  That's how I labeled it.  I also put the milestone at future, because nothing currently depends on it. 

Having said that, feel free to improve the behavior while making sure not to break any existing code which might depend on current behavior.

**Comment by rayleigh** [comment]
Working on another issue, I noticed that `normal_lpdf` uses `scalar_seq_view` to wrap the arguments passed in and then uses `max_size` to determine what to loop through: 

https://github.com/stan-dev/math/blob/2ab1ea5588637c5e4cce319a08656ad0f1d257cb/stan/math/prim/scal/prob/normal_lpdf.hpp#L74-L88

I'm not sure if it's affecting anything because the tests for `normal_lpdf` passes.

However, if I run the following code:
```
  vector<fvar<double> > a(0, 5); 
  vector<fvar<double> > b(2, 5);
  stan::scalar_seq_view<vector<fvar<double> > > a_vec(a);

  std::cout << stan::length(a) << std::endl;
  std::cout << stan::length(a_vec) << std::endl;
  std::cout << stan::length(b) << std::endl;
  std::cout << stan::max_size(a, b) << std::endl;
  std::cout << stan::max_size(a_vec, b) << std::endl;
  std::cout << a.size() << std::endl;
  std::cout << b.size() << std::endl;
```
my output is the following:
```
1
1
1
1
1
0
2
```

**Comment by bob-carpenter** [comment]
@rayleigh --- is anything using that `stan::length` function in `normal_lpdf``?  

We could probably generalize the `stan::length` function to deal with views. 

I'd strongly prefer `size()` to `length()` because of the ambiguity of "length".

**Comment by bbbales2** [comment]
This looks weird to me. The scalar_seq_views definitely mess up, but normal_lpdf does max_size (which uses length) on the non-scalar_seq_view versions of the arguments.

With this code:
```
#include <stan/math/mix/mat.hpp>
#include <iostream>
#include <vector>

using namespace stan::math;

int main(int argc, char **argv) {
  std::vector<fvar<double> > a(5, 5);
  std::cout << stan::length(a) << std::endl;
}
```

I get:
```
5
```

stan::length should just use size for ```std::vector<T>s``` (https://github.com/stan-dev/math/blob/2ab1ea5588637c5e4cce319a08656ad0f1d257cb/stan/math/prim/arr/meta/length.hpp)

(For anyone wanting to build this, this should work within a copy of the Math repo: ```clang++ -I . -I lib/eigen_3.3.3 -I lib/boost_1.62.0 -I lib/cvodes_2.9.0/include test.cpp && ./a.out```)

**Comment by rayleigh** [comment]
@bob-carpenter Yes. There is a check early on whether to return 0 using `stan::length`:

https://github.com/stan-dev/math/blob/2ab1ea5588637c5e4cce319a08656ad0f1d257cb/stan/math/prim/scal/prob/normal_lpdf.hpp#L56-L57

@bbbales2 That's interesting. I went back to my test and when I included `<stan/math/mix/mat.hpp>`, the output makes more sense (as you point out, it's still broken for the `scalar_seq_view`):
```
0
1
2
2
2
0
2
```
My includes beforehand were the following:
```
#include <stan/math/fwd/core.hpp>
#include <stan/math/prim/scal.hpp>
#include <stan/math/prim/scal/meta/length.hpp>
#include <stan/math/prim/scal/meta/scalar_seq_view.hpp>
#include <gtest/gtest.h> //I was playing around within the testing framework.
#include <vector>
```

**Comment by mcol** [comment]
Now `length` is called `size`. I've updated the testcase above to read:
```
using stan::math::fvar;
using stan::math::size;
using stan::math::max_size;

std::vector<fvar<double>> a(0, 5);
std::vector<fvar<double>> b(2, 5);
stan::scalar_seq_view<std::vector<fvar<double>>> a_vec(a);

std::cout << "size(a)\t\t\t" << size(a) << std::endl;
std::cout << "size(a_vec)\t\t" << size(a_vec) << std::endl;
std::cout << "size(b)at\t\t" << size(b) << std::endl;
std::cout << "max_size(a, b)\t\t" << max_size(a, b) << std::endl;
std::cout << "max_size(a_vec, b)\t" << max_size(a_vec, b) << std::endl;
std::cout << "a.size()\t\t" << a.size() << std::endl;
std::cout << "b.size()\t\t" << b.size() << std::endl;
```
The output I get is the following:
```
size(a)                 0
size(a_vec)             0
size(b)at               2
max_size(a, b)          2
max_size(a_vec, b)      2
a.size()                0
b.size()                2
```
This looks like it's not a problem anymore (perhaps it was #1471 that fixed it).
