### ISSUE TITLE
zero length simplex causes   std::bad_alloc

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#580]
_From @aaronjg on July 25, 2017 22:44_

#### Summary:
Allocating a simplex with 0 elements causes std:bad_alloc

#### Description:
int x = 0;
simplex[x] variable;
results in at run time std::bad_alloc

#### Current Output:
std::bad_alloc

#### Expected Output:
Either a zero length vector "variable," or a more informative error. 

#### Current Version:
v2.16.0

_Copied from original issue: stan-dev/stan#2365_

**Comment by bob-carpenter** [comment]
There aren't any size zero simplexes, because they have to add up to one.  

We should catch zero size declarations for simplexes and throw an exception.  This has to be at runtime when we know the size.  I should also update the doc.

**Comment by bob-carpenter** [comment]
I moved the issue to `stan-dev/math`, because the constraining transform needs to be instrumented to throw an exception.  Then the new line numbering @mitzimorris is putting in for declarations will locate the problem.

**Comment by mitzimorris** [comment]
verified that the new numbering does locate the problem.
program named `bad_simplex.stan`:

```
transformed data {
  int x = 0;
  simplex[x] variable;
}
```
generates runtime error:
Exception: bad_simplex_model_namespace::bad_simplex_model: variable has size 0, but must have a non-zero size  (in 'bad_simplex.stan' at line 3)

**Comment by bob-carpenter** [comment]
Awesome.  Nice side effect of the wider scope of the `try`/`catch`.   Closing.
