### ISSUE TITLE
check nan input for matrix functions

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#59]
_From @bob-carpenter on December 18, 2014 21:57_

- [ ] max_test.cpp: returns NaN if any input is NaN
- [ ] mdivide_left_ldlt_test.cpp
- [ ] mdivide_right_ldlt_test.cpp
- [ ] min_test.cpp
- [ ] ? fmin and fmax if they're vectorized
- [ ] sort_indices_test.cpp: if any input is NaN, then the first index will be that of the NaN (everything else that follows is what would normally be returned)
- [ ] sort_test.cpp: if any input is NaN, then the first argument in the vector return is NaN

_Copied from original issue: stan-dev/stan#1176_

**Comment by bob-carpenter** [comment]
Not clear what this is asking for, so I'm closing. Issue #253 addresses sorting.
