### ISSUE TITLE
Remove stan:: namespace qualification

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#594]
#### Summary:
We don't need the `stan::` namespace qualification within the `stan` namespace (all of the math library) unless there's ambiguity with another namespace.

See @bob-carpenter's [comment](https://github.com/stan-dev/math/pull/588#discussion_r130221763)

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
Thanks much for turning these into issues.

**Comment by andrjohns** [comment]
Closed via #1155
