### ISSUE TITLE
Fix order of return for normal_cdf

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#597]
#### Summary:
See @bob-carpenter's [comment](https://github.com/stan-dev/math/pull/588#discussion_r130223172)

> This is a different order of return vs. all the other cases. Should we fix one? I don't think there's an efficiency concern either way, but I think having the return be a constant and the return defined afterwards is easier to understand (doesn't require you to go look back to find value of cdf being returned).

#### Current Version:
v2.16.0

**Comment by andrjohns** [comment]
Closed via #632
