### ISSUE TITLE
update lib to Boost 1.64.0

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/math#599]
#### Summary:
lib/stan_math must build with Boost 1.64.0.  currently fails to do so. R is upgrading to use Boost 1.64.0, Stan needs to do the same.  see https://github.com/stan-dev/rstan/issues/441

#### Current Version:
v2.16.0

**Comment by mitzimorris** [comment]
hit this issue:  https://github.com/dealii/dealii/issues/4302
need to change #includes in certain .hpp files - is this kosher?
e.g.

```
perl -p -i -e 's!#include <boost/serialization/array.hpp>!#include <boost/serialization/array_wrapper.hpp>!' lib/boost_1.64.0/boost/numeric/ublas/*.hpp
```

**Comment by syclik** [comment]
I'm a little puzzled. Is there a reason why we need to patch boost? I'd expect we need to fix that in the math headers, but not boost.

**Comment by mitzimorris** [comment]
you're quite correct  - proper solution is #ifdefs in the math headers.
