### ISSUE TITLE
libc++ flag causing problems with Ubuntu 16.04

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#604]
#### Summary:

I'm getting errors trying to build the tests with the latest Stan math library

```
/usr/include/c++/v1/cxxabi.h:21:10: fatal error: '__cxxabi_config.h' file not found
#include <__cxxabi_config.h>
```

If I comment out the line:
```
  CXXFLAGS += -stdlib=libc++
```

From make/detect_cc, Things work. I have the Clang libc++ installed. Clang 3.8, Ubuntu 16.04.

#### Description:

This is the command I run:

```
./runTests.py test/unit
```

This is a more detailed output:

```
make -j1 test/unit/math/rev/arr/meta/VectorBuilder_test test/unit/math/rev/arr/meta/partials_return_type_test test/unit/math/rev/arr/meta/contains_nonconstant_struct_test test/unit/math/rev/arr/meta/return_type_test test/unit/math/rev/arr/meta/is_constant_struct_test test/unit/math/rev/arr/meta/VectorBuilderHelper_test
In file included from test/unit/math/rev/arr/meta/is_constant_struct_test.cpp:1:
In file included from ./stan/math/rev/arr.hpp:8:
In file included from ./stan/math/prim/arr.hpp:38:
In file included from ./stan/math/prim/arr/functor/integrate_ode_rk45.hpp:13:
In file included from lib/boost_1.62.0/boost/numeric/odeint.hpp:73:
In file included from lib/boost_1.62.0/boost/numeric/odeint/integrate/observer_collection.hpp:23:
In file included from lib/boost_1.62.0/boost/function.hpp:24:
In file included from lib/boost_1.62.0/boost/function/detail/prologue.hpp:17:
In file included from lib/boost_1.62.0/boost/function/function_base.hpp:21:
In file included from lib/boost_1.62.0/boost/type_index.hpp:29:
In file included from lib/boost_1.62.0/boost/type_index/stl_type_index.hpp:34:
In file included from lib/boost_1.62.0/boost/core/demangle.hpp:32:
/usr/include/c++/v1/cxxabi.h:21:10: fatal error: '__cxxabi_config.h' file not found
#include <__cxxabi_config.h>
```

#### Current Version:
develop

**Comment by bgoodri** [comment]
Do you have libc++abi1 and the packages that go with it installed?

**Comment by bbbales2** [comment]
Yeah, I installed all the stuff that looked mildly interesting on https://launchpad.net/ubuntu/+source/libc%2B%2B

I'd assume it's just my desktop that's messed up (the packages on here are all crazy) but I tried it on my laptop and got the same thing.

**Comment by bgoodri** [comment]
It works for me on Debian unstable with clang++-3.8. If you have
libc++abi-dev, then maybe Ubuntu just messed up the search path or
something.

**Comment by bbbales2** [comment]
Yeah, might just be an Ubuntu problem.

From https://stackoverflow.com/a/43769803/3769360 it sounds like the libc++ might just be out of date in the package manager (this is the correct link for 16.04, it says it only has 3.7, whereas clang is at 3.8 https://packages.ubuntu.com/xenial/libc++-dev)

I dunno. If this sounds like an Ubuntu issue that can't be addressed, feel free to close this. I'm happy just commenting out the flag.

**Comment by avehtari** [comment]
I had today this same problem, and commenting out that line helped.
