### ISSUE TITLE
check_matching_dims' behavior is inconsistent with its description

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/math#607]
#### Summary:
The behavior of `check_matching_dims` is inconsistent with its description.

#### Description:
In `check_matching_dims`, the function is described as following:

https://github.com/stan-dev/math/blob/82ca96a44358f8f68ed31051a109128a54296090/stan/math/prim/mat/err/check_matching_dims.hpp#L14-L18

However, in `test/unit/math/prim/mat/err/check_matching_dims_test.cpp`,

https://github.com/stan-dev/math/blob/82ca96a44358f8f68ed31051a109128a54296090/test/unit/math/prim/mat/err/check_matching_dims_test.cpp#L61-L64

https://github.com/stan-dev/math/blob/82ca96a44358f8f68ed31051a109128a54296090/test/unit/math/prim/mat/err/check_matching_dims_test.cpp#L77-L79

#### Reproducible Steps:
Run `test/unit/math/prim/mat/err/check_matching_dims_test.cpp`.

#### Current Output:
`check_matching_dims` only checks the dimensions using `.rows()` and `.cols()`.

https://github.com/stan-dev/math/blob/82ca96a44358f8f68ed31051a109128a54296090/stan/math/prim/mat/err/check_matching_dims.hpp#L42-L47

#### Expected Output:
I expect there to be a check on the compile time rows and cols.

#### Current Version:
v2.16.0

**Comment by mcol** [comment]
This was fixed by #619.
