### ISSUE TITLE
Sort out CXX and CC, make detect_cc ONLY detect the compiler type.

### ISSUE THREAD

**Issue by sakrejda** [stan-dev/math#617]
#### Summary:
Compiler flags can get borked.  It causes compilation errors

#### Description:
Currently `stan-dev/math` uses $(CC) to specify the C++ compiler and `stan-dev/cmdstan` (correctly) uses $(CXX) for the same thing.  This breaks things when `cmdstan` sets $(CXX) from $(CC) but includes `stan-dev/math` detect_cc in its makefile (which ignores $(CXX)).  

#### Reproducible Steps:

```
git clone git@github.com:stan-dev/cmdstan
cd cmdstan
```
edit `make/local` to say `CXX=g++`

```
make examples/bernoulli/bernoulli
```

This fails because g++ is called with a clang++ flag.

#### Current Output:
--- Linking C++ model ---
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -stdlib=libc++ -Wno-unused-function -Wno-uninitialized -DNO_FPRINTF_OUTPUT -pipe   -O3 -o examples/bernoulli/bernoulli src/cmdstan/main.cpp -include examples/bernoulli/bernoulli.hpp stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a
g++: error: unrecognized command line option ‘-stdlib=libc++’
make/models:10: recipe for target 'examples/bernoulli/bernoulli' failed
make: *** [examples/bernoulli/bernoulli] Error 1

#### Expected Output:
Success.

#### Additional Information:
http://discourse.mc-stan.org/t/clang-ubuntu-problems/1761

#### Current Version:
v2.17.0 AND develop

**Comment by sakrejda** [comment]
The solution is to modify `stan-dev/math` makefiles to use CXX and CC correctly, and to move the setting of CXXFLAGS out of `detect_cc`

**Comment by rok-cesnovar** [comment]
We use CXX both for both math and cmdstan. Fixed.
