### ISSUE TITLE
skew_normal_rng seems a little too happy to return infs

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#618]
#### Summary:
The way skew normals are generated, it's pretty easy to end up generating a pile of infs.

#### Description:

When I was writing the vectorized skew normal tests I kept getting segfaults in one of the unit distribution tests (assert_matches_quantiles in test/unit/math/prim/scal/prob/util.hpp). These segfaults were coming about cause the skew_normal_rng was spitting out infs.

It's possible to patch assert_matches_quantiles so it doesn't blow up (and the tests pass) by just manually counting inf values in the appropriate quantile (either the minimum or maximum quantile), but I don't think the rng should be returning these infs in the first place.

This is the code that generates the skew_normal random variates:
```c++
boost::math::skew_normal_distribution<> dist(mu, sigma, alpha);
output[n] = quantile(dist, uniform_rng(0.0, 1.0, rng));
```

I think something is going wrong in the optimization problem in quantile. Suggestions on what to do? I can just dodge the issue and bin the numbers appropriately, but it doesn't seem great that we're getting infs.

#### Reproducible Steps:
This code will generate infs:
```c++
#include <boost/math/distributions.hpp>
#include <iostream>

int main(int argc, char **argv) {
  boost::math::skew_normal_distribution<> dist(-2.5, 0.1, -2.5);

  double r0 = 0.99990;

  for(int i = 0; i < 10; i++) {
    double r = r0 + i * 0.00001;
    std::cout << "quantile " << r << " = " << quantile(dist, r) << std::endl;
  }
}
```

Build and run with (in a math git repo):
```
clang++ -I lib/boost_1.64.0/ skew.cpp && ./a.out
```

The output is something like:
```
bbales2@frog:~/math-vec$ clang++ -I lib/boost_1.64.0/ skew.cpp && ./a.out 
quantile 0.9999 = -2.38662
quantile 0.99991 = -2.38553
quantile 0.99992 = -2.38432
quantile 0.99993 = -2.38296
quantile 0.99994 = inf
quantile 0.99995 = inf
quantile 0.99996 = inf
quantile 0.99997 = inf
quantile 0.99998 = inf
quantile 0.99999 = inf
```

#### Current Version:
v2.17.0

**Comment by bgoodri** [comment]
Dup of https://github.com/stan-dev/math/issues/527
