### ISSUE TITLE
No quantiles test in the unit tests for exp_mod_normal_rng

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#635]
#### Summary:
There aren't any tests that validate exp_mod_normal_rng via assert_matches_quantiles. These tests are there for all the other distributions.

#### Description
Current code: https://github.com/stan-dev/math/blob/develop/test/unit/math/prim/scal/prob/exp_mod_normal_test.cpp

Example _rng with test: https://github.com/stan-dev/math/blob/develop/test/unit/math/prim/scal/prob/normal_test.cpp

The issue with this is it's not easy to test that exp_mod_normal_rng is working correctly. I found this out after I introduced a bug into it in my local working branch (trying to make it a little faster -- these changes didn't get committed) and the unit tests passed.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
Thanks for filing the issue.  The CDFs are implemented, so it shouldn't be hard to add them.

**Comment by bob-carpenter** [comment]
P.S.  I assigned to you (@bbbales2), but if you don't want to deal with it, please unassign yourself.

**Comment by mcol** [comment]
I believe this was fixed in #833.
