### ISSUE TITLE
Lack of function for computing the inverse of a matrix from its Cholesky factor

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#648]
#### Summary:

We do not have a function that inputs a Cholesky factor `L` and outputs `(L * L')^(-1)`.

#### Description:

Such a function (for upper triangular Cholesky factors) exists in LAPACK and R under the name `chol2inv`.

#### Expected Output:

`(L')^(-1) * L^(-1)`

#### Additional Information:

I have written such a function.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
@bgoodri, it's gonna be pretty exhausting if you want to call things "stupid" all the time. There are a few things you can do:
- [ ] (easy) remove the section when you create the issue
- [ ] (better) use the section to describe actual tests
- [ ] (best) be constructive and suggest a change to the template that's better than what we have

I'm sure there are other possible things you can do.

If you didn't know, the pull request template is in the code base here: https://github.com/stan-dev/math/blob/develop/.github/ISSUE_TEMPLATE.md

We are using GitHub to the best of our ability. There is currently no ability to conditionally serve a template based on the label. Whatever process we have is fluid and we can change it.

Thanks. (I couldn't tell if that was in jest -- it's really hard to read emotion through an issue.)

**Comment by bob-carpenter** [comment]
I agree with @syclik here.  Please try to not insult people on GitHub or our forum.

When someone calls something you've done "stupid", it feels like they're calling you "stupid" and it hurts.

**Comment by bgoodri** [comment]
I am fine with removing sections, which I had assumed were obligatory. I should have said "Having to fill out a section for Reproducible Steps for a missing feature is stupid."

**Comment by bob-carpenter** [comment]
I understood that.  I'm pretty thick-skinned myself, but I've worked with a lot of people who take "stupid" as the worst possible insult, so I think we should just avoid the term (and synonyms).   Having said that, I have a hard time following that advice myself, being particularly prone to overuse "idiotic" in relation to what I think are really bad ideas.

**Comment by syclik** [comment]
I didn't read the original remark as an insult, but as frustration directed at the process / template. I'd rather just find a way to make the process better than have it be a source of frustration. Anyway, feel free to remove when you create an issue when it's not appropriate or suggest something more appropriate to replace it with.
