### ISSUE TITLE
Automate style guidelines

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#661]
#### Summary:
cpplint detects some issues, but doesn't fix them. There are automated tools like [clang-format](http://www.labri.fr/perso/fleury/posts/programming/using-clang-tidy-and-clang-format.html) that can be installed as githooks (and editor plugins) to help us write code more consistently in an automated way. There are some good reasons to do this [described here](https://mtlynch.io/human-code-reviews-1/#let-computers-do-the-boring-parts).

#### Description:
I propose to use clang-format and clang-tidy on our codebase and provide an automated solution for developers to ensure that whenever code is committed, it is formatted automatically (as best we can - automation can't fix everything on its own). I don't want us to make our own tools for this, however, so this will entail adopting something even closer to the Google style guide than we currently are.

#### Current Version:
v2.17.0

**Comment by bgoodri** [comment]
I think it is worth considering dumping Google's rules to a file and
editing them to become Stan rules. If this is (which I think it should be)
something that is mostly automated and humans do not necessarily need to
memorize, then the cost of deviating from Google's style is low.

**Comment by seantalts** [comment]
I'm starting it off with the Google style guide dumped to the file used for this, `.clang-format`. One thing I would love to avoid is trying to arbitrate or otherwise becoming involved in any style discussions. Do you think there are deviations worth a potential bike-shedding flame war?

**Comment by bgoodri** [comment]
I think most people would not object to the deviations from Google that are
already part of the Stan style guidelines. I hope that most people do not
strongly favor that many additional deviations.

**Comment by seantalts** [comment]
Which parts do you care about? The major one jumping out at me is that we indent namespaces

**Comment by seantalts** [comment]
I changed the namespace indentation and the access modifier (public, private, etc) indentation to match our style guide.

**Comment by bgoodri** [comment]
I don't actually care about much of them. It was mostly @bob-carpenter I think. But I do like putting for loops on a single line when they are less than 80 characters.

**Comment by bob-carpenter** [comment]
I like the basic idea.  

I'm OK not indenting namespaces.

But there are some big conflicts with their style guide that are going to take some work, if not be impossible;  this is from memory, but I'm now going to go through their new style guide item by item to give you a better feel for the scope of making Stan's code bases compliant.  Some biggies:

* exceptions are forbidden;  they want everything done C-style by return code for visibility.

* reference arguments are forbidden;  they want everything done with pointers.

* camel-case naming, which would destroy our own code base
and require a symbol-table rewrite intervention with the language for
now and into the future to allow us to keep the naming convention.

* `.cc` and `.h` rather than `.cpp` and `.hpp` for file naming

The last two are backward-compatibility breaking, of course.

I'm not keen on a bunch of more formatting-oriented stuff, like

* the one-character indent on `:` in constructors

*  the left-brace on its own line for function definitions but not loops; don't know where they want the `const` in that situation.

I could live with both those, though.

**Comment by bob-carpenter** [comment]
If you want to know where our style came from, I tried to follow the standard libary naming conventions, the way Stroustroup wrote code in his book on C++, and the way the code was laid out on cplusplus.com and the way it was done in Java, which Daniel and I were both used to.  About the only deviation from those is that I didn't put a left brace on its own line for function definitions.  I have no idea why people like this given the other conventions, but as I said, I'm willing to comply.

**Comment by seantalts** [comment]
There's also stuff like that Daniel "doesn't like" the way the Google guide says access modifiers should be offset by 1 space instead of 2 from class definition. It just all seems so arbitrary and faced with these things I vastly prefer adopting an existing standard instead of coming up with some hybrid thing that, by definition, no one else could possibly be familiar with when trying to come onboard to the project. 

Switching to Google's style guide on names would be a huge task given the way the math functions are visible with no mapping layer through to the Stan language, so I would propose we not mess with that. But everything else the automated formatter can fix to be some industry standard, I feel like we would need a compelling reason to deviate from it (beyond some developers personal taste).

**Comment by seantalts** [comment]
When I brought this up at the meeting, I thought I had the green light from everyone to go ahead and move us closer to the Google style guide (or at least as close as can be automated easily).

**Comment by syclik** [comment]
> There's also stuff like that Daniel "doesn't like" the way the Google guide says access modifiers should be offset by 1 space instead of 2 from class definition. It just seems arbitrary and faced with these things I vastly prefer adopting an existing standard instead of coming up with some hybrid thing that, by definition, no one else could possibly be familiar with when trying to come onboard to the project.

Just FYI, the comment in bold was me, the comment before that was Bob. In fact, most of that was discussed on our old google groups and was from Bob. I was the one that collected it and put it up on our wiki. (The reason for the dislike there was a practical one: emacs doesn't indent that way by default.)

And you can see that on a lot of them, both Bob and I aren't that picky. We just preferred it one way, but were willing to go with Google's style guide.

> Switching to Google's style guide on names would be a huge task given the way the math functions are visible with no mapping layer through to the Stan language, so I would propose we not mess with that. But everything else the automated formatter can fix to be some industry standard, I feel like we would need a compelling reason to deviate from it (beyond some developers personal taste).

Agreed. While you're doing this, it would be good to let us know which exceptions are being overturned. And if there's ambiguity in Google's guidelines and we've explicitly called it out (in that doc), then go with what we've already done.

**Comment by syclik** [comment]
> When I brought this up at the meeting, I thought I had the green light from everyone to go ahead and move us closer to the Google style guide (or at least as close as can be automated easily).

Yes, you still do. But if there are any conflicts between our style and Google's style (or however it gets automated), unless it's just a matter of opinion, it should still be a discussion.

**Comment by seantalts** [comment]
Okay, great. I will just go ahead and move us to pure Google in the areas where clang-format can automatically convert us and where that doesn't impact functionality at all, and turn off the import reordering for now while we sort that issue out on the discourse thread. Installing the emacs plugin for Google style as mentioned in the PR should make emacs respect the Google way.

I think the only ways in which we differ from Google on style-only stuff that can be automated are:
1. a few indentation and spacing rules
2. namespace comments at the end of namespaces (`}  // namespace math`).

It can automatically fix all of that every time someone commits, so it shouldn't be any burden on developers.

**Comment by syclik** [comment]
AWESOME!

Should the devs run it locally? Or is this something that's only run
remotely?

**Comment by seantalts** [comment]
I think the best model is that devs have clang-format and the git pre-commit hook (included) installed, and ideally an editor plugin so they aren't frustrated with it going back and forth.

**Comment by syclik** [comment]
That makes sense. What do you envision happening with exceptions to clang-format? Will it be auto-formatted for them? Or will the build error?

**Comment by seantalts** [comment]
The build will error if they disobey the .clang-format file, which will
require someone to not have the hook installed or to bypass it. The only
exception to what clang-format can do automatically for Google style is the
include order sorting.

**Comment by bob-carpenter** [comment]
I agree with just going with the standard even if I don't like bits of it.  The one change I was asking for on where to break operators isn't described one way or the other by their style guide.  At least if if it is, I can't see it.  

What's this going to do for operators?  Their spec's ambiguous and says spaces are required around operators like `=`, `+`, and `-` but are optional around factors (presumably `*` and `/`).  I'd rather have spaces, but didn't see how to format it.  Both are compatible.  

You mean we need it byte-by-byte matching to the output of the clang-reformat?  Why not just do that automatically then?

**Comment by seantalts** [comment]
With words they say both are fine: "Note that when the code wraps in this example, both of the && logical AND operators are at the end of the line. This is more common in Google code, though wrapping all operators at the beginning of the line is also allowed." We can change it to your style.

re: byte-by-byte matching and doing it automatically - it is automatic, but generally developers have preferred to be able to interact with the formatter locally via automated git hooks than to have it change on their branch remotely and deal with that conflict every time.

**Comment by sakrejda** [comment]
I'm not sure I understand this.  If it can change remotely them it becomes
a conflict next time I pull? I can see that being strange but I'm not sure
if that's what you mean.

**Comment by seantalts** [comment]
Yes.

**Comment by seantalts** [comment]
I mean, it doesn't have to become a conflict, but it does become a commit to your branch formatting the files you were working on. It's likely to conflict over time.
