### ISSUE TITLE
Change std::string back to char* (PR #584) for performance reasons

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#667]
#### Summary:
We changed from char* to std::string in #584, issue #460.

This was bad for performance. We should
- [ ] revert #584 
- [ ] reopen #460 (C++11 should be able to do this without the performance hit)

#### Reproducible Steps:
Run the performance tests. No other behavior changed.

#### Current Version:
v2.17.0

**Comment by beckermr** [comment]
Does anyone have an estimate of how big this regression was? I updated to 2.17.1 and saw a big decrease in runtime. Trying to figure out if this issue being fixed is a plausible solution.

**Comment by beckermr** [comment]
I am doing the test tonight but I don’t really understand what I should be testing. Like is this only bad for models with loops and indexing for example?

**Comment by bob-carpenter** [comment]
It's bad pretty much everywhere functions get called. 

They all pass error messages, such as the function name, to validation functions.

These were being converted back and forth with copies that were costly.  It's fixed in the current release.

**Comment by beckermr** [comment]
Thanks @bob-carpenter! 

I am not seeing a big difference on the eight schools file but I suspect this model is probably too small.

**Comment by beckermr** [comment]
Wow ok. I am seeing closer to 3x locally so this appears to real. 

Thanks for the fix and the help!
