### ISSUE TITLE
Fix warning on neg_binomial_test.hpp

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#671]
#### Summary:
http://d1m1s1b1.stat.columbia.edu:8080/job/Math%20-%20Tests%20-%20Distribution/380/warnings10Result/source.3628587390108625363/#73
"control reaches the end of non-void function" here:

```
    if (alpha > 1e10)
        return -lgamma(n + 1.0) + multiply_log(n, alpha / beta) - alpha / beta;
    if (n != 0)
        return binomial_coefficient_log<typename stan::scalar_type<T_shape>::type>(n + alpha - 1.0, n)
          -n * log1p(beta) + alpha * log(beta / (1 + beta));
  }
```
I'd fix it but I'm not sure what it's supposed to do if both of those fail. Git blame calls out Daniel Lee so assigning him for now.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
The current implementation should be OK as long as n + alpha > 1.  

You might want to replace this with throwing an exception otherwise just to be clear it's undefined behavior.
