### ISSUE TITLE
remove redundant Eigen typedefs

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#68]
Remove the redundant typedefs:

* [x]  remove `src/stan/math/prim/mat/typedefs.hpp`
* [x] replace `matrix_d` with `Eigen::MatrixXd`
* [x] replace `vector_d` with `Eigen::VectorXd`
* [x] replace `row_vector_d` with `Eigen::RowVectorXd`
* [x] replace uses of `size_type` with `int`

There's more utility in these, but they should probably also go as they introduce inconsistent conventions and don't allow polymorphism:

* [ ]  remove `src/stan/agrad/rev/matrix/typedefs.hpp`
* [ ]  remove `src/stan/agrad/fwd/matrix/typedefs.hpp`
* [ ] replace `var`-based uses with the full types

_Copied from original issue: stan-dev/stan#1251_

**Comment by bob-carpenter** [comment]
Having just removed the double typedefs (hit 224) files in branch `feature/0068-remove-eigen-typedefs`, I realized this is actually a bad idea, so I'm closing the issue.

**Comment by bob-carpenter** [comment]
Having just removed the double typedefs (hit 224) files in branch `feature/0068-remove-eigen-typedefs`, I realized this is actually a bad idea, so I'm closing the issue.
