### ISSUE TITLE
upgrade to boost 1.65.1

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#680]
#### Summary:
MPI support is broken in 1.64.0 and BH is at 1.65

#### Description:
MPI things cannot be build with this.

#### Reproducible Steps:
try to build MPI libs from boost 1.64.0 - it fails

#### Current Output:
NaN

#### Expected Output:
Things should just build.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by wds15** [comment]
we could consider to use also include the boost serialization and mpi library into stan-math. Currently we only distribute the header-only libs, but not the libraries which need compilation.

The mpi and the serialization library will be a requirement for within-chain parallelization to work.

**Comment by bgoodri** [comment]
Do you know what commit fixed MPI in 1.65.1? I can possibly get it into the
next rstan. Having mpi and serialization is not a big deal for R because we
are building a shared object for StanHeaders anyway (to include CVODES).

**Comment by wds15** [comment]
to get mpi working the 1.65.0 boost is sufficient (only 1.64.0 has a broken MPI in the released version). I was suggesting 1.65.1 because it was released very shortly after 1.65.0. Hence I don't mind either way. We could ask Dirk about bumping to 1.65.1 or we live with 1.65.0.

**Comment by wds15** [comment]
as discussed earlier we are going to include the boost mpi and the serialization library into stan-math. Can we simply include those with this issue?

**Comment by syclik** [comment]
Yes, but can you be more specific? What other things does it need? It
sounds like we need to include Boost Build as well? Is that it?

**Comment by wds15** [comment]
it would probably be the easiest way to deploy if we include boost build. The alternative is to figure out what boost build is actually doing in order to build mpi and serialization. It seems to me that there are not any extra-dependencies such that we could well be able to figure out a makefile to build it ourselves without boost build. I am open for either approach - it depends what others think and what our goals are here (minimize stuff to include vs convenience of building boost mpi+serialization).

**Comment by bob-carpenter** [comment]
If Boost build works, it'll be easier in the long run to just call that.

**Comment by wds15** [comment]
could we quickly run this by the bigger stan team today in the meeting if we should consider this as an option to include boost build?

**Comment by bob-carpenter** [comment]
I try to run user-facing decisions in the language by the larger team, but something like this won't matter to most people as long as it doesn't make installation any harder from their perspective.  I'd rather not reimplement their build system if what they have works for us.

**Comment by bob-carpenter** [comment]
I'm working on adding the basic boost now, but we'll then need to go and add in the rest of 1.65.1 that @wds15 needs.

**Comment by bgoodri** [comment]
Boost is up to 1.66.0 now anyway. It has a nice metaprogramming library.

**Comment by bob-carpenter** [comment]
Boost's at 1.66, but BH is still at 1.65.0, so we should stick to 1.65 to not get ahead of BH.  I went with the patch version 1.65.1 which fixes some bugs in 1.65.0 in modules I don't even think we use.

**Comment by bgoodri** [comment]
I think it is fair to assume that if 1.66.0 were necessary for something,
BH could be upgraded to 1.66.0 in a few weeks. I don't think the MPI stuff
falls in that category. The metaprogramming library would, but that is OT.

**Comment by wds15** [comment]
65 or 66 should not matter for mpi. If 66 is so much better, then let’s just ask Dirk. He is very quick in responding usually.

**Comment by bob-carpenter** [comment]
I don't even know what's in 1.66.  I was just saying we need to keep in synch with BH.  It's fine if that happens through both of us keeping up with new Boost releases.
