### ISSUE TITLE
Vectorised error checking needs additional includes for standalone use

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#682]
#### Summary:
Error checking functions (```check_bounded``` , ```check_not_nan```, etc) are not working with vectors unless the headers for ```prim/mat/meta/is_vector```, ```prim/mat/meta/get```, and ```prim/mat/meta/length``` are included

#### Description:
Compilation fails as error functions attempt to check entirety of vector at once, rather than iterating through each value. This is because the ```prim/scal``` functions being used for testing if the input is a vector and for retrieving values from the vector.

The ```prim/mat``` versions of these (is_vector, get, and length) need to be included at some point for functions to compile and run correctly.

#### Reproducible Steps:
```
#include <stan/math/prim/mat/fun/Eigen.hpp>
#include <stan/math/prim/scal/err/check_not_nan.hpp>

int main() {
      Eigen::Matrix<double, Eigen::Dynamic, 1> vec(4);
      vec << 0.11, 0.5, std::numeric_limits<double>::quiet_NaN(), 0.2;

      stan::math::check_not_nan("Error test", "input", vec);
      return 0;
}
```
```
clang++ -I ~/math -I ~/math/lib/eigen_3.3.3/ -I ~/math/lib/boost_1.64.0/ -I ~/math/lib/cvodes_2.9.0/include/ -std=c++1y err.cpp 
In file included from err.cpp:2:
In file included from /home/andrew/math/stan/math/prim/scal/err/check_not_nan.hpp:8:
/home/andrew/math/stan/math/prim/scal/fun/value_of_rec.hpp:24:14: error: cannot
      convert 'const Eigen::Matrix<double, -1, 1, 0, -1, 1>' to 'double' without
      a conversion operator
      return static_cast<double>(x);
             ^~~~~~~~~~~~~~~~~~~~~~
/home/andrew/math/stan/math/prim/scal/err/check_not_nan.hpp:20:22: note: in
      instantiation of function template specialization
      'stan::math::value_of_rec<Eigen::Matrix<double, -1, 1, 0, -1, 1> >'
      requested here
          if (is_nan(value_of_rec(y)))
                     ^
/home/andrew/math/stan/math/prim/scal/err/check_not_nan.hpp:60:49: note: in
      instantiation of member function 'stan::math::(anonymous
      namespace)::not_nan<Eigen::Matrix<double, -1, 1, 0, -1, 1>, false>::check'
      requested here
      not_nan<T_y, is_vector_like<T_y>::value>::check(function, name, y);
                                                ^
err.cpp:8:19: note: in instantiation of function template specialization
      'stan::math::check_not_nan<Eigen::Matrix<double, -1, 1, 0, -1, 1> >'
      requested here
      stan::math::check_not_nan("Error test", "input", vec);
                  ^
1 error generated.

```
#### Current Output:

The output shows that the input is not being recognised as a vector::
 ```
not_nan<Eigen::Matrix<double, -1, 1, 0, -1, 1>, false>::check'
      requested here
      not_nan<T_y, is_vector_like<T_y>::value>::check(function, name, y)
```

If ```#include <stan/math/prim/mat/meta/is_vector.hpp>``` is added, the input is then recognised as a vector but the check still fails:
```
clang++ -I ~/math -I ~/math/lib/eigen_3.3.3/ -I ~/math/lib/boost_1.64.0/ -I ~/math/lib/cvodes_2.9.0/include/ -std=c++1y err.cpp 
In file included from err.cpp:3:
In file included from /home/andrew/math/stan/math/prim/scal/err/check_not_nan.hpp:8:
/home/andrew/math/stan/math/prim/scal/fun/value_of_rec.hpp:24:14: error: cannot
      convert 'const Eigen::Matrix<double, -1, 1, 0, -1, 1>' to 'double' without
      a conversion operator
      return static_cast<double>(x);
             ^~~~~~~~~~~~~~~~~~~~~~
/home/andrew/math/stan/math/prim/scal/err/check_not_nan.hpp:32:24: note: in
      instantiation of function template specialization
      'stan::math::value_of_rec<Eigen::Matrix<double, -1, 1, 0, -1, 1> >'
      requested here
            if (is_nan(value_of_rec(stan::get(y, n))))
                       ^
/home/andrew/math/stan/math/prim/scal/err/check_not_nan.hpp:60:49: note: in
      instantiation of member function 'stan::math::(anonymous
      namespace)::not_nan<Eigen::Matrix<double, -1, 1, 0, -1, 1>, true>::check'
      requested here
      not_nan<T_y, is_vector_like<T_y>::value>::check(function, name, y);
                                                ^
err.cpp:9:19: note: in instantiation of function template specialization
      'stan::math::check_not_nan<Eigen::Matrix<double, -1, 1, 0, -1, 1> >'
      requested here
      stan::math::check_not_nan("Error test", "input", vec);
                  ^
1 error generated.
```
This is failing because ```get``` should be passing the ```n```th value of ```y``` to ```value_rec```, but is instead just passing the entire vector ```y```

If ```#include <stan/math/prim/mat/meta/get.hpp>``` is added, it then compiles without issue. However, the compiled program does not throw (when it should).

This is because the size of the vector is being checked with ```prim/scal/meta/length```, which returns length = 1. If ```#include <stan/math/prim/mat/meta/length.hpp>``` is added, it compiles and throws as it should:

```
#include <stan/math/prim/mat/fun/Eigen.hpp>
#include <stan/math/prim/mat/meta/is_vector.hpp>
#include <stan/math/prim/mat/meta/get.hpp>
#include <stan/math/prim/mat/meta/length.hpp>
#include <stan/math/prim/scal/err/check_not_nan.hpp>

int main() {
      Eigen::Matrix<double, Eigen::Dynamic, 1> vec(4);
      vec << 0.11, 0.5, std::numeric_limits<double>::quiet_NaN(), 0.2;

      stan::math::check_not_nan("Error test", "input", vec);
      return 0;
}
```
```
clang++ -I ~/math -I ~/math/lib/eigen_3.3.3/ -I ~/math/lib/boost_1.64.0/ -I ~/math/lib/cvodes_2.9.0/include/ -std=c++1y err.cpp 

./a.out 
terminate called after throwing an instance of 'std::domain_error'
  what():  Error test: input[3] is nan, but must not be nan!
Aborted (core dumped)
```

#### Expected Output:
Should return std::domain_error

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
I believe this is correct behavior. You should include stan/math/prim/mat.hpp ahead of including check_not_nan. 

There is a way to include headers individually, but it's trickier than I can type on my phone. Please check the math wiki's home page to see if that explains enough.

**Comment by andrjohns** [comment]
For new ```prim/mat``` functions as well? Seems like that would pull in a lot of unnecessary headers

**Comment by syclik** [comment]
No. For the implementation in the math library, you only include the minimal header files. And yes, they won't resolve without the correct traits if you included those alone, but that's a feature of modern c++ we are leveraging in order to build the math library. (If we were to include those prim traits in that file, we'd not be able to build it with rev or fwd or mix properly.)

The test code, or in your example, the file that contains int main(), should include the big header file before including your new function. Please see examples of tests in the math library. If you need help finding them, reach out.

**Comment by andrjohns** [comment]
That makes sense, thanks for clearing that up for me. Pretty new to c++ so thanks for the patience while I muddle through!

**Comment by syclik** [comment]
No problem! Our use of C++ leans hard on templating meta programming and is pretty complex. We're happy to help figure things out. 

Feel free to open threads on discourse if you're spending more than a few hours on any single problem.
