### ISSUE TITLE
doc fix for effective_sample_size

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#683]
#### Summary:

@avehtari pointed out on our formus that the doc for the ESS code doesn't match its implementation:

http://discourse.mc-stan.org/t/n-eff-bda3-vs-stan/2608/2

Fix so that it matches.

P.S.  It'd also be nice to fix that Eigen Matrix of Eigen Matrix data structure.

#### Current Version:
v2.17.0

**Comment by avehtari** [comment]
Is there somewhere support for the comment in the doc for the current ESS implementation? If not, then it would be better to change the code to match BDA3 as there is theory behind the Geyer's approach.

**Comment by bob-carpenter** [comment]
I thought our implementation matched the BDA definition.

I don't mind if matches or not or what the implementation is---@betanalpha and @andrewgelman would be the ones to ask (don't know if Andrew gets GitHub messages).

**Comment by avehtari** [comment]
I asked @betanalpha, and he was in favor of BDA3 definition. @andrewgelman accepted definition in BDA3, when BDA3 was written.

**Comment by avehtari** [comment]
I added a branch https://github.com/stan-dev/stan/tree/bugfix/issue-683-effective_sample_size
Now it's bit confusing that this issue is is in stan-dev/math, but the chains.hpp is in stan-dev/stan,
and I didn't notice this before pushing the branch. I guess I should make a new issue in stan-dev/stan?

**Comment by bob-carpenter** [comment]
What you have on the branch linked isn't a documentation fix, so this issue should be updated to reflect what's really going on.

If this requires fixes to math and to stan itself, it'll need two issues.  If it's only doc on stan, then you can just add that to the ongoing doc issue.

**Comment by avehtari** [comment]
Both the code and doc need fixing. I'll add another issue for the code in stan-dev/stan.
I assigned myself to fix the doc, too.

**Comment by bob-carpenter** [comment]
Functionality changes and doc should go together in one issue and one pull request.

**Comment by avehtari** [comment]
Ok. I close this issue as the correct issue should be in stan-dev/stan (not in math).
