### ISSUE TITLE
Scaled inverse chi squared random number generated isn't right

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#684]
#### Summary:
I don't think the scaled inverse chi square random number generator is right.

#### Description:
Offending line here:
https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/prob/scaled_inv_chi_square_rng.hpp#L39

Instead of
```
nu * s / chi_square_rng();
```

It should be
```
nu * s * s / chi_square_rng();
```

This is going by the formula in the summary at the top of: https://en.wikipedia.org/wiki/Scaled_inverse_chi-squared_distribution

The scalar tests don't catch it cause they test s == 1.

#### Current Version:
v2.17.0

**Comment by mcol** [comment]
This was fixed in #722.
