### ISSUE TITLE
Beta Binomial CDF + CCDF give wrong value at boundary

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#688]
#### Summary:
The BetaBinomial CDF and CCDF give wrong values at the 0 boundary.

#### Description:
The CDF is defined as Prob(r <= n) such that for n=0 we should get the pmf value for n=0. Right now, the CDF defined in stan::math returns 0 which is not the correct value.

The CCDF has a similar problem. This is defined as Pr(r > n). Therefore, for n=0 we should get 1-Pr(r=0), but we do get 1 at the moment.

#### Reproducible Steps:
Just evaluate the CDF for n=0 which gives wrongly 0 and the CCDF for n=0 gives wrongly 1.

#### Current Output:
As described.

#### Expected Output:
As described.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
This should be tackled together with #912.
