### ISSUE TITLE
.github/ISSUE_TEMPLATE.md out of date: still says 2.17.0

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#690]
#### Summary:
It's useful to know when issues were created.

#### Description:
We have the current version stored in the .github/ISSUE_TEMPLATE.md file. 

It's usually updated when we release a new version. It helps us keep track of when the issues were created. If we don't want to track it, we should just remove it from the template altogether.

#### Current Version:
v2.17.1

(the template says v2.17.0)

**Comment by syclik** [comment]
Wait... I bet this is because we're branched from v2.17.0? @seantalts, can you confirm?

**Comment by seantalts** [comment]
It’s because 2.17.1 is on a leaf node that won’t be merged in.

**Comment by syclik** [comment]
Thanks! Closing the issue.
