### ISSUE TITLE
system_functor missing f_ initiliazation

### ISSUE THREAD

**Issue by yizhang-cae** [stan-dev/math#696]
#### Summary:
system_functor in algebra_system.hpp missing f in init line

#### Reproducible Steps:
This bug causes failure of torsten library's generalOdeModel_test unit test.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
How do you run the torsten unit test?

**Comment by yizhang-cae** [comment]
I'll check in a minimal test to reproduce the failure

**Comment by bob-carpenter** [comment]
Welcome to the project and thanks for reporting.  Feel free to just submit a pull request with a unit test and fix.
