### ISSUE TITLE
Remove all caps typenames for Solaris compilation

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#698]
#### Summary:

Solaris fails to compile Stan with all-caps type names.

#### Description:

From @bgoodri on http://discourse.mc-stan.org/t/stan-broken-on-solaris-need-fix-today/2826:

Stan models don't compile on Solaris 

It has something to do with using all capital letters for a typename. For more detail, see

https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/bayesplot-00check.html
Describe the issue as clearly as possible.

#### Current Output:

```
> 
> stan/math/rev/mat/functor/algebra_system.hpp:97:24: error: expected nested-name-specifier before numeric constant
>      template <typename FS, typename F, typename T0, typename T1>
>                         ^
> /home/ripley/R/Lib32/StanHeaders/include/stan/math/rev/mat/functor/algebra_system.hpp:97:24: error: expected ‘>’ before numeric constant
> /home/ripley/R/Lib32/StanHeaders/include/stan/math/rev/mat/functor/algebra_system.hpp:100:7: error: expected unqualified-id before numeric constant
>        FS fs_;
>        ^
```

#### Expected Output:

Compiler not complaining.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
Any suggestions on how to prevent this from happening in the future? We could add a script to search for this pattern if that helps.

**Comment by bob-carpenter** [comment]
That's the only way I could see it mattering.  The only complication I see would be distinguishing the int cases from variable declarations.
