### ISSUE TITLE
warnings in math dependencies

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#727]
#### Summary:
The current develop branch has warnings when running:
```
make test-math-dependencies
```

#### Description:
We shouldn't have any warnings. (A lot of these go away if we ever merge `scal`, `arr`, `mat`, but while we still have that distinction, we should maintain the separation.)

It looks like Jenkins doesn't check for this on pull requests. @seantalts, mind looking into that?

#### Reproducible Steps:
```
> make test-math-dependencies
```

#### Current Output:
```
> make test-math-dependencies
stan/math/prim/scal/prob/exp_mod_normal_rng.hpp(21): File uses std::vector. [scal]
stan/math/prim/scal/prob/skew_normal_rng.hpp(19): File uses std::vector. [scal]
stan/math/prim/scal/prob/cauchy_rng.hpp(19): File uses std::vector. [scal]
stan/math/prim/scal/prob/student_t_rng.hpp(19): File uses std::vector. [scal]
stan/math/prim/scal/prob/double_exponential_rng.hpp(20): File uses std::vector. [scal]
stan/math/prim/scal/prob/gumbel_rng.hpp(19): File uses std::vector. [scal]
stan/math/prim/scal/prob/logistic_rng.hpp(19): File uses std::vector. [scal]
stan/math/prim/scal/prob/normal_rng.hpp(19): File uses std::vector. [scal]
stan/math/prim/scal/prob/exp_mod_normal_rng.hpp(22): File uses Eigen. [scal]
stan/math/prim/scal/prob/skew_normal_rng.hpp(20): File uses Eigen. [scal]
stan/math/prim/scal/prob/cauchy_rng.hpp(19): File uses Eigen. [scal]
stan/math/prim/scal/prob/cauchy_rng.hpp(20): File uses Eigen. [scal]
stan/math/prim/scal/prob/student_t_rng.hpp(20): File uses Eigen. [scal]
stan/math/prim/scal/prob/double_exponential_rng.hpp(20): File uses Eigen. [scal]
stan/math/prim/scal/prob/double_exponential_rng.hpp(21): File uses Eigen. [scal]
stan/math/prim/scal/prob/gumbel_rng.hpp(19): File uses Eigen. [scal]
stan/math/prim/scal/prob/gumbel_rng.hpp(20): File uses Eigen. [scal]
stan/math/prim/scal/prob/logistic_rng.hpp(19): File uses Eigen. [scal]
stan/math/prim/scal/prob/logistic_rng.hpp(20): File uses Eigen. [scal]
stan/math/prim/scal/prob/normal_rng.hpp(19): File uses Eigen. [scal]
stan/math/prim/scal/prob/normal_rng.hpp(20): File uses Eigen. [scal]
```

#### Expected Output:
No warnings.

#### Additional Information:
Looks like it got in with a pull request for vectorized rngs?

#### Current Version:
v2.17.0

**Comment by mcol** [comment]
Commit 8e83e4f2c98859faa85c8d58ee412d8493c6eb35 introduced them: they appear in the documentation rather than in the code, but the regular expression used to spot them doesn't know about this.

**Comment by syclik** [comment]
Thanks! That really helps. I'll try to fix it.

**Comment by seantalts** [comment]
Were you asking me to look into making Jenkins fail if test-dependencies shows warnings? I was just going to squash the directories and remove the test, haha.

**Comment by syclik** [comment]
Not sure what you're asking. We should have caught this before it got merged. This one's in the doc, so we should be able to fix it easily.

Regarding squashing directories, that's good, but it's not something that we should do lightly. This is something we should have a discussion about on discourse and give it some serious thought. It's not something that can be undone easily. It'll affect any users that use the math library directly. And... it'll have a large impact on our meta library. I think all for the better, but this is a big decision. Want to kick off the discussion on discourse? Of course, we'll also need a plan for this. It'll really touch a lot of things at once in the math library.

And we shouldn't be removing all of these tests, just the ones that check for misuse of `std::vector` and `Eigen`.

**Comment by seantalts** [comment]
The jobs were set up to let the math dependencies warnings slide by without setting the build to failed. You can see that in the old Math jobs [here.](http://d1m1s1b1.stat.columbia.edu:8080/job/Math%20-%20Warnings%20-%20Dependencies/322/). I copied that behavior into the new pipeline jobs.

Reason for squashing and ignoring the tests until then being that we at one point decided that we didn't have a reason to keep them separate anymore and it seemed like you and Bob were fine with the sort of change in moral imperative such that we no longer want to support people who want to use the math library without Eigen, and even without the autodiff stuff (there was some of this conversation [here](http://discourse.mc-stan.org/t/why-is-our-math-library-header-only/2451/17)). I added a new thread [here](http://discourse.mc-stan.org/t/users-of-stan-math-not-via-stan-language-scal-arr-mat-distinction-useful/3080) to explicitly announce our intentions and see if anyone was using the functionality.

Are you saying there are other math-dependencies checks we want to fail builds? I haven't looked too closely at them.

**Comment by syclik** [comment]
Re: old math jobs. I see the current behavior, but it used to fail when there were any warnings. I didn't see any radical changes to the config, so maybe it's an updated Jenkins / plugin? Either way, we want to stop pull requests when it fails that test (even now).

Let's continue the discussion on discourse.
