### ISSUE TITLE
testing for mdivide derivatives

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#763]
#### Summary:

There are no tests for derivatives for mdivide_right (which is defined in terms of mdivide_left).  There should be tests of both instantiations (vector and matrix), and for the triangular and square versions.  If mdivide_left isn't tested, add symmetric tests for that.

The tests could use the reduction to `mdivide_left` to test derivatives if the tests exist for `mdivide_left`.  

#### Description:

It'd be best to get the higher order testing framework in place for derivatives.  Then this would be easy.

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
The tests in https://github.com/stan-dev/math/blob/develop/test/unit/math/mix/mat/fun/mdivide_right_test.cpp are now equivalent to those in https://github.com/stan-dev/math/blob/develop/test/unit/math/mix/mat/fun/mdivide_left_test.cpp so I am closing this.

**Comment by bob-carpenter** [comment]
Thanks!  You must be really good at the game Concentration.
