### ISSUE TITLE
Bump Boost to 1.66.0

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/math#765]
#### Summary:

BH is based on Boost 1.66.0 so we should match sometime before the next release

#### Description:

BH is based on Boost 1.66.0 so we should match sometime before the next release. Also, if we want to use the Boost Compute library from 1.66.0, we can.

#### Reproducible Steps:

There is no issue.

#### Current Output:

There is no output.

#### Expected Output:

I do not expect any output.

#### Additional Information:

There is no additional information.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
I'll take caref of this.  It's testing on my machine now, so if it works, I should be able to push this afternoon.
