### ISSUE TITLE
Matrix exponential action

### ISSUE THREAD

**Issue by yizhang-cae** [stan-dev/math#771]
#### Summary:
Speed up calculation of `exp(A)*b` where `A` is a matrix and `b` is a vector.

#### Description:
Seeking comments and suggestions. 

I've implemented a prototype of [Al-Mohy's paper.](http://epubs.siam.org/doi/abs/10.1137/100788860) The method is designed to speed up matrix exponential action on a vector, which is ubiquitous in linear ODE and PDE solutions. Initial wall time comparison shows significant speed improvement in calculating `exp(A)*b` using the new "action" method vs. the old "explicit" method (`stan::math::matrix_exp(A) * b`). See below for results from random matrix `A` and vector `b` with size 10-500.
![mat_exp_compare](https://user-images.githubusercontent.com/33104304/36445097-369685a8-164b-11e8-96e2-4a06405b1506.png)

The prototype can be found in 
https://github.com/yizhang-cae/math/tree/feature/matrix_exp_action

#### Reproducible Steps:
Unit test
`test/unit/math/prim/mat/fun/matrix_exp_action_test.cpp`

#### Current Version:
v2.17.2

**Comment by bob-carpenter** [comment]
Hard to argue with the results.  I'd want to see what things look like for smaller matrices to see if there's some transition point or if the new thing's always better.

Did you compute analytic gradients?  And is the plan to add a new Stan function to match this somewhere?  That'll be easy if the function exists.

**Comment by yizhang-cae** [comment]
For smaller matrices the speed gain is less obvious. Here's random matrices wall time for N=1-15.
<img width="445" alt="screen shot 2018-02-20 at 5 18 23 pm" src="https://user-images.githubusercontent.com/33104304/36452343-182db354-1662-11e8-8437-0610692f028b.png">

I didn't compute analytic gradients. For function interface I'm thinking about overloading `matrix_exp`, like [Mathematica](http://reference.wolfram.com/language/ref/MatrixExp.html), but not sure how that'd work with Stan.

**Comment by bob-carpenter** [comment]
Yes, we can overload functions.  They just have to have distinct argument signatures, like in C++.

I'm not sure which is which here, but the "action" column seems much more consistent, so that's the one I'd choose from just this data at these sizes.

Analytic gradients, when possible, can come with big speed boosts and even bigger memory savings.

**Comment by betanalpha** [comment]
At the very least the derivative of the exponential times a vector
will be of the form 

d(matrix_exp * vector) = d(matrix_exp) * vector + martix_exp * d(vector)

so you can compute a crude analytic gradient by using the current
code to compute the analytic gradient of the matrix_exponential and
the input vector and then compute the product rule explicitly.  That
should save on significant memory, and then one could work on 
figuring out a more optimal calculation for d(matrix_exp) * vector.

**Comment by charlesm93** [comment]
In my experience, we often deal in pharmacometrics with systems of less than 10 ODEs, so the low dimension regime remains of interest. That said, I expect semi-analytical gradients will give the action of the matrix exp a major advantage, since as @bob-carpenter  said during the Stan meeting we would only compute the derivatives for a vector.

**Comment by bob-carpenter** [comment]
There are two benefits:

* less memory:  you only need to store the partials from the vector of outputs to the matrix and vector of inputs (still large)
* faster: operations to calculate the gradients can move from operating on autodiff types in an interpreted fashion (virtual function calls) we'd have static calls on `double` types.
