### ISSUE TITLE
integrate_ode_rk45 takes y0 by value

### ISSUE THREAD

**Issue by ChrisChiasson** [stan-dev/math#773]
#### Summary:
integrate_ode_rk45 takes parameter y0 by value

#### Description:
integrate_ode_rk45 takes y0 by value, when it should be taken by reference like integrate_ode_bdf.

#### Reproducible Steps:
Nothing to reproduce, it just produces extra copies of the entries in y0

#### Current Output:
No change

#### Expected Output:
No change

#### Additional Information:
Note, I won't be fixing the issue myself because I am having trouble making the python test script work with my MinGW GCC. I found this issue while trying to solve another one (a compile error when switching from integrate_ode_rk45 to integrate_ode_bdf with the exact same parameter list)... which I still haven't solved.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
Thanks.  This one should be easy to fix just using the GitHub interface.  Our CI tests should then run if you turn it into a PR.

But if that's too much hassle, it'll be easy for someone else to fix.

**Comment by ChrisChiasson** [comment]
I actually didn't know it was possible to fix it via the web. I will look around and try to figure out how to do that.

**Comment by bob-carpenter** [comment]
Maybe what I'm suggesting only works with doc files.  For some reason, I can't edit this one without being on a branch:

https://github.com/stan-dev/math/blob/5f6e8ddd100f00ddf5163c7082ecda077b1e8770/stan/math/prim/arr/functor/integrate_ode_rk45.hpp

I seem to recall at one point just being able to edit a file and then having it let me make a pull request directly.  I'm terrible at remembering how to do this kind of thing.

**Comment by syclik** [comment]
You can edit on a pull request, but that requires there to already be a
branch.
