### ISSUE TITLE
remove boost 1.65.1 & binary things in boost 1.66.0

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#777]
#### Summary:
get rid of outdated boost

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

#### Current Output:
The current output. Knowing what is the current behavior is useful.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by wds15** [comment]
and maybe we should remove from boost 1.66.0 a few binary left overs which were not supposed to land in there. Like:

- math/lib/boost_1.66.0/tools/build/src/engine/bin.macosxx86_64/
- math/lib/boost_1.66.0/tools/build/src/engine/bootstrap/jam0 (this is a binary)

**Comment by bob-carpenter** [comment]
Sorry about that.  I thought I git rm-ed it as part of the 1.66 PR.

**Comment by wds15** [comment]
Ups... you did remove the old boost! But there were binary files check into math which are the ones I quote above.

**Comment by wds15** [comment]
Merged with #782
