### ISSUE TITLE
[Feature Request] Make doxygen into github page

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/math#781]
Do we have the doxygen docs hosted somewhere online that I am unable to find? using them on my local was very nice.

I have some free time this weekend and could try out hosting the docs and adding something to Jenkins to auto-update them. I'm guessing that we would probably want to make/host them in another repository so stan-math does not get crowded with a bunch of html.

**Comment by syclik** [comment]
Once upon a time, we did that. (this was when it was just a single repo for Stan and Math)

We can actually do this pretty easily if we put the generated doxygen in a branch called gh-pages. I don't think there needs to be any additional structure there. Then it'll show up as http://mc-stan.org/math. Hopefully we don't have anything there already.

**Comment by SteveBronder** [comment]
Alright cool beans. If you are cool with this then I'll play around with it this weekend. I've used something like the below in a python package makefile. We could put something like this in math's makefile and have Jenkins run it when the master branch runs

```make
.PHONY: deployDocs
deployDocs: 
	-git -C $(BUILDDIR) checkout --detach
	-git -C $(BUILDDIR) branch -D gh-pages
	git -C $(BUILDDIR) checkout --orphan gh-pages
	-touch $(BUILDDIR)/.nojekyll
	git -C $(BUILDDIR) add .
	git -C $(BUILDDIR) commit -m "auto-generated from sphinx"
	git -C $(BUILDDIR) push origin +gh-pages:gh-pages
	@echo "Deployed!"
```

**Comment by syclik** [comment]
Thanks, @SteveBronder! This was fixed.
