### ISSUE TITLE
prim/mat/meta/is_vector_like.hpp weirdness through check_finite.hpp

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#79]
_From @rtrangucci on February 25, 2015 20:25_

matrix specialization for is_vector_like doesn't work as it should. In order for is_vector_like to work correctly, mat/meta/is_vector.hpp must be included, which shouldn't be the case.

_Copied from original issue: stan-dev/stan#1312_

**Comment by syclik** [comment]
_From @bob-carpenter on February 28, 2015 9:0_

Do you need help with this, and if so, could you create a branch with a test that fails that you think should pass?

**Comment by syclik** [comment]
_From @bob-carpenter on February 28, 2015 9:0_

Also, whenever creating an issue, please give it a milestone and labels, and ideally an assignee.

**Comment by bob-carpenter** [comment]
@rtrangucci  Any idea if this is still an issue?  If so, mind figuring it out?

**Comment by rtrangucci** [comment]
@bob-carpenter This is still an issue, and not surprisingly I ran into this while I was writing `cov_exp_quad`. Totally inscrutable behavior for `is_vector_like`. I'll look into it this week.

**Comment by bob-carpenter** [comment]
I'm assigning to @seantalts because he's been going through and cleaning up this metafunction behavior.  Maybe he's already knocked this one off, but I'll leave it for him to close.

**Comment by syclik** [comment]
Closing. This issue isn't clear enough to have a reproducible example. It may have been fixed by now.
