### ISSUE TITLE
Streaming output for container slices

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#792]
#### Summary:

Currently, cannot compile a Stan program with

```
print(a[1:2]);
```

because sliced containers have no output stream function overload.

#### Description:

Add the overload so these print.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
This is related to the issue with turning slices into lvalues:  https://github.com/stan-dev/stan/issues/2482

**Comment by rok-cesnovar** [comment]
Not an issue on develop anymore.
