### ISSUE TITLE
'check_ordered' does not work with row vectors or std::vectors

### ISSUE THREAD

**Issue by andrjohns** [stan-dev/math#798]
#### Summary:
The error checking function ```check_ordered``` is currently only able to be used for checking vectors.

#### Description:
```check_ordered``` only has a template for vectors (i.e. ```Matrix<double, Dynamic, 1>```) and so is not functional with row vectors or std::vectors.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
Is there a use case for this function?

**Comment by syclik** [comment]
And thanks for submitting the issue -- just not sure what would motivate adding the additional functions. (I'm sure it's easy enough to do, but probably would require a little more testing.)

**Comment by andrjohns** [comment]
The only use case for me is allowing the ordered logistic distribution to take the ordered cutpoints as any of the vector types.

I'll submit a PR for this relatively soon, so you can assign this to me if you like.
________________________________

**Comment by syclik** [comment]
> The only use case for me is allowing the ordered logistic distribution to take the ordered cutpoints as any of the vector types.

Is there a reason you'd want to do that? Right now, the Stan function signature is:
```
real ordered_logistic_lpmf(int k | real eta, vector c)
```

And you'd want one more or two more function signatures?
```
real ordered_logistic_lpmf(int k | real eta, row_vector c)
real ordered_logistic_lpmf(int k | real eta, real c[])
```

Is there a discussion on Discourse or an issue in the Stan library that is linked to this? I'm still trying to understand what's motivating the request.

Once again, it can be done. It's just a lot more maintenance.

**Comment by andrjohns** [comment]
> And you'd want one more or two more function signatures?

Not specifically for that purpose, just a nice side-effect. I'm more looking to generalise the function so that it can be applied to more use-cases in the future. 

At the moment the template is unnecessarily restrictive by specifying that the input is a vector. Eigen's map functionality could be used to access other input types like they were vectors with minimal changes to the existing code:
```
template <typename T_y>
void check_ordered(const char* function, const char* name,
                   const T_y& y_n) {

  //Get type within container
  typedef typename T_y::value_type mem_y;

  //Get location of container in memory
  const mem_y *p = &y_n[0]; 

  //Map contents of container to vector
  Eigen::Map<const Eigen::Matrix<mem_y, Eigen::Dynamic, 1> > y(p, y_n.size());
```

With the rest of the code unchanged.

As for the maintenance, what would be involved? Updating tests?
