### ISSUE TITLE
Link to license in README.md is dangling

### ISSUE THREAD

**Issue by dmbates** [stan-dev/math#802]
#### Summary:
The `README.md` file contains a link to the `new BSD license` as

https://raw.githubusercontent.com/stan-dev/math/develop/licenses/stan-math-library-license.txt

but that file does not exist.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
Thanks, @dmbates, the fix is merged into the development branch and staged for the next release.
