### ISSUE TITLE
Undefined behavior in std_isinf.hpp and std_isnan.hpp

### ISSUE THREAD

**Issue by danluu** [stan-dev/math#812]
#### Summary:

I believe it's undefined behavior to add to `std`, with the exception of adding template specializations for STL templates in some circumstances. `std_isinf` and `std_isnan` add functions to the `std` namespace.

#### Description:

C++ standard:
> The behavior of a C++ program is undefined if it adds declarations or definitions to namespace std or to a namespace within namespace std unless otherwise specified. A program may add a template specialization for any standard library template to namespace std only if the declaration depends on a user-defined type and the specialization meets the standard library requirements for the original template and is not explicitly prohibited.
>
> The behavior of a C++ program is undefined if it declares
>
> (2.1) an explicit specialization of any member function of a standard library class template, or
>
> (2.2) an explicit specialization of any member function template of a standard library class or class template, or
> 
> (2.3) an explicit or partial specialization of any member class template of a standard library class or class template.
> 
> A program may explicitly instantiate a template defined in the standard library only if the declaration depends on the name of a user-defined type and the instantiation meets the standard library requirements for the original template.

#### Current Version:
v2.17.0

**Comment by bob-carpenter** [comment]
Right.  `std::isinf` is not a template function, even in C++11:  http://www.cplusplus.com/reference/cmath/isinf/

I'm not sure what this is here to fix.  Nothing should ever be trying to apply `std::isinf` in these situations.  So if we have calls to `std::isinf`, then those should be replaced with our own `stan::math::is_infinfite` function.

**Comment by danluu** [comment]
> Nothing external should ever be trying to apply std::isinf to anything other than a primitive.

Does that mean that these can be deleted without deprecating them first?

**Comment by bob-carpenter** [comment]
I just meant that I doubt they were put in place to deal with some external system calling isinf(T) on some unknown T.  It was probably just a fudge in some of our own code that would be easily replaced.

I think it's OK to replace code that previously had undefined behavior without deprecating.

We haven't been that tight in backwards compatibility with the math lib anyway other than for the main things that people use in stan::math.

**Comment by betanalpha** [comment]
Perhaps is was in to enable autodiffing through some 
of the Eigen algorithms?

**Comment by syclik** [comment]
I'm closing this issue. Yes, it's undefined behavior to add to the std namespace and we're aware of it. Unfortunately, some of the libraries we use assume the templated types are primitives and call functions in std namespace explicitly. The easiest workaround is to provide our own definitions.

As long as we have unit tests for these function definitions and we're testing on enough of the platforms, I think we're pretty good thinking that it'll behave properly. If these tests start failing, we'll know that under that particular configuration it doesn't work and we'll have to deal with it appropriately. Hopefully that's never.
