### ISSUE TITLE
Add performance regression test to pull request CI suite

### ISSUE THREAD

**Issue by seantalts** [stan-dev/math#837]
#### Summary:
We've had a couple of merged PRs that caused performance regressions that were caught by daily CI tests, but it'd be nice to run a quick performance regression smoke test on every PR push. This should be fairly easy using the compare-git-hashes.sh (or something like it) script from https://github.com/stan-dev/performance-tests-cmdstan.

#### Current Version:
v2.17.0

**Comment by rok-cesnovar** [comment]
We have performance test for PRs now. Closing.
