### ISSUE TITLE
regular array and vector constructor functions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#838]
#### Summary:

Create functions to create regular arrays. 

Here's one from MATLAB (also related to Python `range`):

```
/**
 * Return vector of evenly spaced elements with given minimum and maximum.  Behavior for size = 0 and size = 1 to be determined.  Requires min <= max.
 */
vector linspace_vector(real min, real max, int size);
```
There could also be `linspace_array` and `linspace_row_vector` versions. It might be possible to call the vector or array version just `linspace`.  

Python provides `range`, which is a bit different.

```
/**
 * Return sequence of numbers min, min + by, min + 2*by, ...
 * up to but not including max.  Requires min <= max and by > 0.
 */
vector range_vector(real min, real max, real by);
```

In R, there's a function `seq` that allows either of these parameterizations, but we don't want to follow that redundant pattern.

This one's a suggestion from peterzh on http://discourse.mc-stan.org/t/create-vector-from-a-number-range/3760.

This will then get pushed through to Stan.

#### Current Version:
v2.17.0

**Comment by linwangidd** [comment]
function for creating regular arrays is still not available?

**Comment by bob-carpenter** [comment]
Correct.  It's easy to  write one yourself and Stan gets compiled to efficient code, so we haven't prioritized this.  If someone builds it, we'll accept a PR for this.

**Comment by mcol** [comment]
In #1636 we have added `spaced_vector` and friends, but I now think that `linspace_vector` could be a better name, as it matches what matlab, numpy and Eigen use. This will allow us to add a `logspace_vector` if we ever wanted. @bob-carpenter do you have an opinion?

**Comment by bob-carpenter** [comment]
I like the idea of matching MATLAB, numpy, and Eigen and am happy to review the changes.   I'm also OK just leaving it spaced_vector with "linear" as a default.  Is it really linspace_vector and not linspaced_vector?  I like the adjectival form better!


 But if the current ones escaped to a language release, they're going to need to be deprecated.

**Comment by mcol** [comment]
These are not exposed yet, so we are free to pick what we want. I also think `'linspaced_vector` would work well,  so we could go with that.

**Comment by mcol** [comment]
The `range` function as described here (with size of the resulting vector deduced rather than predeclared) would limit the uses of this function to only some contexts (see https://github.com/stan-dev/math/pull/1666#issuecomment-581156139,  and https://github.com/stan-dev/math/pull/1666#issuecomment-581553249).
