### ISSUE TITLE
map_rect MPI

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#848]
#### Summary:
Introduce MPI enabled map_rect backend

#### Description:
enable within-chain parallelization in stan using MPI in map_rect.

The map_rect facility allows to specify N independent function evaluations at once and this issue is meant to establish a parallel execution mechanism through the use of MPI.

#### Reproducible Steps:
NA

#### Current Output:
all good, bbut too slow for some applications like ODE based hierarchical models

#### Expected Output:
faster output with more CPUs

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by wds15** [comment]
@bob-carpenter Progress! The main branch is up in `feature/issue-848-map_rect-MPI`. While the `mpi_parallel_call` class can be crammed into our `internal` namespace and thus only be implicitly tested through `map_rect_mpi` tests, I think it is worth to place this class in `stan::math` which means I need to write up some tests for it.

If you think the above mentioned class should be `internal` I can do that and file the PR now. However, I think with using mock classes should allow to write those tests efficiently and we would gain this facility for general use. I will do this unless you disagree.

**Comment by bob-carpenter** [comment]
Sounds good to me.  I'm not going to be able to get to reviewing all this for a week or so anyway.

**Comment by wds15** [comment]
Ok, then I will add those tests using mockups.

One more thing: The threading stuff is now in a useful state with the latest fixes going into stan-math. My plan is to have the map_rect MPI code use threading locally whenever STAN_THREADS is defined. Are u good with reviewing this all at once? The design I have in mind would turn to serial execution if STAN_THREADS is not defined, but otherwise I would use threading. The design would follow what I have done for map_rect_concurrent, see here:
https://github.com/stan-dev/math/blob/f5be4eba4114895c9880f793931e77acb90070fc/stan/math/prim/mat/functor/map_rect_concurrent.hpp#L74

If you prefer to first go over a MPI only map_rect, we do that. Performance wise it will be very interesting to combine threading (on-machine parallelism) with MPI (between machine parallelism).

**Comment by yizhang-cae** [comment]
Can you provide more background in issue summary. I don't follow the setup of "within chain parallel" + MPI

**Comment by bob-carpenter** [comment]
I think it'll be easier to review MPI and multi-threaded separately if possible.

**Comment by wds15** [comment]
@yizhang-cae I hope the edit makes it clear.

@bob-carpenter Ok, let's go in steps.
