### ISSUE TITLE
Add Matern Kernels to Gaussian Process Library

### ISSUE THREAD

**Issue by drezap** [stan-dev/math#864]
#### Summary:
Add special cases Matern class of covariance functions to the gaussian process library.
These include:
Exponential (Matern 1/2) (`gp_exp_cov()`)
Matern 3/2 (`gp_matern32_cov()`)
Matern 5/2 (`gp_matern52_cov()`)
Exponential Quadratic (Matern lim v -> inf) (`gp_exp_quad_cov()`)

#### Description:
Each matern covariance function will have 4 parameterizations:

`gp_function_cov(x, sigma, length_scale)`
`gp_function_cov(x, sigma, length_scale, jitter)`
`gp_function_cov(x1, x2, sigma, length_scale)`
`gp_function_cov(x1, x2, sigma, length_scale, jitter)`

Where we x is the data vector, x1 and x2 are two different data vectors of type `real` (or possible ints), `sigma` is the marginal standard deviation, `length_scale` is the length scale, and `jitter` is a small real number that is added onto the diagonal for numerical stability during cholesky decomposition.

#### Inputs to support
The input datatypes that should be tested for `x`, `x1` and `x2`  are:
`std::vector<double>`, `std::vector<Eigen::Matrix<double, 1, -1>` (row vec w/ `doubles`), `std::vector<Eigen::Matrix<double, -1, 1>` (col vec w/ `double`), and varying x lengths.

The input datatypes that should be tested for `l` are:
`double`, `std::vector<double>` (the latter for ARD (automatic relevance determination)).

For `rev` versions, we also need to test all combinations of `var` and `double`, (and their related gradients).

I'm leaving in both Eigen's vectors and row vectors, because the same code generally supports both, so we (meaning mostly I) might as well throw some extra test cases in there.

For `sigma` we only need `double`.

#### Expected Output:

A data matrix that is a covariance function. If the input is only `x`, the output is symmetric real matrix that is positive semi-definite. Otherwise, output a matrix of reals.

#### Additional Information:
We want to support easy summation of kernels:

`gp_exp_quad(x, sigma, length_scale) + gp_exp_quad(x, sigma, length_scale, jitter)`

We like to use Rasmussen and WIlliams as a reference, however, in Chapter 4 they do not include the parameterization that has the marginal standard deviation, although this parameter is used later in the book in many places. We include this in our parameterization for these special cases of Matern kernels. 

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
Can you specify what C++ types the different arguments can take?

**Comment by drezap** [comment]
@syclik updated
