### ISSUE TITLE
add 'add_diag' function

### ISSUE THREAD

**Issue by drezap** [stan-dev/math#866]
#### Summary:
This will take any matrix and add a `double` along the diagonal. This can be used when adding `jitter` along the diag in a covariance matrix, for numerical stability (i.e. taking the inverse or cholesky decomposition), as it will force the matrix to be non-degenerate. 

Requirements: 
  1) number of rows or number of columns > 1.

#### Description:
`add_diag(Eigen::Matrix mat, double diag);`
If the matrix is not square, we have two different cases: 
  1) #cols > #rows: in this case, the daig will be equal to the # rows.
  2) #rows > #cols: in this case, the diag will be equal to the # columns.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
How about calling it `add_diag_jitter` to be more specific? I can imagine a function like `add_diag` to also accept a `vector`. Are you imagining the `jitter` term accepting `var`?

I think the function, whatever it's called, has merit. Having simpler functions to compose is definitely easier to handle.

**Comment by drezap** [comment]
if I use `add_jitter`, it implies the function is more applicable to a covariance matrix (i.e., jitter term I've only come across in the GP literature). I initially thought this might have applications elsewhere, which is why I left the name more generic. If this is OK, I'd like to make the name just `add_jitter` or something. 

I can extend to accept a vector too. Should I require the vector to be the length of min(#rows, #cols), or should I use a "recycling" rule, similar to R?

**Comment by syclik** [comment]
If it's `add_jitter`, I don't think it makes sense to accept a vector. Just
as a rule of thumb, for the math library there is no automatic recycling.

**Comment by betanalpha** [comment]
Adding a diagonal matrix to a dense matrix is a common operation
in linear algebra and hence worth having a dedication function.
If the function is templated to take a scalar (which then gets broadcast
to each diagonal) or a vector/row_vector then

+ sigma * I

and

+ v

functionalities are both implemented and the “add_diag” name is
entirely reasonable.

**Comment by syclik** [comment]
@betanalpha makes a good point.

@drezap, I'll let you decide what you want to implement. `add_jitter` is going to be a lot simpler. `add_diag` will be a lot more work, but more useful.

What I mean by this:
- `add_jitter` looks like:
  * `Eigen::Matrix<double, -1, -1> add_jitter(Eigen::Matrix<double, -1, -1> &mat, double jitter)`
  * `Eigen::Matrix<var, -1, -1> add_jitter(Eigen::Matrix<var, -1, -1> &mat, double jitter)`

- `add_diag` looks like (this can be done in a templated way, but these are the possible instantiations):
  * `Eigen::Matrix<double, -1, -1> add_diag(Eigen::Matrix<double, -1, -1> &mat, double jitter)`
  * `Eigen::Matrix<double, -1, -1> add_diag(Eigen::Matrix<double, -1, -1> &mat, std::vector<double> jitter)` (maybe this one isn't necessary)
  * `Eigen::Matrix<double, -1, -1> add_diag(Eigen::Matrix<double, -1, -1> &mat, Eigen::Matrix<double, -1, 1> jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<var, -1, -1> &mat, double jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<var, -1, -1> &mat, std::vector<double> jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<var, -1, -1> &mat, Eigen::Matrix<double, -1, 1> jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<double, -1, -1> &mat, var jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<double, -1, -1> &mat, std::vector<var> jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<double, -1, -1> &mat, Eigen::Matrix<var, -1, 1> jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<var, -1, -1> &mat, var jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<var, -1, -1> &mat, std::vector<var> jitter)`
  * `Eigen::Matrix<var, -1, -1> add_diag(Eigen::Matrix<var, -1, -1> &mat, Eigen::Matrix<var, -1, 1> jitter)`

**Comment by betanalpha** [comment]
No std::vector signatures are necessary — just the linear algebra vectors
as consistent with the matrix addition signatures.

**Comment by syclik** [comment]
Cool. That cuts it down by 3, so still 9 different instantiations.

**Comment by bob-carpenter** [comment]
I second Michael's proposal.  To be precise, we'd have two functions exposed in Stan itself:

1.  `matrix add_diag(matrix, real);`

2.  `matrix add_diag(matrix, vector);`

You can just implement the first one to start.

**Comment by syclik** [comment]
I just found a related issue: #411.

**Comment by drezap** [comment]
Yeah, I came across the memory issue in the implementation, and ended up copying what Bob call's `V` in that post. I had considered doing removing the `const` so we're passing by reference and avoiding the extra memory consumption, but I didn't think you guys allowed this, as confirmed by bob in this post. 

I avoided parsing the matrix and copied a diagonal instead, and then added to the diagonal as a vector, hoping it would be more efficient. I actually think I actually may have made it less efficient by doing so, because if eigen's library is using element access than I'm doing it twice, and creating an extra object. As I think is C-style arrays, one uses modular arithmetic for element access, right (i.e. it's not an actual array, it's just values stored as a string)?  Similar to [this post](https://softwareengineering.stackexchange.com/questions/252407/why-is-the-complexity-of-fetching-a-value-from-an-array-be-o1)

Not quite so sure the most efficient approach

**Comment by drezap** [comment]
yeah, I can update the PR to have the functionality bob mentioned in that issue: 

```template <typename T1, typename T2>
Matrix<typename promote_args<T1, T2>::type, -1, -1>
add_diag(const Matrix<T1, -1, -1>& a,
const Matrix<T2, 1, -1> & v) {
check_square(...)
check_matching_sizes(...)
Matrix<typename promote_args<T1, T2>::type, -1, -1> a_plus_v(a);
for (int k = 0; k < v.rows(); ++k)
a_plus_v(k, k) += v(k);
return a_plus_v;
}
```

Kind of the same thing but without the unnecessary copying that I did in the PR. I also used non-square matrices.

**Comment by drezap** [comment]
this has been addressed, and merged. I can also close the other related issue

**Comment by ShaunMcDonald1021** [comment]
This function has been added? I can't find it in the Functions Reference - I didn't know it existed until I saw this thread.

**Comment by drezap** [comment]
@ShaunMcDonald1021 it's been merged in the math lib but not added to the language, thanks for the reminder.
