### ISSUE TITLE
Link to cpplint guidelines in the math wiki. 

### ISSUE THREAD

**Issue by drezap** [stan-dev/math#872]
#### Summary:
`make cpplint` throws an error when c libraries are at the top, (i.e. `#include <cmath>`), but says `Found C system header after C++ system header. Should be: gp_matern32_cov_test.h, c system, c++ system, other.`

It actually prefers that c headers come after the Stan math library headers (the `.hpp` ones). What is actually preferred? How can I fix this issue? It's shaving time off of my days having to do extra commits.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
If you haven't seen it, it's described in the Stan wiki:
https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms

There's a link in there to the actual cpplint guide that tells you all the rules enforced. 

I'm going to change the title of the issue to indicate that this should be linked from our wiki.

**Comment by drezap** [comment]
solved
