### ISSUE TITLE
differential equations library build should be in readme

### ISSUE THREAD

**Issue by ChrisChiasson** [stan-dev/math#878]
#### Summary:
I am not sure, but it seems like a recent change introduced a cvodes include into one of the basic stan-math headers. I now have old programs that didn't use the differential equations solver complaining that they can't find the library files at the linking step (until I build them)

#### Description:
It is difficult to find documentation on how to build the libraries, and examples tend to go out of date due to changes in the library versions and paths. By including cvodes in one of the high level headers, it seems to require the libraries to be built for even basic usage of stan-math. We don't want to create a bad initial user experience for the stan-math, so we should include the build directions in the readme.

#### Reproducible Steps:
````
chris_chiasson@instance-1:~/0g$ make
clang++-5.0 -stdlib=libstdc++ -std=gnu++1z -pedantic -pedantic-errors -Wall -Wextra -Werror -Wno-overlength-strings -Wfatal-errors  -ffunction-sections -fdata-sections -pthread -march=native -mtune=native -mno-avx -fmessage-length=0 -I./src -I../gsl/include -isystem../opt/boost_1_66_0/include -isystem../eigen-git-mirror -isystem../stan-dev/math -I../stan-dev/math/lib/sundials_3.1.0/include -O3 -flto -DNOMINMAX -DBOOST_UBLAS_NDEBUG -DNDEBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION  -c -MMD -o src/main.o src/main.cpp
clang++-5.0 -stdlib=libstdc++ -Wl,--icf=all -Wl,-s -Wl,--gc-sections -Wl,--strip-all -fuse-ld=lld -std=gnu++1z -pedantic -pedantic-errors -Wall -Wextra -Werror -Wno-overlength-strings -Wfatal-errors  -ffunction-sections -fdata-sections -pthread -march=native -mtune=native -mno-avx -fmessage-length=0 -I./src -I../gsl/include -isystem../opt/boost_1_66_0/include -isystem../eigen-git-mirror -isystem../stan-dev/math -I../stan-dev/math/lib/sundials_3.1.0/include -O3 -flto  src/main.o  -L../opt/boost_1_66_0/lib -lboost_filesystem -lboost_system -lboost_random -Wl,-rpath,../opt/boost_1_66_0/lib -Wl,-rpath,../stan-dev/math/lib/sundials_3.1.0/lib -L../stan-dev/math/lib/sundials_3.1.0/lib -lsundials_cvodes -lsundials_nvecserial -o src/main
````
#### Current Output:
````
/usr/lib/llvm-5.0/bin/ld.lld: error: unable to find library -lsundials_cvodes
/usr/lib/llvm-5.0/bin/ld.lld: error: unable to find library -lsundials_nvecserial
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
<builtin>: recipe for target 'src/main' failed
make: *** [src/main] Error 1
````

#### Expected Output:
Nothing. It should exit successfully.

#### Additional Information:
To fix, the readme should describe the command to build cvodes
````
~/stan-dev/math$ make lib/sundials_3.1.0/lib/libsundials_cvodes.a lib/sundials_3.1.0/lib/libsundials_nvecserial.a lib/sundials_3.1.0/lib/libsundials_idas.a 
make: 'lib/sundials_3.1.0/lib/libsundials_cvodes.a' is up to date.
make: 'lib/sundials_3.1.0/lib/libsundials_nvecserial.a' is up to date.
make: 'lib/sundials_3.1.0/lib/libsundials_idas.a' is up to date.
````

#### Current Version:
develop

**Comment by syclik** [comment]
Thanks! I'll check into it from a clean build. We shouldn't need the link
libraries to compile, build, and run when there's no ODE involved.

Thanks for being thorough. Please let us know if you have any additional
suggestions. The readme you're referring to is the top-level README.md?

**Comment by ChrisChiasson** [comment]
I have just realized something to my horror. The cvodes-3.1.0 directory in my install had the built libraries. When I pointed my makefiles to the new sundials_3.1.0 to reflect the latest directory location, it is likely that alone is the source of error messages.

**Comment by syclik** [comment]
Thank you! For both following up and for proactively closing issues!

If anything like that pops up, please post again.
