### ISSUE TITLE
Evaluating bernoulli at theta = 1.0 doesn't work

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#879]
#### Summary:
Because bernoulli usings log1m internally, it blows up when evaluated with parameter value 1.0. This has caused multiple people to have trouble with model initialization, with little debugging info:

http://discourse.mc-stan.org/t/initialization-between-2-2-failed-after-100-attempts/3941
http://discourse.mc-stan.org/t/initialization-differences-between-normal-and-logistic-irt/4395

Switching to bernoulli_logit helps.

What's confusing about this is theta = 1.0 is a valid parameter for the bernoulli distribution (and is listed as such in the manual) but doesn't actually work in Stan.

#### Reproducible Steps:
There's an example model here that exudes this issue: http://discourse.mc-stan.org/t/initialization-between-2-2-failed-after-100-attempts/3941

#### Current Output:
It fails, but doesn't give super-helpful output.

#### Expected Output:
We can either try to make bernoulli behave better for theta = 1.0, or print a warning. I don't see how to handle the numerical issue (seems like a loss of precision to me).

Does printing a warning make sense here?

What's the behavior of Stan/math in other similar situations?

#### Current Version:
v2.17.0

**Comment by syclik** [comment]
Mind clarifying? It looks like you're specifying the behavior from an interface. 

At the math level, we could easily run the Bernoulli lpdf to see what happens. I'd imagine that it passes all reasonable tests, but if there's some odd behavior, we can fix that. 

At the Stan level, what's the program you're trying to run? Is there data? What's the first argument to the function?

**Comment by bob-carpenter** [comment]
Thanks for reporting.  I'm trying to move issues to be more precise so that others can easily take up the issue an fix it.  

Any idea if the problem is due to `inv_logit` or `bernoulli_lpdf`.  We ideally want a simple math lib test case that fails.   And ideally, some hint at what needs to be fixed and how.

I think we should support this edge case if it's feasible.

The derivative of `inv_logit(x)` is `inv_logit(x) * (1 - inv_logit(x))`.  So the derivative is going to be zero, which may also be causing problems when you go to the log scale.

**Comment by bbbales2** [comment]
I ran some tests with the bernoulli_lpmf and I'm wrong. bernoulli_lpmf is giving the expected behavior, so I'm closing this.

I guess this is just an annoying to debug behavior, and bernoulli_logit(x) should just be preferred over bernoulli(inv_logit(x)) to avoid the loss of precision.

**Comment by bob-carpenter** [comment]
Thanks for following up.  That is indeed why we built bernoulli_logit and try to recommend it.  Another motivation for a lint mode.
