### ISSUE TITLE
Order of checks in matrix functions

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#88]
_From @rtrangucci on March 31, 2015 11:33_

Checks in matrix functions not ordered correctly; e.g.

mdivide_left_spd.hpp:

```
stan::math::check_symmetric("mdivide_left_spd", "A", A);
stan::math::check_pos_definite("mdivide_left_spd", "A", A);
stan::math::check_square("mdivide_left_spd", "A", A);
stan::math::check_multiplicable("mdivide_left_spd", 
                                                   "A", A,
                                                   "b", b);
```

@syclik pointed out we should be checking whether the two matrices are multiplicable before we run the check_pos_definite test. Check_pos_definite also already checks symmetry internally, so no need to call it twice.

_Copied from original issue: stan-dev/stan#1415_

**Comment by syclik** [comment]
_From @bob-carpenter on March 31, 2015 12:17_

The positive definiteness check should also check that the
matrix is square.

- Bob

**Comment by syclik** [comment]
_From @rtrangucci on March 31, 2015 18:47_

@bob-carpenter I should have added that check_pos_definite calls check_symmetric which subsequently calls check_square, so there only need to be two checks in mdivide_left_spd(A,b):

```
check_multiplicable(A,b)
check_pos_defininte(A)
```

**Comment by bob-carpenter** [comment]
They also don't need all those `stan::math` qualifications.  I'm a little reluctant to take on some of these issues because they involve massive code reviews.
