### ISSUE TITLE
dynamic linking of MPI libs fragile

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#883]
#### Summary:
Currently, the use of relative path's for dynamic linking via rpath can easily break things.

#### Description:
This popped up during testing in cmdstan: Whenever things change slightly between compilation and use of the final executable (in terms of relative path locations), then the final binary did not find the dynamic libraries from boost (mpi and serialization).

#### Reproducible Steps:
The add MPI facilities on cmdstan PR demonstrate this by failing tests.

#### Current Output:
NA

#### Expected Output:
Things should just continue to work; no matter if path's change artificially.

#### Additional Information:
Provide any additional information here.

#### Current Version:
develop

**Comment by SteveBronder** [comment]
@wds15 is this still an issue?

**Comment by wds15** [comment]
No idea…have not used mpi in a long time.
