### ISSUE TITLE
allow initial guess to be var in algebraic solver

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#886]
#### Summary:

The initial guess might be based on parameter values.

Gradients are not needed, so `value_of` should be able to pull out just `double` value and the argument templated so that not much implementation should be required.  Just a bit of testing.

This arose as a request on the forum:

http://discourse.mc-stan.org/t/correct-use-of-algebra-solver-getting-odd-error/4284/6

#### Current Version:
v2.17.0

**Comment by charlesm93** [comment]
Already solved.
See https://github.com/stan-dev/math/pull/703.
