### ISSUE TITLE
matrix_exp tolerances in tests are large, needs review

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#902]
#### Summary:
In order to stabilize the unit testing pipeline the tolerances of the matrix exponential tests needed adjustment to 1E-6 (instead of 1E-10 before). This needs investigation if the tests need to be written more carefully or if we need to improve the implementation (or just doc its limitation).

#### Description:
The matrix exponential tests which involve true randomness need a careful review by the reason given above.

#### Reproducible Steps:
Change the relative error from 1E-6 to 1E-10 again and let the tests run many times:
```
test/unit/math/fwd/mat/fun/matrix_exp_test.cpp
test/unit/math/fwd/mat/fun/matrix_exp_pade_test.cpp
test/unit/math/rev/mat/fun/matrix_exp_test.cpp
test/unit/math/prim/mat/fun/matrix_exp_test.cpp
test/unit/math/prim/mat/fun/matrix_exp_pade_test.cpp
```

#### Current Output:
Undefined.

#### Expected Output:
Well defined and doced behavior.

#### Additional Information:
Provide any additional information here.

#### Current Version:
develop

**Comment by andrjohns** [comment]
Closed via #901
