### ISSUE TITLE
beta distribution mean/count parameterization

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/math#914]
#### Summary:

Implemement a paramterization of the `beta(a, b)` in terms of `p = a / (a + b)` and `c = a + b`.

#### Description:

For `p` in [0, 1], `c > 0` and `y` in [0, 1], 

```
beta_proportion(y | p, c) = beta(y | p * c, (1 - p) * c)
```

This will require a `beta_proportion`

* [ ] `_lpmf`
* [ ] `_lcdf`
* [ ] `_lccdf`
* [ ] `_rng`

Any or all of these `beta_proportion_X` functions may be implemented in `prim` by delegating to the equivalent `beta_X` function.  

It is not a requirement for completing this issue, but it would be worth implementing `beta_proportion_lpmf` directly with analytic gradients for the speed and memory savings.

#### Current Version:
v2.17.0

**Comment by roualdes** [comment]
I'm working on this issue and wondering, from where do you get the 22 decimal places of precision to use in the tests of, for instance, `math/test/prob/beta/beta_test.hpp`?

My first thought was R or Python, but despite their willingness to print 22 decimal places, they start to disagree starting at the 17 decimal place, and neither R nor Python agrees with the full number(s) given in the file above.

Thanks.

**Comment by bob-carpenter** [comment]
I have no idea, but it's ridiculous to test to 22 decimal places when we only have about 16 in double-precision floating point :-)  Just lower the test case precision to 16 places and don't test all of them---use the floating point comparisons or expect-near.  

I'd guess they came from either MATLAB or Boost.  In general, magic numbers like this should be documented as to their source!

**Comment by andrjohns** [comment]
Closed via #975
