### ISSUE TITLE
Simplex of size 0 still causes problems in Stan

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/math#920]
#### Summary:
As per #580 problems with 0 length simplices should have been solved. This is however not the case.

#### Description:
I have observed two weird behaviors when trying to allocate a simplex of size 0:
a) The program throws a `std::badalloc` (don't have a short reproducible example)
b) Stan never stops (I do have a reproducible example)

I believe those two might be related.

Since issue #580 was reported in this repo, I am not reporting in `stan`, even though it might actually be a Stan problem.

#### Reproducible Steps:

This R code with a Stan program:

```
code <- "
data {
int N;
}

parameters {
simplex[N] a;
}
"

stan(model_code = code, data = list(N = 0), chains = 1, iter = 10)
```

#### Current Output:
Stan starts and never finishes.

#### Expected Output:
An error message claiming that I can't allocate a 0 size simplex.

#### Additional Information:
Provide any additional information here.

#### Current Version:
rstan_2.17.3

**Comment by bob-carpenter** [comment]
@martinmodrak --- were you going to submit a PR to fix it?  If not, we can assign someone else.

It should throw a `std::domain_error` in the transform.  This is an easy fix.  It can use the `check_greater` function with `y = 0` and `low` the input container.

**Comment by mcol** [comment]
Are you referring to check_simplex()? There's already a `check_nonzero_size(function, name, theta);`, 
I tried to replace it with `check_greater(function, name, theta.size(), 0);` and nothing much changed. If you point me to the correct place I could have another go.

**Comment by bob-carpenter** [comment]
`check_simplex()` is for validating arguments.  What you need is the reader code calling the transforms or the transforms themselves.  I think the problem could be fixed by adding a condition to both versions of `simplex_constrain()` (there's one that computes a Jacobian and one that doesn't).  The relevant file is [stan/io/reader.hpp](https://github.com/stan-dev/stan/blob/8a0755e827838452ba03736ee9e56e4dda93a892/src/stan/io/reader.hpp).

**Comment by martinmodrak** [comment]
@bob-carpenter  Sorry for the late reply, I am not planning on working on this in the near future.

**Comment by mcol** [comment]
Was this fixed by https://github.com/stan-dev/stan/pull/2773?

**Comment by bob-carpenter** [comment]
Yes, fixed by https://github.com/stan-dev/stan/pull/2773.  Closing.
