### ISSUE TITLE
testing view metaprograms

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#93]
_From @bob-carpenter on May 6, 2015 20:4_

Before anything else gets committed against these things, we need tests for
- VectorViewMvt
- scalar_type_pre

_Copied from original issue: stan-dev/stan#1442_

**Comment by seantalts** [comment]
I'm taking a look at doing this and using the VectorView_test.cpp as an example. But I'm a bit confused about what this file is testing. Can anyone comment on its intentions? For example, I'm confused that the `TEST(MetaTraits,VectorView)` section would not appear to test any additional functionality over the  `TEST(MetaTraits, VectorView_matrix_double)` section, seemingly differing only in how the Eigen matrices are initialized. And within the latter section, I can't figure out what lines 21-24 are trying to test beyond what the preceding lines tests.

I'll translate these tests (and add a few more for additional multivariate functionality) for VectorViewMvt and put up a pull request we can comment on as well, in case that's a better format.

**Comment by syclik** [comment]
Thanks! They're horribly named. See this issue #464 for a better description of what these things actually are. I think maybe if we rename them first, the testing will be much easier just because it's clearer what functionality they provide.

**Comment by seantalts** [comment]
I agree they should be renamed but I think I get what the classes are trying to do... But I still don't really see how the tests I mentioned differ from each other! I might be missing something obvious or some specialized C++ thing, or there's a chance the tests were intended to test different functionality but actually don't? Not sure.

**Comment by syclik** [comment]
I'll take a better look tomorrow. There might be duplicate tests.

**Comment by seantalts** [comment]
Awesome, thanks!

**Comment by seantalts** [comment]
Hey,

What is scalar_type_pre supposed to do? Here is the doc string:
```
  /**
    * Metaprogram structure to determine the type of first container of
    * the base scalar type of a template argument.
    *
    * @tparam T Type of object.
  */
```
I would read this to say that given something like a `Matrix<double, Dynamic, Dynamic>` it would pull out the `double`.

But when I see it used in VectorViewMvt, it’s used like this:
`    typedef typename scalar_type_pre<T>::type matrix_t;` where T is in this case the `Matrix<double, Dynamic, Dynamic>` from above, and then matrix_t becomes, again, `Matrix<double, Dynamic, Dynamic>`. 

How is this different from just using `T` as `matrix_t` and dropping the scalar_pre_type thing?

I am still very new to C++ so please be kind :)

**Comment by bob-carpenter** [comment]
@seantalts --- could you close this if it's now redundant given the other work you're doing generalizing `operands_and_partials`.  Thanks.
