### ISSUE TITLE
Integrating positive ODE systems

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#94]
_From @betanalpha on May 21, 2015 12:47_

A common component of many ODE systems is that the states are positive, which can cause numerical problems if the states are small.  One potential solution to small state values is to automatically convert the ODE system into one for the log states and then solve that.  In particular, if

dC/dt = f(t, C, theta)

then

d logC / dt = exp( logC ) f(t, logC, theta).

It's not clear if the exp( logC ) term would make the unconstrained ODE system any more stiff, but it would be easy to implement this with an `integrate_positive_ode` function just to experiment.  

Formally this can be generalized to other constrained states but I don't think any others would be particularly useful and be worth the generalization.

_Copied from original issue: stan-dev/stan#1455_

**Comment by wds15** [comment]
@bbbales2 we can close this as well I would say. I don’t think we will implement this (users can handle it and there are good hacks available and a decent solution requires special features of cvodes)

**Comment by bbbales2** [comment]
Agreed. This is a transformation that makes sense to do manually.
