### ISSUE TITLE
Test one compiler per OS

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#952]
#### Summary:
This is a continuation of #943.

We would like to test one compiler per OS for our tests. Here are the tests we are currently running:
- mac / clang 6 / libc++ Threading unit tests
- linux / gcc 5 / stdlibc++ OpenMPI unit tests
- mac clang 6 libc++ OR linux clang 6 libc++[2] distribution tests (without row vectors)

Additional tests on merge to develop
- linux / gcc 5 / stdlibc++ Threading unit tests
- mac / clang 6 libc++ OR linux / gcc 5 stdlibc++[1] GPU unit tests
- mac clang 6 libc++ OR linux clang 6 stdlibc++[2] distribution tests (with row vectors)

For tests, these are the tests that should be tested on each of those configurations:
1. header tests. `make test-headers`
2. unit tests. `./runTests.py test/unit`
3. distribution tests. `./runTests.py test/prob` (listed here only for completeness)

Here are remaining tests we need:
- [x] windows / gcc 4.9.3 (Rtools) unit tests
- [ ] windows headers tests
- [ ] mac / clang 6 / libc++ headers tests
- [ ] linux / gcc 5 / stdlibc++ headers tests

We will not be looking to run all the distribution tests on all platforms. It's not feasible.

#### Description:
These are the remaining things that need to be tested according to the original proposal #943.

#### Reproducible Steps:
This should be a Jenkinsfile change.

#### Current Version:
v2.18.0

**Comment by rok-cesnovar** [comment]
On the Stan Math level this issue is fixed.
