### ISSUE TITLE
improve poisson_lpmf performance for some special cases

### ISSUE THREAD

**Issue by wds15** [stan-dev/math#958]
## Description
The `poisson_lpmf` performs unnecessary costly calculations for a few use cases. Specifically (referencing `math/stan/math/prim/scal/prob/poisson_lpmf.hpp`):

1. line 54: the upper for loop limit should be `size(lambda_vec)` to avoid the loop for the case of `lambda` being a scalar
2. line 66: This line leads to an evaluation of `lgamma` for each element  - even if `n` is a scalar. We should probably introdcue the usual `VectorBuilder` logic to save calculations and only perform them as many times as needed given the case of a scalar or a vector input.

## Example

This example should execute much faster for the second case, but it doesn't do that at the moment:
```cpp
#include <stan/math/rev/mat.hpp>
#include <gtest/gtest.h>
#include <test/unit/math/rev/mat/fun/util.hpp>
#include <vector>

TEST(large, poisson_lpmf) {
  using stan::math::value_of;
  using stan::math::var;
  using std::vector;

  const std::size_t terms = 10000000;

  using stan::math::vector_v;

  vector_v lambda(terms);
  std::vector<int> n(terms, 3);

  for (int i = 0; i < terms; i++)
    lambda(i) = 1.0;

  var lp = stan::math::poisson_lpmf(n, lambda);

  lp.grad();
}

TEST(large, poisson_lpmf_n1) {
  using stan::math::value_of;
  using stan::math::var;
  using std::vector;

  const std::size_t terms = 10000000;

  using stan::math::vector_v;

  vector_v lambda(terms);
  // std::vector<int> n(terms, 3);

  for (int i = 0; i < terms; i++)
    lambda(i) = 1.0;

  var lp = stan::math::poisson_lpmf(3, lambda);

  lp.grad();
}
```

## Expected Output
The above test should be faster in the second case.

## Additional Information
Any additional information goes here.

## Current Math Version
v2.18.0

**Comment by bob-carpenter** [comment]
Thanks, @wds15.  We should probalby audit all these implementations to make sure we're not doing redundant work like this.

**Comment by wds15** [comment]
Could someone explain me why we use `lgamma(n + 1.0)` in the normalization constant of the Poisson (which is what the `poisson_lpmf` seems to implement)? The correct normalization would be `lgamma(n)`, I think.

(this does not affect sampling, but only the normalization constant). If someone could confirm, then we can add this to this Poisson cleanup issue.

**Comment by betanalpha** [comment]
The normalization is correct.

log n! = lgamma(n + 1)
