### ISSUE TITLE
Custom reverse mode autodiff for positive ordered, ordered, and simplex constraints

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#960]
## Description
positive ordered, ordered, and simplex constraints do not currently have custom reverse mode autodiff implementations. custom autodiff would be nice cause it would make them faster. This is the issue paired with pull req. #959 

## Expected Output
There should be no change to the functionality of the math library. Custom autodiff should just make these faster.

## Current Math Version
v2.18.0

**Comment by andrjohns** [comment]
Closed via #959
