### ISSUE TITLE
Multiple input adjoint vector-Jacobian product form of precomputed gradients for reverse

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#963]
## Description
The current adjoint/Jacobian mechanism (designed to this specification: https://github.com/stan-dev/math/issues/876 and implemented here: https://github.com/stan-dev/math/pull/924) for implementing custom autodiff requires that the function being specialized for reverse mode take in a single Eigen::VectorXd.

It would be nice if we could use this mechanism for functions that took in multiple arguments that could be doubles, any Eigen type, ints, and std::vector<doubles>, std::vector<Eigen types>, and std::vector<int>s. This would make it possible to implement this custom adjoint^T * jacobian autodiff for a much larger class of functions.

Adjusting from the model @bob-carpenter proposed in pull #924:
```
struct bar {
  template<size_t size>
  Eigen::VectorXd operator()(const array<bool, size>& needs_adj, const T1& x1, const T2& x2, ...) {
    if(needs_adj[0]) {
       // prepare any special calculations for the x1 adjoint
    }
    if(needs_adj[1]) {
       // prepare any special calculations for the x1 adjoint
    }
    ...
    Eigen::VectorXd results;
    // Compute results from x1, x2, etc.
    return results;
  }

  template<size_t size>
  std::tuple<T1, T2, ...> adjoint_jacobian_multiply(const array<bool, size>& needs_adj, const Eigen::VectorXd& adj_y) {
    T1 adj_x1;
    T2 adj_x2;
    ...
    if(needs_adj[0]) {
       // resize adj_x1 and actually compute it
    }
    if(needs_adj[1]) {
       // resize adj_x2 and actually compute it
    }
    ...
    return std::make_tuple(adj_x1, adj_x2, ...);
}
};
```

Significant points:
1. I added the argument needs_adj to both operator() and adjoint_jacobian_multiply. This is an array of booleans of length equal to the number of arguments letting the person implementing the adj_jac operator whether they need to actually compute the adjoint of all the variables in different situations.

From the perspective of someone implementing the op, they only work with doubles. However Stan might call the function with mixes of var and double types. To make things efficient, there needs to be a way for people implementing the ops to know what calculations are optional or not.

2. The template types T1, T2, etc. probably wouldn't actually be template types. They're just there to represent any combination of int, double, Eigen types, std::vector<int>, std::vector<double>, and std::vector<Eigen types>

3. The fact that adj_jac_vari will need to handle operators with different numbers of arguments can be handled nicely with C++ parameter packs (https://en.cppreference.com/w/cpp/language/parameter_pack)

4. The adjoint_jacobian_multiply return type can be auto which makes things slightly nicer

This is kindof a working design in the sense that this is the thing I got working, it looks nice to me, and so this is what I'm proposing we do. I'll upload a pull request with the code to show how this works.

## Current Math Version
v2.18.0

**Comment by andrjohns** [comment]
Closed via #964
