### ISSUE TITLE
value_of doesn't actually just pass through const references of double Eigen::Matrix/std::vector types like it says

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#968]
## Description
value_of doesn't actually just pass through const references of double Eigen::Matrix/std::vector types like it says in the docs

```
inline Eigen::Matrix<double, R, C> value_of(const Eigen::Matrix<double, R, C>& x)
```
```
inline std::vector<double> value_of(const std::vector<double>& x)
```

should be

```
inline const Eigen::Matrix<double, R, C>& value_of(const Eigen::Matrix<double, R, C>& x)
```
```
inline const std::vector<double>& value_of(const std::vector<double>& x)
```

I don't think these changes will have side effects? I guess it's possible, cause certainly they'll change how the code works in places. We'll see what CI says.

See discussion here:
http://discourse.mc-stan.org/t/value-of/5091

## Current Math Version
v2.18.0

**Comment by ChrisChiasson** [comment]
Also, it seems like this part
https://github.com/stan-dev/math/blob/develop/stan/math/prim/mat/fun/value_of.hpp#L24-L30
should be using unaryExpr with a lambda function
`return M.unaryExpr([](auto const& t){return value_of(t);});`
Have y'all considered passing matrix expressions everywhere in stan math?

**Comment by bbbales2** [comment]
>> should be using unaryExpr with a lambda function

That's neat. I didn't know about that. And I suppose an auto on the return type of the function itself would be appropriate as well. Maybe the child_type vector program is defunct at this point? Do those sorts of lambdas get inlined efficiently n' all? Or are there jumps?

>> Have y'all considered passing matrix expressions everywhere in stan math?

Like this stuff: https://eigen.tuxfamily.org/dox/TopicFunctionTakingEigenTypes.html ? Or something else? I think I'd like it cause it'd help me avoid a few unnecessary copies. When I mentioned it to Bob he seemed to like it as well, but I don't know the full implications, and it's a big ol' hunka code to be rewritin'.

**Comment by ChrisChiasson** [comment]
If you used the auto return type, the resulting matrix expression would, I assume, contain operations meant to be applied to the memory pointed to by the M reference parameter of the function.  Since M could be pointing to an rvalue.... I dunno, try and see? Might blow up.

Yea, I mean in the style that Eigen requires, i.e. the tradeoff where the caller manages the lifetime in exchange for the ability to pass matrix expressions everywhere.

**Comment by SteveBronder** [comment]
> If you used the auto return type, the resulting matrix expression would, I assume, contain operations meant to be applied to the memory pointed to by the M reference parameter of the function.

Sean found some weird things when working with `auto` and Eigen (see [discourse link](http://discourse.mc-stan.org/t/profiling-c-code/3033/23?u=stevo15025)).

Though looking back on this I think we could use auto with Eigen's `matrix.cast<type>()` or `matrix.template cast<type>();`

**Comment by bbbales2** [comment]
Niiiiice! Thanks for the link @SteveBronder. This applies to me in other pulls. I will have to think about this.

**Comment by ChrisChiasson** [comment]
Regarding inling: it depends on value_of's definition, but I'd say the chances of beating a hard coded lambda passed to Eigen's own looping functions is low, so it should not be any slower...

**Comment by SteveBronder** [comment]
@bbbales2 yes I highly recommend! He has a very opinionated writing style which is nice to read.

If the discussion is moving away from the initial issue maybe it's better to move this to a discourse thread. I'm pretty pro not using auto when returning Eigen types, though I think it's good in other places

**Comment by bbbales2** [comment]
@ChrisChiasson @SteveBronder yeah I'm keeping this issue just strictly fixing the const/ref stuff.

I think you're right about the Eigen stuff though. We do want to do fancy Eigen type stuff and be all modern (presumably using things like you wrote with the lambdas). But yeah, that's another, much bigger conversation, haha.

**Comment by betanalpha** [comment]
auto is tricky when used with expression templates, but careful use
of eval() can work wonders as @ChrisChiasson notes.  Basically
we want to evaluate the expressions templates down to a specific
return type in most calculations so we want to either avoid auto
and use the expected return type (which helps to make the code
more explicit and force errors on unexpected types) or use auto
but with eval().  I’d prefer the former, even though it requires more
thought from the developer.

**Comment by bob-carpenter** [comment]
The only way to know is to test the speed or look at the generated assembly.  Of course, this varies by compiler and won't necessarily be the same for the next compiler versions.

I'm not sure what hard-coded means for a lambda---are there different flavors?  I would have thought lambdas induce the overhead of building the functor even if you never convert from system-specific type.  Then all the closure variables need to be set, if any.

I'm also curious as to whether the functions inside lambdas get inlined.  If everything's known statically, then it should be possible.  Is that what you mean by hard-coded---no closure variables?  Or do you mean allocated fully on the stack so no mallocs?

**Comment by ChrisChiasson** [comment]
If a lambda captures no variables, it is treated like a function call,
afaik.. maybe I am wrong

**Comment by bob-carpenter** [comment]
> On Aug 7, 2018, at 1:17 PM, ChrisChiasson <notifications@github.com> wrote:
> 
> If a lambda captures no variables, it is treated like a function call,
> afaik.. maybe I am wrong

Right---that's why I was asking about the closures.  

If there's nothing captured by closure, then the functor class won't have member variables and the constructors and destructors will be no-ops, so I wouldn't be surprised if the compiler could unroll the whole thing into a simple function call.  It's certainly valid semantically in that case.

**Comment by ChrisChiasson** [comment]
There is actually a rule saying a non capturing lambda has to be able to be
callable through a bald non-class type function pointer, so that is why I
had said I think it compiles to a function

**Comment by wds15** [comment]
Did you measure performance differences with this thing being in?

**Comment by bbbales2** [comment]
I did not. I just took it for granted this is the thing I wanted to happen.

**Comment by ChrisChiasson** [comment]
Are performance tests run automatically in the new CI?
