### ISSUE TITLE
Allow different output types in the adj_jac_apply stuff

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#970]
## Description
Following up on Issue #876 (implemented in #924), it'd be nice to be able to use this mechanism functions with outputs that are not ```Eigen::Matrix<double, Eigen::Dynamic, 1>```s.

Adapting from @bob-carpenter 's prototype in (https://github.com/stan-dev/math/pull/924#issuecomment-401986209), it would be nice to support functors with this signature:
```
struct bar {
  T operator()(const Eigen::Matrix<double, Eigen::Dynamic, 1>& x);
  Eigen::Matrix<double, Eigen::Dynamic, 1> adjoint_jacobian(const T& y);
};
```

where T is a placeholder (not a real C++ template) for double, std::vector<double>, all the Eigen::Matrix double types, and maybe std::vectors of those?

## Current Math Version
v2.18.0

**Comment by andrjohns** [comment]
Closed via #1016
