### ISSUE TITLE
enable_if gp_dot_prod_cov

### ISSUE THREAD

**Issue by drezap** [stan-dev/math#979]
## Description
Previously, I implemented GP dot product kernel to take in a double, in an effort to deal with Stan's `vector x[N]`, and `vector[D] x[N]` data types. When doing this, at the time I could only get both to compile while setting one of the input arguments as a double. This did not compile when running a Stan model 

## Example
For **bug reports**:

Any model that uses `gp_dot_prod_cov`.

## Additional Information
I've fixed this locally with enable_if metaprogramming and will open up a PR with the fix shortly, as I've been using this version in my local command Stan.

## Current Math Version
v2.18.0

**Comment by bbbales2** [comment]
So this is the signature we're talking about:

`
gp_dot_prod_cov(const std::vector<T_x> &x, const T_sigma &sigma)
`

Was it that the code wasn't working when the scalar type of the first and the second were both doubles or both vars?
