### ISSUE TITLE
Remove is_nan from fvar constructor

### ISSUE THREAD

**Issue by syclik** [stan-dev/math#983]
## Description
Currently, `is_nan` is called in the `fvar` constructor. Remove. It's not done for primitives and `stan::math::var`s.

Please also remove the include to `is_nan.hpp`.

## Additional Information
This was introduced as a quick check for autodiff. We're still not confident all of forward mode works yet. This might be a good way to debug, but it's not meant to be included in the forward mode implementation.

Thanks @dpsimpson for finding a bug related to this through pr #978.

## Current Math Version
v2.18.0

**Comment by rok-cesnovar** [comment]
Fixed with #1384
