### ISSUE TITLE
Fix the math constants definitions on Windows

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/math#986]
## Description

The math constants are not defined in standard C++. In order to use them you must first define `_USE_MATH_DEFINES` and then include `<cmath>`.

Some further information is given [here](http://www.cplusplus.com/forum/general/102410/) and [here](https://msdn.microsoft.com/en-us/library/4hwaceh6.aspx).

As discussed in #976, adding `_USE_MATH_DEFINES` to the make file fixes this problem.

## Example
Running the following tests on Windows

```
./runTests.py test/unit/math/prim/mat/fun/gp_periodic_cov_test.cpp
./runTests.py test/unit/math/prim/scal/fun/log_modified_bessel_first_kind_test.cpp
./runTests.py test/unit/math/rev/mat/fun/gp_periodic_cov_test.cpp
./runTests.py test/unit/math/rev/mat/fun/matrix_exp_action_handler_test.cpp
```
produces the following errors

`error: 'M_PI' was not declared in this scope
`
`error: 'M_E' was not declared in this scope
`
## Expected Output

The tests should compile and pass on Windows.

## Additional Information

/

## Current Math Version
v2.18.0

**Comment by syclik** [comment]
Thank you!!!
