### ISSUE TITLE
prim implementation of sum has wrong return type

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#987]
## Description
The templated version of sum in stan/math/rev/mat/fun/sum.cpp always returns a double.

It should instead return the scalar type of the Eigen::Matrix it is summing.

The reason it works is that there are template specializations for the other types Stan might use (and they are correct), but this is still wrong.

## Current Math Version
v2.18.0

**Comment by cqfd** [comment]
Looks like this hasn't been picked off yet, want me to make a little PR?

Along code cleanup lines, would it make sense to rewrite the `std::vector` version in stan/math/prim/arr/fun/sum.hpp to use `std::accumulate`? (Not sure if that's in scope, happy to just do the one double -> T change.)

```.cpp
#include <numeric>
template <typename T>
inline T sum(const std::vector<T>& xs) {
  return std::accumulate(xs.begin(), xs.end(), T{0});
}
```

**Comment by bbbales2** [comment]
Go for it. If you wanna do the accumulate patch on prim/arr/fun, go ahead.

An issue with the initial issue is I said the problem was in stan/math/rev/mat/fun/sum.cpp. As you probably noticed that's not a real file, haha. The issue is actually in stan/math/prim/mat/fun/sum.hpp. Looks like me being lazy at the keyboard.

Since this is a bug, we'd want to add a test to make sure this doesn't get incorrectly changed back.

That'd go in test/unit/math/mat/prin/fun/sum_test.cpp

Maybe sum some types that Stan doesn't use, like floats, and then make sure the output is still a float? (and didn't get cast to a double somewhere in the middle?) I think that'd be appropriate.
