### ISSUE TITLE
prim/mat/fun implementation of divide is too specialized

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#988]
## Description
One argument is templated and one is not. It always returns an Eigen::Matrix with double scalars.

See: https://github.com/stan-dev/math/blob/develop/stan/math/prim/mat/fun/divide.hpp#L22

It's probably compiling fine because the other necessary specializations exist to take over, but I do not think this is properly templated.

Either both arguments should be templated (if this is expected to handle some of the high order stuff) or both the arguments should be doubles (if the other implementations cover all the necessary templated types)

## Current Math Version
v2.18.0

**Comment by bob-carpenter** [comment]
There are overloads in `rev` and `fwd`:

https://github.com/stan-dev/math/blob/develop/stan/math/rev/mat/fun/divide.hpp

https://github.com/stan-dev/math/blob/develop/stan/math/fwd/mat/fun/divide.hpp

But I agree the base case should be cleaned up and the overloads more clearly set up for argments so the right versions get called.  And ideally they should have analytic derivatives, not this promotion to autodiff vars, which is very inefficient.
