### ISSUE TITLE
improve beta_lccdf and beta_lcdf performace

### ISSUE THREAD

**Issue by roualdes** [stan-dev/math#997]
## Description
Both  `math/stan/math/prim/scal/prob/beta_lccdf.hpp` and ` math/stan/math/prim/scal/prob/beta_lcdf.hpp` perform unnecessary calculations by looping over digamma(x) excessively.

Lines 99 in `beta_lccdf` and 101 in `beta_lcdf` should loop over `max_size(alpha, beta)` instead of `N`.

As an aside, lines 83 and 84 in both 'beta_lccdf' and 'beta_lcdf' are duplicates.

## Example
This issue was discovered during the writing of the `beta_proportion` PR https://github.com/stan-dev/math/pull/975

## Expected Output
Both `beta_lccdf` and `beta_lcdf` should run faster.

## Additional Information
None

## Current Math Version
v2.18.0

**Comment by andrjohns** [comment]
Closed via #1000
