### ISSUE TITLE
Stan's direct C++ error wrapers should return throwable objects, not do the throw themselves

### ISSUE THREAD

**Issue by bbbales2** [stan-dev/math#998]
## Description
The functions concerned are (at least):
* [ ] https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/err/out_of_range.hpp
* [ ] https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/err/system_error.hpp
* [ ] https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/err/domain_error.hpp
* [ ] https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/err/invalid_argument.hpp
* [ ] https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/err/invalid_argument_vec.hpp
* [ ] https://github.com/stan-dev/math/blob/develop/stan/math/prim/scal/err/domain_error_vec.hpp

I have an variant of an overloaded function that needs to exist for the code to compile, but in practice should always throw an error:
```
T& get(size_t i) {
   throw std::domain_error();
}
```

@bob-carpenter pointed out if I do this then I don't actually have to figure out a way to return a non-temporary reference to a T to trick the compiler into not throwing warnings. An always throwing function doesn't need to actually return.

If I use the Stan domain_error, i get something like this:

```
T& get(size_t i) {
   domain_error("func", "i", i, "msg");
}
```

The compiler then complains that there's no return from this function.

I dunno what else this affects but I suspect it's a harmless change.

## Current Math Version
v2.18.0

**Comment by bob-carpenter** [comment]
What type are you going to have it return that'll work with a generic `T`?  

I've really wanted to factor those validation functions into three parts:

(1) test function returning bool
(2) exception factory to generate formatted messages of correct exception type
(3) the validation function that applies the test and if it fails, throws the exception

We also need to get them all uniformly vectorized.  This'd be a great first project as it has high positive impact and stays away from the really hairy parts of the code base.

**Comment by dmuck** [comment]
I'd like to work on this, but I've noticed the links posted above are broken. 

@bob-carpenter are the functions in question located [here](https://github.com/stan-dev/math/tree/develop/stan/math/prim/err)? Also, has anything changed since the header files were moved, or are you of the same opinion that the validation functions should be split into three parts and uniformly vectorized?
